### ISSUE TITLE
Automatically commit the initial crate template.

### ISSUE THREAD

**Issue by nathan-at-least** [rust-lang/cargo#10039]
### Problem

This is probably a taste thing, but whenever I run `cargo new`, I immediately enter the directory and run `git add . && git commit -m 'Cargo skeleton'`. The reason I do this is that I want to distinguish Cargo's project template/skeleton from the first changes _I_ make as a human on the project. If Cargo's template changes over time or is configured with local tweaks, I want to be able to clearly determine that later for any project.

My guess is many people immediately make modifications, then later commit the result. This probably works fine 99% of the time. Even in that case, though, is there any harm in automatically creating the first commit?

### Proposed Solution

Automatically commit the result of populating a new crate from the template with the specified revision control system. If it seems necessary, add a flag to opt-out.

### Notes

The proposed solution might surprise existing users used to Cargo. I can't foresee any outright problems this might cause, other than surprising existing Cargo users. However, it's very possible there are edge cases I'm not anticipating.

**Comment by joshtriplett** [comment]
We talked about this in today's cargo meeting. We felt that while some people might like this behavior, the current behavior allows people to modify the template *before* committing, because they'd like the "initial version" commit to include useful data rather than a Cargo template.

In addition to that, the transition from one behavior to the other would surprise people. So the criteria can't be "is there any harm", it'd have to be "this is much much better, worth pushing users through a transition".

**Comment by nathan-at-least** [comment]
That's a totally reasonable conclusion. Thanks for taking the time to discuss it!
