### ISSUE TITLE
Allow setting quiet from config

### ISSUE THREAD

**Issue by frioux** [rust-lang/cargo#10128]
### Problem

I prefer the output to be `--quiet` and would like to set it as a config option.

### Proposed Solution

I'd like to be able to set quiet in config.toml just like you can set verbose.  Maybe something like this:

```ini
[term]
quiet = true
```

If people think this is a reasonable idea I'd be happy to try my hand at implementing it.

**Comment by ehuss** [comment]
Sounds reasonable to me. There are some details about the exact behavior when mixing flags that this should be careful about.  I think people may have different opinions about how it should work, but I'm thinking of something like the following:

* `--verbose` and `--quiet` CLI options take precedent over anything set in config.
* You can't set both `verbose` and `quiet` in config (it is an error).

Otherwise, let me know if you have any questions.

**Comment by frioux** [comment]
agree on both
