### ISSUE TITLE
Cargo build crash in project with git Split Index

### ISSUE THREAD

**Issue by de-husk** [rust-lang/cargo#10150]
### Problem

Cargo build is breaking when a build.rs file is present in a project with a git repo using [split indexes](https://github.com/git/git/blob/b46013950aff31b6626af96ccbf2c48469e36c66/Documentation/git-update-index.txt#L393-L416).

```
$ cargo build

error: failed to determine package fingerprint for build script for split_index_bug v0.1.0 (/.../split_index_bug)

Caused by:
  failed to determine the most recently modified file in /.../split_index_bug

Caused by:
  failed to determine list of files in /.../split_index_bug

Caused by:
  failed to open git index at /.../split_index_bug/.git/

Caused by:
  unsupported mandatory extension: 'link'; class=Index (10)
 ```

### Steps to Reproduce

I have made a small repo where you can reproduce the issue https://github.com/Samangan/cargo-split-index-bug

### Version

```text
cargo 1.56.0 (4ed5d137b 2021-10-04)
release: 1.56.0
commit-hash: 4ed5d137baff5eccf1bae5a7b2ae4b57efad4a7d
commit-date: 2021-10-04
```

**Comment by weihanglo** [comment]
Confirmed that libgit2 v1.3.0 doesn't support split-index extension at this moment.

https://github.com/libgit2/libgit2/blob/v1.3.0/src/index.c#L2604-L2616

**Comment by arlosi** [comment]
Bringing the discussion from #13498 back into the issue.

This issue is preventing me from vendoring crates into a repo that uses unsupported git extensions. When attempting to build any crate that has a `build.rs` file, the error is encountered.

Potential solutions:
1. Ignore the error (log it to tracing and fall back to the non-git heuristic approach): proposed in #13498 
   - As @weihanglo pointed out, this goes against Cargo documentation.
3. Ignore the error, but only for building, not for publishing (where it would still be an error)
4. Do the `.gitignore` processing in Cargo, rather than using `libgit2` (either always, or only if libgit2 fails)
5. Have a config option that disables using git when calculating includes/excludes for a package.
6. Require `build.rs` scripts to use `rerun-if-changed` as needed in the 2024 edition so that enumerating the files in a path source is no longer required to build.

**Comment by epage** [comment]
iirc [jj](https://github.com/martinvonz/jj) is looking to switch to [ignore](https://crates.io/crates/ignore).

**Comment by Byron** [comment]
It looks like [this code segment](https://github.com/rust-lang/cargo/blob/e08a81333c510255606e58062a154d7bb29d5288/src/cargo/sources/path.rs#L254) in Cargo is involved in triggering this behaviour [as suggested by Weihanglo](https://rust-lang.zulipchat.com/#narrow/stream/246057-t-cargo/topic/.60gitoxide.60.20integration.20updates/near/425732372).

A `gitoxide` based implementation should be available soon, which could serve as a workaround. Please note that in order to be fully Git compatible, one has to consider the Git index, which as far as I know `ignore` does not, and which is the reason `git2` fails in the first place. However, maybe using `ignore` in the `git2` track *if* it failed would still be a viable trade-off.

**Comment by ehuss** [comment]
Update from the meeting last week: @arlosi is going to try to investigate if it is feasible to have a `git` CLI fallback in cases where libgit2 is unable to open the repository. If that is a relatively small change, that might be something we will consider for at least a short-term fix.
