### ISSUE TITLE
--crate-type cdylib causes errors looking for rlib dependencies

### ISSUE THREAD

**Issue by seanmonstar** [rust-lang/cargo#10356]
### Problem

When running `cargo rustc --crate-type cdylib -Z unstable-options`, I see errors that dependencies were expected to be available in `rlib` format. If I put the crate-type in the `Cargo.toml`, I don't see these errors.

Output:

```
 ~/code/test.rs $ cargo rustc --crate-type cdylib -Z unstable-options
   Compiling scratchpad v0.0.0 (/home/sean/code/test.rs)
error: crate `http` required to be available in rlib format, but was not found in this form

```

### Steps

Here's a minimal repro:

1. Make a new crate, using any simple dependency. `http = "*"` works.
2. In `lib.rs`, add `pub extern "C" fn yeet() { println!("{:?}", http::StatusCode::OK) }`.
3. Run `cargo rustc --crate-type cdylib -Z unstable-options`.

I originally discovered this by trying to convert hyper to use it:

1. Removing the `[lib]` and `crate-type = ["cdylib", "staticlib", "lib"]` lines.
2. Run `cargo rustc --crate-type cdylib -Z unstable-options`.

### Notes

- If I keep the line in `Cargo.toml`, then hyper builds properly.
- When making a minimal repro, I noticed that it works without a dependency, and it also works with a dependency that isn't used. You must _use_ the dependency in the file.

### Version

```text
cargo 1.60.0-nightly (25fcb13 2022-02-01)
release: 1.60.0-nightly
commit-hash: 25fcb135d02ea897ce894b67ae021f48107d522b
commit-date: 2022-02-01
host: x86_64-unknown-linux-gnu
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:OpenSSL/1.1.1l)
os: Ubuntu 16.04 (xenial) [64-bit]
```

**Comment by seanmonstar** [comment]
Relevant tracking issue: https://github.com/rust-lang/cargo/issues/10083

**Comment by weihanglo** [comment]
The root cause is that #10093 handles rustc's `--crate-type` arg well but doesn't take care of others, such as `--extern`. The unit thought it only requires `rmeta` but actually it needs `rlib` to build artifacts other than `rlib`. Below are the differece between two rustc invocations. (left: toml, right: cmd arg) 

<img width="1652" alt="image" src="https://user-images.githubusercontent.com/14314532/153457319-28eca8e2-2a83-48cd-8a1b-ef115a27e77c.png">


Here is a simple patch for [`cargo::core::compiler::context::Context::only_requires_rmeta`](
https://github.com/rust-lang/cargo/blob/227f4c4fcfa4e56d712cd62688dbdc0911d6242e/src/cargo/core/compiler/context/mod.rs#L581-L590) to let the build pass.

```patch
         // object code must be useful in some fashion
         && !dep.requires_upstream_objects()
         && dep.mode == CompileMode::Build
+        && !self.bcx.rustc_crate_types_args_for(parent)
+            .map_or(false, |v| v.iter()
+                .map(|s| s.into())
+                .any(|ty: super::CrateType| ty.requires_upstream_objects()))
+}
```

However, there are lots of places calling `Unit::requires_upstream_objects`, which are not `Context`-aware and I cannot think of an easy way to fix without duplicate our `--crate-type` overridden logic. 

An intuitive solution is setting crate types into `unit.target.kind` directly, so that no extra workaround is needed. Unfortunately `Unit` doesn't implement `DerefMut` but only `Deref`. This mutating approach won't work unless we open a mutable backdoor on `Unit`.

@ehuss Any insight into this?

**Comment by elichai** [comment]
I'm still having this problem on Rust `1.66.1`.
on MacOS X86_64:

`Cargo toml`:
```toml
[package]
name = "yeet"
version = "0.1.0"
edition = "2021"
[dependencies]
jni = "0.20"
```

`src/lib.rs`:
```rust
#[no_mangle]
pub extern "C" fn yeet() {
    println!("{:?}", jni::JNIVersion::V1);
}
```
Command:
`cargo rustc --target x86_64-linux-android -- --crate-type=cdylib`
Output:
```
❯ cargo rustc --target x86_64-linux-android -- --crate-type=cdylib
   Compiling bytes v1.3.0
   Compiling cfg-if v1.0.0
   Compiling cesu8 v1.1.0
   Compiling jni-sys v0.3.0
   Compiling memchr v2.5.0
   Compiling thiserror v1.0.38
   Compiling log v0.4.17
   Compiling jni v0.20.0
   Compiling combine v4.6.6
   Compiling wat v0.1.0 (/private/tmp/wat)
error: crate `jni` required to be available in rlib format, but was not found in this form

error: could not compile `wat` due to previous error
warning: build failed, waiting for other jobs to finish...
```

CC @weihanglo

**Comment by weihanglo** [comment]
I feel like you didn't use `--crate-type` flag correctly. Flags after `--` go directly to rustc invocation, whereas the RFC stabilized `--crate-type` for `cargo-rustc` affects how Cargo determine the crate type of the final artifact. 

Could you try `cargo rustc --target x86_64-linux-android --crate-type=cdylib`?

**Comment by weihanglo** [comment]
Oh I see. Glad you figured it out :)
