### ISSUE TITLE
Use rust-provided lld linker when compiling build.rs

### ISSUE THREAD

**Issue by bradjc** [rust-lang/cargo#10378]
### Problem

Is it possible to compile and link build.rs (the `build_script_build` step) with the lld linker that is included with the rust toolchain? We're running into an [issue](https://github.com/tock/tock/pull/2957#issuecomment-1034920899) where on very small development containers we cannot compile a rust binary because no linker was found to link build.rs. The rest of the compilation should entirely use tools that are included in the rust toolchain to cross compile for embedded targets.

I tried setting the `CARGO_TARGET_X86_64_APPLE_DARWIN_LINKER` environment variable to the path to `rust-lld`, which did change the linker. However, that resulted in an error because `-arch` is not being set.

### Proposed Solution

The easiest thing for me would be a cargo option/flag that instructs cargo/rustc to use the provided linker. However, there may already be a way to do this, but I couldn't find anything describing how to do it, or if it's even possible.

**Comment by ehuss** [comment]
I don't think this is feasible at this point in time.  On macOS, lld can't be used directly because rustc expects the linker (usually clang) to handle generating all the correct linking arguments for the platform.  I'm also not sure how reliable lld is on macOS (historically it wasn't great, but I think there has been progress made in the past few years).  I'm also not sure what the current incantation is to try to get lld working on macOS with clang.  I'm going to close in favor of https://github.com/rust-lang/rust/issues/39915 which contains a lot more context.  It would be great to make Rust more self-contained and make cross-building easier, but I think that is a pretty long road that can't be tracked here.
