### ISSUE TITLE
`cargo new` generates gitignore file that ignores non-root `Cargo.lock`s, causing errors with `cargo vendor`

### ISSUE THREAD

**Issue by ashpil** [rust-lang/cargo#10370]
The default gigignore template generates a line with `Cargo.lock` rather than `/Cargo.lock`, causing necessary `Cargo.lock`s in non-root directories to be ignored.

This becomes an issue if one uses `cargo vendor` to vendor deps - as the gitignore file ignores the dependencies' `Cargo.lock`s, which one is required to have to build without error.

**Comment by weihanglo** [comment]
I've traced down the issue:

1. The original implementation did ignore root `/Cargo.lock`. https://github.com/rust-lang/cargo/pull/321
2. Someday one wanted to support both gitignore and hgingore's syntax and removed the leading slash. https://github.com/rust-lang/cargo/pull/1247
3. Later, one found that we should not ignore `target` other than under root directory and added `/target` back. https://github.com/rust-lang/cargo/pull/4099
4. It turns out that the syntax is not compatible between gitignore and hgignore. Therefore, one started to use hgignore special syntax to handle `Cargo.lock`. https://github.com/rust-lang/cargo/pull/4342

Personally, I believe this should be fixed, especially when cargo start supporting artifact dependencies. Though checking out`Cargo.lock` into version control system is not recommended.

**Comment by Eh2406** [comment]
With that explanation I am +1 on fixing this. Thanks @weihanglo for the writeup!
