### ISSUE TITLE
Don't close jobserver fd when executing external subcommand

### ISSUE THREAD

**Issue by trinity-1686a** [rust-lang/cargo#10477]
### Problem

I tried to use [`cargo-fuzz`](https://github.com/rust-fuzz/cargo-fuzz) from a Makefile, expecting it to use make's jobserver to limit concurency.
When running it as `cargo-fuzz`, it worked as intended, but when running it as `cargo fuzz`, it did not seem to acknowledge make job count.
I found `cargo-fuzz` environment variables contained `--jobserver-auth=3,4` as expected, but these file descriptors are closed.

### Steps

- create a script called `cargo-sleep` and put it into your $PATH
```bash
#!/bin/bash
sleep $2
```
- write a simple Makefile calling this command with jobserver passing
```Makefile
all:
        +cargo sleep 10
```
- run the makefile with jobserver
```sh
make -j2
```
- look at the environment of `sleep`. It contains `MAKEFLAGS= -j2 --jobserver-auth=3,4` (actual number may vary)
- look at open file descriptors of `sleep`, 3 and 4 (in my case) are not open.

### Notes

As stated there is a simple workaround, calling the sub-command directly instead of through cargo

### Version

```text
cargo 1.59.0 (49d8809dc 2022-02-10)
release: 1.59.0
commit-hash: 49d8809dc2d3e6e0d5ec634fcf26d8e2aab67130
commit-date: 2022-02-10
host: x86_64-unknown-linux-gnu
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:OpenSSL/1.1.1l)
os: Arch Linux [64-bit]
```

**Comment by weihanglo** [comment]
Thanks for the report. The behaviour indeed reflects how Cargo runs external subcommands: Cargo doesn't call [`ProcessBuilder::inherit_jobserver()`] for external subcommands[^1], so file descriptors get close due to [`FD_CLOEXEC` flag](https://github.com/alexcrichton/jobserver-rs/blob/b38aa0245447a75dae3103a040ace62f1ab6f125/src/unix.rs#L83-L97) (on Linux).

Not sure whether it's a bug or a feature. GNU Make says[^2]:

> If your tool determines that the --jobserver-auth option is available in MAKEFLAGS but that the file descriptors specified are closed, this means that the calling make process did not think that your tool was a recursive make invocation (e.g., the command line was not prefixed with a + character). You should notify your users of this situation. 

If I get it correctly, it's up to Cargo to determine whether the process should inherit the   jobserver or not. It seems that `cargo-fuzz` is a reasonable use case and personally I'd love to see it working.

[`ProcessBuilder::inherit_jobserver()`]: https://github.com/rust-lang/cargo/blob/cd4616448056f56f8b6aeaf0fa632f7f5125638f/crates/cargo-util/src/process_builder.rs#L149-L156

[^1]: https://github.com/rust-lang/cargo/blob/cd4616448056f56f8b6aeaf0fa632f7f5125638f/src/bin/cargo/main.rs#L176-L184
[^2]: https://www.gnu.org/software/make/manual/html_node/POSIX-Jobserver.html#POSIX-Jobserver

**Comment by weihanglo** [comment]
Hi. We have [discussed inheriting jobserver fd on Zulip](https://zulip-archive.rust-lang.org/stream/246057-t-cargo/topic/external.20subcommand.20inherits.20jobserver.20fd.html). There might be some compatibility issues: It's rare but some commands might use fd 3 and 4 without notice of the existence of jobserver. As you said, there is a simple workaround. I'd recommend sticking with that.

**Comment by trinity-1686a** [comment]
I understand the compatibility concern.
> You should notify your users of this situation.

Could cargo do that, so that at least other peoples stumbling on this bug/feature are made aware of the workaround? There are multiple external subcommands that actually call cargo internally (cargo-fuzz, cargo-tarpaulin...).

Also some such external subcommands do not support being called directly (I'm thinking about [cargo-ndk](https://github.com/bbqsrc/cargo-ndk/blob/a82d48f7de327a64df4d37155206fa2d9cbb5b02/src/main.rs#L12)). This is not *my* use case, but it could me someone else's.
