### ISSUE TITLE
Cannot specify timings in .cargo/config

### ISSUE THREAD

**Issue by jerryc05** [rust-lang/cargo#10509]
### Problem

Cannot specify `timings` option in `.cargo/config`

### Steps

1. Add these to `.cargo/config`:
   ```
   [build]
   timings = ['html']
   ```
2. Shows warning: `warning: unused config key build.timings`, and timings not activated.

### Possible Solution(s)

Parse `build.timings` in `.cargo/config` since `timings` is removed from unstable in nightly cargo.

### Version

```text
cargo 1.61.0-nightly (109bfbd 2022-03-17)
release: 1.61.0-nightly
commit-hash: 109bfbd055325ef87a6e7f63d67da7e838f8300b
commit-date: 2022-03-17
host: x86_64-unknown-linux-gnu
libgit2: 1.4.2 (sys:0.14.2 vendored)
libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:OpenSSL/1.1.1m)
os: Debian unstable (sid) [64-bit]
```
```


<!-- TRIAGEBOT_START -->

<!-- TRIAGEBOT_ASSIGN_START -->

<!-- TRIAGEBOT_ASSIGN_DATA_START$${"user":"hi-rustin"}$$TRIAGEBOT_ASSIGN_DATA_END -->

<!-- TRIAGEBOT_ASSIGN_END -->
<!-- TRIAGEBOT_END -->

**Comment by hi-rustin** [comment]
@weihanglo @ehuss Is this acceptable? I think I can help to add it.

**Comment by ehuss** [comment]
Seems like a reasonable addition to me.  Roughly the things that need to be done to add this are:
* Add to [`CargoBuildConfig`](https://github.com/rust-lang/cargo/blob/1a052aeb0a4c6c0e87659d5fa93019efb9ecfd63/src/cargo/util/config/mod.rs#L2164-L2181)
* Check the value around [here](https://github.com/rust-lang/cargo/blob/1a052aeb0a4c6c0e87659d5fa93019efb9ecfd63/src/cargo/util/command_prelude.rs#L530-L555). I'm not sure if it should take the union of options of the config + cli, or if the CLI should override the config. Needs some thought, but since there is only 1 stable option, probably isn't too critical right now.
* Add a test in the [timings module](https://github.com/rust-lang/cargo/blob/master/tests/testsuite/timings.rs).
* Update the [config documentation](https://github.com/rust-lang/cargo/blob/master/src/doc/src/reference/config.md).
* Update the [environment variables documentation](https://github.com/rust-lang/cargo/blob/master/src/doc/src/reference/environment-variables.md#configuration-environment-variables).
* Add a mention of the config setting in the [timings documentation](https://github.com/rust-lang/cargo/blob/master/src/doc/src/reference/timings.md).
* Add a mention of the config setting in the [`--timings` docs](https://github.com/rust-lang/cargo/blob/master/src/doc/man/includes/options-timings.md). See [`--jobs`](https://github.com/rust-lang/cargo/blob/master/src/doc/man/includes/options-jobs.md#L3) as an example of how this is done. Then [rebuild the man pages](https://github.com/rust-lang/cargo/tree/master/src/doc#building-the-man-pages).

**Comment by epage** [comment]
@jerryc05 could you expand on why you are interested in this being in the config?  This seems like a transient option for me and the use case for making it more permanent in a file seems unclear.

**Comment by hi-rustin** [comment]
@jerryc05 Friendly ping~

Could you share your use cases?

**Comment by hi-rustin** [comment]
@epage Maybe we can close this issue now? I think there are no reasonable use cases for this config. Because it's a debugging config, we can always pass it.

**Comment by epage** [comment]
I'm not quite seeing why this would be put in a starter template as it seems like you wouldn't want timings on every run but only when specifically wanting to measure a build.

If someone does come up with a reason for wanting timings on every run, we can reconsider this.  For now, I'm going to close this though as there doesn't seem to be sufficient motivation provided.
