### ISSUE TITLE
Keeping track of both git and crates.io dependencies

### ISSUE THREAD

**Issue by bvssvni** [rust-lang/cargo#1052]
In Piston I keep separate branch named "crates.io" for each project, which I rebase and force push upstream each time I want to publish a new version on crates.io. What I want to do, is publish directly from the master branch.

While git dependencies are not allowed when publishing, I would like some sort of "magic" that only uses the crates.io dependencies when publishing and ignores the git dependencies.

**Comment by alexcrichton** [comment]
I think that in general this is a problem that will smooth itself out over time. The primary source of dependencies will originate from crates.io, and we're primarily just in a transitional period where we suffer more pain than we would otherwise.

Your previous comment is what I initially tried to do (git deps on git, crates.io deps on crates.io), but I've since just migrated all my dependencies to crates.io and I've found it to actually be pretty nice and much easier. 

I don't think that this is something we need a long term solution to, and I don't think it's too too onerous in the meantime, so I'm going to close this for now.
