### ISSUE TITLE
View source on site

### ISSUE THREAD

**Issue by bvssvni** [rust-lang/cargo#1054]
Currently you have to do something like this:

```
curl -OL https://crates.io/api/v1/crates/curl-sys/0.1.0/download
tar -zxvf download
```

What I want to do, is to view the source on the site in the browser, if possible.

**Comment by withoutboats** [comment]
It's good to know about the workaround at the top of the page (it solved the problem that brought me here), but this doesn't seem like a non-issue at all to me. Getting a readable source from crates.io is not accessible, even though its the code on crates.io that is compiled and depended upon. It isn't particularly important in my opinion if its available on the site or as a documented cargo command or some other method, but the source of crates available through cargo should also be available through cargo or crates.io.

Nothing about crates.io or cargo requires or particularly encourages users to create and maintain a public repository for the source of their crate. Of course, distributing the source is essential to free and open source software, so it seems quite bad to me that cargo enables users to neglect that aspect of distributing their projects.

I found this issue while trying to access the source of a crate which has a repo on GitHub, but the head of the GitHub repo is more than 3 months behind the version on crates.io. This problem is not theoretical.

**Comment by BatmanAoD** [comment]
If nothing else, it would help if the GItHub link (when there is one) were a little more prominent. Putting it in the midst of a list of other arbitrary "links" near the bottom of the page is a bit confusing.

**Comment by carols10cents** [comment]
Would a [command called cargo-open](https://github.com/rust-lang/cargo/issues/1929) that opens the location on your filesystem that a dependency's source has been downloaded to in your $EDITOR meet the needs described in this issue?

**Comment by alexcrichton** [comment]
@carols10cents yeah I'd consider something like that to fit the bill here basically. I think of this as basically making it convenient to download source from crates.io and explore it.

**Comment by durka** [comment]
It would still be great to have a way to get the source on the site without having to create a cargo project and add a dependency. It could just be a download link, not an online viewer.

**Comment by diwic** [comment]
How difficult / resource draining would it be to run `cargo doc` for crates when they are uploaded and add a link to that? Not only would that give you fresh and up-to-date documentation, but they also have source links.

It seems fairly straight-forward to implement (with a caveat for crates that are different depending on arch, as well as sandboxing build scripts). I just don't know enough about web development to know what kind of load such a server would require.

**Comment by withoutboats** [comment]
> It would still be great to have a way to get the source on the site without having to create a cargo project and add a dependency. It could just be a download link, not an online viewer.

Yeah, though I think the best solution to this is probably a `cargo source` command which takes a crate name as an argument, rather than a link on the crate pages on crates.io.

**Comment by JanLikar** [comment]
https://github.com/janlikar/cargo-clone Check this out!

**Comment by durka** [comment]
@JanLikar great!!

**Comment by carols10cents** [comment]
I think between cargo-clone, cargo-open, github, and docs.rs, we've got enough options for this. Please reopen if you disagree!
