### ISSUE TITLE
Set sysroot/lib in dylib path when running custom subcommand

### ISSUE THREAD

**Issue by Emilgardis** [rust-lang/cargo#10644]
### Problem

I have a cargo subcommand that depends on rustc-dev internals, to properly run these, users need to assure that the sysroots libraries are visible when executing the command as

`cargo subcommand command`

### Proposed Solution

in https://github.com/rust-lang/cargo/blob/9fa2bba6791f9df06a13dbfe18bf7add9b9b2d1b/src/bin/cargo/main.rs#L176

do the same operation that `cargo run` does to set the dylib path. E.g add the active toolchains sysroot/lib to the path

### Notes

I stumbled upon this developing [cargo-whynot](https://github.com/Emilgardis/cargo-whynot) which uses `rustc_driver` etc to call rustc in a custom way. I did not have the sysroot libraries in path, so running `cargo whynot` could not load, but when in the local workspace `cargo run -- whynot` worked fine. In particular, I'm on windows, setting `LD_LIBRARY_PATH` to `"$(rustc --print sysroot)/lib:$($env:LD_LIBRARY_PATH)"` solved the issue.

`cargo run -- subcommand` sets the appropriate path, but `cargo subcommand` does not.

**Comment by ehuss** [comment]
I don't think this is something cargo can do because it requires some non-trivial overhead. In order to discover the sysroot, cargo needs to run `rustc --print=sysroot` which can take tens or hundreds of milliseconds.  Additionally, assuming you mean you are linking against the `rustc_driver` shared library or similar, then the appropriate sysroot will depend on the toolchain used to compile your program, which often won't match the current sysroot due to rustup overrides. I'm not sure I have an answer, but I suspect you'll need to do some rpath shenanigans to get it to work reliably. You may want to ask on one of the user forums if and how people have gotten it to work. [This](https://github.com/rust-lang/rust/blob/c51871c469f7ed3b35ae25d7e6e77bc73fbdd0e3/src/bootstrap/builder.rs#L1358-L1376) I believe is how clippy and other tools do it.
