### ISSUE TITLE
Disable default features of `git2` to enable avoiding openssl in builds

### ISSUE THREAD

**Issue by brooksmtownsend** [rust-lang/cargo#10703]
### Problem

When depending on the `cargo` crate, the `git2` dependency has default features enabled which forces bringing in the openssl dependency. It would be great if that dependency had `default-features = false` attached to it, perhaps even with a feature flag, so that dependents of `cargo` can have a more static binary experience.

### Proposed Solution

I propose that we change the dependency in Cargo.toml for `git2` to also disable default features. If the openssl dependency required for `git2` and I'm missing the use case, then it would be great if that could be enabled in a feature flag that could be included as a default feature for `cargo`.

### Notes

I may be missing a core reason why openssl is required for the `git2` library, and would like to know if that's the case

**Comment by epage** [comment]
> I propose that we change the dependency in Cargo.toml for git2 to also disable default features. If the openssl dependency required for git2 and I'm missing the use case, then it would be great if that could be enabled in a feature flag that could be included as a default feature for cargo.
> 
> I may be missing a core reason why openssl is required for the git2 library, and would like to know if that's the case

I'm assuming its required to pull registries and git dependencies that require authentication.  If we allow it to be disabled, we need to make sure that the version of cargo pulled in by rustup / integrators has it enabled, whether by making sure they enable it or having it enabled by default.

In general, I'd recommend finding the reasons for why something is before removing it so you can plan for whatever that reason is.

Something else to keep in mind is that the cargo crate API is not a priority for the cargo team and we tend to discourage its use compared to calling cargo commands with the help of crates like cargo_metadata and escargot.
