### ISSUE TITLE
IPv6-Only Hosts Fail to Build

### ISSUE THREAD

**Issue by TheBlueMatt** [rust-lang/cargo#10711]
### Problem

IPv6-only hosts are becoming more and more common with IPv4 cost skyrocketing. In some cases (eg Vultr's IPv6-only offerings) there's not any CG-NAT either, so `cargo` fails to run at all because the first thing it does is try to clone from `github.com`.

### Proposed Solution

Look at providing a CF-wrapped git-clone domain or look at alternative hosting providers like gitlab.

**Comment by est31** [comment]
Earlier thread: https://internals.rust-lang.org/t/unable-to-build-over-ipv6-only-requires-ipv4/9673

Even earlier: https://internals.rust-lang.org/t/ipv6-reachability-of-rust-websites/4379

**Comment by jonhoo** [comment]
I wonder if https://github.com/rust-lang/cargo/issues/9069 might help avoid this problem 🤔

**Comment by arlosi** [comment]
> I wonder if https://github.com/rust-lang/cargo/issues/9069 might help avoid this problem 🤔

Yes, index.crates.io is available on IPv6, so it should work.

**Comment by weihanglo** [comment]
crates.io is still on Heroku. It is the biggest blocker so far I guess.

**Comment by weihanglo** [comment]
Hi @MarcoFalke. If I recall correctly, [crates.io web API and download link redirections](https://doc.rust-lang.org/nightly/cargo/reference/registry-index.html#index-configuration) are served on Heroku, and [Heroku doesn't support IPv6](https://help.heroku.com/I8L6RW01/does-heroku-support-ipv6). To move on, we should consult crates.io team. Perhaps file an issue against rust-lang/crates.io repository or ask [t-crates-io](https://rust-lang.zulipchat.com/#narrow/stream/318791-t-crates-io) on Zulip.

BTW, I found a [Zulip topic](https://rust-lang.zulipchat.com/#narrow/stream/318791-t-crates-io/topic/IPv6) about this. Maybe someone could ask there to verify if this issue is still relevant.

**Comment by weihanglo** [comment]
> If I recall correctly…
> To move on, we should consult crates.io team…

No. I am not sure. That's why I suggest asking crates-io team. I am not too familiar with the infra there.

> Also, `cargo` seems to be working locally.

That sounds great!! If you could help we verify and check with the crates-io team, it would be even better :)

**Comment by paolobarbolini** [comment]
I tried calling endpoints from a dualstack host, forcing curl to use IPv6 via `-6` and they all seem to work. GitHub on the other hand still doesn't support it, so if for any reason you need to clone crates.io-index it won't work on an IPv6-only host.

```shell
# cargo related operations
curl -I https://crates.io/api/v1/crates/chrono/0.4.26/download -6
curl -I https://static.crates.io/crates/chrono/chrono-0.4.26.crate -6
curl -I https://index.crates.io/ch/ro/chrono -6

# rustup related operations
curl -I https://static.rust-lang.org -6
```

**Comment by arlosi** [comment]
I disabled IPv4 and successfully use `rustup` to install stable and build cargo. That tests:
* static.rust-lang.org - uses CloudFront / Fastly with v6 enabled
* static.crates.io - uses CloudFront / Fastly with v6 enabled
* crates.io - uses CloudFront CDN with v6 enabled
* index.crates.io - uses CloudFront with v6 enabled

Even though Heroku doesn't support IPv6, the CloudFront CDN in front of it does. GitHub still does not support v6, so it's necessary to use cargo 1.70+ to get sparse index by default.
