### ISSUE TITLE
process didn't exit successfully: (signal: 9, SIGKILL: kill)

### ISSUE THREAD

**Issue by Fujiwara-Chika** [rust-lang/cargo#10823]
### Problem

<img width="840" alt="image" src="https://user-images.githubusercontent.com/44722787/177170166-2e07e314-3282-40c3-9a24-8d0599cca7e4.png">

### Steps

cargo install xxxx

### Version

```text
⋊> ~ cargo version --verbose                                                                21:59:57
cargo 1.62.0 (a748cf5a3 2022-06-08)
release: 1.62.0
commit-hash: a748cf5a3e666bc2dcdf54f37adef8ef22196452
commit-date: 2022-06-08
host: x86_64-apple-darwin
libgit2: 1.4.2 (sys:0.14.2 vendored)
libcurl: 7.54.0 (sys:0.4.51+curl-7.80.0 system ssl:LibreSSL/2.6.5)
os: Mac OS 10.14.6 [64-bit]
```

**Comment by Fujiwara-Chika** [comment]
> Why do you think this is a bug with Cargo and not with `quote`?

<img width="840" alt="image" src="https://user-images.githubusercontent.com/44722787/177176500-eb5f0dfc-a45e-4d83-87f1-a6ae8e09d008.png">

**Comment by weihanglo** [comment]
Which method did you install rust with? It sometimes leads to toolchain corruptions. I'd recommend installing Rust via [rustup](https://rustup.rs/).

**Comment by ehuss** [comment]
SIGKILL is almost always caused by the operating system or something in the environment.

One way to diagnose is to get the logs from `Console.app`.  With `Console.app` open and recording logs, try running cargo again, and then look through and see if there are any entries that look relevant. Typically they would be from the kernel, taskgated, syspolicyd, or something similar.

I also notice that it is reporting as running on 10.14. Can you say more about what hardware you are running on? That version is quite old, so I'm wondering if it is related.

Other information that could be helpful:
* `xcodebuild -version`
* `xcode-select -p`
* `clang --version`

**Comment by Fujiwara-Chika** [comment]
`console log: nw_path_close_fd Failed to close guarded necp fd 5 [9: Bad file descriptor]
`<img width="840" alt="image" src="https://user-images.githubusercontent.com/44722787/178309815-9531aacc-33af-49d6-b58c-5fc59f8312da.png">

**Comment by Fujiwara-Chika** [comment]
> Which method did you install rust with?

`curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`

**Comment by ehuss** [comment]
Without more information, I'm going to close since I don't think we'll be able to help.
I tested on High Sierra (10.13) with Command Line Tools 10.1 and building seems to work fine.
`Console.app` is your best bet for discovering why the process is being killed.

If you have some more details to share or ways someone else can reproduce, feel free to share them here.
If you are having general problems using Rust, I might suggest one of the user forums like https://users.rust-lang.org/ where people might be able to help you better.
