### ISSUE TITLE
cargo-add: Insert dependencies alphabetically

### ISSUE THREAD

**Issue by sfackler** [rust-lang/cargo#10880]
### Problem

I like to keep my dependencies all sorted alphabetically in my Cargo.toml, but `cargo add` appears to always append to the end of the dependency list.

### Proposed Solution

It would be nice if `cargo add` would preserve the sort when possible. I guess it'd probably have to be some heuristic where if the list is already sorted it'll preserve the sort and append otherwise?

**Comment by Muscraft** [comment]
`cargo add` should try and preserve order from what I can remember. It checks if the [table is sorted](https://github.com/rust-lang/cargo/blob/d8d30a75376f78bb0fabe3d28ee9d87aa8035309/src/cargo/ops/cargo_add/mod.rs#L93), and [sorts it](https://github.com/rust-lang/cargo/blob/d8d30a75376f78bb0fabe3d28ee9d87aa8035309/src/cargo/ops/cargo_add/mod.rs#L134) after a new entry is added (if it is sorted).

I'm not sure why it wouldn't be keeping the order. Do you mind sharing the `Cargo.toml` and the command you ran?

**Comment by epage** [comment]
Yes, if it isn't preserving your existing sorting, that is a bug.  We'll need more concrete reproduction steps to be able to identify the root cause and fix it.

For sorting already unsorted entries, we explicitly removed that feature when upstreaming into cargo.  Defining manifest styling and formatting according to that is outside of the scope of cargo-add and belongs in a tool specialized to that, like rustfmt (see https://github.com/rust-lang/rustfmt/issues/4091).   As rustfmt defines and implements a default style, cargo-add should work to conform to that.  It'll be a little more of a stretch but maybe once rustfmt config fields are defined and stablized, cargo-add could respect those as well.

**Comment by sfackler** [comment]
Ah - It turns out my existing list was slightly unsorted! Yeah, makes sense that rustfmt should take the lead on overall Cargo.toml format.

**Comment by bbb651** [comment]
Has this regressed? This doesn't [here](https://github.com/YaLTeR/niri/blob/7884d3bfea810740fe2ca7021b102af0f049ccae/Cargo.toml#L52-L94) even though it's sorted, with e.g. `cargo add systemd --optional`

Using `cargo 1.86.0 (adf9b6ad1 2025-02-28)`

**Comment by epage** [comment]
I'm nit aware of any regressions.

However, I did notice in your file
```toml
clap = { workspace = true, features = ["string"] }
clap_complete = "4.5.47"
```
```toml
pango = { version = "0.20.9", features = ["v1_44"] }
pangocairo = "0.20.7"
```
vs
```toml
tracing-subscriber.workspace = true
tracing.workspace = true
```

**Comment by epage** [comment]
Hopefully `cargo fmt` will handle this one day.
