### ISSUE TITLE
`--emit` option in `rustflags` causes `cargo check` to fail with "crate `foo` required to be available in rlib format"

### ISSUE THREAD

**Issue by jeffy1009** [rust-lang/cargo#10908]
### Problem

`--emit` option in `rustflags` causes `cargo check` to fail with "crate `foo` required to be available in rlib format"

### Steps

1. `cargo new --lib foo`
2. `cargo new --bin bar`
3. Add `foo` to `dependencies`
```
# bar/Cargo.toml
[dependencies]
foo = { path = "../foo" }
```
4. Use function in `foo`
```
# src/main.rs
fn main() {
    let _ = foo::add(0, 1);
}
```
5. `RUSTFLAGS="--emit=llvm-bc" cargo check`
```
error: crate `foo` required to be available in rlib format, but was not found in this form
```

### Notes

Any available options for `--emit` results in the same behavior.

### Version

```text
cargo 1.64.0-nightly (85b500cca 2022-07-24)
release: 1.64.0-nightly
commit-hash: 85b500ccad8cd0b63995fd94a03ddd4b83f7905b
commit-date: 2022-07-24
host: x86_64-unknown-linux-gnu
libgit2: 1.4.2 (sys:0.14.2 vendored)
libcurl: 7.83.1-DEV (sys:0.4.55+curl-7.83.1 vendored ssl:OpenSSL/1.1.1n)
os: Ubuntu 18.04 (bionic) [64-bit]
```

**Comment by weihanglo** [comment]
Thank you for raising this issue! The error you saw I believe is from rustc. [Here] should be where you got it. 

Except dep-info and rmeta, other forms of output types (llvm-ir, mir, asm, ...) [are defined as sorts of "code generation"] at this moment. It first found itself [need to codegen], then ran [the following algorithm] and realized it was producing an executable. That's why it tried to search for rlib artifacts.

Could you share the reason you're trying to emit LLVM bitcode with `cargo check`? I am a bit confused since the main purpose of `cargo check` is to avoid codegen. It helps if we share the same view :)

[Here]: https://github.com/rust-lang/rust/blob/1f5d8d49eb6111931091f700d07518cd2b80bc18/compiler/rustc_metadata/src/dependency_format.rs#L227-L232
[are defined as sorts of "code generation"]: https://github.com/rust-lang/rust/blob/1f5d8d49eb6111931091f700d07518cd2b80bc18/compiler/rustc_session/src/config.rs#L429-L440
[need to codegen]: https://github.com/rust-lang/rust/blob/1f5d8d49eb6111931091f700d07518cd2b80bc18/compiler/rustc_metadata/src/dependency_format.rs#L79
[the following algorithm]: https://github.com/rust-lang/rust/blob/1f5d8d49eb6111931091f700d07518cd2b80bc18/compiler/rustc_metadata/src/dependency_format.rs#L25-L42

**Comment by jeffy1009** [comment]
Project I'm working on, I need llvm-ir for compiler-builtins so I passed `--emit=llvm-bc` (in .cargo/config) for all rustc invocation. We also have git commit hook for cargo check, so git commit fails afterwards. I found the workaround but left the issue for others who might have the same inconvenience.

**Comment by ehuss** [comment]
I'm going to close as this is more of a consequence of how rustc works, and as mentioned, `llvm-bc` is part of codegen which `cargo check` doesn't do.
