### ISSUE TITLE
Externally discover the source directories of dependencies?

### ISSUE THREAD

**Issue by patrickjm** [rust-lang/cargo#1098]
Regarding https://github.com/phildawes/racer/issues/73

At the moment it is difficult to find the local source directories of a crate's dependencies after they have been fetched. It's easy to search Cargo's folder that holds the downloaded git repositories, but this gets awkward when there is no simple way to link these with the actual Cargo.toml you're working with because Cargo uses its own hash (rather than git's) in the build directory. Not to mention that not all dependencies are git. 

A Cargo command to print the source root of a dependency would *greatly* help the state of Rust's autocompletion (and probably tooling in general). `cargo print-source-root` was [suggested](https://github.com/phildawes/racer/issues/73#issuecomment-66364027).

Alternatively, these source directories could be printed along with the other json in `cargo read-manifest`, which actually seems more appropriate to me...

How feasible is this? Is there some simple internal cargo `fn` that I'm not seeing that could be exposed?

Thanks.

**Comment by eklavya** [comment]
I did some experimentation on this and I was able to get source roots for all dependencies (I think).
I have zero knowledge of Rust and Cargo so maybe someone from cargo team can pick it up. I think this will really enhance the noob experience for Rust as going back and forth to docs for looking up all the methods and such becomes quite hectic for a newcomer.

I added:

```rust
println!("{}", pkg.get_manifest_path().dir_path().display());
```
in ops/cargo_rustc/compilation.rs in function process.

I could work on it but I have absolutely no idea what to do.

**Comment by DanielKeep** [comment]
This is currently flummoxing me with `cargo-script`.  Specifically, I want to insert automatically-generated `extern crate FOO;` items for expressions specified on the command line, as writing them inside an expression is kinda painful.

The *only* thing I need from Cargo at this point is some way to find out where the manifest of a dependency is.  Everything else, I can handle.  The only other option available to me at this point is to deliberately trigger a failing build with `-v`, and parse the output to reconstruct the command-line passed to rustc (which cargo doesn't correctly quote), then parse rustc's command line to extract the `--extern` switches.

I *really* don't want to go through with that, mostly because it's utterly ridiculous to just get some crate names...

**Comment by almereyda** [comment]
Why does this also make me think of `npm link` for cases in which one is developing a dependency in the same time?

**Comment by alexcrichton** [comment]
I believe this is implemented now that `cargo metadata` has landed, thanks @matklad!
