### ISSUE TITLE
`cargo tree --prefix depth` unintended format

### ISSUE THREAD

**Issue by windowsboy111** [rust-lang/cargo#10995]
### Problem

The depth number sticks to the crates name. Seems to be unintentional.

### Steps

1. Have a cargo project with at least 1 dependency
2. Run `cargo tree --prefix depth`

Sample output:
Run `cargo tree --prefix depth` in any valid cargo project.
Output:
```
0cargo-depbuilder v0.1.0 (/home/windowsboy111/MEGA/repos/cargo-depbuilder)
1execute v0.2.11
2execute-command-macro v0.1.8
3execute-command-macro-impl v0.1.8 (proc-macro)
4execute-command-tokens v0.1.6
4quote v1.0.21
5proc-macro2 v1.0.43
6unicode-ident v1.0.3
4syn v1.0.99
5proc-macro2 v1.0.43 (*)
5quote v1.0.21 (*)
5unicode-ident v1.0.3
2execute-command-tokens v0.1.6
2generic-array v0.14.6
3typenum v1.15.0
3version_check v0.9.4
1indexmap v1.9.1
2hashbrown v0.12.3
2autocfg v1.1.0
1regex v1.6.0
2aho-corasick v0.7.18
3memchr v2.5.0
2memchr v2.5.0
2regex-syntax v0.6.27
```

### Possible Solution(s)

[`src/cargo/ops/tree/mod.rs` L291](https://github.com/rust-lang/cargo/blob/master/src/cargo/ops/tree/mod.rs#L291):
```rs
        Prefix::Depth => drop_print!(config, "{} ", levels_continue.len()),
        //                                      ^ space missing
```

### Version

```text
cargo 1.61.0 (a028ae4 2022-04-29)
release: 1.61.0
commit-hash: a028ae42fc1376571de836be702e840ca8e060c2
commit-date: 2022-04-29
host: x86_64-unknown-linux-gnu
libgit2: 1.4.2 (sys:0.14.2 vendored)
libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:OpenSSL/1.1.1m)
os: Arch Linux [64-bit]
```

**Comment by weihanglo** [comment]
Thanks for the report! Hmm… I feel like it's not unintentional. There even is [a test exercise] for it. And it has been there since the age of [cargo-tree as a 3rd party subcommand][3rd-subcommand]. 

I would suggest using `--format|-f` flag to customise your own display today, such like

```shell
cargo tree --prefix depth -f ' {p}'
```

[a test exercise]: https://github.com/rust-lang/cargo/blob/84941490fd7304317282a89309c1fe2123200a8b/tests/testsuite/tree.rs#L794-L813
[3rd-subcommand]: https://github.com/sfackler/cargo-tree/blob/4abcac4ddfb69f6dfde1af0164f2f0ee0e230336/src/tree.rs#L189

**Comment by weihanglo** [comment]
Closing as changing it breaks the already-stabilized output format. People now can customize the format as [mentioned earlier](https://github.com/rust-lang/cargo/issues/10995#issuecomment-1216347771). The current format can also be parsed easily by a program, as a package name cannot start with a digit in order to conform to [Unicode Standard Annex #31](http://www.unicode.org/reports/tr31/). It is just not that eye-pleasing.

Please comment below or discuss on [Zulip](https://rust-lang.zulipchat.com/#narrow/stream/246057-t-cargo) if you have any other thought. Thank you!
