### ISSUE TITLE
cargo publish failed for rs_pbrt crate (worked before)

### ISSUE THREAD

**Issue by wahn** [rust-lang/cargo#11057]
### Problem

I tried a `$ cargo release --execute` from within my latest changes on [sourcehut](https://git.sr.ht/~wahn/rs-pbrt). It worked before (several times) and I only updated some depenencies, but I get this error message:

```
$ cargo release --execute
...
    Finished dev [unoptimized + debuginfo] target(s) in 1m 14s
   Uploading rs_pbrt v0.9.8 (/home/jan/git/sourcehut/rs-pbrt)
error: failed to publish to registry at https://crates.io

Caused by:
  the remote server responded with an error: invalid upload request: invalid length 26, expected a keyword with less than 20 characters at line 1 column 9863
```

**Comment by epage** [comment]
I'm assuming its due to the `physically-based-rendering` keyword.

Not sure why it says "at line 1 column 9863"

Also, no idea why it would have worked before but now it doesn't.  This is enforced on the server side and [at a quick glance](https://github.com/rust-lang/crates.io/commits/master) I didn't see any changes that stood out to me but there are a lot of dependency and test changes and I could have missed it in all of those

**Comment by wahn** [comment]
Wow. Thanks for your quick response. I tried it without the `physically-based-rendering` keyword and that worked. Thanks a lot!
