### ISSUE TITLE
cargo not recognizing newest versions for bug fixes with '-test-1' suffix

### ISSUE THREAD

**Issue by landonwork** [rust-lang/cargo#11061]
My team has a small crates registry with interdependent crates. Specifically, there is a crate which contains datatypes that gets shared among the others and which I will call `datatypes`. We've been using a suffix, '-test-' followed by the number of the attempt, to push and test bug fixes on our crates including this one. Depending on `datatypes` are three other crates; each one of these also depends on the previous one. I'll call them `production1`, `production2`, and `production3`.

A very strange thing has happened while trying to test our bug fixes like this. `production1` depends on a bug fix `datatypes = "^0.2.0-test-9"`. `production2` depends on version `datatypes = "^0.2.1"` and the latest version of `production1`. The version for `datatypes` resolves to "0.2.1". From previous debugging with this problem (I specified `datatypes = "^0.2.2-test-1"` in `production2`'s dependencies and tried resolving those), I know that cargo also sees and considers versions "0.2.0-test-9.1", "0.2.0-test-9.2", and "0.2.0-test-9.3" to be compatible with `production1`.

When I get to `production3`, things get hairy. `production3` depends on `datatypes = "0.2.2-test-1"`. If I try to do `cargo update`, I get this error

```
error: failed to select a version for `datatypes`.
    ... required by package `production2 v0.1.0 (registry `private`)`
    ... which satisfies dependency `production2 = "^0.1.0"` of package `crosswalk v0.1.0 (/path/to/project)`
versions that meet the requirements `>=0.2.1, <0.3.0` are: 0.2.1

all possible versions conflict with previously selected packages.

  previously selected package `datatypes v0.2.2-test-1 (registry `private`)`
    ... which satisfies dependency `datatypes = "^0.2.2-test-1"` of package `production3 v0.1.0 (/path/to/project)`

failed to select a version for `datatypes` which could resolve this conflict
```

If version `datatypes 0.2.2-test-1` did not exist, cargo would be showing me a different error, so cargo found 0.2.2-test-1. But when it tries to resolve this version with the other dependencies, it's like it has become invisible. One important fact I should mention is that there is no version `datatypes 0.2.2`.

Here is what I think may be happening and what I would like help understanding. One of three things:

1. Cargo does not consider 0.2.2-test-1 to be newer than 0.2.1
2. Cargo does not automatically upgrade to versions with suffixes, or "minor-minor" versions, ever
3. Cargo's dependency resolver is unable to add 0.2.2-test-1 to the graph/tree/whatever data structure it is using because it lacks the 0.2.2 node, so when resolving dependencies 0.2.2-test-1 does not get considered.

Can someone smarter and with more knowledge than me help me to understand why this is happening?

(Edit: I am also reading through the section of the Cargo Book that talks about patches and local versions and such things. I think it will come in handy for getting around this, but I would still like to know what is wrong.)

**Comment by landonwork** [comment]
Update: I created a version `datatypes 0.2.2` and changed `production3`'s dependency to "^0.2.2" and things resolved normally, but they still do not resolve when I specify `datatypes = "0.2.2-test-1"`.

**Comment by epage** [comment]
> We've been using a suffix, '-test-' followed by the number of the attempt, to push and test bug fixes on our crates including this one. 

While some ecosystems have both pre-release and post-release suffixes (e.g. [python](https://peps.python.org/pep-0440/#public-version-identifiers)), [semver 2.0](https://semver.org/) (which cargo mostly follows) only recognizes pre-release suffixes.  Cargo also does not have `^` version requirements (the default operator) match pre-release versions by default.

**Comment by Eh2406** [comment]
> But when it tries to resolve this version with the other dependencies, it's like it has become invisible.

There are many interconnected things going wrong here. But the most direct one is a recently discovered bug where that error message refuses to print out pre-release versions. https://github.com/rust-lang/cargo/issues/11006#issuecomment-1220015041 So the line `versions that meet the requirements `>=0.2.1, <0.3.0` are: 0.2.1` is just lying to you. Sorry. It should not be hard to fix. PRs welcome.

> Cargo does not consider 0.2.2-test-1 to be newer than 0.2.1

This is not consistent with my understanding of how cargo works. In semver 2.0 `0.2.1` is before `0.2.2-test-1` witch is before `0.2.2`.

> Cargo's dependency resolver is unable to add 0.2.2-test-1 to the graph/tree/whatever data structure it is using because it lacks the 0.2.2 node, so when resolving dependencies 0.2.2-test-1 does not get considered.

This is also not consistent with my understanding. Different versions of packages are considered completely separately. There is no dependence between a version with pre-release and it's corresponding version without.

> Cargo does not automatically upgrade to versions with suffixes, or "minor-minor" versions, ever

This is much closer to being true. A version requirement that does not include a suffix can not match any version with a suffix, and it can only match if the major minor and patch all are the same no matter what the operator is. This is not a particularly practical semantics, but unfortunately we are stuck with it due to backwards compatibility.

`"^0.2.2-test-1"` matches `0.2.2-test-1` as the major minor and patch are the same, and it matches the ordering requirements provided by `^`

`">=0.2.1, <0.3.0"` or `"^0.2.1"` will not match `0.2.2-test-1` even though it matches the ordering requirement provided by `^`, because none of the requirements (with the same major minor and patch) has a suffix
