### ISSUE TITLE
Cannot work offline

### ISSUE THREAD

**Issue by ijackson** [rust-lang/cargo#11074]
### Problem

I am about to board a ferry from Wales to Ireland.  On the ferry and for much of the rest of my trip, I will have no useful internet access.  I am developing a proc macro crate.  That crate's tests use `macrotest`, which in turn runs `cargo metadata` and `cargo expand`.

These commands access the internet.  I can run `cargo --offline test` but that doesn't help, because the inner cargo invocations run online.

As far as I can tell there is nothing sensible that the `cargo expand` crate, or the `macrotest` crate, could do about this.  They could support a custom environment variable to add to their cargo runs, but that seems like a bad idea.

### Proposed Solution

cargo should honour `CARGOFLAGS`.  Then I could set `CARGOFLAGS=--offline`.

Additionally, cargo should honour `--no-locked` to override `CARGOFLAGS=--offline --locked`.  That way, I could set `CARGOFLAGS=--offline --locked` and crates like `macrotest` that build little private projects could use `--no-locked` to indicate that they need to regenerate the lockfile.  (Ideally they would somehow have their deps represented in the toplevel lockfile but I suspect that is too hard wth the current architecture of cargo.)

See also #9273 #8207 #11041.

In the meantime I am going to try putting a shell script wrapper called `cargo` on my `PATH`, which will  force offline mode.  I don't know how this will interact with rustup's cargo wrapper.  Badly I suspect :-/.

**Comment by epage** [comment]
> As far as I can tell there is nothing sensible that the cargo expand crate, or the macrotest crate, could do about this. They could support a custom environment variable to add to their cargo runs, but that seems like a bad idea.

`cargo expand`  supports `--offline`, so it does its part.

The interesting part is `macrotest` because the tests likely can't run with `--offline` in some scenarios (like fresh CI runs) which makes `--offline` a transient flag based on the environment and so doesn't belong in the `macrotest` crate or in the calls to the `macrotest` crate.  As you call out, an environment variable is best.  The main question is whether to be in `macrotest` or `cargo` (for now, not going to comment on that, just wanted to expand on the use case).

**Comment by ehuss** [comment]
Offline mode can be globally enabled via the [`net.offline`](https://doc.rust-lang.org/nightly/cargo/reference/config.html#netoffline) config option. That can also be set with the `CARGO_NET_OFFLINE=true` environment variable.
 Does that sufficiently handle your use case?
