### ISSUE TITLE
Support setting "-C linker=" for rustc

### ISSUE THREAD

**Issue by hukka** [rust-lang/cargo#1109]
Some cross compilation tools have prefixes in their name and path, for example the armel linker on Debian is /usr/bin/arm-linux-gnueabi-gcc. Cross compile targets would need a way to specify -C linker for rustc in the manifest.

**Comment by mpe** [comment]
For anyone else who doesn't read the documentation properly, the ```target.$triple.linker``` settings goes in ```.cargo/config``` **not** in ```Cargo.toml```. If you put it in ```Cargo.toml``` it will be silently ignored.

eg:
```
[target.arm-unknown-linux-gnueabi]
linker = "/usr/bin/arm-linux-gnueabi-gcc"
```

**Comment by tigerleapgorge** [comment]
> If you put it in Cargo.toml it will be silently ignored.

Isn't that rather error prone?

**Comment by rightfold** [comment]
How do I find my target triple?

**Comment by alexcrichton** [comment]
@rightfold if you run `rustc -vV` it'll tell you the default target that you compile for (under `host`), otherwise you're passing `--target` in which case that's the target triple.

**Comment by rightfold** [comment]
Thanks! 😃

Sent from my iPhone.

**Comment by jeroen** [comment]
Is there any way to set the linker via an environment variable or `cargo` parameter rather than a config file?

**Comment by jeroen** [comment]
@alexcrichton what environment variable would I use to set the `linker` for `target.x86_64-pc-windows-gnu` and `target.i686-pc-windows-gnu`?

**Comment by jeroen** [comment]
Or just in general can I set the linker for the current cargo build (any target)?

**Comment by alexcrichton** [comment]
@jeroen you'd use `CARGO_TARGET_I686_PC_WINDOWS_GNU_LINKER`

**Comment by jeroen** [comment]
Thanks @alexcrichton! Now I am stuck on one final issue:

We use a version of mingw-builds that was compiled with `--static-gcc`. Therefore our toolchain does not contain a copy of `libgcc_eh.a`, instead those objects are available from `libgcc.a`. 

Currently when I try to build [imageoptim-sys](https://crates.io/crates/imagequant-sys) the linker fails because it can't find `libgcc_eh.a`. I think that is because this flag is [hardcoded in rust](https://github.com/rust-lang/rust/blob/385ef1514c80fb8c0cb061dc69eb1d953a84e2b3/src/libunwind/build.rs#L38). Is there some way I can tell rust that my linker wants to be linked with `-lgcc` instead of `-lgcc_eh`? 

The cmake folks have a [similar topic](https://gitlab.kitware.com/cmake/cmake/merge_requests/1460) about not linking to `libgcc_eh` directly.

**Comment by alexcrichton** [comment]
@jeroen ah unforutnately you can't change that right now, so the only recourse would be to write a wrapper script that translates `-lgcc_eh` to `-lgcc`, it's not great :(

**Comment by lobianco** [comment]
For anyone who stumbles into this thread looking for an answer that doesn't involve `.cargo/config`, you can set the linker as a parameter of your `cargo` command like this:

```bash
RUSTFLAGS="-C linker=/path/to/linker" cargo run ...
```

**Comment by sanmai-NL** [comment]
> @jeroen ah unforutnately you can't change that right now, so the only recourse would be to write a wrapper script that translates `-lgcc_eh` to `-lgcc`, it's not great :(

See https://github.com/rust-lang/rust/issues/29527
