### ISSUE TITLE
`cargo publish` error message unhelpful with `publish = false`

### ISSUE THREAD

**Issue by wooorm** [rust-lang/cargo#11262]
### Problem

```sh
$ cargo publish --dry-run
error: `xxxxxxxx` cannot be published.
The registry `crates-io` is not listed in the `publish` value in Cargo.toml.
```

It’s a bit stupid on my part, I forgot for a second that I had `publish = false` in my `Cargo.toml` to prevent publishing, but this error message threw me off.
I can imagine that some other folks would run into this too, so I’m raising this here.

### Proposed Solution

How about an error message, if `publish = false`, along the lines of:

```
error: `xxxxxxxx` cannot be published.
`publish` is set to `false` in Cargo.toml and prevents publishing.
```

**Comment by hi-rustin** [comment]
> ```shell
> The registry `crates-io` is not listed in the `publish` value in Cargo.toml.
> ```

I think this message makes sense but maybe needs some improvement.
Cargo said that because we can add a registry list in the `publish` field. You can check out [this reference.](https://doc.rust-lang.org/cargo/reference/manifest.html#the-publish-field)
So I think the error message makes sense to say that. And I think it also makes sense to add a clear error message if we just set the `publish` field be `false`.

I am happy to help improve it if it is acceptable.
