### ISSUE TITLE
Support configuration for "landing-pads"

### ISSUE THREAD

**Issue by tcr** [rust-lang/cargo#1128]
I created a POC branch that allows configuration of landing-pads via profile configuration:

https://github.com/tcr/cargo/commit/b317b0905ee3509bc3ae7eabcc5152f449fe3d76

I wonder if the flexible target spec isn't a better correct location for this feature (defining if unwinding is possible on a target), but profiles was the easiest to add this feature to (a la lto).

**Comment by alexcrichton** [comment]
With `cargo rustc` the need for this is now much less, and I think that this is likely to be better done through a custom target specification in the compiler rather than in Cargo itself. Once the compiler supports a more official "build with no landing pads" feature, however, then Cargo may grow configuration to control that.

For now though I'm going to close this due to `cargo rustc`
