### ISSUE TITLE
`cargo publish` times out waiting for crate to be in index with sparse-registry with JFrog

### ISSUE THREAD

**Issue by yuvalojfrog** [rust-lang/cargo#11314]
### Problem

In JFrog we have an automation that verifies the cargo sparse support using the nightly image.
As soon as version cargo 1.66.0-nightly (7e484fc1a 2022-10-27) was released, we began to notice that publishing was unstable and sometimes took quite a while, which caused a timeout in our tests. The question was if there have been any recent changes in publish that might lead to performance issues.

**Comment by epage** [comment]
Could you clarify what you mean by unstable?

Could you provide the output?

A likely candidate is our new [blocking feature](https://github.com/rust-lang/cargo/issues/9507#issuecomment-1296058029).  Any idea why this would be incompatible with JFrog?

**Comment by yuvalojfrog** [comment]
Thank you so much for responding so quickly.
In response to your link, we added timeout = 0 with the -Zpublish-timeout and it seems to have resolved the issue.
When we continuously push two packages with different versions one after the other, the second publish failing most of the times.
is it expected? or an issue that will be fixed before the stabilization of the sparse index feature

**Comment by epage** [comment]
The blocking feature is independent of the index protocol used and is expected to stablize in 1.66.  Ideally, we can root cause this quickly to know if there is a fundamental bug in it.

There are several parts to where this could be going wrong:
- publishing the crate, client side
- publishing the crate, server side
- blocking on the update / updating the index

Can you provide reproduction steps verbose `cargo publish` output (even better is configure `CARGO_LOG`)?

Can this be reproduced with your git registry support or with crates.io with either protocol?

**Comment by yuvalojfrog** [comment]
we can't reproduce it with the git registry.
[CARGOLOG.txt](https://github.com/rust-lang/cargo/files/9920436/CARGOLOG.txt)
here is the cargo_log

**Comment by epage** [comment]
I've tried creating various test cases to reproduce this but haven't been able to so far.

There is a chance there is a bug in JFrog's backend.  Could you do some debugging on this to help figure out if its on cargo of JFrog's end?

**Comment by yuvalojfrog** [comment]
We ruled out the possibility that it was a bug on our side for a number of reasons:
1. We haven't made any changes recently.
2. We are also experiencing the same errors in previous versions of our product, versions that have worked so far.
3. With an earlier nightly version we experience no problems.
4. After adding the suggested workaround, everything works.
