### ISSUE TITLE
Attempting to run `cargo new hello_cargo` gives an error, not finding `safe.directory`

### ISSUE THREAD

**Issue by bismurphy** [rust-lang/cargo#11365]
### Problem

Hello,

I'm attempting to start using Rust for the first time. I was going through this guide:

https://doc.rust-lang.org/book/ch01-03-hello-cargo.html

I ran the basic Hello World, and now when it was time to start using Cargo, I went into my projects directory (which currently holds only the `hello_world` directory), and, as per the guide, ran `cargo new hello_cargo`. When I run this, I get the following error:

```
error: Failed to create package 'hello_cargo' at '/home/bismurphy/Projects/Rust/hello_cargo'

Caused by:
  config value 'safe.directory' was not found; class=Config (7); code=NotFound (-3)
```

After this occurs, the `hello_cargo` directory has been created, but is empty.

### Steps

Unable to provide any reliable reproducing steps.

### Notes

I'm running a fairly fresh installation of Mint 21. I just installed it last week. I'm not using Docker or anything like that, and I just installed Rust with the procedure listed in the guide I linked above.

### Version

```text
cargo 1.65.0 (4bc8f24d3 2022-10-20)
release: 1.65.0
commit-hash: 4bc8f24d3e899462e43621aab981f6383a370365
commit-date: 2022-10-20
host: x86_64-unknown-linux-gnu
libgit2: 1.5.0 (sys:0.15.0 vendored)
libcurl: 7.83.1-DEV (sys:0.4.55+curl-7.83.1 vendored ssl:OpenSSL/1.1.1q)
os: Linux Mint 21 (vanessa) [64-bit]
```

**Comment by ehuss** [comment]
Thanks for the report!  I have identified what is causing the error and am preparing a fix.

As for getting you up and running now, we might need to do a little investigation to figure out why it is happening to you.

The problem is that git doesn't allow opening git repositories that are owned by a different user.  If you are creating your project in a directory that is owned by a different user, that looks like it will trigger the error.

Can you check what your current user is (running `id`) and check the ownership of the directory you are creating your project in? 

If the ownership is different, some things you can do:
* Change the ownership so they are the same
* Work in a different directory where you can ensure the ownership is the same
* Alternatively, you can add the `safe.directory` config option to your global git config. There is more information [here](https://git-scm.com/docs/git-config#Documentation/git-config.txt-safedirectory) about this option and what it does.

And, finally, I think you can just ignore the error.  IIUC, `cargo new` has completed successfully, it's just doing a check at the end that is failing.  There should be a `Cargo.toml` and `src` directory with your new project.

**Comment by bismurphy** [comment]
Got it! I changed the ownership to be the same (the directory I was using was from an old Linux installation and it was still registered to the old user). Seems that this was just a matter of poorly-written error message.

I was now able to run the cargo command as expected.
