### ISSUE TITLE
Cargo should pass -W unstable=allow when building examples, tests and benches

### ISSUE THREAD

**Issue by tomaka** [rust-lang/cargo#1147]
Tests, examples and benches are written against a library. If this library's functions are marked as unstable (which should be the case during the library's development process), compiling them will produce lots of warnings which don't really make sense.

This will be even worse when `unstable` will switch from `warn` to `deny`. You will be forced to add `#[allow(unstable)]` in every single test, bench or example.

**Comment by alexcrichton** [comment]
Due to https://github.com/rust-lang/rfcs/blob/master/text/0507-release-channels.md and the clear indication that stability attributes aren't intended for third-party libraries right now, I don't think that Cargo wants to do this.

In a theoretical system that Cargo does grow, however, this would most certainly be a concern!
