### ISSUE TITLE
Impossible to publish: failed to prepare local package for uploading

### ISSUE THREAD

**Issue by contactomorph** [rust-lang/cargo#11522]
### Problem

When trying to publish my crate:
```
PS C:\repos\tensorism> cargo publish -vv
    Updating crates.io index
   Packaging tensorism v0.1.0 (C:\repos\tensorism)
   Archiving
error: failed to prepare local package for uploading

Caused by:
  failed to open for archiving: `C:\repos\tensorism`

Caused by:
  Access is denied. (os error 5)
```

### Notes

I tried to publish it from a friend's machine, suspecting the problem was related to something about my local environment but I got exactly the same error.

### Version

```text
cargo 1.67.0-nightly (f6e737b1e 2022-12-02)
release: 1.67.0-nightly
commit-hash: f6e737b1e3386adb89333bf06a01f68a91ac5306
commit-date: 2022-12-02
host: x86_64-pc-windows-msvc
libgit2: 1.5.0 (sys:0.15.0 vendored)
libcurl: 7.86.0-DEV (sys:0.4.59+curl-7.86.0 vendored ssl:Schannel)
os: Windows 10.0.19045 (Windows 10 Pro) [64-bit]
```

**Comment by weihanglo** [comment]
Not exactly the same issue but probably you can follow this to investigate <https://github.com/rust-lang/cargo/issues/11544>.

**Comment by ehuss** [comment]
This is caused by having an empty readme field in `Cargo.toml`:

```toml
[package]
name = "foo"
version = "0.1.0"
readme = ""
```

This also happens with `license-file = ""`.

I think the solution is to generate a better error message when `readme` or `license-file` is set to an empty string.

**Comment by kylematsuda** [comment]
Hi! So the problem seems to be the following lines from the `build_ar_list` function for `license-file` (and a similar section below that for `readme`):

https://github.com/rust-lang/cargo/blob/be338923a4b54ba4462b29248011014bd0d2bbcf/src/cargo/ops/cargo_package.rs#L281-L293

If `license-file = ""`, then `abs_file_path` points at the crate root and the `abs_file_path.exists()` check is `true`, leading to `abs_file_path` being added to the archive list. The error then occurs later when `tar` is eventually called, which expects a file for `license-file` instead of a directory.

A simple fix could be to change `Path::exists` to `Path::is_file`. This would also catch the case where an existing directory is provided for `license-file`, for example `license-file = "./src"` (which currently causes the same error as `license-file = ""`).

Does that approach sound okay? The same change (+ adding a helpful warning message) should also work for `readme`.

**Comment by ehuss** [comment]
That sounds good to me!
