### ISSUE TITLE
Stance on C library dependencies

### ISSUE THREAD

**Issue by djrenren** [rust-lang/cargo#1153]
I'm seeing several libraries linking against precompiled C libraries, especially ones like OpenGL, freetype, SDL2, etc.

These libraries are requiring a C library to be installed on the OS prior to installation with Cargo. This behavior essentially breaks down the awesome "`cargo build` and forget" model.

Is there a community stance on whether or not this is something we should continue doing?

Obviously, I fall into the camp that thinks we should discourage this, and act similar to node where libraries with native components pull their native dependencies at install time. Any thoughts?

**Comment by zmyaro** [comment]
+1

**Comment by weswigham** [comment]
The only time this would is even half-acceptable is when you have a tool akin to `gyp` (which is a hack in its own way) to build the dependencies cross-platform. `cargo` does lose a lot of its use if it can't take you from 0 to functioning reasonably. While I understand that linking into existing C libraries is often a requirement for stuff like SDL, it should probably be expected that a given package can give you some way to build or acquire that dependency (without telling you to figure it out on your own - especially since there's normally versioning constraints which need to be adhered to).

**Comment by alexcrichton** [comment]
This was actually one of the primary motivations for Cargo's [build script](http://doc.crates.io/build-script.html) feature. Build scripts are the primary sources for learning about native libraries, where they're located, and how to link to them. This ends up meaning that the responsibility of ensuring that a C library is available is on the crate's build script itself, not cargo.

Many build scripts today bundle the C library's source, but this is not necessarily a requirement. I would open up issues on specific repositories requesting that the build scripts were beefed up to handle the case that a library is missing on the target platform, but do keep in mind that this does often require some nontrivial implementation work!

As Cargo supports this use case, however, I'm going to close this as basically fixed.

**Comment by djrenren** [comment]
Ah that makes tons of sense. Is there some sort of "best practices" doc that this could be put in?

**Comment by alexcrichton** [comment]
I'd love to add more to the documentation! The page I linked to is probably the best place to put it currently.
