### ISSUE TITLE
Redirect nightly doc to `doc.rust-lang.org/nightly/nightly-rustc/cargo`

### ISSUE THREAD

**Issue by weihanglo** [rust-lang/cargo#11555]
### Problem

After https://github.com/rust-lang/rust/pull/105036, docs of Cargo and its companion crates are live now at https://doc.rust-lang.org/nightly/nightly-rustc.

I wonder whether https://doc.crates.io/contrib/apidoc/cargo should be redirected to that "canonical" URL. It might be more discoverable as all rustc internal docs are already there, whereas the doc will only get updated when cargo gets synced into `rust-lang/rust` repo, which happens only once or twice a week.

### Proposed Solution

Follow the steps:

1. Replace all occurrences of `doc.crates.io/contrib/apidoc/cargo` with `doc.rust-lang.org/nightly/nightly-rustc/cargo` in this repo.
2. Do a [redirect](https://rust-lang.github.io/mdBook/format/configuration/renderers.html?highlight=redirect#outputhtmlredirect) in [mdbook `book.toml`](https://github.com/rust-lang/cargo/blob/master/src/doc/book.toml) from `/apidoc/cargo` to `https://doc.rust-lang.org/nightly/nightly-rustc/cargo`.
3. Remove CI changes in ba3d2e981bf69b13f7024eee7914e719a96cc620 and 1c82d9c8c3f00075ea4535fcd5fb86fb8dd99ac6.

**Comment by weihanglo** [comment]
cc @epage, as you participated in the PR building API doc. I personally favor keeping only <https://doc.rust-lang.org/nightly/nightly-rustc/cargo> though is fine with having both.

**Comment by epage** [comment]
I'm fine with that.  I assume the main side effect is it isn't updated until rust-lang/rust updates their copy of cargo?

**Comment by weihanglo** [comment]
Yep. That's the main one. I cannot think of others at this moment though.

**Comment by jofas** [comment]
Hi,
person who is looking to make his first-time contribution here. Do I understand the [contribution guide](https://doc.crates.io/contrib/process/index.html#issue-assignment) correctly that as long as this issue is tagged `E-easy`, I can open a PR that will be merged? Double checking, because [`CONTRIBUTING.md`](https://github.com/rust-lang/cargo/blob/master/CONTRIBUTING.md) has a prominent notice, that only issues with `Feature accepted` tag are considered for merging.

**Comment by weihanglo** [comment]
Thank you for asking! The words might be a bit too strong but the team does have a limited capacity for both design and code review. The idea here is to encourage people to start a discussion from an issue before submitting a pull request.

In general, with <https://github.com/rust-lang/cargo/labels/E-easy> label an issue is good to give it a shot. <https://github.com/rust-lang/cargo/labels/E-mentor> is similar as well. I'll also take care of that if it's tagged by me.

If you are willing to help a certain issue, you could optionally post a comment `@rustbot claim` to assign yourself.

**Comment by jofas** [comment]
Great, thank you!

**Comment by jofas** [comment]
> 2\. Do a [redirect](https://rust-lang.github.io/mdBook/format/configuration/renderers.html?highlight=redirect#outputhtmlredirect) in [mdbook `book.toml`](https://github.com/rust-lang/cargo/blob/master/src/doc/book.toml) from `/apidoc/cargo` to `https://doc.rust-lang.org/nightly/nightly-rustc/cargo`.

I'm not quite sure which `book.toml` to change here, [`src/doc/book.toml`](https://github.com/rust-lang/cargo/blob/master/src/doc/book.toml) (the one linked in the description) or the [`src/doc/contrib/book.toml`](https://github.com/rust-lang/cargo/blob/master/src/doc/contrib/book.toml). I think that the file @weihanglo wanted to link should be `src/doc/contrib/book.toml`, it would fit the redirection source `/apidoc/cargo` instead of `/contrib/apidoc/cargo`. Also, the contribution guide and the api docs are built in a different CI workflow than the cargo book, so I'd keep everything concerning the contribution guide (including the deprecated apidoc subdirectory) in  [`src/doc/contrib`](https://github.com/rust-lang/cargo/blob/master/src/doc/contrib/), right?

**Comment by weihanglo** [comment]
Oops that's my fault. And yes, you're totally correct! I believe that should work.
