### ISSUE TITLE
 this version of Cargo is older than the `2021` edition, and only supports `2015` and `2018` editions.

### ISSUE THREAD

**Issue by ArieCurzon** [rust-lang/cargo#11657]
### Problem

Although I downloaded the latest rust version I get this error when trying to install a package in PyCharm

**Comment by weihanglo** [comment]
Without a minimal set of steps to reproduce, and the environment you're working in, this is unlikely to investigate the issue further. A few questions may help. 

* How did you download the latest Rust?
* Is PyCharm configured correctly to use the latest Rust version?

Run `cargo -vV` may help identify the version you are currently using. `rustup -vV` may also have some information.

**Comment by ArieCurzon** [comment]
I downloaded rust from https://www.rust-lang.org/tools/install
PyCharm is only used as a wrapper to run pip and install packages. Thus, it
uses the installed version on windows.
Before I installed rust I got a different error that I need to install
it....
cargo -v gives the latest version.

‫בתאריך יום ג׳, 31 בינו׳ 2023 ב-14:24 מאת ‪Weihang Lo‬‏ <‪
***@***.***‬‏>:‬

**Comment by weihanglo** [comment]
I am going to close due to lack of a minimal set of steps to reproduce, and it has been inactive for a while. This seems to be an issue of Rust integration issue inside PyCharm or your python project. Unfortunately we are unable to provide support here for helping with issues. I suggest you try one of the user forums such as <https://users.rust-lang.org/> to see if someone can help. Or if you can create an MCVE, please open a new issue. THank you
