### ISSUE TITLE
`cargo install` does not respect `.cargo/config.toml`

### ISSUE THREAD

**Issue by thoren-d** [rust-lang/cargo#11660]
### Problem

When I run `cargo install ripgrep` in a directory with a `.cargo/config.toml` overriding the install root (like below), it installs to `$HOME/.cargo/bin` instead.

The interesting thing is that `cargo uninstall` reads the configured root correctly, so if I immediately run `cargo uninstall ripgrep` in the same directory, it complains that `package ID specification `ripgrep` did not match any packages`.

Contents of `.cargo/config.toml`:
```
[install]
root = "./apps"
```

### Steps

1. Create a config file like the one above.
2. Make an `apps` directory
3. Run `cargo install ripgrep` (or anything)

### Notes

Also tried nightly just now with the same result.

Obviously I can just `cargo install --root apps ...`, but I was trying to experiment with patching dependencies and building with different compile options and it seems `cargo install` is completely ignoring the configuration file.

### Version

```text
cargo 1.67.0 (8ecd4f20a 2023-01-10)
release: 1.67.0
commit-hash: 8ecd4f20a9efb626975ac18a016d480dc7183d9b
commit-date: 2023-01-10
host: x86_64-pc-windows-msvc
libgit2: 1.5.0 (sys:0.16.0 vendored)
libcurl: 7.86.0-DEV (sys:0.4.59+curl-7.86.0 vendored ssl:Schannel)
os: Windows 10.0.22621 (Windows 10 Pro) [64-bit]
```

**Comment by ehuss** [comment]
Thanks for the report! It is intentional behavior that `cargo install <registry-package>` does not honor the configuration in the current working directory. I think there are two issues here:

* That does not seem to be documented in the [cargo install](https://doc.rust-lang.org/cargo/commands/cargo-install.html) page.
* `cargo uninstall` should probably have similar behavior to avoid the asymmetry.

**Comment by weihanglo** [comment]
For the installation root precedence, the rule is not documented at all. It starts searching configurations upward from the given `--path`, or `CARGO_HOME` if no `--path` provided. This should probably be documented as well.

https://github.com/rust-lang/cargo/blob/efd37336e94e2f98260ad28d89e509e02fe4a556/src/bin/cargo/commands/install.rs#L89-L95

I wonder if we could reconsider calling `set_search_stop_path(home)`, though it is definitely a breaking change, so 🤷🏾‍♂️.

**Comment by jofas** [comment]
> * That does not seem to be documented in the [cargo install](https://doc.rust-lang.org/cargo/commands/cargo-install.html) page.

Any reason why `cargo install` ignores the configuration in the current directory? It would probably be a good idea to add the reason behind this decision to the documentation.

@rustbot claim

**Comment by weihanglo** [comment]
@jofas 
See https://github.com/rust-lang/cargo/pull/6026. The basic idea here is `cargo install` is a system or user level command instead of project-local. For `--path` <https://github.com/rust-lang/cargo/pull/6804> tells that it makes sense `--path` respecting project local configurations.

**Comment by jofas** [comment]
Thanks for the explanation!

**Comment by jofas** [comment]
I think in order to document the fact that  `cargo install` (and in the future `cargo uninstall`) only consider the global configuration file in `$CARGO_HOME/config.toml`, I'd like to add a small note here:

https://github.com/rust-lang/cargo/blob/426263643a17692504ad3dc7d627556850c7f1ce/src/doc/man/includes/description-install-root.md?plain=1#L5

Something along the lines of 

> **Note:** only the global configuration file `$CARGO_HOME/config.toml` is considered

As the snippet is only used for the man pages of `install` and `uninstall` (and both will have the same behaviour), I think this should be okay?

Somwhere here on the `cargo install` man page :

https://github.com/rust-lang/cargo/blob/426263643a17692504ad3dc7d627556850c7f1ce/src/doc/man/cargo-install.md?plain=1#L48-L50

I'd add a note saying that using `--path` will change the default behaviour of `cargo install` to only consider the configuration in `$CARGO_HOME/config.toml` to the configuration at the given path.

Any thoughts anyone? @weihanglo?

**Comment by weihanglo** [comment]
I am fine with your suggestion, though it's a bit complicated. Not only `install.root` is ignored but the entire [configuration discovery] starts from `$CARGO_HOME/config.toml` instead of current working directory. I am not sure if it is worth putting so much concepts here. The suggested fix of `--path` looks good but falls into the same situation as well.

In terms of the display on manpage, I only found one `quote` usage in man in [`cargo bench`](https://github.com/rust-lang/cargo/blob/9d5b32f503fc099c4064298465add14d4bce11e6/src/doc/man/cargo-bench.md#L42). It looks good to me btw via `cargo help bench` (the bad part is due to link rendering). If you don't feel satisfied with the way it displays, we can also fall back to starting with plain `Note that…`.

[configuration discovery]: https://doc.rust-lang.org/nightly/cargo/reference/config.html#hierarchical-structure

**Comment by jofas** [comment]
> I am not sure if it is worth putting so much concepts here.

That was my reservation, too. I just couldn't figure out a good spot where I could add the relevant information in the text on first glance. I'll figure something out and create a PR where we can discuss further details.
