### ISSUE TITLE
Confusing dead code warning with module unused in lib target

### ISSUE THREAD

**Issue by bryceberger** [rust-lang/cargo#11686]
### Problem

When a module is declared as a `mod example;` in `lib.rs` but not used, `cargo build` warns about dead code. However, the output does not mention that the dead code is for the `lib` target, even if the code is used in the `bin` target. (Confusingly, the warning also shows up when running `cargo build --bins`?)

### Steps

`main.rs`
```
mod example;

fn main() {
    example::do_something();
}
```

`lib.rs`
```
mod example;
```

`example.rs`
```
pub fn do_something() {
    println!("did something");
}
```

Run `cargo build`, `cargo build --bins`, `cargo run`, or similar

### Possible Solution(s)

Classify warnings based on which target they come from, don't display warnings for targets not being built.

### Notes

(Please correct me if I'm wrong in my assumption of what's going on here, not entirely familiar with `cargo`)

### Version

```text
cargo 1.65.0-nightly (4ed54cecc 2022-08-27)
release: 1.65.0-nightly
commit-hash: 4ed54cecce3ce9ab6ff058781f4c8a500ee6b8b5
commit-date: 2022-08-27
host: x86_64-unknown-linux-gnu
libgit2: 1.5.0 (sys:0.15.0 vendored)
libcurl: 7.83.1-DEV (sys:0.4.55+curl-7.83.1 vendored ssl:OpenSSL/1.1.1q)
os: Arch Linux [64-bit]
```

**Comment by weihanglo** [comment]
Thanks for the report. I am not sure how to improve it. 

When you run `cargo build`, it builds all binary and library targets[^1]. In your example, it in fact calls `rustc` twice: one for the library target and one for the binary. During rustc builds lib target, it notices that no one uses `example` mod so the warning appears.

```console
warning: function `do_something` is never used
 --> src/example.rs:1:8
  |
1 | pub fn do_something() {
  |        ^^^^^^^^^^^^
  |
  = note: `#[warn(dead_code)]` on by default

warning: `x` (lib) generated 1 warning  <--- THIS LINE SHOWS `(lib)` TARGET GENERATED 1 WARNING
    Finished dev [unoptimized + debuginfo] target(s) in 1.19s
```


There is an implicit assumption that binaries in the same Cargo package depends on the library target. That means even you run `cargo build --bins` it'll still build the library target. That's why you still saw the warning there.

To share code between library target and binary targets, I would recommend  letting library target expose them (e.g. `pub mod`), and then binary targets use them via library target.


[^1]: https://doc.rust-lang.org/nightly/cargo/commands/cargo-build.html#target-selection

**Comment by bryceberger** [comment]
Ah, somehow I had never noticed the line that specifically says the lib target generated the warning. That's the feature I had in mind. Seems to be a user issue more than a tool issue, thanks!
