### ISSUE TITLE
Enhance the doc of timing report with graphs

### ISSUE THREAD

**Issue by weihanglo** [rust-lang/cargo#11708]
### Problem

The chapter "[Reporting build timings](https://doc.rust-lang.org/nightly/cargo/reference/timings.html#reporting-build-timings)" is well written. It could be way better if we have graphs and tables along with the explanation.

### Proposed Solution

The chapter mentions there are two graphs in the report, so at least we could have two graphs and maybe include two tables as well. We could have pointers and indicators on those graphs, making it more learnable and understandable. Human are visual animals anyway.

<img width="405" alt="image" src="https://user-images.githubusercontent.com/14314532/218761830-e3e93faf-bcba-4f15-b8d1-b9c0163b68da.png">

**Comment by epage** [comment]
Aside: that graph looks so much better than the old one with `toml_edit` takinga really long time to compile.

I should see what can be done to improve `nom8`s compile times.

**Comment by QiangHeisenberg** [comment]
There are some details that I'd like to discuss, whether to choose Cargo as an example of the image? Because Cargo builds with a large number of units, the picture will be large if it's all displayed. For example, the first time I used it, I had 222 units.

Or adjust the parameters and display them? For example, the following.
![image](https://user-images.githubusercontent.com/46313511/219351737-97d88fae-e39e-4546-b4c3-9acddde8493a.png)



There is also an issue where the build times on the chart don't match the times on my system, sometimes poor. Should it be adjusted to the system time?
