### ISSUE TITLE
Cargo version

### ISSUE THREAD

**Issue by mdinger** [rust-lang/cargo#1178]
I didn't see the cargo version process specified but cargo is currently version 0.0.1 and rust version 1.0 alpha. Will cargo go 1.0 with rust? If this is undecided, it might be useful to specify somewhere.

**Comment by coderanger** [comment]
To make this a bit more concrete, it would be really nice if when the 1.0 beta comes out (or next alpha if one happens) that there is a simultaneous alpha/beta release of cargo. This makes life a lot easier for people building packages and distributing Rust since right now there is no specific version of Cargo that corresponds to 1.0.0-alpha beyond whatever commit the official installers happened to use.

**Comment by jljusten** [comment]
@brson: Since you updated the rust page for the alpha release, would you happen to know which cargo version was included with the alpha release builds? Maybe that cargo version could be tagged?

**Comment by brson** [comment]
At the moment there aren't concrete plans to make releases of Cargo. The Cargo nightly that corresponds to releases of Rust is in this file: https://github.com/rust-lang/rust-packaging/blob/master/cargo-revs.txt. Note that it's only set up to permanently record cargo revisions for stable releases of Rust.

cc @alexcrichton

**Comment by jljusten** [comment]
cargo-revs.txt has:
<pre>
1.0.0: 2015-01-07
</pre>

That doesn't really indicate a particular cargo hash, nor does it indicate 'alpha'. Would it be possible to clarify that in cargo-revs.txt? (Assuming a cargo tag isn't possible.)

**Comment by brson** [comment]
@jljusten That's right, it's just a date from the nightly archives, and it's not connected to the alpha. The way cargo versions in rust-packaging is set up doesn't account for the pre-1.0 release process - it only considers stable releases to be releases.

It would be possible to add more metadata there but I'm not sure its the appropriate place since the tool doesn't require it.

**Comment by jljusten** [comment]
@brson: Is it possible to trace that nightly cargo release back to a cargo repo version?

**Comment by brson** [comment]
@jljusten Yes, `cargo --version` will print the git commit, though I'd like to make that bit of metadata more accessible for tooling: https://github.com/rust-lang/rust/issues/21243

**Comment by jljusten** [comment]
In case anyone is interested, for the 1.0.0 alpha it appears to be 23ed197405509ae17654a86b6d59a8fb6d367f9e:
<pre>
rust-1.0.0-alpha-x86_64-unknown-linux-gnu/bin$ ./cargo --version
cargo 0.0.1-pre-nightly (23ed197 2015-01-06 02:37:42 +0000)
</pre>

I suppose the cargo-revs.txt date discrepancy is due to the commit vs. build times, but it certainly doesn't help with the confusion. :)

**Comment by alexcrichton** [comment]
I don't particularly have many strong opinions here, as @brson said we don't have a clear story for the versioning of Cargo separate from Rust right now.

That being said I don't mind "cutting a version" at some point to just say that we're on 0.1.0 or something like that.

**Comment by beatgammit** [comment]
"cutting a version" makes it much easier to package, so I'm very much in favor of giving it a version number.

@alexcrichton Where is the best place to start the discussion on if/how `cargo` releases relate to `rust` releases?

**Comment by callahad** [comment]
FWIW, Rust 1.0.0-beta shipped with:

    $ ./cargo --version
    cargo 0.0.1-pre-nightly (84d6d2c 2015-03-31) (built 2015-03-31)

Link: https://github.com/rust-lang/cargo/commit/84d6d2c7d6d8c28e3c1b10c2ec43032f75fd3c44

**Comment by lloeki** [comment]
FYI, this is blocking on [Homebrew](https://github.com/Homebrew/homebrew/issues/33322), so there's currently only a rust package and no cargo, which drastically reduces usefulness.
