### ISSUE TITLE
alias "i" for "install"

### ISSUE THREAD

**Issue by JimLynchCodes** [rust-lang/cargo#11838]
### Problem

Currently cargo doesn't recognize "cargo i enquirer"

### Proposed Solution

`cargo i ...` can be an alias for `cargo install ...` 

### Notes

This is how npm and other package managers work. Also, it's just a nice user experience.

**Comment by epage** [comment]
Since `npm` is mentioned, I thought I'd check what the [documentation](https://docs.npmjs.com/cli/v9/commands/npm-install) says:
```
npm install [<package-spec> ...]

aliases: add, i, in, ins, inst, insta, instal, isnt, isnta, isntal, isntall
```

I appreciate their helping people with typos :)

**Comment by epage** [comment]
Some quick thoughts on the role of aliases
- For interactive and not programmatic use as programmatic use should use more explicit forms of things
- For something done frequently.

Maybe my perspective is just limited but `install` does not seem like a frequent enough command to justify an alias.  Not being a node developer, whats not too clear to me is if `npm install` is a good precedence for "this justifies an alias" because it is unclear to me whether `npm install` is more like `cargo install`, `cargo add`, or a combination of the two.  The `cargo add` workflow I see as being a higher use workflow (not as high as `build` and `test`) though its already a short command name.

**Comment by weihanglo** [comment]
> Maybe my perspective is just limited but `install` does not seem like a frequent enough command to justify an alias.

Agree on this. It's also what I just thought of. Do we have any popular  command that may fit alias `i`?

**Comment by epage** [comment]
Honestly,. I probably `cargo init` / `cargo new` more often than `cargo install` but I don't think `cargo init` deserves an alias

**Comment by Turbo87** [comment]
@epage `npm install` is a lot more common since it installs the current dependencies of the package into the `node_modules` folder. if `npm install foo --save` is used it would be roughly equivalent to `cargo add foo`. 

given that `cargo install` is entirely different from `npm install` and used a lot less, I don't think we necessarily need such an alias.

**Comment by JimLynchCodes** [comment]
why are `cargo add` and `cargo install` not the same thing?

**Comment by Turbo87** [comment]
see https://doc.rust-lang.org/cargo/commands/cargo-add.html vs. https://doc.rust-lang.org/cargo/commands/cargo-install.html

**Comment by QiangHeisenberg** [comment]
I don't think this alias will help me much, but may cause confusion.

**Comment by ehuss** [comment]
The cargo team discussed this, and have decided that this isn't something we want to add at this time. Some of the concerns are:

* `cargo install` is quite a bit different from `npm install`. We want installing to be a clear and explicit operation.
* `cargo install` isn't something we expect the user to reach for very frequently.
* There is ambiguity with `cargo init`.

Thank you for the suggestion, though!

**Comment by VuiMuich** [comment]
Just wanted to leave on possible use case where `cargo install` could occur in regular use:

There is a bunch of projects, that are stable enough to live on the `main`/`dev` branch with daily use. For me those are `helix`, `nushell`, `atuin` and `wire-notify` among others.
To some I have or am currently contributing, others I like to have the `README` and examples around so I clone the repo instead of installing the package, so for convenience I use `cargo install` quite a lot. 

Possible other workflows would of course be symlinking the binaries or adding the target directory to PATH, but in most cases this would less convenient, at least imho.

I don't necessarily want this issue to be reopened, but provide some insight in possible cases where the alias might be actually useful and bring a small qol improvement if this gets debated in the future.
