### ISSUE TITLE
New project creating default

### ISSUE THREAD

**Issue by EdorianDark** [rust-lang/cargo#1188]
Currently a new project is created by `cargo new hello_world --bin`.
I think that especially for beginners it is more common to begin a new program than to begin a new library.
The default should be the most used option.

Or do you think that more libraries than programs are build?

**Comment by alexcrichton** [comment]
cc @steveklabnik, @wycats, thoughts on this?

**Comment by steveklabnik** [comment]
Unsure. I think both of us maybe write way more libraries than not.

**Comment by schickling** [comment]
+1 for bin

**Comment by FlashYoshi** [comment]
@steveklabnik isn't this because Rust is still developing it's standard library and not many libraries exist for it yet? If you take look at wider spread languages, like C, I think more programs than libraries are written. Those would especially be small programs, for a school project for example, but a program, not a library nevertheless.

**Comment by steveklabnik** [comment]
No, it's just a consequence of the fact that a single application depends on > 1 library. At worst, it's 1-1.


Even in a well-developed language like Ruby, lots of libraries get written.

**Comment by steveklabnik** [comment]
(Thinking about that now, they can depend on the _same_ library, so that intuition isn't valid. Still, bundler defaults to a library.)

**Comment by FlashYoshi** [comment]
Valid argument, I think that answers EdorianDark's question so I suppose this issue can be closed? @steveklabnik

**Comment by alexcrichton** [comment]
I agree with @steveklabnik, so I'm going to close this.
