### ISSUE TITLE
Cargo new / cargo init, origin should be master

### ISSUE THREAD

**Issue by erwanvivien** [rust-lang/cargo#11899]
### Problem

I think it's weird to have many conventions.

[Github](https://github.com/github/renaming#new-repositories-use-main-as-the-default-branch-name) & [Gitlab](https://about.gitlab.com/blog/2021/03/10/new-git-default-branch-name/) changed their default branch name, it would be great to follow.

```bash
➜  heyo git:(master) ✗ cargo new MY_RUST && cd MY_RUST
     Created binary (application) `MY_RUST` package
➜  MY_RUST git:(master) ✗ git st
On branch master
```

### Proposed Solution

Update to main by default

**Comment by weihanglo** [comment]
If I recall correctly, the behavior is controlled by Cargo's dependency `libgit2`[^1]. Also, as of git v2.40, the initial branch name is still master[^2].

You could override the default branch name by setting [`init.defaultBranch`](https://git-scm.com/docs/git-config/2.40.0#Documentation/git-config.txt-initdefaultBranch). I personally might just leave it to git/libgit2 to avoid hardcoded values.

From a different angle, `git init` warns when you use the deault "master" for the initial branch, such as

```
$ git init .
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint:
hint:   git config --global init.defaultBranch <name>
hint:
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint:
hint:   git branch -m <name>
```

We may consider adding such a warning as well, but need to take more care of the wording since not every system has `git` installed.

[^1]: "The `init.defaultBranch` setting is now respected and `master` is no longer the hardcoded as the default branch name."
    https://github.com/libgit2/libgit2/blob/2f20fe8869d7a1df7c9b7a9e2939c1a20533c6dc/docs/changelog.md?plain=1#L560-L561
[^2]: https://git-scm.com/docs/git-init/2.40.0#Documentation/git-init.txt---initial-branchltbranch-namegt

**Comment by erwanvivien** [comment]
I think you're right @weihanglo, thanks for the insights, very interesting

**Comment by weihanglo** [comment]
Now I reconsider my suggestion. The warning might be less useful than I thought.

From the perspective of git, branch names are relatively important, as they are deeply linked to the workflow of git. In Cargo, other information might be more critical than branch names. Cargo shouldn't choke users' console for a thing that is essentially controlled by an external tool, unless it blocks the use of Cargo. Moreover, if a user cares about the branch name pretty much, they might already know or figure out how to configure git.

Due to it somewhat draws a certain level of complexity with little value in return, I'll close this issue and kindly recommend people configuring git's [`init.defaultBranch`](https://git-scm.com/docs/git-config/2.40.0#Documentation/git-config.txt-initdefaultBranch) instead. Thank you!

**Comment by blyxyas** [comment]
I just finished the fix 😢 ...

**Comment by weihanglo** [comment]
Saw [your message on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/246057-t-cargo/topic/Verbose.20branch.20warnings/near/350258956) and thought “Oh, I gave a bad suggestion and you're correct it's too verbose.”

Sorry for the inconvenience 😢🙇🏾
