### ISSUE TITLE
Cargo  adds deps to docs when running cargo doc --no-deps --target-dir ./documentation

### ISSUE THREAD

**Issue by Vilayat-Ali** [rust-lang/cargo#12007]
### Problem

I want to generate documentation in the root of my project and I want cargo to exclude documenting all dependencies in the project.

I tried running the command `cargo doc --no-deps --target-dir <path>`. This command have generated the documentation in the required path but ignored the `--no-deps` flag for some reason.

### Possible Solution(s)

Either there is a missing handler for handling --no-deps args in the cli.
Missing logic

### Version

```text
cargo 1.68.2 (6feb7c9cf 2023-03-26)
```

**Comment by ehuss** [comment]
Can you clarify what makes it appear that the dependencies are being documented? There should be only one crate in the `documentation/doc` directory. Just keep in mind that dependencies still need to be "checked" in order to generate the metadata required for documenting your own crate. Those will be stored as `.rmeta` files in the `deps` directory.
