### ISSUE TITLE
1.67.0: sparse protocol problems

### ISSUE THREAD

**Issue by peter-kehl** [rust-lang/cargo#12058]
### Problem

Summary: Switching between several Rust versions with `rustup default ...` got Rust `1.67.0` (maybe other, too) versions fail with "usage of sparse registries requires `-Z sparse-registry`". Disabling the new protocol in `~/.cargo/config` "fixes" it; re-enabling it brings the problem back.

Before switching to `1.67.0` Rust, I have build the same project (https://github.com/coop-rs/allow -> sub-directory `allow`), mostly on `nightly`, then 1.45, 1.52, 1.63.

I didn't check many other Rust versions yet, but `rustup default 1.67.0` causes it.

1.69.0 toolchain makes `cargo check` work, even with the sparse protocol. Reverting the toolchain back to 1.67.0 brings the sparse error back. But, I don't remember setting/enabling the sparse protocol manually before this.

(`rustup` installed NOT from Rust website, but as it comes with the current Manjaro (Arch Linux derivative) x64.)

```
> rustup toolchain list
stable-x86_64-unknown-linux-gnu
beta-x86_64-unknown-linux-gnu
nightly-i686-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-musl
1.45-x86_64-unknown-linux-gnu
1.52-x86_64-unknown-linux-gnu
1.63-x86_64-unknown-linux-gnu
stage0
stage1
1.58.1-x86_64-unknown-linux-gnu
1.67.0-x86_64-unknown-linux-gnu (default)
1.69.0-x86_64-unknown-linux-gnu
```

Please
- suggest any steps/commands for me to investigate. Otherwise I may clean up my `~/.cargo` and this may not be reproducible anymore.
- comment on whether this is a known issue specific to 1.67.0 (or any other versions?), and if there would be any patch for 1.67 (or any other) version streams (if that could be done at all).
Thx.

### Steps

```bash
> cargo check
error: failed to get `rustversion` as a dependency of package `allow v0.1.0 (/share/pkehl/GIT/allow/allow)`

Caused by:
  failed to load source for dependency `rustversion`

Caused by:
  Unable to update registry `crates-io`

Caused by:
  usage of sparse registries requires `-Z sparse-registry`

allow/allow on  main [!+] is 📦 v0.1.0 via 🦀 v1.67.0 
❯ cargo --version 
cargo 1.67.0 (8ecd4f20a 2023-01-10)
```

### Version

```text
See above.
```

**Comment by weihanglo** [comment]
Sparse registry support has been stabilized in the 1.68 release[^2]. That means you cannot use it with any stable channel of Rust before 1.68. Cargo gave you the error message because you either have set `CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse` environment variable or `registries.crates-io.protocol = "sparse"` in `.cargo/config.toml`[^1].

If you have nightly channel installed, run `cargo +nightly -Z unstable-options config get --show-origin` can help you find where those configurations come from.

And sorry. At this moment, there is no mechanism to backport toolchain beyond the current stable and beta channels. This is also unlikely a bug so probably no backport needed.


[^2]: https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#sparse-registry
[^1]: https://doc.rust-lang.org/cargo/reference/config.html#registriescrates-ioprotocol

**Comment by weihanglo** [comment]
Close as it doesn't seem to be a bug in Cargo. If this is wrong, let us know and we can re-open.
