### ISSUE TITLE
--locked-for-binaries flag (same as --locked but only if the crate is / has a binary)

### ISSUE THREAD

**Issue by BKDaugherty** [rust-lang/cargo#12091]
### Problem

I have a monorepo that has many crates in it. For every crate, I'd like to ensure that, if it has a binary, the `Cargo.lock` file is up to date. 

In order to do that, I want to run `cargo check --locked` on all of the binaries that I have, and if it fails I want to fail CI.

Given that the [recommendation](https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries) is that binaries check in their `Cargo.lock` files and libraries don't, it'd be awesome if there was a `cargo` command that I could run that would add --locked only if `cargo` is working on a binary. 

I couldn't find an easy way to figure out whether or not a crate had a binary. At the moment, my solution has been...

```
 $ cargo metadata --format-version 1 --no-deps | jq '.["packages"] | .[] | .targets | .[] | .kind' -c | grep bin && cargo check --bins --locked
 $ cargo check --all-targets
```

But this means I'm running `cargo check` twice for each binary I have. 

### Proposed Solution

Provide a flag `--locked-for-binaries` where `cargo check` (and other commands) errors if cargo needs something not in the lock file for binaries, but doesn't error if the `Cargo.lock` file doesn't exist for libraries.

**Comment by weihanglo** [comment]
Thanks for the idea! It's hard to say whether a specialized flag is good or not. I can see the convenience the flag bringing. Once Cargo stabilizes a flag it will stay forever. We tend to think more before adding flags, especially if there are some (not elegant but working) workarounds.

Besides, the _dont-commit-lockfile-for-libraries_ recommendation is in an interesting situation. Here is [a recent discussion around it](https://rust-lang.zulipchat.com/#narrow/stream/246057-t-cargo/topic/Commit.20lockfiles.20for.20libs.3F>). I would say, if the official guideline gonna change, this flag might become even less useful. That's why we need to be a bit  more conservative toward this proposal.

**Comment by BKDaugherty** [comment]
Hey! Just wanted to say I appreciated your diplomatic and welcoming answer @weihanglo! Given https://github.com/rust-lang/cargo/issues/8728, and the fact that my team is now checking in all of the Lockfiles for our libraries too, I'm going to close this.
