### ISSUE TITLE
Cargo is downloading excessively slow.

### ISSUE THREAD

**Issue by DAMACANER** [rust-lang/cargo#12175]
### Problem

I am talking about 36 kb/s speeds:

![image](https://github.com/rust-lang/cargo/assets/92731060/fa20478b-6360-4f85-bcbb-987e2eeb2723)

And, okay, I am living in a literal shithole, like we are still using 3G but my internet is still not that bad:

![image](https://github.com/rust-lang/cargo/assets/92731060/9bc686fc-7e11-4e5e-8b7f-ecee0bfc2773)

Is this a bug of some sort?

### Version

cargo 1.69.0 (6e9a83356 2023-04-12)

**Comment by DAMACANER** [comment]
```
[caner@derp-x8664 muted]$ CARGO_NET_GIT_FETCH_WITH_CLI=true cargo build
    Blocking waiting for file lock on package cache
    Updating crates.io index
remote: Enumerating objects: 350470, done.
remote: Counting objects: 100% (315/315), done.
remote: Compressing objects: 100% (111/111), done.
Receiving objects:   6% (21844/350470), 3.30 MiB | 36.00 KiB/s  
```

same reulst with git CLI.

**Comment by weihanglo** [comment]
> Receiving objects:   6% (21844/350470), 3.30 MiB | 36.00 KiB/s  

The speed indeed doesn't look right. The GitHub connection is great right now. I have 300Mbps network and the download speed can up to 2MiB/s for me. I am not sure if there is something between you and GitHub. You could try again with `CARGO_HTTP_DEBUG=true` and `CARGO_LOG=cargo::ops::registry=trace` environment variables, and `--verbose` flag to see if anything relevant happen.

Also, how is the speed when you just `git clone https://github.com/rust-lang/crates.io-index.git`? `CARGO_NET_GIT_FETCH_WITH_CLI=true` did use something to `git fetch` CLI, so I guess it won't help much.

Otherwise you could try using [sparse protocol](https://doc.rust-lang.org/nightly/cargo/reference/config.html#registriescrates-ioprotocol), whose instruction is described in <https://github.com/rust-lang/cargo/issues/11014> and will be the default for index fetch.

**Comment by DAMACANER** [comment]
![image](https://github.com/rust-lang/cargo/assets/92731060/21991f02-cfe7-46ae-8155-e4ac5508038b)

There is nothing relevant here, the only interesting bit is I am connected to the other side of the world. I will try sparse protocol thank you.
