### ISSUE TITLE
Consider aliasing `cargo new --library` to `cargo new --lib` rather than throwing an error for it

### ISSUE THREAD

**Issue by kayagokalp** [rust-lang/cargo#12467]
### Problem

Currently if a cargo user wants to create a library project, they need to use `cargo new --lib` and `cargo new --library` throws an error with a nice error message:

```console
error: unexpected argument '--library' found

  tip: a similar argument exists: '--lib'

Usage: cargo new --lib <path>

For more information, try '--help'.
```

But `--library` and `--lib` means the same thing and I feel like there would not be an ambiguity if we also accept `--library`.

I would argue that it would feel more natural to some people.

### Proposed Solution

If there are no strong reasons to not do that, I think we can also accept `--library` as a valid argument and basically make sure that `cargo new --library` and `cargo new --lib` actually does the same thing.

This can be further expanded `--bin` and `--binary`.

**Comment by weihanglo** [comment]
Thanks for the idea. 

I feel like the error message is quite clear to route you to the right argument. Also, `bin` and `lib` are already used everywhere in other subcommands, Cargo.toml, as well as rustc.

I lean towards not adding clever aliases at this moment, in order to reduce the overhead for both users and developers.

**Comment by epage** [comment]
Agreed.  When I first read this, I thought it was for the other way around, which made sense to me.  For better or worse, the rust ecosystem uses a lot of abbreviations.

If the existing clap message wasn't useful, we would have instead wanted to make it more useful at a later point, like when https://github.com/clap-rs/clap/issues/4706 is implemented.  Since it is useful, I don't see something to do here.

**Comment by arlosi** [comment]
Agreed. Since the error message suggests the correct flag, I think we can close this. 

Thank you for the suggestion.
