### ISSUE TITLE
Cargo install --Verbose, -vv is not verbose

### ISSUE THREAD

**Issue by huronbikes** [rust-lang/cargo#12465]
### Problem

I was trying to install librespotify to a device running Ubuntu-Touch using cargo and getting spurious network errors and timeouts.  Thing is I don't know what resources are being requested so I have no diagnostic information to go on.  I don't even know what packages are supposedly being installed.  If I pass -vv into install, no additional logs are generated.  If I pass --verbose in, no logs are generated.

This is on cargo 1.71.1 (7f1d04c00 2023-07-29)

### Steps

1. Run cargo install -vv librespotify
expected: verbose information about what the install process is doing
actual: no additional information logged

### Version

```text
cargo 1.71.1 (7f1d04c00 2023-07-29)
release: 1.71.1
commit-hash: 7f1d04c0053083b98fa50b69b6f56e339b0556a8
commit-date: 2023-07-29
host: aarch64-unknown-linux-gnu
libgit2: 1.6.4 (sys:0.17.1 vendored)
libcurl: 8.0.1-DEV (sys:0.4.61+curl-8.0.1 vendored ssl:OpenSSL/1.1.1t)
ssl: OpenSSL 1.1.1t  7 Feb 2023
os: Ubuntu 16.04 (xenial) [64-bit]
```

**Comment by epage** [comment]
When I run the above command, I get the following
```console
$ cargo install -vv librespotify --root foo
    Updating crates.io index
error: could not find `librespotify` in registry `crates-io` with version `*`
```
If I then pick something that can be installed, like `committed`, I do get very verbose output.

In this case, I think we just don't have any verbose output to show before that error occurs.  Separately, you can debug the internals of cargo with `CARGO_LOG=trace cargo install librespotify --root foo` but that isn't needed for the error I got since just checking https://crates.io/search?q=librespotify shows the package isn't there under that name.

**Comment by huronbikes** [comment]
Apologies, librespot is the package name.

**Comment by weihanglo** [comment]
For network debugging, please refer to [`http.debug`](https://doc.rust-lang.org/nightly/cargo/reference/config.html#httpdebug) config value. Something like `CARGO_HTTP_DEBUG=true CARGO_LOG=cargo::ops::registry=trace cargo build` could help.

**Comment by weihanglo** [comment]
Going to close this, as we could use approaches above for debugging. If you have further questions, please comment here or ping us on Zuilp. Thank you.
