### ISSUE TITLE
Support inheriting jobserver when using `cargo run`

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/cargo#12597]
### Problem

Sometimes commands run through `cargo run` actually perform build actions for a larger build system.

For example in https://github.com/rust-lang/cargo/pull/10511#issuecomment-1092057057 the scenario is running something like `cargo run -p binding_generator` which generates headers to be used during the build later.

And in https://github.com/rust-lang/rust/pull/113730#discussion_r1308504892 cargo-miri is set as `target.runner` and runs as a part of `cargo run` (and calls build tools like cargo and rustc recursively).

### Proposed Solution

In all cases like these cargo shouldn't close its jobserver file descriptors (or other handles), but pass them to the tool being run instead.

I think doing this under an options would be fine.
The default for such option can be decided upon later (probably kept being false, which is equivalent to the current behavior).

**Comment by RalfJung** [comment]
> In all cases like these cargo shouldn't close its jobserver file descriptors (or other handles), but pass them to the tool being run instead.

From what I understood in the PR, this does not seem to be what the PR does. The PR only makes it so that if cargo uses an external jobserver, that one is now propagated to `cargo run` as well.

So maybe the issue should be reopened?

**Comment by weihanglo** [comment]
From reading this issue title, and the context of <https://github.com/rust-lang/cargo/pull/10511#issuecomment-1092057057>, I made an assumption that miri (or some other tool alike) would like to _inherit existing jobserver from the environment_, exactly as how Cargo treats external commands today since #10511. #12776 made it so. It's my fault that didn't request more details from the issue author.

The line between compilation and execution is not always clear in cargo, like `--keep-going` flag. What is kept going, rustc or the final binary run? 🤯  

That said, if this doesn't resolve the miri issue, I am sorry 😞. I would suggest opening another issue to clarify the workflow and expectation, and we could consider a piped-based jobserver by default (see PR description in #12776).

**Comment by RalfJung** [comment]
Well, it's less of an issue for Miri than a peculiar  interaction of how cargo-miri works (a big pile of hacks to get cargo to do what we need it to do) and how cargo works, that was noticed as part of https://github.com/rust-lang/rust/pull/113730. I'm not aware of this causing actual problems for Miri users.
