### ISSUE TITLE
`Cargo build` should leave the file descriptors opened for the build script

### ISSUE THREAD

**Issue by octplane** [rust-lang/cargo#1262]
Current code does not forward `stdin`, `stderr`, `stdout` to the spawned build script.

This behavior can be desired if your build script is interactive (vaguely related with #1208).

**Comment by alexcrichton** [comment]
Unfortunately due to the concurrent nature of Cargo's build process I don't think that this is a feasible feature to implement. We may want some form of a request-response system from a build script to Cargo at some point, but for now it wouldn't work super well if 4 build scripts decided to ask for input all at once :(

**Comment by octplane** [comment]
Sure. I didn't realize Cargo could multithread its build process...
