### ISSUE TITLE
XML Test Report

### ISSUE THREAD

**Issue by Blackhole16** [rust-lang/cargo#1273]
I'm trying to set up jenkins to be used as build and test system for a cargo/rust project. Could you please offer an option for cargo-test to export the results into an xml, which can be interpreted by jenkins?

Kind Regards,
BH16

**Comment by alexcrichton** [comment]
I think that this may be a better option for the test runner itself rather than Cargo. Cargo doesn't necessarily understand what tests were run, all it does is possibly pass `--test` to the compiler and then it'll run the output executable.

Our current testing infrastructure does provide [an output log](https://github.com/rust-lang/rust/blob/master/src/libtest/lib.rs#L319-L320), but it's not really in a nicely structure format.

In general I'd love to support custom test frameworks through either Cargo or the compiler itself, it's just not possible at this time. For now I'm going to close this in favor of https://github.com/rust-lang/rfcs/issues/816.
