### ISSUE TITLE
Breaking change to `cargo login`

### ISSUE THREAD

**Issue by Diggsey** [rust-lang/cargo#12828]
### Problem

SInce updating to Cargo 1.73, the `cargo login` command no longer accepts the token after `--`.

Used to work:
`cargo login -- <token>`

This now re-requests the token if in an interactive terminal, or else prints the confusing error:
> error: credential provider `cargo:token ***` failed action `login`
> 
> Caused by:
>   please provide a non-empty token

This is mostly an issue for CI.

**Comment by weihanglo** [comment]
Oops. That was an unexpected side effect when we added the support of [credential providers](https://doc.rust-lang.org/nightly/cargo/reference/credential-provider-protocol.html#credential-provider-protocol) in nightly, which will be landed in 1.74. (In https://github.com/rust-lang/cargo/pull/12499 we did the change).

Trailing arguments for `cargo login` was supported unintentionally. Since now trailing arguements are passed to upcoming credential plugins, there is little chance the behavior will be reverted 😞.

Could you try if `cargo login <token>` works for you? That should be well-supported but if not please let us know.

**Comment by Diggsey** [comment]
Yeah I've fixed it in my CI by removing `--` but thought I'd open an issue since breaking changes are not expected. Feel free to close if there's nothing to be done.

**Comment by Diggsey** [comment]
(Also this might be useful if anyone else googles "please provide a non-empty token" - when I did the only result was the cargo source!)

**Comment by weihanglo** [comment]
It's so nice of you to open this issue!

I am thinking of putting a compatibility notice in CHANGELOG.md under 1.73 Changed section, calling out this unfortunate with an big ❗.

Going to do that later today, or if someone is faster than me please do it :)
