### ISSUE TITLE
Escaped quotes in arguments

### ISSUE THREAD

**Issue by Zymlex** [rust-lang/cargo#12824]
### Problem

In `$CARGO_HOME/config.toml` used escaped quotes for linker arguments, but quotes passed as is (with backslash) to the arguments.

![image](https://github.com/rust-lang/cargo/assets/25817412/a9f451bb-d15e-43da-8240-1ce7eeef3d5e)
![image](https://github.com/rust-lang/cargo/assets/25817412/c4fcd180-dd30-4cfe-bebc-afbd6e207fee)
and so directly to the linker.

### Version

```text
cargo 1.75.0-nightly (6fa6fdc76 2023-10-10)
release: 1.75.0-nightly
commit-hash: 6fa6fdc7606cfa664f9bee2fb33ee2ed904f4e88
commit-date: 2023-10-10
host: x86_64-pc-windows-msvc
libgit2: 1.7.1 (sys:0.18.1 vendored)
libcurl: 8.3.0-DEV (sys:0.4.66+curl-8.3.0 vendored ssl:Schannel)
os: Windows 10.0.17763 (Windows Server 2019) [64-bit]
```

**Comment by epage** [comment]
Could you give full reproduction steps, including the final observed problem?

**Comment by weihanglo** [comment]
I am going to close due to lack of a minimal set of steps to reproduce, and it has been inactive for a while. Here are tips about [how to create a minimal, complete, and verifiable example][mcve].

Feel free to comment below or open a new issue if there is any update.

[mcve]: https://stackoverflow.com/help/mcve
