### ISSUE TITLE
Cargo help colorful, missing in action. Rust 1.73 everything revealed mentions cargo help being colorful

### ISSUE THREAD

**Issue by AddictArts** [rust-lang/cargo#12931]
### Problem

cargo help is not colorful

### Steps

1. cargo help

### Possible Solution(s)

I understand the project is independent of rust release announcements, but this feature was discussed as a new feature in 1.73.

The pull request has no information on how to enable it.

### Version

```text
cargo 1.73.0 (9c4383fb5 2023-08-26)
release: 1.73.0
commit-hash: 9c4383fb55986096b414d98125421ab87b5fd642
commit-date: 2023-08-26
host: x86_64-unknown-linux-gnu
libgit2: 1.6.4 (sys:0.17.2 vendored)
libcurl: 8.2.1-DEV (sys:0.4.65+curl-8.2.1 vendored ssl:OpenSSL/1.1.1u)
ssl: OpenSSL 1.1.1u  30 May 2023
os: Red Hat Enterprise Linux 9.2.0 [64-bit]
```

**Comment by weihanglo** [comment]
Thanks for the report. It should be fixed by <https://github.com/rust-lang/cargo/pull/12578>. You can `rustup install beta` and run `cargo +beta help` to try it :)

**Comment by epage** [comment]
>  but this feature was discussed as a new feature in 1.73.

Where did you see that announced?  I'm not seeing it on [RELEASES.md](https://github.com/rust-lang/rust/blob/master/RELEASES.md), [our changelog](https://github.com/rust-lang/cargo/blob/master/CHANGELOG.md#cargo-173-2023-10-05), or on the [announcement blog post](https://blog.rust-lang.org/2023/10/05/Rust-1.73.0.html).

I did see one user's announcement video mentioning it which was confusing because they demoed it and yet it won't be available until 1.74.

**Comment by epage** [comment]
> The pull request has no information on how to enable it.

If you look on the sidebar for pull requests, you can see the "Milestone" mentions which Rust release it will be available in.

![image](https://github.com/rust-lang/cargo/assets/60961/3733a7a5-23b1-408e-879f-917ad877b322)

**Comment by AddictArts** [comment]
@weihanglo thanks, I will try that.
@epage thanks. Apologies. It was a video that mentioned it and I thought the milestone was 1.73 when I looked. My apologies and thanks for the quick replies.
