### ISSUE TITLE
Inconsistency between Cargo.toml and Cargo.lock for pre-release crate version

### ISSUE THREAD

**Issue by sleshep** [rust-lang/cargo#12942]
**Issue**
`Cargo.lock` does not match the pre-release version specified in `Cargo.toml` after running `cargo add`.

**Reproduction Steps**
1. `cargo new test_project`
2. `cargo add memflow@0.2.0-beta10`
3. `Cargo.toml` correctly shows `memflow = "0.2.0-beta10"`
4. `Cargo.lock` reflects `memflow` as `0.2.0-beta9`

**Expected**
Both `Cargo.toml` and `Cargo.lock` should list `memflow` as `0.2.0-beta10`.

**Actual**
`Cargo.lock` lists `memflow` as `0.2.0-beta9`.

**Cargo Version**
cargo 1.75.0-nightly (7046d992f 2023-11-08)

**Operating System**
Ubuntu 22.04

The discrepancy between lock and manifest files for a pre-release version is causing dependency resolution issues.

**Comment by epage** [comment]
First, pre-releases aren't considered breaking changes between each other, so the lockfile and the manifest are free to disagree.  There is discussion on this in #2222.

As for why `beta9` was picked over `beta10` is because [semver precedence](https://semver.org/#spec-item-11) only does numeric comparisons for `.` delimited numbers.  That would need to be `beta.9` and `beta.10`.

**Comment by sleshep** [comment]
@epage  Thanks for the clarification; it resolved my issue. I'm closing this thread.

**Comment by weihanglo** [comment]
FWIW, use `cargo add memflow@=0.2.0-beta10` if want exactly a specific pre-release version.

**Comment by sleshep** [comment]
@weihanglo It works for me, thanks.
