### ISSUE TITLE
Allow a git dependency to resolve for a registry dependency

### ISSUE THREAD

**Issue by vincentdephily** [rust-lang/cargo#12983]
### Problem

Dependencies sourced from git are not considered as valid candidates for "normal" dependencies.

### Steps

1. Create a Cargo.toml with `env_logger = "0.10.0"` and `log = "=0.4.15" `
2. Run `cargo update` and `cargo tree`
3. As expected, there is a single copy of the `log` crate 
4. Switch to `log = {git = "https://github.com/rust-lang/log", tag = "0.4.15" }`
5. Run `cargo update` and `cargo tree`
6. We now have two copies of the log crate

### Notes

Might be related to #6921

### Version

```text
cargo 1.73.0
release: 1.73.0
host: x86_64-unknown-linux-gnu
libgit2: 1.6.4 (sys:0.17.2 vendored)
libcurl: 8.4.0 (sys:0.4.65+curl-8.2.1 system ssl:rustls-ffi/0.10.0/rustls/0.21.0)
os: Gentoo Linux 2.14 [64-bit]
```

**Comment by ehuss** [comment]
Thanks for the report! This is intended behavior, since cargo treats crates from different sources as distinct.

The correct way to indicate that you want to replace a registry dependency with one from a git dependency is to use a [`[patch]` table](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html).

**Comment by vincentdephily** [comment]
This makes sense, thanks.
