### ISSUE TITLE
Cargo add/Cargo install + tab should list all available crates

### ISSUE THREAD

**Issue by dev-ardi** [rust-lang/cargo#13043]
### Problem

`cargo add ser` + tab takes a while. I think that it's doing a network request every time.

### Proposed Solution

Download a list of all crates.

### Notes

I would like to try this if I could get some mentoring!

**Comment by dev-ardi** [comment]
If you're confused, you should be. This is not a cargo feature, it's a fish feature!
https://github.com/fish-shell/fish-shell/blob/master/share/completions/cargo.fish#L39
Anyways, I think it would be cool to have this in cargo

**Comment by epage** [comment]
FYI there is no list of packages names for a registry at this time.

Itd also help if complete reproduction steps were given including what shell and shell version.

**Comment by weihanglo** [comment]
Not sure how it would work for cargo to get this built-in as shell completion, since it is a shell's stuff.

**Comment by dev-ardi** [comment]
> there is no list of packages names for a registry at this time

Would that be hard to implement?

>Itd also help if complete reproduction steps were given including

1. type cargo install cargo-
2. Press tab
3. Fish will call `cargo search` and display a list of results:
![image](https://github.com/rust-lang/cargo/assets/47633543/5600ea2b-637d-4b90-b4b3-193424c2e092)


> what shell and shell version.
`fish, version 3.6.1`

**Comment by epage** [comment]
We don't provide completions for fish. Those are provided by the fish community.

**Comment by dev-ardi** [comment]
Okay. In order to speed this up for fish it would still be nice to download a list all packages. How hard would this be? I have no idea about how cargo works but it seems like a really simple database query!

**Comment by epage** [comment]
If you'd like fish's completions improved, please open an issue over there.  If the fish maintainers want something from us, the request should come from them.  If they do, we can then work with them on requirements to make sure a solution delivers what they can use, rather than us all speculating..

Note that this is beyond the capabilities of our first-party completion support.  I suspect that fish is parsing human-focused output that is subject to change.

> How hard would this be? I have no idea about how cargo works but it seems like a really simple database query!

There is no database for us to query.  The big issues are
- A performant way of downloading and updating the names of the 131,977 packages on crates.io
- A stable API to expose this information

Related
- #11034 (an API for exposing index information)
- #6645 (this would let our first-party completions have similar capabilities)
- #10655 and some others discuss the problem of not having a list of package names
  - Alternatives exist like just iterating over what packages have downloaded index entries as that will likely cover a lot of cases
