### ISSUE TITLE
Cannot `patch` an optional sub-dependency anymore : `patch was not used in the crate graph`

### ISSUE THREAD

**Issue by BarbossHack** [rust-lang/cargo#13100]
### Problem

Hi,

Lets say : 
- I have a crate `one` with a dependency named `two`.
- Crate `two` has an optional dependency `hex`, not activated by default.
- Crate `one` has a [patch] section to patch `hex` dependency.

When I build `one` with feature `two/hex`, I expect Cargo to activate this optional dependancy, and to patch it. Instead, it activate this optional dependency, but without applying the patch, with warning ```Patch `hex` was not used in the crate graph.```

Some times ago I was able to patch the optional dependency `hex` in this way. I don't know what changed, is this a bug ? A behavior change ?

Thank you for your help

### Steps

1. `git clone https://github.com/BarbossHack/cargo-patch-issue`
2. `cd cargo-patch-issue/one/`
3. `cargo run --features two/hex`

output :
```bash
warning: Patch `hex v0.1.0` was not used in the crate graph.
Check that the patched package version and available features are compatible
with the dependency requirements. If the patch has a different version from
what is locked in the Cargo.lock file, run `cargo update` to use the new
version. This may also occur with an optional dependency that is not enabled.
    Updating crates.io index
    Finished dev [unoptimized + debuginfo] target(s) in 0.11s
     Running `target/debug/one`
Hello, one!
two_featured
```

4. Uncomment feature `activate_hex` in `one` Cargo.toml (we won't use this feature, but `hex` will thus be added in the crate graph)
5. `cargo run --features two/hex`

output : 
```bash
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
     Running `target/debug/one`
Hello, one!
two_patched
```

### Version

```text
cargo 1.74.0 (ecb9851af 2023-10-18)
release: 1.74.0
commit-hash: ecb9851afd3095e988daaa35a48bc7f3cb748e04
commit-date: 2023-10-18
host: x86_64-unknown-linux-gnu
libgit2: 1.7.1 (sys:0.18.0 vendored)
libcurl: 8.4.0-DEV (sys:0.4.68+curl-8.4.0 vendored ssl:OpenSSL/1.1.1u)
ssl: OpenSSL 1.1.1u  30 May 2023
os: Fedora 38.0.0 [64-bit]
```

**Comment by ehuss** [comment]
Thanks for the report and detailed reproduction!  I believe this is a manifestation of #3629. Cargo isn't supposed to allow you to say `--features two/hex`, because `two` is not a part of a workspace in your example. One workaround is to use a workspace in which one and two are members, in which case it will work.

I'm going to close in favor of #3629.

**Comment by BarbossHack** [comment]
Thabk you for your answer

In my example I created `two` locally to be able to modify it easily, but in my real-world scenario, `two` and `hex` are crates.io crates (I do not own them). So I have nothing to do with a workspace here... or did I misunderstand something in your answer ?

**Comment by ehuss** [comment]
If `two` is a crates.io crate, then indeed you won't be able to directly support this situation, as cargo should not be allowing enabling optional dependencies on registry packages from the CLI. The reason for not allowing that is because unused optional dependencies are not recorded in the lock file, which allows for the use of unlocked dependencies which is not the intended way that cargo should work. They can't be added to the lock file because that would add many dependencies that typically aren't used, and would negatively impact resolution as it would put more constraints on it.

Another workaround is to re-export the optional feature in `one`. For example:

```toml
[features]
two-hex = ["two/hex"]
```

That tells cargo that the optional dependency is a potential candidate to use during resolution, and should then allow you to set it.

**Comment by BarbossHack** [comment]
Thank you for your answer ! I think I understand

in my example,
- `hex` is not in the crate graph (not in the lock file)
- if I `cargo run --features two/hex` , it will activate and use `hex` (even if it's not in the crate graph)
So, this shouldn't be allowed. So it's a cargo bug that exists for years...

I was trying to patch the unused crate `hex` (while enabling it through CLI), but if it's not even allowed to enable `hex` through CLI, I will have to add a feature (like I did in the "Steps" section of my issue)

**Comment by BarbossHack** [comment]
Well... according to the [Rust Book](https://doc.rust-lang.org/cargo/reference/features.html#optional-dependencies), when adding an optional dependency, it implicitly defines a feature that looks like this:

```toml
[features]
hex = ["dep:hex"]
```
So running `cargo run --features two/hex` should be allowed ?
