### ISSUE TITLE
Consider removing `v` prefix in `cargo tree`  display result

### ISSUE THREAD

**Issue by wangkirin** [rust-lang/cargo#13120]
### Problem

Hi all:
We all know that  the version of Cargo package follows the  `SemVer`.   Recently  I met a issue, that when I run `cargo tree ` command in a cargo project, the  output  is like 
```
myproject v0.1.0 (/myproject)
└── rand v0.7.3
    ├── getrandom v0.1.14
```
the version after dependency package name has a prefix `v` . Actually,  the Standard SemVer format  doesn't contains  prefix `v` (see  [https://semver.org/#is-v123-a-semantic-version]( https://semver.org/#is-v123-a-semantic-version )) , we also didn't add prefix `v`   in  `[dependencies]`  specify in `Cargo.toml`.   And the  display result of some other commands like `cargo metadata`  doesn't contains  prefix `v` in `version` field.  

So I suggest consider removing `v` prefix in `cargo tree`  display result，to avoid misunderstanding. It can also simplify the similar scenario I encountered:  automatically process the dependency resolution result of the `cargo tree` command and invoke the `crates.io` API to query crate information based on the parsed dependency information.In that scenario, `v1.1.0` needs extra transformation to `1.1.0`.

If the community agree ,  I am happy to submit a PR to remove it. 
Thank you very much 

### Proposed Solution

remove the  `v` prefix in `cargo tree`  command display result

**Comment by epage** [comment]
The SemVer spec is referring to the value.  `Cargo.toml` and `cargo metadata` carry that forward.  That is independent of UX concerns for distinguishing that a number is a version and it is very common to add a `v` prefix.

> automatically process the dependency resolution result of the cargo tree command and invoke the crates.io API to query crate information based on the parsed dependency information.In that scenario, v1.1.0 needs extra transformation to 1.1.0.

`cargo tree`s output is not stable or design for automated processing but is intended for humans.

**Comment by weihanglo** [comment]
From [the link](https://semver.org/#is-v123-a-semantic-version) you provided:

> No, “v1.2.3” is not a semantic version. However, **prefixing a semantic version with a “v” is a common way (in English) to indicate it is a version number**. Abbreviating “version” as “v” is often seen with version control.

For some other Cargo status message like `Compiling smallvec v1.10.0`, they prefix the version with a `v`. It makes sense to have a prefix "v" for consistency across different kinds of messages for human.

> `cargo tree`s output is not stable or design for automated processing but is intended for humans.

While I agree the argument, there is still some kind of stability for automated processing since `cargo tree` provides [format options](https://doc.rust-lang.org/nightly/cargo/commands/cargo-tree.html#tree-formatting-options). I wonder if cargo can provide more options like `{v}` for version and `{n}` for package name purely, though the use case might be rare and missing of that shouldn't essentially block stuff.

**Comment by epage** [comment]
Just because we allow controlling how the UI is rendered, I don't think that means we guarantee enough about automated use or would want to design for it, like adding new format specifiers just for it. I see this similar to discussions around `cargo new` and being able to subtly change it that it benefits people but isn't predictable enough for automation.

**Comment by weihanglo** [comment]
Given that, I propose to the team to close this.

Label it as `P-low` as well.

**Comment by epage** [comment]
I second closing this
