### ISSUE TITLE
Specifying features of dependencies on the command line

### ISSUE THREAD

**Issue by dhardy** [rust-lang/cargo#13199]
From #3058 it sounds like one is not supposed to be able to specify features of dependencies on the command-line, though it's not clear since the example involves transitive features (two slashes).

Attempt to replicate that fails, as expected:
```
$ git clone https://github.com/kas-gui/kas.git && cd kas
$ cargo check --features kas-widgets/kas-core/winit
error: multiple slashes in feature `kas-widgets/kas-core/winit` is not allowed
```

However, using a single slash is currently functional:
```
$ cd crates/kas-widgets
$ cargo test --features kas/winit,kas/wayland
[...]
test result: ok.
```
*Should* this be supported?

Aside: in this particular case, this approach feels justifiable since `kas-widgets` is only ever intended to be used in addition to `kas-core` (here renamed `kas`), thus it makes no sense to re-export its features under `kas-widgets`.

This came up [on docs.rs](https://github.com/rust-lang/docs.rs/issues/2359): it would appear that their build process does not support correct dependency retrieval for features enabled in this way.

**Comment by ehuss** [comment]
Thanks for the report!

Features of packages in a workspace can be specified with the `/` syntax. That is documented [here](https://doc.rust-lang.org/nightly/cargo/reference/features.html#command-line-feature-options), that is the expected behavior.

When building a standalone package (like `kas-resvg`) outside of the workspace (like what docs.rs does), dependencies like `kas-core` are no longer workspace members. It is not intended that you can specify features like `kas/winit` from the command-line if nothing else enables that feature when that is a registry dependency. This is a known bug that it is allowed in some circumstances (#3629).

I would recommend configuring your dependencies (like `kas-resvg`) to enable the necessary features on `kas-core`, either in the `kas-core` dependency declaration, or in the `[features]` table. That will tell cargo that you need the dependencies that those features enable.

**Comment by dhardy** [comment]
Thanks for the clarification...

... however, docs.rs *is* building from the workspace, right?

In particular, the feature resolution should never be a problem in any other circumstance I can foresee since it is never intended that `kas-widgets` be used without also having a direct dependency on `kas-core`. Of course, `docs.rs` does not support specification of additional dependencies, thus to me it seems that it *should* support feature specification of workspace members like this.

**Comment by ehuss** [comment]
> ... however, docs.rs _is_ building from the workspace, right?

I do not think so. I believe it just downloads and extracts the `.crate` file from crates.io and builds it directly.

**Comment by dhardy** [comment]
Thanks @ehuss; that concludes this issue.
