### ISSUE TITLE
Cargo install documentation should no longer mention default location

### ISSUE THREAD

**Issue by manfredbrandl** [rust-lang/cargo#13200]
### Problem

cargo install without --path is no longer supported. cargo --list explains cargo install as "Install a Rust binary. Default location is $HOME/.cargo/bin". Please replace "Default location ... " with "Requires --path".

### Steps

cargo --list ; cargo install

### Version

cargo 1.74.1 (ecb9851af 2023-10-18)

**Comment by ehuss** [comment]
Thanks for the report! I believe there may be a misunderstanding of what it means by "default location". That is the default location where the binaries will be installed *into*.  That can be overridden with `--root`.  The `--path` option is to set where cargo installs *from*.

Would it be clearer if the text instead said this?

```
Install a Rust binary. Default installs into $HOME/.cargo/bin
```

FWIW, I'm on the fence as to whether or not it is appropriate to even include that text at all. It was added in #6354 due to some confusion, but I wouldn't expect this tiny bit of text be the appropriate way to learn what the command does.

**Comment by weihanglo** [comment]
Instead, I think we might want to revert #6354. People wanting to learn more than the one-line explanation from `cargo --list` should run `cargo install --help` or even `cargo help install`.

**Comment by manfredbrandl** [comment]
Cargo install tells me:
error: Using `cargo install` to install the binaries for the package in current working directory is no longer supported, use `cargo install --path .` instead. Use `cargo build` if you want to simply build the package.
So there is no default location to install into any more.

cargo install —help tells me:
…
Usage: cargo install [OPTIONS] [crate]...
…
But there is no install without —path.

cargo help install tells me:
…
The installation root is determined, in order of precedence:

       •  --root option
…
       •  $HOME/.cargo
…
But there is no install into $HOME/.cargo

Did I miss anything or does the documentation describe behavior cargo does not deliver?

**Comment by weihanglo** [comment]
From [`cargo help install`](https://doc.rust-lang.org/nightly/cargo/commands/cargo-install.html):

> …all executables are installed into the installation root’s `bin` folder

and


> There are multiple sources from which a crate can be installed. The default location is crates.io but the `--git`, `--path`, and `--registry` flags can change this source.

Should be fairly clear I guess.

`-path` option in `cargo install` defines the "source" your binary would be installed "from". `--path` has nothing to do with the default installation root a.k.a. the installation destination.

FWIW, I just posted a PR to clarify it a bit <https://github.com/rust-lang/cargo/pull/13205>.
