### ISSUE TITLE
 support system ENV set crate registry

### ISSUE THREAD

**Issue by joebnb** [rust-lang/cargo#13282]
### Problem

in China there are many limitation of network，would cargo support to directly set registry form env

i read the handbook of cargo env section,but no idea to how change the ENV by set system envs.

![image](https://github.com/rust-lang/cargo/assets/1646883/9b7fba6f-c651-4b92-828a-e846de83c4b7)

**Comment by weihanglo** [comment]
If you want to use a mirror index of crates.io, [source replacement](https://doc.rust-lang.org/nightly/cargo/reference/source-replacement.html) is the way to go.

Checkout the doc on <https://mirrors.tuna.tsinghua.edu.cn/help/crates.io-index.git> as well.

As for environment variables for source replacements, I am not aware of any but an intentionally undocumented unstable feature `-Zadvanced-env` supporting this. Use at your on risk since there might be some corner cases:

https://github.com/rust-lang/cargo/blob/0c98d6ec3a3fc72683fe00963b8a55ffaa204d2a/tests/testsuite/advanced_env.rs#L30-L34

**Comment by joebnb** [comment]
thanks for answer my question,i this  should be  works
