### ISSUE TITLE
that “cargo doc” supports different versions of one crate seems more helpful

### ISSUE THREAD

**Issue by miaomiao1992** [rust-lang/cargo#13327]
### Problem

now, if i “cargo doc” higher version of one crate, the html files of lower version generated by “cargo doc” will be erased.

### Proposed Solution

cargo doc should support different versions of one crate

**Comment by miaomiao1992** [comment]
### Problem

now, if i “cargo doc” higher version of one crate, the html files of lower version generated by “cargo doc” will be erased.

### Proposed Solution

cargo doc should support different versions of one crate

### Notes

_No response_

**Comment by ehuss** [comment]
Without more information, I'm going to close. If you have more information on your use case and how this would be useful to you, feel free to reopen. However, I suspect general support for this would be blocked on https://github.com/rust-lang/cargo/issues/10241, since we don't have the ability to have arbitrary directory names. I would suggest if you need something that retains multiple versions (like https://docs.rs/ does) that you'll just need to move the directories to a more suitable location.
