### ISSUE TITLE
`cargo fetch` not useful for packaging Rust software

### ISSUE THREAD

**Issue by wizeman** [rust-lang/cargo#1334]
(Sorry, I don't know how else to name this issue. Please feel free to rename it to something better).

Linux package managers usually do not allow accessing the network when building software.  This is done, among other things, to avoid indeterministic results when building software.

Consequently, it seems that `cargo fetch` is intended to be the solution to prevent `cargo` from attempting to access the network when building a Rust project.

However, IMHO I don't think `cargo fetch` is a solution to this problem, or that it is even needed or useful when packaging Rust software.

When packaging a library or program, the "fetching" part is the easy one. When creating a package for a program or a library, the "fetching" of the software's source code is initially done manually by the maintainer (or is already automated to some degree by other tools). Then, either the maintainer uploads the source code to some distro repository (this is my understanding of what Debian maintainers do), or they just specify the URL of the source code to the packaging tool (such as in Gentoo ebuilds or Nix derivations), so that the package manager knows where to get the source code to compile the program or library.

In Rust's case, usually the programs' source code is available in github, and libraries' source code can be downloaded from `crates.io`, so I think this is not a problem at all.

Right now, AFAICT the only really hard part in packaging Rust software is convincing the build system of the Rust program (the build system being `cargo` in this case) to use the libraries that are already installed in the system.

That is, if I want to package a Rust program called `racer` and it needs a library called `rust-serialize`, then the `rust-serialize` library also needs to be packaged by the distribution. Then, when I'm building `racer`, I need to convince `cargo` to use the `rust-serialize` library that is already installed in the system. I especially cannot allow `cargo` to download anything when building a project.

If there is something that prevents `cargo` from linking to an already-compiled library (such as lack of ABI stability?), at the very least I need to convince `cargo` to use the libraries' source code that I provide to it. This may not be enough for distros such as Debian (I'm not sure), but it would be a first step and certainly would be acceptable for Nix/NixOS (and maybe Gentoo?).

Bottom line is, the **fetching/downloading** of the source code always needs to be done by the maintainer or the distro's package manager. The build system (`cargo` in this case) cannot download anything. Instead, give us an easy and standardized way to point `cargo` to the dependencies that are already somewhere on the system (hopefully as a compiled library, or at the very least in the form of downloaded and extracted source code).

**Comment by alexcrichton** [comment]
Unfortunately this is actually an area where the compiler is the limiting factor. Rust does not have a stable ABI right now and it is currently not suitable to install a rust library globally on the system. Until this becomes feasible I don't think that you want to package Rust software this way.

For a no-network-available-build I would recommend using `CARGO_HOME` and `cargo fetch` to download all dependencies into the local directory. That directory can then be uploaded to a builder where when `cargo build` is run it shouldn't touch the network (assuming you have `CARGO_HOME` pointing at the right place and there are no bugs).

In general, though, the story of Cargo using a system-installed Rust library is definitely lacking (as you have discovered), and this is intentionally so. We will likely have to tackle this problem in the future, but at this time there's not much we can do about it due to the ABI stability problem.

As a result it sounds like `cargo fetch` + `CARGO_HOME` will fit the bill if you're comfortable downloading and building all dependencies. The problem of using a system-installed library isn't really actionable here and will likely evolve over time, so I'm going to close this. Thank you for the detailed issue though, and please feel free to let me know if I should reopen!

**Comment by wizeman** [comment]
I don't agree with your assessment of the situation. Lack of ABI stability between compiler versions is not an excuse for lack of support for linking to libraries installed system-wide.

As an example, the most used Haskell compiler (GHC) does not maintain ABI stability between compiler versions. Yet, it supports linking to libraries installed system-wide.

Furthermore, I don't think any Linux distribution would accept your recommendation for packaging Rust libraries or Rust programs. It would be inadequate for a number of reasons, e.g.:
* The result of `cargo fetch` of Rust programs would include the source code of all the Rust libraries used by that program (including libraries used transitively).
* The above would lead to massive duplication of source code for Rust libraries. Also, since each Linux distribution needs to maintain its own copies of `cargo fetch`, this would also mean that each Linux distro would need to keep its own repository of source code for Rust libraries, and each repository would have to store each Rust library a number of times (proportional to how many Rust programs use each library).
* The above would also lead to practical inability to audit libraries for security vulnerabilities and apply security fixes.
* Since `cargo fetch` also downloads the contents of the `crates.io` git tree, it would also lead to massive duplication of these contents.

Sorry for being so negative, but I think this issue was closed without being correctly addressed.

Until this issue is addressed, I will be forced to write a script to recursively parse and rewrite `Cargo.toml` files, so that `cargo` will look for the source code of dependencies in local directories provided by the package manager, instead of looking for them in `crates.io` or git repositories. As you can imagine, this is highly undesirable and error-prone.

(BTW, this workaround in its current form doesn't yet solve the "link to libraries that are already installed" issue, but at least it already solves the "let me override the place where you can find the source code of this library" issue).
