### ISSUE TITLE
`--out-dir` is ignored when combined with `cargo build --tests`

### ISSUE THREAD

**Issue by brymer-meneses** [rust-lang/cargo#13370]
### Problem

Cargo ignores the `--out-dir` option if it's combined with `cargo build --tests`. 

For instance, invoking
 ```
 cargo build --tests -Z unstable-options --out-dir=bin
 ```
results to cargo not being able to recognize the `--out-dir` option and doesn't put the binaries into  `bin`

It also doesn't give any indication that the flag was ignored just the following 
```
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
```

I can confirm that putting it into `.cargo/config.toml` doesn't work as well.

### Steps

1.  invoke `cargo new reproduce_bug` 
2.  run `cargo build --tests -Z unstable-options --out-dir=bin` 

### Version

```text
cargo 1.77.0-nightly (7bb7b5395 2024-01-20)
release: 1.77.0-nightly
commit-hash: 7bb7b539558dc88bea44cee4168b6269bf8177b0
commit-date: 2024-01-20
host: aarch64-apple-darwin
libgit2: 1.7.1 (sys:0.18.1 vendored)
libcurl: 8.4.0 (sys:0.4.70+curl-8.5.0 system ssl:(SecureTransp
ort) LibreSSL/3.3.6)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Mac OS 14.2.1 [64-bit]
```

**Comment by epage** [comment]
This looks to be the same request as #11110.  Closing in favor of that so all of the conversation can be centralized.  The original filer, rather than the cargo team, closed it.  If, after reading the thread, you feel it should be re-opened, let us know.  Overall, it sounds like this is outside of the intended use case but we can see if we feel its worth re-opening.
