### ISSUE TITLE
static linking in windows

### ISSUE THREAD

**Issue by thewh1teagle** [rust-lang/cargo#13389]
### Problem

I'm trying to static link `ffmpeg` with the library `ffmpeg-next` on `windows` using pre build native libraries
And even though I enable static linking it doesn't link them staticlly (I suspect that it doesn't select the right `.lib` files.

[thewh1teagle/ffmpeg-next-msvc-static](https://github.com/thewh1teagle/ffmpeg-next-msvc-static)

### Steps

1. clone
```console
git clone https://github.com/thewh1teagle/ffmpeg-msys2-static
```
2. build (I use ps1 to download pre built `ffmpeg`)
```console
./build.ps1
```

### Possible Solution(s)

When I remove the shared libraries from the pre build `ffmpeg` and keep only the `lib*` files then it doesn't find anything,
but if I change them then and rename to be without prefix of lib then it finds
But then it yields many errors of unresolved references

### Notes

It may not related to cargo. checking anyway.

### Version

```console
cargo 1.75.0 (1d8b05cdd 2023-11-20)
release: 1.75.0
commit-hash: 1d8b05cdd1287c64467306cf3ca2c8ac60c11eb0
commit-date: 2023-11-20
host: x86_64-pc-windows-msvc
libgit2: 1.7.1 (sys:0.18.1 vendored)
libcurl: 8.4.0-DEV (sys:0.4.68+curl-8.4.0 vendored ssl:Schannel)
os: Windows 10.0.22631 (Windows 11 Professional) [64-bit]
```

**Comment by weihanglo** [comment]
It might depend on how `static` works in build.rs in `ffmepg-sys-next`.

https://github.com/zmwangx/rust-ffmpeg-sys/blob/86e6da66e2c988643043de8ca10da5af85032ca0/build.rs#L685-L691

Saw you create an issue <https://github.com/zmwangx/rust-ffmpeg-sys/issues/68>, so close in favor of that.

If it later turns out to be identified as a Cargo issue, free feel to create a new one.
