### ISSUE TITLE
use named pipe when creating new jobserver

### ISSUE THREAD

**Issue by NobodyXu** [rust-lang/cargo#13483]
> Thanks, my proposed solution is to change rust-lang/jobserver to use a named pipe instead of an annoymous one.
> 
> The named pipe is passed down by its path in filesystem and opening it using `O_NONBLOCK` doesn't affect others.
> 
> We can also retain backwards compatibility by keeping the jobserver fds inheritable and keeping them in the environment variable.
> 
> E.g. `MAKEFLAGS='--jobserver-auth=fifo:/path/to/fifo --jobserver-fds=3,5'`

_Originally posted by @NobodyXu in https://github.com/rust-lang/cargo/issues/13476#issuecomment-1960513530_

**Comment by NobodyXu** [comment]
cc @weihanglo since you also interacted with the issue in cargo.

**Comment by weihanglo** [comment]
Thanks for the report.

This is somehow blocked on <https://github.com/rust-lang/jobserver-rs/issues/47> or something need to be done there I feel like. How can Cargo help the situation, or is this just a tracking issue of that?

**Comment by NobodyXu** [comment]
> This is somehow blocked on <https://github.com/rust-lang/jobserver-rs/issues/47> or something need to be done there I feel like.

Hmmm is that for previous cargo release which uses an old jobserver version?

I thought that latest version of jobserver can handle it just well?

> How can Cargo help the situation, or is this just a tracking issue of that?

I will open a PR in next few days, and hopefully we can cut a new patch release of cargo to use the latest jobserver release.

**Comment by weihanglo** [comment]
> I thought that latest version of jobserver can handle it just well?

🤔… Unless I missed something important, there seems no way for Cargo to create a fifo jobserver via `jobserver` crate.

**Comment by NobodyXu** [comment]
> Unless I missed something important, there seems no way for Cargo to create a fifo jobserver via `jobserver` crate.

That's what I'm proposing: change `jobserver::Client::new` to create a fifo instead of pipe by default and retain backwards compatibility by making it inheritable with env `MAKEFLAGS='--jobserver-auth=fifo:/path/to/fifo --jobserver-fds=3,5'`.

AFAIK `--jobserver-auth` is introduced when fifo is first supported in make.

**Comment by NobodyXu** [comment]
I was meant to create this on rust-lang/iobserver 😂

**Comment by NobodyXu** [comment]
Unfortunately, --jobserver-auth is introduced in 4.2, but fifo jobserver and --jobserver-style is introduced in make 4.4

This means that if we use fifo we would break backwards compatibility, so closing this for now.

**Comment by joshtriplett** [comment]
make 4.4 supporting the FIFO jobserver was released in October 2022, which is more than three years old now, and most distributions have this support already. Given the substantial benefit of not relying on inherited file descriptors, and thus being able to work with *any* child process rather than only those specifically designated as having jobserver support, it'd be useful to do this by default.

For compatibility, we could provide an option to change the default to use the older jobserver protocol, but I think we should change the default at this point. (Note, in particular, that the *setup* could be the same; users of jobserver who want the inherited-fd-based jobserver for use with older make just need to provide inherited copies of the file descriptors and present a different MAKEFLAGS. So we could do the setup the same way every time, and then change how we present it to subprocesses.)
