### ISSUE TITLE
Cargo doesn't respect dependency renaming when using `--package` flag for running examples

### ISSUE THREAD

**Issue by mawallace** [rust-lang/cargo#13487]
### Problem

I have a workspace with dependences. One of my member crates has the same name as a dependency, so I rename the dependency using 

```
b = { version = "x.x.x", package = "a" }
```

_My_ version of the `a` crate has examples, but those examples clash in name with _another_ crate.

Given this, I try to run the example from _my_ `a` crate using

```
cargo run --example example_name --package a
```

but Cargo gives an error like the following

```
error: There are multiple `a` packages in your project, and the specification `a` is ambiguous.
Please re-run this command with one of the following specifications:
  a@0.1.0    <- this is my version
  a@x.x.x    <- this is the dependency
```

I would expect Cargo to respect my renaming if I try to use the `--package` flag when running examples, but it does not.

### Version

```text
cargo 1.76.0 (c84b36747 2024-01-18)
release: 1.76.0
commit-hash: c84b367471a2db61d2c2c6aab605b14130b8a31b
commit-date: 2024-01-18
host: aarch64-unknown-linux-gnu
libgit2: 1.7.1 (sys:0.18.1 vendored)
libcurl: 8.5.0-DEV (sys:0.4.70+curl-8.5.0 vendored ssl:OpenSSL/1.1.1w)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Ubuntu 22.4.0 [64-bit]
```

**Comment by weihanglo** [comment]
Thanks for the report. One thing worth pointing out that `-p`/`--package` accepts a [Package ID Spec](https://doc.rust-lang.org/nightly/cargo/reference/pkgid-spec.html), which is used as a unique identifier. The spec needs to be unique across different kinds of sources like crates.io index, private registries, git dependencies and local path dependencies. It doesn't record any renames as renames are not necessary to uniquely identify a package. For simplicity reasons, I personally don't think the spec will evolve to record that bit of information.

That being said, you're not wrong. If I recall correctly, `cargo run` doesn't support running a binary from arbitrary dependency in the dependency graph. Only workspace members can be specified by `-p` for `cargo run`. It looks like a bug! Do you mind providing a minimal reproducible example so that we can investigate?

**Comment by weihanglo** [comment]
I am going to close due to lack of a minimal set of steps to reproduce, and it has been inactive for a while. Here are tips about [how to create a minimal, complete, and verifiable example][mcve].

Feel free to comment below or open a new issue if there is any update.

[mcve]: https://stackoverflow.com/help/mcve
