### ISSUE TITLE
Add env vars specifying the path for the dependent crate when compiling a dependency

### ISSUE THREAD

**Issue by transbitch** [rust-lang/cargo#13636]
### Problem

When building a dependency, currently it is not possible for the dependency to find the path for the dependent crate (e.g. if `foo` depends on `bar`, `bar` can't find `foo`'s manifest).

### Proposed Solution

I suggest adding two new env vars to both build scripts and crates*:
- `CARGO_DEPNT_MANIFEST_DIR` points to the crate which directly depends on this crate (the "dependent")
- `CARGO_TARGET_MANIFEST_DIR` points to the crate which is being built.

Currently, `CARGO_TARGET_MANIFEST_DIR` can be found from a build script by looking at `OUT_DIR` and then traversing up the directory tree until a `Cargo.toml` is found. I'm not sure if `CARGO_DEPNT_MANIFEST_DIR` can be found.

*It doesn't really make sense to limit it to buildscripts. Someone may want to `include!`, and people can just set up a build script to pass it through anyways.

### Use case
A library may want to read a config file in the user's crate, or data from the `metadata` field of `Cargo.toml`. Currently, that isn't possible. Instead, the library must use features (which are binary on/off) or env variables (which are just strings). Cargo.toml provides structured data beyond bools and strings. See #8375

**Comment by epage** [comment]
Sounds like you want the top-most dependent, right? There isn't guaranteed to be one dependent due to workspaces.There is a request for the workspace in #3946 and config is brought up in it, see https://github.com/jamesmunns/toml-cfg

See also #13484

That said, this inverts cargo's dependency relationship and i wonder if it'd be better served with https://internals.rust-lang.org/t/pre-rfc-mutually-excusive-global-features/19618

**Comment by epage** [comment]
Closing in favor of #13484. If there is a reason we should keep this open separately, let us know!
