### ISSUE TITLE
cargo clippy error when using compile option --emit=obj, and crate-type = ["staticlib"]

### ISSUE THREAD

**Issue by cathy-sjh** [rust-lang/cargo#13661]
### Problem

I have a simple crate,  the **crate-type** is **staticlib**, and depends on **lazy_static**, when add compile option **--emit=obj**, **cargo clippy** error.

### Steps

rust_project/Cargo.toml:
```
[package]
name = "mangle1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"

[lib]
name = "mangle1"
crate-type = ["staticlib"]
```
rust_project/src/lib.rs:
```
use lazy_static::lazy_static;

lazy_static! {
    pub static ref G_LAZY_VALUE1: i32 = 1;
}
pub fn test_func() -> i32 {

    *G_LAZY_VALUE1
}
```

rust_project/.cargo/config.toml
```
[build]
rustflags = [
    "--emit=obj",
]
```

Then `cargo build `is successful. 
But `cargo clippy` fails with the following error:
```
Checking lazy_static v1.4.0
    Checking mangle1 v0.1.0 (/usr1/xxxx/rust_program/rust_language_test/clippy_test/rust_project)
error: crate `lazy_static` required to be available in rlib format, but was not found in this form

error: could not compile `mangle1` (lib) due to previous error
```

When the crate-type is a **dylib**, the cargo clippy has the same error. 
Is there a way to make clippy not report an error, but the --emit=obj option and crate-type = ["staticlib"] can't be changed?

### Version

```text
cargo 1.72.0-nightly (03bc66b55 2023-06-23)
release: 1.72.0-nightly
commit-hash: 03bc66b55c290324bd46eb22e369c8fae1908f91
commit-date: 2023-06-23
host: aarch64-unknown-linux-gnu
libgit2: 1.6.4 (sys:0.17.2 vendored)
libcurl: 8.1.2-DEV (sys:0.4.63+curl-8.1.2 vendored ssl:OpenSSL/1.1.1u)
ssl: OpenSSL 1.1.1u  30 May 2023
os: Linux 2.0 (SP8) [64-bit]
```

**Comment by weihanglo** [comment]
`cargo clippy` runs `cargo check` underneath the hood. `cargo check` is a specialized command that avoids code generations as possible as it could. If you run `cargo check --verbose` you see it passes `--extern lazy_static=/.../target/debug/deps/liblazy_static-<xxxx>.rmeta` to the rustc invocation for building `mangle1`. [`.rmeta`](https://doc.rust-lang.org/1.60.0/rustc/command-line-arguments.html#--emit-specifies-the-types-of-output-files-to-generate) is not an object, so it doesn't satify the [requirement of `staticlib`](https://doc.rust-lang.org/nightly/reference/linkage.html): _"all upstream dependencies are required to be available in rlib formats."_.

You might ask, `--emit obj` is set and present in the rust invocation, why it cannot be found. The truth is `build.rustflags` or any RUSTFLAGS variant is complete opaque to Cargo. Cargo doesn't parse any of those flags, so it doesn't know there are object files emitted.

>  Is there a way to make clippy not report an error, but the `--emit=obj` option and crate-type = ["staticlib"] can't be changed?

AFAIK The short answer is no, but there are some alternatives.

* Remove `build.rustflags` and instead pass it conditionally via environment variable or command line, so that cargo clippy can works without issues.
* Remove `crate-type = ["staticlib"]` from Cargo.toml. Instead, only build staticlib when needed via `cargo rustc --crate-type staticlib`. This approach might avoid unnecessary staticlib being build when in the future you need to build rlib as well.

**Comment by weihanglo** [comment]
I am going to close due to lack of activity for a while. Feel free to comment below or open a new issue if there is any update on your side. Thank you.
