### ISSUE TITLE
Error while running : cargo install spl-token-cli

### ISSUE THREAD

**Issue by aniketch07** [rust-lang/cargo#13700]
### Problem

error: failed to compile `spl-token-cli v3.4.0`, intermediate artifacts can be found at `/tmp/cargo-installUaNXyE`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

Caused by:
  failed to download `solana-account-decoder v1.18.9`

Caused by:
  unable to get packages from source

Caused by:
  failed to download replaced source registry `crates-io`

Caused by:
  failed to find solana-account-decoder v1.18.9 in path source

### Steps

Run: cargo install spl-token-cli

### Version

```text
cargo 1.77.1 (e52e36006 2024-03-26)
release: 1.77.1
commit-hash: e52e360061cacbbeac79f7f1215a7a90b6f08442
commit-date: 2024-03-26
host: x86_64-unknown-linux-gnu
libgit2: 1.7.2 (sys:0.18.2 vendored)
libcurl: 8.5.0-DEV (sys:0.4.70+curl-8.5.0 vendored ssl:OpenSSL/1.1.1w)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Ubuntu 22.04 (jammy) [64-bit]
```

**Comment by aniketch07** [comment]
note: this is an unexpected cargo internal error

**Comment by weihanglo** [comment]
The CLI can be installed inside a docker image without the error.

> Caused by:
failed to download replaced source registry crates-io

You might have configured [source replacement](https://doc.rust-lang.org/nightly/cargo/reference/source-replacement.html) or vendoring somewhere. Check `.cargo/config.toml` or run `cargo +nightly -Zunstable-options config get source --show-origin` to find where it is set.

Close as it is likely to be a misconfiguration slipping in. Let us know if it turns out to be a bug in Cargo and we will revisit.
