### ISSUE TITLE
Generate nix package from a crate

### ISSUE THREAD

**Issue by dev-ardi** [rust-lang/cargo#13746]
### Problem

It would be nice for the maintainers of nix packages to be able to generate a package from the current version of a crate.

### Proposed Solution

`cargo build --generate-nix-package`

Reads the data from Cargo.toml and generates something like
```nix
{ lib, stdenv, fetchCrate, rustPlatform, pkg-config }:

let
  pname = "cargo-my-package";
  version = "1.0.0";
in

rustPlatform.buildRustPackage rec {
  inherit version pname;

  src = fetchCrate {
    inherit version pname;
    hash = "sha256-GiUjsSqnrUNgiT/d3b8uK9BV7cHFvaDoq6cUGRwPigM=";
  };

  cargoHash = "sha256-oXOPpK8VWzbFE1xHBQYyM5+YP/pRdLvTVN/fjxrgD/c=";

  nativeBuildInputs = [ pkg-config ];

  meta = with lib; {
    description = "My crate description";
    homepage = "https://github.com/dev-ardi/my-package";
    license = licenses.mit;
    maintainers = with maintainers; [ "dev-ardi" ];
  };
}
```

**Comment by epage** [comment]
Aren't there existing third party tools for this?

As for building something in,
- This would be part of our compatibility story which limits what we can
- This builds in support for a specific ecosystem without consideration for other ecosystems or what happens when that ecosystem is no longer relevant

**Comment by dev-ardi** [comment]
It makes sense to not have inside of cargo proper, a plugin would make more sense, you're right.
