### ISSUE TITLE
`missing-docs` triggers for missing module docs in build scripts

### ISSUE THREAD

**Issue by wmmc88** [rust-lang/cargo#13799]
I created an empty `build.rs` file and build with `-W missing-docs` and it triggered this warning:
```
warning: missing documentation for the crate
 --> crates\wdk-alloc\build.rs:4:1
  |
4 | fn main() {}
  | ^^^^^^^^^^^^
  |
  = note: requested on the command line with `-W missing-docs`
```

AFAIU, buildscripts functions/modules/etc can't show up in generated rustdocs, so should this warning not trigger?

### Meta

`rustc --version --verbose`:
```
rustc 1.77.2 (25ef9e3d8 2024-04-09)
binary: rustc
commit-hash: 25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04
commit-date: 2024-04-09
host: x86_64-pc-windows-msvc
release: 1.77.2
LLVM version: 17.0.6
```

This also happens on latest nightly.

**Comment by weihanglo** [comment]
Just transferred and realized it also happens when people try to document binaries.

It's a bit hard to tell the intent of using [`missing-docs`](https://doc.rust-lang.org/rustc/lints/listing/allowed-by-default.html#missing-docs) lint. People might just want to document every item in source code, regardless being generated to rustdoc HTML.

Users have the option that put a `#[allow(missing-docs)]` and move on.

**Comment by weihanglo** [comment]
I generally consider it as expected. Is there any missing piece that blocks something I am not aware of?

**Comment by wmmc88** [comment]
I opened it without considering the use case of just documenting everything (vs. things that show up in rustdoc)
