### ISSUE TITLE
bit-set 0.2.0 compilation failed

### ISSUE THREAD

**Issue by positiveway** [rust-lang/cargo#13824]
### Problem

https://github.com/rust-lang/cargo/issues/9885
Same issue reappeared with bit-set v.0.2.0 dependency of libusb on nightly 1.80.0 (maybe even on 1.79, it was ok last time I checked 2 weeks ago)

**Comment by epage** [comment]
This has had a "we'll break this in the future" message for 2.5 years (though not elevated for dependents to see).  The last `bit-set` version with this problem was 0.3.0 and was released 8 years ago with the fix in 0.4.0 was also released 8 years ago.  There have been 4 newer versions since then.

Of the 93 dependents, the following are the only ones where the latest version still depends on a "bad" version of `bit-set`:
- https://crates.io/crates/libusb
- https://crates.io/crates/bdf
- https://crates.io/crates/rustlex_codegen

**Comment by epage** [comment]
We talked about this in today's meeting.

We are planning to keep this as-is because
- This was a bug
- We started notifying several years ago about this
- Newer versions of the package are fixed and this is a problem with an unmaintained dependent
  - There seem to be maintained, more popular replacements in the form of [rusb](https://crates.io/crates/rusb) which had a release just 3 days ago and has 6x the total downloads

**Comment by tanriol** [comment]
I want to note that the error message here is less useful than usual - it tells me about the problematic crate, but does not tell me how it got pulled in, and `cargo tree -i bit-set` just produces the same error again without any additional information.
