### ISSUE TITLE
Allow linker override specifically for build scripts and proc macros

### ISSUE THREAD

**Issue by AldanTanneo** [rust-lang/cargo#14105]
### Problem

When cross compiling for a target that has the same architecture as the host, the build scripts and proc macros are compiled with the target linker. However, those builds are not meant to be run on the target!

In my use case, I was building on an x86_64-unknown-linux-gnu host with glibc 2.31, and the target environment was x86_64-unknown-linux-gnu with glibc 2.38, and a specific linker for this target. 

The build scripts and proc macros were failing with dynamic linking errors, saying they couldn't find the correct libc version, because they had been linked with the target linker, not the host linker.

### Proposed Solution

Allow the user to specify if they want to build the build scripts / proc macros with a different linker or not.

### Notes

As a workaround, I used [this rustc wrapper script](https://gist.github.com/AldanTanneo/5c1f57dc0917d1a1757150a521d63929), that will remove the `-C linker=...` arguments if the crate name is `build_script_build`, or the crate type is `proc-macro`

**Comment by epage** [comment]
Could you provide reproduction steps to remove any chance of misunderstanding in what you are running into?

if I understand correctly, instead of saying `cargo build --target <host>`, you are doing `cargo build` and the linker flags are being applied to everything.  If so, is there a reason you can't use `--target`?

Also, if I'm understanding correctly, we have no mechanism to set the linker, so in the end, this is about setting `RUSTFLAGS` until and unless we expose the linker otherwise (see #12739).

**Comment by AldanTanneo** [comment]
Steps to reproduce:
- Have a crate with a build script or proc macro somewhere in the dependency tree
- Start a Debian 11 x86_64 container, and somehow install/copy GCC 12 on it
- Build the crate with `cargo build --target x86_64-unknown-linux-gnu`, with GCC 12 as the linker for `x86_64-unknown-linux-gnu` in `.cargo/config.toml`
- Behold: build scripts and proc macros fail to run, as they were linked with GCC 12, which links to glibc >=2.32, and Debian 11 only has glibc 2.31

**Comment by epage** [comment]
So you are using `--target` , the cross-compiler linker is being used?  Is it being used with just `cargo build` as well?

#4423 is about something similar (RUSTFLAGS for build scripts) but specifically mentions that RUSTFLAGS is only applied to the platform-target builds and not the host-target builds.  So how are your host-target builds using GCC 12?  I wonder if rustc is using a system linker and somehow GCC 12 is being treated as the system linker.  If so, then likely the core of your problem is a system configuration problem, rather than #4423.

if somehow that can't be addressed and can only be solved in Cargo, then this is another version of #4423.  Closing in favor of that.  If there is a reason for us to keep this open separately, let us know!

**Comment by AldanTanneo** [comment]
Well my issue boils down to the fact that when target and host have the same triple, the target linker is used for build scripts, which only happens in this case. In a sense, this is the opposite of #4423? As, if I understand correctly, #4423 is about *adding* flags to build script compilation, and I want to remove some? Unless I did not read the issue far enough

**Comment by AldanTanneo** [comment]
I found an issue on the rust forums with the same problem that might be clearer as to what the issue actually is: https://users.rust-lang.org/t/same-arch-cross-compile-linker-mixup/82337
