### ISSUE TITLE
Allow build scripts to add dependencies to the library being built

### ISSUE THREAD

**Issue by daboross** [rust-lang/cargo#1417]
It would be awesome if build scripts could build fully-made crates in the $OUT_DIR folder, including a Cargo.toml, which the library could then depend on.

I'm not sure of the best way to implement this, but here are a few iedas:
- Add support for parsing a `cargo:add-local-dependency:$path` output from the build script
- Add support for environmental variables in `Cargo.toml`, so you could use:
  ```
  [dependencies.generated-module]
  path = "$OUT_DIR/generated-module/"
  ```

The reasoning for doing this instead of just `include!()`ing the code is for build scripts which generate code which depends on some crates.io library which the main program does not.

Here's my use case for this:

Adding this would allow for a rust program to accept (at compilation time) self-dependent `plugin` rust files, with dependency information in comments at the top of the file. `build.rs` would generate a Cargo.toml including what the plugin depends on, which the main library could then depend on.

**Comment by daboross** [comment]
One other thing that would need to be changed to allow this is parsing all of the Cargo.toml files for dependencies *before* running the build script.

Because the build script would be generating a dependency, the `Cargo.toml` for the generated dependency would not exist before `build.rs` is run.

**Comment by alexcrichton** [comment]
I think that this opens too many more cans of worms than we'd really like to do unfortunately. Generating dependencies dynamically sounds like it can easily cause problems where builds succeed in one place but not others (because Cargo can't ensure that all dependencies follow the project).

Right now the build script doesn't really provide all that much feedback back to the build process though and I could definitely see improving that aspect and providing a few more options here and there.

**Comment by daboross** [comment]
Ok, sounds good. I guess for my use case at least, a wrapper with `make` will probably be the best solution.

**Comment by alexcrichton** [comment]
Thanks for the issue regardless!
