### ISSUE TITLE
Mismatch rust version in cargo and global installation

### ISSUE THREAD

**Issue by chandankrishn** [rust-lang/cargo#14219]
### Problem

solana-hello-world % cargo build-bpf
error: package `bumpalo v3.16.0` cannot be built because it requires rustc 1.73.0 or newer, while the currently active rustc version is 1.72.0-dev
Either upgrade to rustc 1.73.0 or newer, or use
cargo update -p bumpalo@3.16.0 --precise ver
where `ver` is the latest version of `bumpalo` supporting rustc 1.72.0-dev
 solana-hello-world % rustc --version
rustc 1.79.0 (129f3b996 2024-06-10) (Homebrew)

I have been running cargo build-bpf. It is showing some different version of rustc and while global rustc is different 
- I have tried uninstalling rustc by brew
- I have reinstalled it several times

**Comment by Muscraft** [comment]
If I am reading [this issue](https://github.com/solana-labs/solana/issues/31428) correctly, the problem you are running into is caused by `solana`, not by `cargo`. It looks like that issue talks about possible solutions and links to others that have potential solutions.

**Comment by Skgland** [comment]
Also I just noticed that you are running `cargo build-bpf` rather than `cargo build`, so it looks like this might be a similar problem to https://github.com/solana-labs/solana/issues/34987 it looks like a [better error message was only implemented for `build-sbf`](https://github.com/solana-labs/solana/issues/31428) but not `build-bpf`

**Comment by Skgland** [comment]
Maybe the cargo error message could be improved to indicate where the rustc it is using originates
