### ISSUE TITLE
pass git flags to git command line

### ISSUE THREAD

**Issue by soloturn** [rust-lang/cargo#14311]
### Problem

git clone / fetch is much quicker when using `--filter=blob:none`. how can one pass to cargo that this is used? am trying to convince cargo to use command line git.

```
CARGO_NET_GIT_FETCH_WITH_CLI=true  cargo ... 
```
i am aware of #11165.

**Comment by weihanglo** [comment]
Unsure if this is a thing we want to support. Normally we don't want to depend on external executables. Doing this may also break your global cache `~/.cargo/{registry,git}` because of Git index fetched might not be complete.

I don't think we would like to accept arbitrary args for `git`. A general approach for this issue might be a plugin interface of source fetcher for users to declare how they are going to fetch code sources. (I can't find relevant links/issues at this moment 😞)

In the meanwhile, a workaround in my mind is wrapping your `git` with shell script, and prepend a `PATH` containing that script.

**Comment by soloturn** [comment]
@weihanglo when cloning with ``` --filter=blob:none``` the checkout should work without problems. git would get the blobs from the server.


``` 
❯ git clone --filter=blob:none git@github.com:rust-lang/cargo.git
❯ cd cargo
❯ git checkout 04f9e2dfc
remote: Enumerating objects: 83, done.
remote: Counting objects: 100% (79/79), done.
remote: Compressing objects: 100% (77/77), done.
remote: Total 83 (delta 14), reused 8 (delta 2), pack-reused 4 (from 1)
Receiving objects: 100% (83/83), 664.68 KiB | 1.90 MiB/s, done.
Resolving deltas: 100% (14/14), done.
Updating files: 100% (281/281), done.
Note: switching to '04f9e2dfc'.
```

**Comment by epage** [comment]
To put one of the concerns a different way, Allowing arbitrary arguments could break invariants / assumptions cargo makes which, because of caching, would be carried forward even if you remove these flags.

This would also restrict how we can evolve the implementation because which commands we choose to call could change but our hands would be tied or the user's flags might not have conflicted in the past but then we change what flags we pass and now they do conflict.

Especially as the request is related to an optimization, I propose we close this.

**Comment by weihanglo** [comment]
Fair. Thanks and close.
