### ISSUE TITLE
Display download progress.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/cargo#1435]
If running in a TTY: show a percentage, a progress bar, _even_ a spinning indicator of some sort.
Any of those would have prevented me from assuming it hanged while downloading the Skia dependency of Servo (mentioned in #1171).

As an aside, does Cargo restart a git repository fetch after stopping `cargo build` and running it again, without mentioning what it's doing? That was also somewhat confusing.

**Comment by alexcrichton** [comment]
Right now we have the tooling in place to learn about progress of git downloads, but we do not have the ability to learn about the progress of HTTP downloads (unfortunately). I agree though that this would be quite nice to have!

**Comment by SimonSapin** [comment]
This is still desirable.

Servo regularly gets bugs like https://github.com/servo/servo/issues/7687 filed because the initial build *looks like* it got stuck and is not making progress, while the git clone of servo/skia *is* making progress, but can take a very long time to download 300 MB, depending of the internet connection.

**Comment by n42k** [comment]
Bump!

My internet can be rather slow at times (I've measured <1024B/s before) and a progress bar when files are being downloaded would be very, very useful.

For example, when running "cargo build --release" it takes several minutes, which made me assume it crashed, as I had never used rust before and I was just compiling a program.

**Comment by alexcrichton** [comment]
This has since been implemented
