### ISSUE TITLE
Cargo needs a way to delete a release

### ISSUE THREAD

**Issue by mitsuhiko** [rust-lang/cargo#1436]
Currently you cannot delete a release.  This can turn into a very scary situation if someone accidentally releases an internal package that was never intended for publication or because of other legal problems associated with this.

**Comment by alexcrichton** [comment]
This is currently intentional, the reason being that deleting a release is generally the fist thing you reach for when you accidentally publish and it's rarely what you want to actually do (hence the `yank`). There's definitely a legitimate reason for deletion, however (such as what you've mentioned), but they're pretty rare. For these cases we can be contacted directly for removal, and any form of legal reasons would be forwarded to Mozilla lawyers currently instead of us handling directly.

**Comment by lamont-granquist** [comment]
I just wanted to add a +1 to alexchriton's comment closing this issue.  The semantics of rubygems 'gem yank' are to do a permadelete, and it causes chaos when the artifact disappears while people still have it equality locked in Gemfile.lock files.  The way that cargo's yank works is the correct implementation that steers the use case that most people have of "oh that code sucks nobody should use it" towards just marking the package as 'bad' while still keeping it available.  The use case where someone pushes trade secrets to a public repo is vastly less common and should be handled by a much heavier API (like e-mailing someone).  This is because most people who think they 'need' to delete a release do not really have that 'need' and do not understand the implications and really do need to be steered towards the current 'yank' implementation.

Even in the case where you've accidentally released production secret keys the problem is that there's no possible way to delete all copies of that information off of the Internet and everywhere that it has already been mirrored/cached.  The only real mitigation is for the key material to be rotated, trying to delete it off the internet isn't possible.

**Comment by patcon** [comment]
I'm not a stakeholder, but my 2c:

Should not be yankable, but might be nice if cargo were extremely defensive, and defaulted to publish="false" when unspecified:
http://doc.crates.io/manifest.html#the-publish--field-optional
