### ISSUE TITLE
Readme file is allowed to not be in the .crate package

### ISSUE THREAD

**Issue by xTachyon** [rust-lang/cargo#14468]
### Problem

I'm not sure if this is known, it's considered fine, or even if this is the right place, but here we go.

I found [this](https://github.com/tokio-rs/valuable/blob/3d820c0bb193a34d05c7145632266d058d37db97/valuable/Cargo.toml#L7) crate that's published as `valuable:v0.1.0` that has this line:
```
readme = "../README.md"
```
The readme seems to be available on [crates.io](https://crates.io/crates/valuable) with no problem, but it's not available in the .crate package.

While this is probably fine for most users, it has issues if you're ever trying to parse the .crate format by yourself, and see the readme.

### Possible Solution(s)

IMHO, paths outside the package directory should not be allowed.

**Comment by weihanglo** [comment]
The [`valuable`](https://crates.io/crates/valuable) crate was published a few years ago. Cargo started emitting warning for non-existent README since <https://github.com/rust-lang/cargo/pull/12036>, and it becomes a hard error since <https://github.com/rust-lang/cargo/pull/13921>. It's impossible to go back in time and fix that, but any crate published later shouldn't have this issue.

Since the issue is fixed, I am going to close. If you find it happen again, please let us know. Thank you :)

**Comment by epage** [comment]
Besides the error on non-existent READMEs, `cargo package` should also copy readmes from outside the package to inside it on `cargo package`
https://github.com/rust-lang/cargo/blob/c1fa840a85eca53818895901a53fae34247448b2/src/cargo/ops/cargo_package.rs#L557-L579

This was added in #10548 (1.62) to help with inheriting `workspace.package.readme`.
