### ISSUE TITLE
Default cargo output should prioritize warnings over "Compiling foo" line spam

### ISSUE THREAD

**Issue by bonsairobo** [rust-lang/cargo#14596]
### Problem

It's very easy to miss some warnings because they are printed *before* a deluge of "Compiling foo" lines that quickly fill the terminal buffer.

This is not a problem when using the `-q` flag, but this is not the default. `-q` also doesn't provide a progress bar.

### Proposed Solution

The default cargo output should exclude spam, while ensuring that warnings and progress are visible.

If users still want the spam, they should use `-v`.

**Comment by epage** [comment]
As an example of what you are referring to, on a small scale
```console
$ cargo check
    Checking utf8parse v0.2.2
    Checking is_terminal_polyfill v1.70.0
    Checking anstyle-query v1.1.0
    Checking colorchoice v1.0.1
    Checking anstyle v1.0.8
warning: type `foo` should have an upper camel case name
   --> clap_lex/src/lib.rs:127:8
    |
127 | struct foo;
    |        ^^^ help: convert the identifier to upper camel case (notice the capitalization): `Foo`
    |
    = note: `#[warn(non_camel_case_types)]` on by default

warning: struct `foo` is never constructed
   --> clap_lex/src/lib.rs:127:8
    |
127 | struct foo;
    |        ^^^
    |
    = note: `#[warn(dead_code)]` on by default

    Checking strsim v0.11.1
warning: `clap_lex` (lib) generated 2 warnings
    Checking anstyle-parse v0.2.4
    Checking anstream v0.6.14
    Checking clap_builder v4.5.18 (/home/epage/src/personal/clap/clap_builder)
    Checking clap v4.5.18 (/home/epage/src/personal/clap)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 1.05s
```

We currently printing events as they happen, rather than buffering them.

#8749 has the same root problem but only focuses the solution discussion on a subset of the problem (handling of summaries).  In #8889, we are discussing a more generalized improvement to our compilation output.  #8743 is about having quiet output while seeing progress indicators.  I'd recommend we consolidate the conversation to those issues and am closing in favor of them.
