### ISSUE TITLE
`cfg(doc)` isn't set in build scripts

### ISSUE THREAD

**Issue by maia-s** [rust-lang/cargo#14601]
### Problem

I want to skip (building and) linking a native library when generating documentation, because it takes a long time and might fail on docs.rs, but `cfg(doc)` isn't set in build scripts when generating documentation.

### Steps

1. Create a build script for a crate:
```rust
fn main() {
    #[cfg(doc)]
    panic!("doc");
}
```
2. Run `cargo doc -v`
3. The build script is run, but cfg(doc) isn't true

### Version

cargo 1.81.0 (2dbb1af80 2024-08-20)
release: 1.81.0
commit-hash: 2dbb1af80a2914475ba76827a312e29cedfa6b2f
commit-date: 2024-08-20
host: aarch64-apple-darwin
libgit2: 1.8.1 (sys:0.19.0 vendored)
libcurl: 8.7.1 (sys:0.4.73+curl-8.8.0 system ssl:(SecureTransport) LibreSSL/3.3.6)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Mac OS 15.0.0 [64-bit]

cargo 1.83.0-nightly (c1fa840a8 2024-08-29)
release: 1.83.0-nightly
commit-hash: c1fa840a85eca53818895901a53fae34247448b2
commit-date: 2024-08-29
host: aarch64-apple-darwin
libgit2: 1.8.1 (sys:0.19.0 vendored)
libcurl: 8.7.1 (sys:0.4.74+curl-8.9.0 system ssl:(SecureTransport) LibreSSL/3.3.6)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Mac OS 15.0.0 [64-bit]

**Comment by weihanglo** [comment]
Thank you for the report!

Similar requests have been open

* #3053
* #8811
* #8944
* This is a summary I made three months ago, which is about differentiating Cargo command/mode in general: https://github.com/rust-lang/cargo/issues/4001#issuecomment-2187763196

At this moment you might need to follow [this docs.rs official guide](https://docs.rs/about/builds#detecting-docsrs) to check whether it is a docs.rs build.

Since this is kinda a dup of those above, I am going to close this. Please let us know if there is a reason to keep this issue open separately. Thanks.
