### ISSUE TITLE
cargo add cannot enable features if version="*" in Cargo.toml

### ISSUE THREAD

**Issue by georgmu** [rust-lang/cargo#14648]
### Problem

When trying to run `cargo add crate -F feature` with `crate = "*"`  or `crate = { version="*" }` in Cargo.toml, an error is returned.

### Steps

1. Add `time = "*"` to Cargo.toml
2. Run the following command:
```
$ cargo +nightly add time -F serde
    Updating crates.io index
      Adding time * to dependencies
error: unrecognized feature for crate time: serde
no features available for crate time
```

3. Change `time = "*"` to `time = "0.3"`
4. Run the command again:
```
$ cargo +nightly add time -F serde
    Updating crates.io index
      Adding time v0.3 to dependencies
             Features as of v0.3.0:
             + alloc
             + serde
             + std
             - formatting
             - itoa
             - large-dates
             - local-offset
             - macros
             - parsing
             - quickcheck
             - quickcheck-dep
             - rand
             - serde-human-readable
             - time-macros
```

List of features changes when using the last concrete version (0.3.36).

### Possible Solution(s)

For version="*", I would expect that it uses the feature list of the used root dependency (as in Cargo.lock)  or of the latest version available.

### Version

cargo 1.83.0-nightly (80d82ca22 2024-09-27)
release: 1.83.0-nightly
commit-hash: 80d82ca22abbee5fb7b51fa1abeb1ae34e99e88a
commit-date: 2024-09-27
host: x86_64-unknown-linux-gnu
libgit2: 1.8.1 (sys:0.19.0 vendored)
libcurl: 8.9.0-DEV (sys:0.4.74+curl-8.9.0 vendored ssl:OpenSSL/1.1.1w)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Fedora 41.0.0 (FortyOne) [64-bit]

**Comment by epage** [comment]
When `cargo add` looks for available features to display and validate against, it looks to the oldest version compatible with your version requirement, assuming
1. You set the minimum supported version in your version requirement
2. The dependency doesn't remove features, making this the lowest common denominator for your version requirement.  Granted, this gets fuzzy with multi-major version requirements.

In your case, its picking `time = "0.1.0"` and only allowing features from that version.

**Comment by Kelvin-1013** [comment]
The issue you're encountering with using cargo add and the version = "*" syntax is related to how Cargo resolves features for dependencies. When you specify a version as "*", Cargo does not fetch the features for the latest version of the crate, which is why you're seeing the error about the unrecognized feature.

-Check Latest Version: If you want to automatically use the latest version while also ensuring you have the right features, you can check the latest version of the crate and specify that version explicitly:
`

> cargo search time

`
-Using cargo update: If you want to ensure that your dependencies are updated to the latest versions, you can run:
`

> cargo update

`
-Feature List Retrieval: If you want to see what features are available for a crate without adding it, you can use:
`

> cargo search time

`
This will show you the latest version and its features.
-Using cargo add with Specific Version: If you want to add the crate with a specific version and include features, you can do so directly:


`> cargo add time@0.3 -F serde
`

**Comment by weihanglo** [comment]
@Kelvin-1013 please don't post LLM responses without reading and reformatting.

**Comment by weihanglo** [comment]
The behavior is written down here in code: <https://github.com/rust-lang/cargo/blob/d8cb5fb7f8f66fc9b4ba3d80b089474164a8a83d/src/cargo/ops/cargo_add/mod.rs?plain=1#L1040-L1054>

It seems pretty like an implementation detail relying on the assumption in the comment. I don't think this should be documented, and picking up the latest version isn't better either. I would propose we close this as the behavior is intended.

**Comment by Kelvin-1013** [comment]
Thank you for your detailed report on the issue with cargo add and the version="*" specification. I appreciate the clarity in your steps and the examples provided.

It's clear that the current behavior is tied to how Cargo determines the lowest common denominator for features based on the earliest compatible version. Your observation about it defaulting to time = "0.1.0" and the limitations that come with that is insightful.

While I understand the rationale behind this implementation, I agree that it can lead to confusion, especially when users expect the latest features to be available with a wildcard version. However, since this behavior seems intentional and documented in the code, I support closing this issue as 'not planned.'

It might be worth considering whether we could improve the documentation around this behavior in the future to help users understand the implications of using wildcard versions better. Thanks again for bringing this to our attention!

**Comment by epage** [comment]
imo if we did anything, it would likely to be lint against wildcard dependencies, see #5340

**Comment by ctz** [comment]
It seems odd that cargo, which has a ton of code about resolving versions of crates, doesn't reuse this for determining which version's features are in play here? Especially in this case where the actual version is already known in Cargo.lock?

A diagnostic sounds good to me -- the current behaviour is surprising.

**Comment by epage** [comment]
The current version is in `Cargo.lock` but your dependency specification says any version in existence could be used instead.  We are trying to pick features that work for your dependency specification.  However, as I said earlier

> Granted, this gets fuzzy with multi-major version requirements.
