### ISSUE TITLE
Cargo should not download the full code repository on which it depends.

### ISSUE THREAD

**Issue by silence-coding** [rust-lang/cargo#14689]
### Problem
like https://github.com/rust-lang/cargo/issues/14687

Some of the problems are solved in the previous issue. However, when the Cargo.lock file is carried and is not a GitHub code repository, the cargo will go to the GitReference::Rev branch due to the lock file. As a result, the cargo will download all tags.

https://github.com/rust-lang/cargo/blob/1975c3ca530e4e168f517275c45a32a3b1b3a3bc/src/cargo/sources/git/utils.rs#L983-L1010

### Proposed Solution

In the fetchall tag scenario, if the content in the source is a tag, the tag branch  is used.
```
[[package]]
name = "hyper"
version = "0.14.30"
source = "git+https://open.codehub.com/hyperium/hyper.git?tag=v0.14.30#618a18580ae14776c05ab6789a82b5c43281fe8b"
```

**Comment by silence-coding** [comment]
https://github.com/rust-lang/cargo/issues/14687

**Comment by weihanglo** [comment]
Okay I see what you mean. `rev` could be an arbitrary git ref. Cargo cannot understand which revision it is looking for without downloading everything.

We have a specialized branch for GitHub because
* GitHub is one of the major Git hosting services that is worth a special optimization.
* GitHub's Git Server has the [`allow-reachable-sha1-in-want`](https://git-scm.com/docs/protocol-capabilities#_allow_reachable_sha1_in_want) and provides API for that. Other Git hosting service  must have such ability so we can investigate

See what we did for GitHub:

* https://github.com/rust-lang/cargo/issues/10078
* https://github.com/rust-lang/cargo/pull/10079
* https://github.com/rust-lang/cargo/pull/10807
* https://github.com/rust-lang/cargo/pull/13946
* https://github.com/rust-lang/cargo/pull/13969

Hence please provide the platform you want to speed up with their docs about Git capabilities and API support. We will evaluate whether the case is worth a dedicated solution.

Worth noting that tags fetch is not the major contributing factor of fetching Git dependencies, shallow clones is the game changer which we already have an unstable feature waiting for feedback.

**Comment by silence-coding** [comment]
You're right. The current cost of pulling full tags is not high, and the community should not pay too much for customization. We can wait until the shallow clones is ready.
