### ISSUE TITLE
cargo doc --open does nothing

### ISSUE THREAD

**Issue by ruabmbua** [rust-lang/cargo#1472]
The command `cargo doc --open` should build the docs, and open them in a browser after compilation finished.

The command only builds the docs, but after building is finished no further action takes place(opening doc in browser). The problem exists for me on both windows and arch linux. Both operating systems have firefox configured as their default browser.

**Comment by huonw** [comment]
Do the docs open if you run `cargo doc; xdg-open target/doc/CRATENAME/index.html`? Also, are you running `cargo doc` inside a shell or inside some other program? Lastly, what is the name of your package? (Specifically, does it contain a hyphen?)

**Comment by ruabmbua** [comment]
xdg-open works just fine. I am using the kde konsole, in which regular bash is running. Also my the full path to my project does only contain [a-zA-Z] characters.

**Comment by Gustorn** [comment]
For me `cargo doc --open` works fine with KDE/Konsole (default browser is Chromium).
Cargo version: 
```
cargo 0.0.1-pre-nightly (471c519 2015-04-08) (built 2015-04-09)
```

KDE / Konsole: 
```
Qt: 5.4.1
KDE Frameworks: 5.9.0
Konsole: 15.04.0
```

**Comment by ruabmbua** [comment]
My versions are:

Qt: 5.4.1
KDE Frameworks: 5.8.0
Konsole: 3.0.1

For the date of me making the bug report, these version were very recent. What is about the Konsole version 15.04.0? On my OS (archlinux) Konsole 3.0.1 is the most recent  one.

**Comment by Gustorn** [comment]
I'm using Arch Linux too, with the `testing` and `kde-unstable` repos.

**Comment by ruabmbua** [comment]
Ah okay. Maybe it will work, when I get access to kde  frameworks 5.9.0 and the more recent konsole. I do not want to use testing, but I will come back here and comment again, when I get the update.

**Comment by mohtar** [comment]
This happened to me, and after some digging I think I may have isolated the problem. Although, I'm not sure if my particular case is the same as @ruabmbua's.

If the package has executables only but no lib (i.e. `src/lib.rs`), then `cargo doc --open` wouldn't work. A workaround is to specify the package name explicitly: `cargo doc --open --package <name>`.

There's another separate case: when the package name contains a hyphen in it, then `cargo doc --open` would also fail (and silently, too). A workaround is to add a `[lib]` section in the manifest with a different `name` from the package, and it must not contain a hyphen.

I'm guessing both behaviors are unintended. I believe know where the culprit lies and I may open a pull request soon... once I devised a viable fix.

**Comment by ruabmbua** [comment]
@mohtar: Yes it seems like I habe the same issue(not having a lib.rs in my source tree).

**Comment by mohtar** [comment]
Well that confirms my suspicions then!

**Comment by mucahitkurtlar** [comment]
I had a similar problem. `cargo doc --open` was opening KDE Itinerary. But fixed it in KDE system settings on my Arch Linux + KDE Plasma machine. Go `Settings > Applications > File Associations > text > html` and `Move Up` or `Add...` your favorite browser
