### ISSUE TITLE
Attempt to kill running process of output binary on access denied error on Windows

### ISSUE THREAD

**Issue by dsherret** [rust-lang/cargo#14757]
### Problem

I'll sometimes run `cargo build` and get an error like the following on Windows:

```
Compiling deno v2.0.4 (V:\deno\cli)
error: failed to remove file `V:\deno\target\debug\deno.exe`

Caused by:
  Access is denied. (os error 5)
```

This is because I accidentally have the process running in the background, so I need to kill the process manually, then re-run `cargo build`.

This isn't so bad for debug builds, but can be a bit of a time waste for release builds.

### Proposed Solution

I propose that if cargo encounters one of these errors it should check if the process is running, kill it and try again. This will collectively save Windows devs a decent amount of time.

An example of how this could be implemented is to just spawn `powershell -Command` with a script source like:

```
Get-WmiObject Win32_Process | Where-Object {
    $_.Path -eq 'V:\deno\target\debug\deno.exe'
} | ForEach-Object {
  if ($_.Terminate()) {
    Write-Host 'Terminated:' $_.ProcessId
  }
}
```

...when it fails it could just surface the original error.

**Comment by epage** [comment]
Another workflow that hits this was reported in #12485 and our suggested fix for that is to improve the error message.

Considering we don't know the users intent and people can hit this with "unrelated" commands like `cargo run` and `cargo test`, I would be disinclined for us to kill the process.  However, we should probably consolidate that conversation on #12485 since the options are mutually exclusive.  As such, I'm closing in favor of #12485.  If there is a reason we should keep this open separately, let us know!

**Comment by dsherret** [comment]
Ah sorry, I searched the issue tracker for the proposed solution and not the problem.
