### ISSUE TITLE
`cargo update --breaking` doesn't update Cargo.lock in some corner-cases

### ISSUE THREAD

**Issue by ia0** [rust-lang/cargo#14888]
### Problem

`cargo update --breaking` (and `cargo metadata`, `cargo check`, etc) fail to resolve a dependency requirement that seems resolvable.

### Steps

I tried to create a minimal reproduction example but I failed. So here is the reproduction example (I'm forcing `+nightly` to avoid polluting your rustup, I don't think the exact version matters):

```shell
git clone https://github.com/google/wasefire.git
cd wasefire/crates/cli-tools
git checkout 247c701928e080530d1bae953c8bdb209608a330
cargo +nightly -Z unstable-options update --breaking
cd ../cli
cargo +nightly -Z unstable-options update --breaking
```

I get the following output:

```
error: failed to select a version for `syn`.
    ... required by package `thiserror-impl v2.0.3`
    ... which satisfies dependency `thiserror-impl = "=2.0.3"` of package `thiserror v2.0.3`
    ... which satisfies dependency `thiserror = "^2.0.3"` of package `cargo_metadata v0.19.1`
    ... which satisfies dependency `cargo_metadata = "^0.19.1"` of package `wasefire-cli-tools v0.2.1-git (/tmp/wasefire/crates/cli-tools)`
    ... which satisfies path dependency `wasefire-cli-tools` (locked to 0.2.1-git) of package `wasefire-cli v0.2.1-git (/tmp/wasefire/crates/cli)`
versions that meet the requirements `^2.0.87` are: 2.0.90, 2.0.89, 2.0.88, 2.0.87

all possible versions conflict with previously selected packages.

  previously selected package `syn v2.0.66`
    ... which satisfies dependency `syn = "^2.0.8"` (locked to 2.0.66) of package `clap_derive v4.5.4`
    ... which satisfies dependency `clap_derive = "=4.5.4"` (locked to 4.5.4) of package `clap v4.5.4`
    ... which satisfies dependency `clap = "^4.5.4"` (locked to 4.5.4) of package `wasefire-cli v0.2.1-git (/tmp/wasefire/crates/cli)`

failed to select a version for `syn` which could resolve this conflict
```

I don't understand why cargo doesn't select `syn v2.0.90`. Is there a way to print debug info during resolution?

### Notes

Similar situations work, so I'm assuming this should always work. But maybe this assumption is wrong and this corner-case is not supported. But I'd like to understand what characterizes this corner-case then.

### Version

```text
cargo 1.84.0-nightly (e75214ea4 2024-10-25)
release: 1.84.0-nightly
commit-hash: e75214ea4936d2f2c909a71a1237042cc0e14b07
commit-date: 2024-10-25
host: x86_64-unknown-linux-gnu
libgit2: 1.8.1 (sys:0.19.0 vendored)
libcurl: 8.9.0-DEV (sys:0.4.74+curl-8.9.0 vendored ssl:OpenSSL/1.1.1w)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Debian n/a (rodete) [64-bit]
```

**Comment by epage** [comment]
iiuc If you run `cargo update foo --precise 3.2.1`, then only `foo` will be updated. If that version of `foo` needs a newer version of `syn` to work, then it will error because we lock all other dependencies.  If you pass `--recursive`, we then only unlock the dependency tree which helps in most cases but not all, and will cause dependencies to update that didn't necessarily need to.

I'm guessing `cargo update --breaking` is leaving the rest of the dependencies locked so they can't update, unlike manually editing `Cargo.toml`.  In a way `--breaking` is an update "force" flag  and a package selection flag.  If we remove the package selection flag part, then non-breaking updates will happen to other dependencies which might not be what the user wants.

I'd be curious if this works with `--recursive`.

Personally, I feel like there are quite a few pitfalls with `cargo update`s defaults and wonder if we should evaluate what can be changed and what the workflows should be.

**Comment by epage** [comment]
Potentially related issues
- #5484
- #10189
- #10307
