### ISSUE TITLE
cargo build-sbf fails with Failed to install platform-tools: HTTP status client error (404 Not Found) error

### ISSUE THREAD

**Issue by farawaystar** [rust-lang/cargo#14909]
when running cargo build-sbf I get this error
ERROR cargo_build_sbf] Failed to install platform-tools: HTTP status client error (404 Not Found) for url (https://github.com/anza-xyz/platform-tools/releases/download/v1.42/platform-tools-osx-x86_64.tar.bz2)

tried solutions but didn't work:
-> reinstalling latest solana version from Anza: sh -c "$(curl -sSfL https://release.solana.com/stable/install)"
-> clearing cache using cargo clean
-> cargo update
-> rustup update
-> ensuring cargo.toml file has same solana version and my CLI
-> cargo build-bpf also gives the same error

help greatly appreciated

**Comment by Muscraft** [comment]
This error is not coming from `cargo` but from [`cargo-build-sbf`](https://github.com/anza-xyz/agave/blob/be115c7a31c51ad549c9b3eac74735c55019d3db/sdk/cargo-build-sbf/src/main.rs#L699), which is [custom subcommand](https://doc.rust-lang.org/cargo/reference/external-tools.html?#custom-subcommands) from Solana. Since that is the case, I am going to close this. I suggest you open an issue in the [agave repo](https://github.com/anza-xyz/agave).
