### ISSUE TITLE
When creating a bin crate inside a lib crate, Cargo.lock is ignored.

### ISSUE THREAD

**Issue by LaylConway** [rust-lang/cargo#1511]
When creating a lib project, cargo will add a .gitignore file for it. When you then create a bin project inside that, it will not add another .gitignore, and the first .gitignore causes the Cargo.lock file in the bin to be ignored.
As a solution for this, perhaps change the default lib .gitignore from:
```
target
Cargo.lock
```
To:
```
/target
/Cargo.lock
```
And do the same for the bin .gitignore, then just add a .gitignore as usual when a new project is created that's nested inside another project, instead of relying the parenting .gitignore to handle that.

**Comment by alexcrichton** [comment]
This has been [brought up](https://github.com/rust-lang/cargo/issues/1415) [in the past](https://github.com/rust-lang/cargo/pull/1488), but the current idea is that the generated gitignore is the "most common" one, but it's always quite easily configurable!

The current common use case is to possibly create component libraries in a repo hierarchy in which case you want to ignore all `target` directories and `Cargo.lock` files. This isn't always the case, however, but that's why `.gitignore` is configurable :)

As a result I'm going to close this, but thanks for the report!
