### ISSUE TITLE
curl hardcoded despite check in configure

### ISSUE THREAD

**Issue by BenBE** [rust-lang/cargo#1514]
When trying to bootstrap cargo from the git alone the make invokation fails if wget but not curl is installed.

Although the configure checks for cul or wget as dependencies and notes the result in config.mk there are at least two places where curl is hard-coded:
- /src/etc/dl-snapshot.sh
- /.travis.install.deps.sh

In both places the determined tool should be used; instead of hard-coding curl.

Also, depending on the system configuration it might be necessary to provide additional arguments to curl/wget to function properly. These are currently ignored too.

**Comment by carols10cents** [comment]
Update: curl is still hardcoded in [download.py](https://github.com/rust-lang/cargo/blob/7c3b8ef9ac8680bae585d02cbf162d992bdaab38/src/etc/download.py#L9-L16) (for non-windows). [configure still probes for wget](https://github.com/rust-lang/cargo/blob/ec85eefd3230a179e023b1f0b9377a43a0694023/configure#L344), but [the readme says curl is required](https://github.com/rust-lang/cargo/blob/master/README.md#compiling-from-source)

[curl was removed from the travis install deps as part of the rewrite to python to support appveyor](https://github.com/rust-lang/cargo/commit/cfb69ad256fc7e16d271d755339345fbfa892b9d).

So perhaps the fix is to change configure to only check for curl? If that's a hard requirement?

**Comment by alexcrichton** [comment]
I... think it would be fair to call this a mess :). Some facts that are at least true today though! (to the best of my knowledge)

* At no point does any script *try* to call wget, we just incorrectly probe for it.
* On Unix, we require `curl` to get a Cargo snapshot unless `--local-cargo` is passed

The `./.travis.install.deps.sh` or `src/etc/install-deps.py` script are largely just for CI nowadays. Any relatively recent version of Cargo or Rust should be able to compile Cargo!

**Comment by alexcrichton** [comment]
I believe we no longer require curl, so closing.
