### ISSUE TITLE
Adding a no-op custom build script causes the build to fail

### ISSUE THREAD

**Issue by Diggsey** [rust-lang/cargo#1582]
Seems to be related to #1299
edit: Also related to #1248

Adding a no-op build script to my cargo.toml causes the build to fail with the message "[17] No submodule named 'lib/libstd/src'"

The message is correct - there is no git submodule there, 'src' happens to be a symlink to a path within a submodule, but why is cargo even looking in the .git folder? I really don't expect a build system to be messing with my version control system. It should be possible to have a completely corrupted .git folder with no ill-effects on the build system (not that the .git folder is corrupted in this case).

Here's the relevent output with logging enabled:
> WARN:cargo::sources::path: list_files_git std v0.0.1 (*\<root\>*)
WARN:cargo::sources::path:   found *\<root\>*/lib/libstd/Cargo.toml
WARN:cargo::sources::path:   found submodule *\<root\>*/lib/libstd/src
DEBUG:cargo: handle_error; err=CliError { error: Error { klass: 17, message: "No submodule named \'lib/libstd/src\'" }, unknown: true, exit_code: 101 }
[17] No submodule named 'lib/libstd/src'

IMO, cargo is trying to be too clever for its own good, and it just results in too many bugs that couldn't have been predicted. Please consider providing a way to disable any interaction with git from the toml file.

**Comment by alexcrichton** [comment]
This may have been inadvertently fixed by https://github.com/rust-lang/cargo/commit/a8e9ce22c1de86a519294e5783cbdd015ddab484, could you try the most recent version of Cargo?

> IMO, cargo is trying to be too clever for its own good, and it just results in too many bugs that couldn't have been predicted. Please consider providing a way to disable any interaction with git from the toml file.

I'd encourage you to take a step back :). Cargo fundamentally tries to not run build commands or the compiler as much as possible, which means that it needs to know what it means when "something changes". When compiling a Rust artifact, the compiler will emit dependency information of all files that were considered as inputs to the compiler, so Cargo has explicit knowledge of what it means for something to have change (the modification time is different than before).

With a build script, however, Cargo does not have such fine-grained knowledge. Cargo must assume that the entire source tree could be an input to the build script, so it must re-run the build script whenever a file changes. Now what if you've got generated files inside of a source directory, but you've ignored them all via `.gitignore`? It would be quite annoying to have to duplicate that `.gitignore` knowledge into `Cargo.toml` via `exclude`, and it's generally viewed as much more convenient that Cargo understands git by default.

In general I wouldn't necessarily go down the road of recommending "cargo be as un-clever as possible" as it makes common tasks all that more burdensome. This issue is definitely a bug, of course, but it doesn't meant that Cargo should throw up its hands and give up on git entirely!

**Comment by Diggsey** [comment]
Sorry if I was overly critical of cargo - I'd been banging my head against the wall trying to get this to work for quite some time.

However, I still believe a simpler, more modular cargo is the way to go. I'm not saying you have to get rid of the git magic entirely, just don't make it integral to the process. git is by no means the only way of solving the problem you're describing (Even if we limit it to getting the information from version control systems, I could be using svn or mercurial!)

At the moment, cargo feels like this magic box, and if it works it's great. If it doesn't... you're gonna have bad time. Don't make cargo un-clever, just separate out the clever bits so that the core of cargo isn't totally crippled by problems with them.

**Comment by alexcrichton** [comment]
Do you have a suggestion about how this could be extracted? For example Cargo is already quite "modular" and a git repository is recognized in precisely one location, and that's it. There is amble room to add in other VCS tools, they just have not been implemented yet.

Regardless, though, does this still reproduce for you? I believe this has been fixed but I haven't gotten around to verifying it yet.

**Comment by Diggsey** [comment]
I've just tested with `cargo 0.2.0-nightly (a078e01 2015-05-11) (built 2015-05-13)` and it does appear to be fixed.
