### ISSUE TITLE
Build script not executed when library search path is overriden

### ISSUE THREAD

**Issue by plietar** [rust-lang/cargo#1587]
Hi,
If the `Cargo.toml` file links the project to an external library, and the path to that library is overridden in `.cargo/config`, then the build script does not seem to run.

Simple example to reproduce, in order `Cargo.toml` `build.rs` and `.cargo/config`. The build succeeds, whereas the build script should panic. After removing the config file, it behaves as expected.
```
[package]
version = "0.1.0"
name = "test"
build = "build.rs"
links = "foo"
```
```
fn main() {
    panic!("Build script executed");
}
```
```
[target.x86_64-apple-darwin.foo]
rustc-link-search = ["/path/to/foo/lib"]
```
```
$ rustc --version
rustc 1.1.0-nightly (7bd71637c 2015-05-06) (built 2015-05-05)
$ cargo version
cargo 0.2.0-nightly (7f810ba 2015-05-03) (built 2015-05-03)
```

**Comment by alexcrichton** [comment]
This is actually quite intentional! When overriding a build script you're taking over providing all the outputs the build script normally provides, so the build script is intentionally not run (by design).

For more information you can see [the documentation](http://doc.crates.io/build-script.html#overriding-build-scripts) on this topic as well.

**Comment by plietar** [comment]
I missed that section.
However in my case the build script is orthogonal to the configuration file.
I use it to generate rust source code from protobuf files, whereas the configuration files is used to specify where to find a library since it is in a non-standard place.
I believe the configuration file should only override the output, but not prevent the script from running.

**Comment by alexcrichton** [comment]
That's one of the reasons for the `foo-sys` package convention. Overridable build scripts should perform the sole operation of building the native library they're listed as `links` for, and otherwise functionality should be located in a parent or external crate with a build script that cannot be overridden.
