### ISSUE TITLE
Cargo attempts to download dependencies that are overriden by 'paths' variable in '.cargo/config' file. 

### ISSUE THREAD

**Issue by BenoitJGirard** [rust-lang/cargo#1614]
I had difficulties using Cargo on a computer that can only access the Internet through a HTTP proxy. 

As a solution, I cloned all dependencies into local directories and configured 'paths' in a '.cargo/config' file to use those local repositories before trying to download code from the Internet. 

But it seems there is code that will try to download dependencies before 'paths' is taken into account and so 'cargo build' still fails with this setup.

**Comment by aloucks** [comment]
The current behavior is also frustrating when you're building a dependency that is not currently published to crates.io or a remote git repository. It forces you to use ```path = "../mydep"``` in Cargo.toml instead of simply ```version = "*"``` and using a ```.cargo/config``` to override it with ```paths```.

**Comment by alexcrichton** [comment]
This is currently intended behavior because Cargo generates a lock file before it factors in overrides. This means that it needs to the metadata for these crates to generate the lockfile. If you truly don't want the network then that's what `path` dependencies are for as the lockfile can reflect that there's no network traffic needed.

**Comment by BenoitJGirard** [comment]
For the record:

Given how much this cripples the override functionality and handicaps those who occasionally have to work offline (Git is supposed to shine in these scenarios), I maintain this is a bug.

**Comment by alexcrichton** [comment]
This is unfortunately just not what overrides were designed for, they're meant to temporarily take over another crate during a normal resolution process, not be a first-class method to provide alternate sources for a package (that's what the manifest is for).

Can you also elaborate a bit on how this hurts working offline? Cargo should never talk to the network unless it needs to.

**Comment by BenoitJGirard** [comment]
Very well:
1. Using Git, clone locally various interdependent Cargo projects - these Cargo projects have 'git' dependencies between them. 
2. Set 'paths' in .cargo/config so the various 'git' dependencies are resolved to these local clones, not network git repositories. 
3. If those foreign git repositories are reachable through the network, this works.
4. If the network is -not- available, this does -not- work.

So even though one has all the code cloned locally, one cannot work offline.

This make it difficult to work on a multi-repository project, ergo on multi-crate projects, as Cargo supports best one crate per repository. 

Perhaps there exists a more canonical way to work offline on a multi-crate, multi-repository project?

As to replacing 'git' dependencies with 'path' dependencies in this scenario: if I have M repositories with an average of N 'git' dependencies, that's M x N tedious local modifications in M files. I also could accidentally submit these.

**Comment by alexcrichton** [comment]
> So even though one has all the code cloned locally, one cannot work offline.

Right, this is because Cargo needs to generate a `Cargo.lock` and for that it needs dependency information, and for that it needs a clone of the repo. Did you run `cargo fetch` ahead of time and find that you *still* can't work offline?

> as Cargo supports best one crate per repository. 

You should actually be able to have many crates in one repository (by just nesting them). Cargo auto-discovers all child crates.

> Perhaps there exists a more canonical way to work offline on a multi-crate, multi-repository project?

It depends what you mean by "offline". If you're ok running `cargo fetch` ahead of time then that should be sufficient, Cargo shouldn't need any network traffic after that. If so, it's a bug.

Otherwise many repos which contain many crates have all the crates in the tree pointing at each other with `path` dependencies, so if it's just a bunch of crates in one repo that suffices.

**Comment by BenoitJGirard** [comment]
No I did not run 'cargo fetch'. I expected Cargo to consult the 'paths' config variable and find the locally cloned code itself. Even after this explanation, I contend that this local lookup should be the correct behavior.

**Comment by vi** [comment]
Reproducible for me as well. `cargo fetch` does not help. Tried with:

* `cargo 0.7.0-nightly (f191c24 2015-11-12)`
* Manually-build from Git `0.6.0-116-gca9bfe2`
