### ISSUE TITLE
Build scripts don't work with multiarch-ized Rust from Debian

### ISSUE THREAD

**Issue by Protagores** [rust-lang/cargo#1665]
I have installed [rustc package](https://packages.debian.org/sid/rustc) from repositories on my Debian system, and cargo nightly from crates.io via `install.sh`. In that package the libraries are located in the path `/usr/lib/<target-triplet>/rust/<version>/lib`, instead of `/usr/local/lib`, where the official binary distributions tend to install them.

However, it seems that, when build scripts are compiled, dynamic libraries are being used, but the necessary rpath entry in the generated binary is missing. When run, this binary, having not found those dynamic libraries in standard locations (`/lib`, `/usr/lib`, `/usr/local/lib`), aborts with error like this:

> /home/user/Projects/bstest/target/debug/build/bstest-01e873619ad587ae/build-script-build: error while loading shared libraries: libstd-4e7c5e5c.so: cannot open shared object file: No such file or directory

**Comment by alexcrichton** [comment]
Hm, I'm a little surprised that this works at all! I would expect the libraries to enter the default `LD_LIBRARY_PATH` because they're required by the compiler at least. Is `/usr/bin/rustc` a script which sets up the right variables? I'm not 100% sure what the packaging story is, but I'm a bit surprised to see the libs buried so deep.

Note that to work you just need `/usr/lib/...-linux-gnu/rust/1.0/lib` in your `LD_LIBRARY_PATH`

**Comment by alexcrichton** [comment]
Build scripts are no longer linked dynamically, so I believe this has been fixed.
