### ISSUE TITLE
Cargo debug command

### ISSUE THREAD

**Issue by vojtechkral** [rust-lang/cargo#1726]
It would be really nice if there were a command such as `cargo gdb` or `cargo debug` or similar that would do what `cargo run` does except run the program in a debugger. Having to do it manually is a bit cumbersome...

**Comment by alexcrichton** [comment]
Unfortunately this would require there to be a cross-platform canonical solution to debugging Rust code, which currently doesn't exist. It could do "best-effort" things like running lldb on OSX and gdb on linux, but I'm not sure what the story on Windows would be. This sounds a lot like a custom subcommand rather than an official one currently.

**Comment by vojtechkral** [comment]
On Windows, I believe `windbg` could be used in much the same manner as `gdb`, although I don't have a hands-on experience. The "best-effort" approach using `gdb` on Linux et al., `lldb` on OS X and `windbg` on Windows sounds good enough to me, but of course the call is yours...

**Comment by vojtechkral** [comment]
Today I needed to trace a rust program with `strace`. People might also to run their programs wrapped in other tools, `valgrind` comes to mind, but there are surely others.

So maybe instead of adding a new subcommand, it would be better to add some kind of a "run-with-command" flag to `cargo run` ... ?

**Comment by vojtechkral** [comment]
Or maybe third-party `cargo-run-with` program would do...
