### ISSUE TITLE
Linking issues using Cargo-built libraries from non-cargo projects.

### ISSUE THREAD

**Issue by Kingsquee** [rust-lang/cargo#1777]
This repository tells all: https://github.com/Kingsquee/unfound

**Comment by Kingsquee** [comment]
My suspicion is it relates to cargo's opinionated compilation of dependencies (afaik, cargo doesn't just let me set a dependency's crate type), but the error cases are still very strange.

**Comment by Kingsquee** [comment]
https://github.com/rust-lang/rust/issues/18807 seems similar, especially with [this 'solution'](https://github.com/rust-lang/rust/issues/18807#issuecomment-102177511)

**Comment by alexcrichton** [comment]
It looks like you're running into https://github.com/rust-lang/rust/issues/14344 because the rlib `foo` is being linked into the dylib `state`, but that bug means it's not actually being included. Later on when `process` depends on `foo` as well (but thinks it gets it through `state`), the assumption is incorrect and a link error happens.

I'm going to close this in favor of that issue, though.

**Comment by Kingsquee** [comment]
@alexcrichton shouldn't that mean changing nocargo/libfoo/build.sh to use --crate-type=lib cause the same issue? So far I can't reproduce the error outside of the cargo version.
