### ISSUE TITLE
Cargo.toml should include supported platforms info

### ISSUE THREAD

**Issue by achanda** [rust-lang/cargo#1911]
Some crates are platform dependent. It will be nice if this dependency can be advertised in the Cargo.toml file. When building a crate on a system, the cargo binary can then use this info to determine if any of the dependencies do not support this platform. This will help in erring out early while building a crate.

**Comment by achanda** [comment]
@alexcrichton how do I get feedback on this? Should this be a RFC?

**Comment by alexcrichton** [comment]
Yeah I'd recommend starting out with a discussion on internals or users to see if others have feedback, and then eventually there'd need to be an RFC for this.

I would personally not want to dive too much into this space, we've already got a number of pain points of platform-specific logic in Cargo.toml. In general we've gotten a whole lot more mileage for pushing this kind of logic into the source code rather than Cargo itself. I also generally feel that lots of infrastructure for just a better error message may not always be worth it, but there may be some other benefits we could get here as well maybe?

**Comment by achanda** [comment]
@alexcrichton I understand.
I was looking at https://internals.rust-lang.org/t/production-user-research-summary/2530 and it seems one of the customer asks is this. I will follow up on this.

**Comment by dwijnand** [comment]
What's the state of platform-specific dependencies in 2018 cargo?

**Comment by alexcrichton** [comment]
Platform-specific dependencies are supported through either:

```toml
[target.wasm32-unknown-unknown.dependencies] # full target name 
# ...

[target.'cfg(windows)'.dependencies] # `cfg` expressions
# ...
```

I think this issue though is moreso about explicitly specifying platform-support in Cargo.toml to have Cargo print a better error message about "This crate doesn't compile or work on Windows", for example, than being about platform-specific dependencies.

**Comment by weihanglo** [comment]
Going to close this in favor of <https://github.com/rust-lang/cargo/issues/11313>. #11313 contains a more complete proposal and recent discussions.
