### ISSUE TITLE
Stable cargo fails to pass complete flags to rustc build.rs

### ISSUE THREAD

**Issue by kali** [rust-lang/cargo#2021]
Test case: https://github.com/kali/cargo-tc-with-features

multirust being up to date, beta channel works, stable channel fails. Observed on macosx and linux. The issue seems related to features flags.

```
04/10 19:49 ~/dev/tmp/tc% multirust override stable && cargo version && cargo build --features with-syntex                        :master
multirust: using existing install for 'stable'
multirust: override toolchain for '/Users/kali/dev/tmp/tc' set to 'stable'
cargo 0.4.0-nightly (553b363 2015-08-03) (built 2015-08-02)
   Compiling rustlex_codegen v0.3.1 (file:///Users/kali/dev/tmp/tc)
build.rs:1:1: 1:28 error: can't find crate for `quasi_codegen`
build.rs:1 extern crate quasi_codegen;
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~
error: aborting due to previous error
Could not compile `rustlex_codegen`.

To learn more, run the command again with --verbose.
[1]    45906 exit 101   cargo build --features with-syntex
04/10 19:50 ~/dev/tmp/tc% multirust override beta && cargo version && cargo build --features with-syntex                          :master
multirust: using existing install for 'beta'
multirust: override toolchain for '/Users/kali/dev/tmp/tc' set to 'beta'
cargo 0.5.0-nightly (833b947 2015-09-13)
   Compiling winapi v0.2.4
   Compiling bitflags v0.3.2
   Compiling libc v0.1.10
   Compiling unicode-xid v0.0.3
   Compiling rustc-serialize v0.3.16
   Compiling winapi-build v0.1.1
   Compiling log v0.3.2
   Compiling kernel32-sys v0.1.4
   Compiling term v0.2.11
   Compiling syntex_syntax v0.16.0
   Compiling syntex v0.11.0
   Compiling quasi v0.3.2
   Compiling aster v0.4.9
   Compiling quasi_codegen v0.3.3
   Compiling rustlex_codegen v0.3.1 (file:///Users/kali/dev/tmp/tc)
```

Comparing the two verbose outputs, the failing build "rustc build.rs" line lacks some of the expected options:

Beta does:
```
   Compiling rustlex_codegen v0.3.1 (file:///Users/kali/dev/tmp/tc)
     Running `rustc build.rs --crate-name build_script_build --crate-type bin -g --cfg feature=\"quasi\" --cfg feature=\"with-syntex\" --cfg feature=\"syntex_syntax\" --cfg feature=\"quasi_codegen\" --cfg feature=\"syntex\" --out-dir /Users/kali/dev/tmp/tc/target/debug/build/rustlex_codegen-27c294f0f5eac399 --emit=dep-info,link -L dependency=/Users/kali/dev/tmp/tc/target/debug -L dependency=/Users/kali/dev/tmp/tc/target/debug/deps --extern quasi_codegen=/Users/kali/dev/tmp/tc/target/debug/deps/libquasi_codegen-6643d65ca3f10c4a.rlib --extern syntex=/Users/kali/dev/tmp/tc/target/debug/deps/libsyntex-9e85868f622485c2.rlib`
```

Stable crashes on:
```
     Running `rustc build.rs --crate-name build_script_build --crate-type bin -C prefer-dynamic -g --cfg feature=\"syntex\" --cfg feature=\"with-syntex\" --cfg feature=\"syntex_syntax\" --out-dir /Users/kali/dev/tmp/tc/target/debug/build/rustlex_codegen-27c294f0f5eac399 --emit=dep-info,link -L dependency=/Users/kali/dev/tmp/tc/target/debug -L dependency=/Users/kali/dev/tmp/tc/target/debug/deps --extern syntex=/Users/kali/dev/tmp/tc/target/debug/deps/libsyntex-9e85868f622485c2.rlib`
build.rs:1:1: 1:28 error: can't find crate for `quasi_codegen`
build.rs:1 extern crate quasi_codegen;
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~
error: aborting due to previous error
Could not compile `rustlex_codegen`.
```

cc @Leotestard

**Comment by alexcrichton** [comment]
I think this was fixed by #1873 (as you've seen it's fixed on beta), so are you thinking the fix should be backported to stable? We haven't currently done any backports for Cargo (much less to stable), but it can in theory be done for a serious-enough issue (although this may not be serious enough).

**Comment by LeoTestard** [comment]
I'm not sure to understand... `cargo --version` reports `0.4.0-nightly` in our build log when building for stable. Is this really the stable channel of Cargo?

Well, I don't mind changing the `Cargo.toml` file if there is a simple enough workaround. I'm not very familiar with it. But if not, I'd still like to be able to somehow build my project using Cargo on the stable channel.

**Comment by alexcrichton** [comment]
Ah yeah currently Cargo only ever reports `-nightly` (it doesn't have quite the same release process as rustc). Additionally, the "stable channel" currently applies moreso to Rust rather than Cargo itself, all "releases" of Cargo are actually just snapshots at some point in its history.

Along those lines, I'd recommend for now using a nightly Cargo build (it should work fine with any `rustc` compiler). The bug was originally caused from a mistake in feature propagation, so I think not relying on features as much or possibly teaking how the defaults are done may also fix it on the stable channel (but updating Cargo is probably your best bet).

As this is fixed on beta/nightly, however, and this probably isn't worth a point release for, I'm going to close this. Let me know if I can help out though!

**Comment by dagit** [comment]
I'm having the same issue trying to use RustLex. Is there really no workaround that lets me stick with the stable version of cargo?

**Comment by alexcrichton** [comment]
Unfortunately the only real workaround I know of is to juggle around features so they're just not used as much (which seems bad), but "updating to a new cargo" should be just moving a new cargo binary into place, so it shouldn't be too hard to do!
