### ISSUE TITLE
Cargo can't unify nearly identical git version and crates.io version of crate

### ISSUE THREAD

**Issue by untitaker** [rust-lang/cargo#2066]
* Compile https://github.com/untitaker/mysteryshack, it compiles.
* Change to use git version of `iron` crate: `https://github.com/iron/iron/`.

`persistent` depends on `iron = 0.2`, which is satisfied by the git version of `iron`. However, cargo still uses both versions, causing type mismatches when trying to compile `mysteryshack`.

**Comment by alexcrichton** [comment]
This is currently an intentional design decision of Cargo, when crates come from different sources they're considered separate crates as we don't really have a correlation among them to realize that they're "actually the same".

If you're looking to temporarily override a dependency for local development you may be interested in [local overrides](http://doc.crates.io/guide.html#overriding-dependencies) which should solve this problem.
