### ISSUE TITLE
Deprecate the "bench" and "test" profiles

### ISSUE THREAD

**Issue by briansmith** [rust-lang/cargo#2085]
AFAICT, any time the "bench" or "test" profile is different from "release", it is a misconfiguration. Cargo should warn whenever a "bench" or "test" profile is defined, and it should always use the "dev" or "release" profile, based on whether or not "--release" was passed.

From #cargo IRC chat today:

<briansmith> I also noticed something strange about profiles: why would one want the "test" profile or "bench" profile to ever be different from "release"?
<briansmith> If they were different, then you wouldn't be testing or measuring what you release.
<acrichto> that's a good point, I've never seen a difference in practice at least
<briansmith> I had mine different for a while because I hadn't thought about it. I'd only changed "release"

**Comment by jonas-schievink** [comment]
Test should be different from release because I don't want to spend ten minutes waiting for optimizations every time I run tests.

**Comment by briansmith** [comment]
> Test should be different from release because I don't want to spend ten minutes waiting for optimizations every time I run tests.

`cargo test` should use the dev profile and `cargo test --release` should use the release profile. cargo bench should always build a release build.

**Comment by jonas-schievink** [comment]
Ah, yes. That makes sense.

**Comment by weihanglo** [comment]
[Cargo named profile (RFC 2678)](https://rust-lang.github.io/rfcs/2678-named-custom-cargo-profiles.html) has been landed since 1.57 (2021-12-02). That should (hopefully) make everyone happy as test/bench profiles now inherits settings from dev/release, but still open to customizations.

Going to close this now. If you found this is a fault, please comment, and we'll consider re-open.
