### ISSUE TITLE
Persistent warning messages when building

### ISSUE THREAD

**Issue by bruno-medeiros** [rust-lang/cargo#2089]
When invoking cargo build, any warning messages will not be output unless it's the first time the build is being performed, or there are changes in the underlying source file (or dependent files) affecting the warning.
The warning messages should always be the same for repeated invocations of cargo build. This is useful for IDEs invoking cargo build (and arguably is useful for direct command line users too)

**Comment by alexcrichton** [comment]
This may not necessarily be something that Cargo itself tackles, but rather something like the [IDE integration](https://github.com/rust-lang/rfcs/pull/1317) being proposed. These warning messages come from the compiler rather than Cargo itself, and Cargo wants to avoid running the compiler as much as possible. I guess in short, I can see the utility of this, but I can't quite see where it'd fit nicely into cargo?

**Comment by bruno-medeiros** [comment]
Yeah, it doesn't have to be done in Oracle, could be in a tool sitting atop it.

**Comment by carols10cents** [comment]
> I can't quite see where it'd fit nicely into cargo?

I'm closing this issue based on this comment.
