### ISSUE TITLE
Changing the codegen units in the [profile] section should not recompile everything

### ISSUE THREAD

**Issue by tomaka** [rust-lang/cargo#2099]
If you have an existing project, and you add:

```toml
[profile.debug]
codegen-units = 2
```

Then Cargo recompiles everything (all dependencies and the project itself).

I'm not actually sure that it's a bug. As far as I know changing the codegen units can produce a different result. However I don't think it's worth recompiling everything just for this.

**Comment by alexcrichton** [comment]
Yeah currently this is intended behavior, whenever an aspect of a profile is changed it triggers everything compiled with that profile to be recompiled. I think that although in principle this doesn't matter there's always the possibility of a buggy implementation or some other oddness to arise, so for now "quick testing" can be done via `cargo rustc` and otherwise it's working as intended.
