### ISSUE TITLE
'Did you mean' could be more helpful

### ISSUE THREAD

**Issue by Wilfred** [rust-lang/cargo#2123]
```
$ cargo --test                                                                                 [0:29:48]
Unknown flag: '--test'. Did you mean '--list'?

Usage:
    cargo <command> [<args>...]
    cargo [options]
```

It would be helpful in this case if cargo could suggest `cargo test`, or at least `cargo help`.

**Comment by MatejLach** [comment]
So I am not at all familiar with the `cargo` codebase and am fairly new to Rust itself, so take this with a grain of salt :-)

Perhaps `find_closest()` could be modified to strip the entered `cmd` of any prefix and postfix symbols that are not letters (like `--` and such) then search `list_commands()` as to whether `cmd` is now valid and if yes, suggest that, otherwise use `lev_distance()` as we do now.
This would not catch all typos, but it should certainly improve the current situation. 

I am also looking into how `git` does this as it has the best "typo suggestions" I've seen so far, perhaps we could use something from there?

**Comment by alexcrichton** [comment]
I believe this error message currently comes from docopt, but other than that it should be possible to handle in Cargo itself.

**Comment by MatejLach** [comment]
I haven't had the time to have look at this, but will soon, if somebody isn't faster.
It seems to me like this needs to be handled somewhere around [here](https://github.com/rust-lang/cargo/blob/master/src/bin/cargo.rs#L143), otherwise `docopt` hijacks the arguments and handles things like `--` on its own, which is not desirable if we want to offer fixes/suggestions for common typos.

**Comment by MatejLach** [comment]
Ok, I've looked into `docopt`.
This is definitely doable from within `cargo` itself, so I should have a pull request ready by tomorrow.

**Comment by saysjonathan** [comment]
In addition to the flags, there's some "Did you mean..." output that's truly bad. Looks like the default subcommand recommendation is `doc`

```
$ cargo 8
error: no such subcommand: `8`

        Did you mean `doc`?

$ cargo q
error: no such subcommand: `q`

        Did you mean `doc`?

$ cargo -
error: no such subcommand: `-`

        Did you mean `doc`?
```

Sometimes it gives an alternative:

```

$ cargo noway
error: no such subcommand: `noway`

        Did you mean `new`?
```

But sometimes it doesn't even make a recommendation:

```
$ cargo nowayy
error: no such subcommand: `nowayy`
```

**Comment by eminence** [comment]
Triage:  cargo has a different CLI parser these days, and it now prints out `For more information try '--help'`.  I think this addresses the original request and so this issue can be closed

**Comment by epage** [comment]
There are a couple of things at play here.

clap did replace docopt and clap is smarter about "did you mean" to only show close results.

clap does not process cargo's subcommands but that is done by cargo itself for alias support.  cargo does only report close matches and also shows how to see all commands
```console
$ cargo lkjkljl
error: no such subcommand: `lkjkljl`

        View all installed commands with `cargo --list`

cargo on  cargo-remove-gc is 📦 v0.68.0
$ cargo testy
error: no such subcommand: `testy`

        Did you mean `test`?

        View all installed commands with `cargo --list`
```

This only leaves the comment about detecting `--test` should be `test`.  This crosses between what clap does and what cargo does.  It also seems like a less likely scenario.

I lean towards closing this as most of the parts mentioned are resolved and we are unlikely to do anything about the last one.

If people have other thoughts, let us know and we can re-open.
