### ISSUE TITLE
`cargo install --path .` recompiles

### ISSUE THREAD

**Issue by Stebalien** [rust-lang/cargo#2143]
`cargo install --path .` recompiles the current crate in `target-install` before installing. This makes cargo install useless for package managers that want to separate build from package logic, wastes time, and wastes space (even small rust projects put a lot of data into the target directory). Cargo should just re-use the current target directory.

**Comment by alexcrichton** [comment]
Sounds like a good idea to me, also an easy bug to tackle!

**Comment by JIghtuse** [comment]
@alexcrichton I've made a simple fix for this issue: https://github.com/JIghtuse/cargo/commit/9e00156fb97c260473fd029cf041618846787175

But I have no idea how to implement a test for it.

## Statically
Final result of current behavior and a new one is the same: if we rebuilt package, we removed `target-install` in the end; if not, we didn't even created `target-install`. Final directory structure and installed binaries will be the same.

## Dynamically
It seems impossible to detect compiler invocation in `compile_pkg` call to make sure we didn't rebuilt package. Also, we should call compiler on first build.

**Comment by alexcrichton** [comment]
Thanks @JIghtuse! I think that instead of using `cwd.join("target")` this may want to use the target directory in that package as well. For that you can use the [`target_dir`](https://github.com/rust-lang/cargo/blob/34269d0af6573a4a24b4ce3beaabf1f782a1e0d2/src/cargo/util/config.rs#L110) function. Also yeah I'd definitely avoid removing `target` after we're done for path dependencies.

Also, for a test, you can probably do something like:

* Create a cargo project
* Run `build --release`
* Run `install --path .`

The last step should have no output generated saying that something is being built because the pre-existing artifacts should be used.

**Comment by JIghtuse** [comment]
@alexcrichton oh yeah, nice idea of test. How could I not think about that?

**Comment by Sebi2020** [comment]
> `cargo install --path .` recompiles the current crate in `target-install` before installing. This makes cargo install useless for package managers that want to separate build from package logic, wastes time, and wastes space (even small rust projects put a lot of data into the target directory). Cargo should just re-use the current target directory.

This still happens with current rust release. `cargo build --release` followed by `cargo install --path .` causes cargo to re-download and rebuild everything instead of using the existing release artifacts.

**Comment by 0xPoe** [comment]
> This still happens with current rust release. `cargo build --release` followed by `cargo install --path .` causes cargo to re-download and rebuild everything instead of using the existing release artifacts.

You could try `cargo install --path . --locked`; this would try to reuse the artifacts from the previous build. The reason `cargo install --path .` doesn’t work is that it resolves the dependencies without the lockfile, which would end up rebuilding everything. This behavior changed in https://github.com/rust-lang/cargo/pull/6840. (Ignore Cargo.lock in cargo install by default)

**Comment by Sebi2020** [comment]
> > This still happens with current rust release. `cargo build --release` followed by `cargo install --path .` causes cargo to re-download and rebuild everything instead of using the existing release artifacts.
> 
> You could try `cargo install --path . --locked`; this would try to reuse the artifacts from the previous build. The reason `cargo install --path .` doesn’t work is that it resolves the dependencies without the lockfile, which would end up rebuilding everything. This behavior changed in [#6840](https://github.com/rust-lang/cargo/pull/6840). (Ignore Cargo.lock in cargo install by default)

Thanks for the hint, I'll give it a try.

Considering recent supply chain attacks with other package managers this is a very questionable and surprising default security wise in my point of view. Especially since the lock-file concept exists for a reason. (I mean there could be still an `--ignore-lockfile` flag if someone really needs the latest version of all dependencies).
