### ISSUE TITLE
Non-`--verbose` error message for an invalid version constraint should mention this

### ISSUE THREAD

**Issue by huonw** [rust-lang/cargo#2146]
``` rust
[package]
authors = []
name = "test"
version = "0.1.0"

[dependencies]
crossbeam = "x"
```

```
$ cargo build 
failed to parse manifest at `.../Cargo.toml`

To learn more, run the command again with --verbose.
$ failed to parse manifest at `/home/huon/projects/test-rust/test-af/Cargo.toml`

Caused by:
  version components must be numeric
```

It would be helpful if it also informed the user of the line number and/or the name of the crate.

**Comment by carols10cents** [comment]
LOL so I tried reproducing this and a Cargo.toml with `crossbeam = "x"` totally compiles and uses the current latest version of crossbeam 😆 So I thought we had a new problem!

Turns out though, that `x` is a valid version requirement now! [From npm's semver docs](https://docs.npmjs.com/misc/semver#x-ranges-12x-1x-12-):

> Any of X, x, or * may be used to "stand in" for one of the numeric values in the [major, minor, patch] tuple.

If I do `crossbeam = "y"` instead, I **am** able to reproduce this issue:

```
$ cargo build
error: failed to parse manifest at `/private/tmp/demo/poop/Cargo.toml`

To learn more, run the command again with --verbose.
08:36:52 {master} /tmp/demo/poop $ cargo build --verbose
error: failed to parse manifest at `/private/tmp/demo/poop/Cargo.toml`

Caused by:
  the given version requirement is invalid
```
