### ISSUE TITLE
Downgrading from latest master to 0.6.0, unable to compile

### ISSUE THREAD

**Issue by Chuongv** [rust-lang/cargo#2178]
I originally compiled cargo from source successfully, a few days back off of master. Now I am trying to downgrade to 0.6.0 to since I was having issues with one project, thought that maybe going down would help.

I also originally had rust on latest master, then I went back to the stable branch. Not sure if that matters.

```
$ rustc -Vv
rustc 1.4.0-dev (8ab8581f6 2015-10-27)
binary: rustc
commit-hash: 8ab8581f6921bc7a8e3fa4defffd2814372dcb15
commit-date: 2015-10-27
host: x86_64-apple-darwin
release: 1.4.0-dev
```

```
$ cc --version
Apple LLVM version 7.0.0 (clang-700.1.76)
Target: x86_64-apple-darwin15.0.0
Thread model: posix
```
Output of make after following the steps from http://github.com/rust-lang/cargo
https://gist.github.com/Chuongv/3dc346ba9fcf7788ac7f

What's weird is that I also wasn't able to do `make test` on latest master either for cargo.

**Comment by Chuongv** [comment]
Seems to be similar to https://github.com/alexcrichton/ssh2-rs/issues/23

```
brew install libssh2
brew install openssl
brew link --force openssl
```
But still get the same error.

**Comment by alexcrichton** [comment]
This basically indicates that the project was compiled against one OpenSSL version and then linked against another. That happens here because compilation uses the homebrew-based OpenSSL but then linking (which picks up `/usr/lib` via a zlib dependency) ends up using the system OpenSSL, a much older version.

You may have to start out from a new clean build directory if you're using a system libssh2 instead of building one from scratch as well, but that in theory should do the trick!

**Comment by Chuongv** [comment]
Thanks!

For anyone curious on how to solve this:

```
make clean
brew link --force openssl
```
Which should let you build again.
