### ISSUE TITLE
Can you preserve comments in ~/.cargo/config?

### ISSUE THREAD

**Issue by lilydjwg** [rust-lang/cargo#2183]
Today I did a `cargo login`, my `~/.cargo/config` was updated, but none of the comments were left.

The config file currently is small, little to comment, but I've lost my vim modeline. If I had some config entries commented out, or some links / explanations, they would be lost too. So, can you preserve them?

**Comment by alexcrichton** [comment]
Yeah this is an unfortunate part of `toml-rs` right now in that it's parsed TOML representation doesn't preserve comments and such. I'd definitely like to support this, and I know other subcommands would as well!

**Comment by carols10cents** [comment]
Triage: This is still a problem.

**Comment by eminence** [comment]
Triage:  These days cargo stores credentials in `~/.cargo/credentials` instead of `~/.cargo/config`, and probably no one is putting valuable comments in the credentials file (but if you do, they won't be preserved either).

Also, cargo these days is no longer using `toml-rs`, and instead is using `toml-edit`, which does have support for preserving comments.

Given that the original complaint is now moot, I think this issue can be closed.

**Comment by epage** [comment]
> Also, cargo these days is no longer using toml-rs, and instead is using toml-edit, which does have support for preserving comments.

Only if using the lower level API, which most of cargo is not using.

But, as you said, credentials aren't being stored in the config, so I think this can be closed.   If we missed something in this, let us know and we can re-open.
