### ISSUE TITLE
`cargo bench` builds build dependencies in release mode

### ISSUE THREAD

**Issue by bluss** [rust-lang/cargo#2234]
Build deps are unrelated to the performance or benchmarking, so they don't need to be rebuilt, and don't need to be in release mode.

**Comment by bluss** [comment]
Example: crate depends on rustc_version which in turn depends on semver. Semver is built in release mode for benchmarks.

**Comment by sfackler** [comment]
I believe this is a more general issue of the release profile building build-dependencies in release mode, of which bench is one case. It's particularly annoying with things like syntex_syntax that *already* take a long time.

**Comment by alexcrichton** [comment]
I don't think there's a clear answer here of what Cargo *should* be doing. Most build dependencies probably don't need to be optimized, but that doesn't mean that *none* need to be optimized. It's unlikely that the optimization of the final artifacts should be related to the optimization of the build scripts

**Comment by dtolnay** [comment]
> It's unlikely that the optimization of the final artifacts should be related to the optimization of the build scripts

In fact I would consider it a bug if the optimization of the final artifacts were related to the optimization of the build scripts. I agree with @bluss and @sfackler that build-dependencies never need to be optimized.

**Comment by alexcrichton** [comment]
Unfortunately others actually feel the opposite, where build dependencies like lalrpop should *always* be optimized as otherwise their execution is super slow.

This is basically what I was just [thinking before](https://github.com/rust-lang/cargo/issues/2234#issuecomment-166145947), however, where I don't think there's a clear answer for what Cargo should do. There should likely be some form of configuration option at least for this, however (in one form or another)

**Comment by nathanaeljones** [comment]
I would love to drop 160 seconds from my release build time by letting Clippy build without optimizations. Clippy is fast enough, it's just slow to compile.

**Comment by pornel** [comment]
I've ran into this too. I use bindgen at build time, and it takes ages to compile it release mode. 

An option to have separate profiles for build dependencies (similar to #1359) would be fantastic.

**Comment by weihanglo** [comment]
With [profile overrides] feature, which is stabilized in 1.41, [build dependencies shouldn't be optimized][bdep-opt] by default. However, it wasn't true until a bug got fixed in 1.47 with #8560.

If you want to optimize build dependencies for `cargo bench`, since `cargo bench` inherits the `release` profile, you will need to override like this:

```toml
[profile.release.build-override]
opt-level = 3
```

Close as resolved in 1.47.


[profile overrides]: https://doc.rust-lang.org/cargo/reference/profiles.html#overrides
[bdep-opt]: https://doc.rust-lang.org/cargo/reference/profiles.html#build-dependencies
