### ISSUE TITLE
Add a flag to build profiles to enable overflow checking

### ISSUE THREAD

**Issue by larsbergstrom** [rust-lang/cargo#2262]
Would it be possible to add a flag to the build profiles:
http://doc.crates.io/manifest.html#the-profile-sections

That allows us to turn overflow checking on? (that is, enable `-Z force-overflow-checks=on`)

While we probably wouldn't ship Servo this way, being able to turn it on in our CI systems would catch a bunch of bugs without requiring us to spin up a parallel set of debug-only builders.

**Comment by alexcrichton** [comment]
There's definitely an interesting question of this I think of where the configuration should go. For something like this it may make sense actually in a few locations. Profiles aren't always the best place because there's only one global compilation profile (chosen by the root crate), which overrides local configuration. So for a use case of "I want overflow checks always enabled in this crate" it's not quite appropriate, but for a CI system it may be appropriate.

That being said Cargo profiles aren't great for CI systems right now as it involves editing Cargo.toml where it's easier to just pass a CLI flag, so there's also that to consider.

Overall, though, I'm very wary about stabilizing any usage of `-Z` options in Cargo as they should likely become full-fledged `-C` options first.

**Comment by llogiq** [comment]
Perhaps something like [overflower](https://github.com/llogiq/overflower) could help?

**Comment by froydnj** [comment]
Now that rust-lang/rust#33134 is stabilizing `-C overflow-checks`, we can add this, correct?  I know in rust-lang/rfcs#1535, @nrc expressed a preference that forthcoming Cargo support for arbitrary flags would be used instead of adding another boolean to profiles...how close is that arbitrary flags support @alexcrichton ?

**Comment by alexcrichton** [comment]
@froydnj let's stick to booleans for now, unforunately arbitrary flags may take awhile :(
