### ISSUE TITLE
The cargo:rustc-flags position matters

### ISSUE THREAD

**Issue by uuhan** [rust-lang/cargo#2292]
Recently , I updated my multirust data. I found something broken.
When I compile the package iron-kaleidoscope[https://github.com/jauhien/iron-kaleidoscope]. "cc" complains that some function from libffi.so not found. But this problem I should had fingured out by add a build.rs to Cargo.toml, with the content:
pub fn main() {
 println!("cargo:rustc-flags=-l ffi");
} 
It works well until do the "multirust update".
After some tracing, I realized that new rustc/cargo add the "-l ffi" flags immediately after rustc's rlibs and before the LLVM libraries, like this:

... "/home/uuhan/.multirust/toolchains/nightly/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-17a8ccbd.rlib" "-l" "ffi" "-l" "LLVMLTO" "-l" "LLVMObjCARCOpts" ... 

but, the real work one should be like this one:
"/home/uuhan/.multirust/toolchains/nightly/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-17a8ccbd.rlib""-l" "LLVMLTO" "-l" "LLVMObjCARCOpts" ...(all the other llvm libraries) ... -l ffi

So, is there a way to specify the "position" of rustc flags from build.rs? Or I missed something.

**Comment by alexcrichton** [comment]
The compiler will order `-l` flags given to the linker based on a topological ordering, so it may be the case that the right dependencies are not in play so the compiler can't order the command line. The actual ordering used can be somewhat nondeterministic due to the use of `HashMap` in the compiler sometimes.
