### ISSUE TITLE
Shared target-dir stale builds

### ISSUE THREAD

**Issue by jwilm** [rust-lang/cargo#2383]
This is best explained with an example.

Say there is a project with crates A and B, and a .cargo/config which specifies `build.target-dir`. B depends on A via `path = "../A"`. B implements `A::Trait` for some type in B. Now, change the definition of `A::Trait`. Crate B still sees old definition of `A::Trait` _IFF_ crate A is rebuilt before B.

Even more concretely, [here is a git repo](https://github.com/jwilm/cargo-path-dep-shared-target-dir-issue) where the problem is easily reproducible.

**Comment by alexcrichton** [comment]
Ok, I think what's happening here is that Cargo's is correctly deducing that crate A was rebuilt the second time, but the problem is that crate A is now located in two places. Both places have their fingerprint information stored in the same place, so that ends up causing a conflict.

I think this would be solved by just storing the fingerprint information in a different location based on whether it's a top-level or transitive dependency, that way everything should always get recompiled as usual.

Thanks for the report though @jwilm!

**Comment by jwilm** [comment]
Can you elaborate on what qualifies as a top-level or transitive dependency? I don't understand.

**Comment by alexcrichton** [comment]
Ah yeah, sorry, in this case the top-level package is the one you're actually running `cargo build` on. The output of that package is stored directly into `target/debug`, whereas all other crates have their output in `target/debug/deps`

**Comment by jwilm** [comment]
Ah, now I understand! Thanks for explaining. :smile:

**Comment by 0ndorio** [comment]
I just tried to find a way that reproduces the wrong behavior in the linked example repository but it seems  like this is already fixed.

**Comment by alexcrichton** [comment]
Nice!
