### ISSUE TITLE
`cargo run` no longer passes a stdin handle to child.

### ISSUE THREAD

**Issue by brson** [rust-lang/cargo#2530]
Until today I could run `cargo run --release` against rustup to kick off the interactive installer, which reads a byte from stdin for confirmation. As of today when I do this rustup exits with an error. Calling `std::stdin().lock().lines().next()` returns `None` where it used to return `Some`.

Working rustc / cargo:

```
rustc 1.9.0-nightly (98f0a9128 2016-03-23)
cargo 0.10.0-nightly (61ad6a0 2016-03-22)
```

Failing rustc / cargo:

```
rustc 1.9.0-nightly (d7a71687e 2016-03-24)
cargo 0.10.0-nightly (4e6434d 2016-03-24)
```

**Comment by steveklabnik** [comment]
I believe I saw another thing about this today; but I can't find it. Something about Rust 1.6 bs 1.9. I thought it was on users, but maybe not...

To be clear, it was someone else surprised by this behavior.

**Comment by steveklabnik** [comment]
Found it!http://stackoverflow.com/q/36295576/24817

**Comment by alexcrichton** [comment]
Yeah this is an instance of https://github.com/rust-lang/rust/issues/32254 which was introduced by https://github.com/rust-lang/rust/pull/31618 and fixed in https://github.com/rust-lang/rust/pull/32257. Cargo upgraded to a "broken rustc" in https://github.com/rust-lang/cargo/pull/2510 and I hope to fix this in https://github.com/rust-lang/cargo/pull/2531
