### ISSUE TITLE
cargo doc should be able to generate std's documentation

### ISSUE THREAD

**Issue by dastbe** [rust-lang/cargo#2563]
Sorry if this is possible and I'm just missing the UX, but it would be useful when I'm offline to be able to have my cargo doc output include std.

**Comment by alexcrichton** [comment]
Thanks for the report! This is actually mostly up to other tools like [rustup](https://github.com/rust-lang-nursery/multirust-rs) to install the documentation for the standard library. Cargo unfortunately does not have access to the source code (unless you tell it so) to the standard library, and otherwise for browsing offline docs the main installers are the best way to get offline docs.

Let me know if you need any help setting that up though!
