### ISSUE TITLE
Versioning of a Git dependency is confusing

### ISSUE THREAD

**Issue by nodakai** [rust-lang/cargo#2586]
```
[build-dependencies]
ctest = { git = "https://github.com/alexcrichton/ctest" }
```

When I run `cargo build`, the corresponding console output from `cargo` looks like

```
   Compiling ctest v0.1.0 (https://github.com/alexcrichton/ctest#a6becb6d)
```

Here, `v0.1.0` does not serve as a proper semantic version of the referenced Git repository because the author could be committing arbitrary changes to the repo between their "releases." Practically speaking, the author isn't likely to update the semver for each and every commit. So the meat of the above console output is in the `a6becb6d` part, except it doesn't look like so at all.

The output format should better be changed to something like

```
Compiling ctest a6becb6d (https://github.com/alexcrichton/ctest)
```

so as to emphasize the fact that there's no fixed "v0.1.0" in the referenced repo (of course, when the build dependency doesn't have the `tag=...` option.)

Ideally we should invent a better way of displaying how a particular revision was chosen by `Cargo.toml` and possibly `Cargo.lock` but that's another topic.

**Comment by dwijnand** [comment]
It's what https://github.com/sbt/sbt-git calls it but I realise it isn't an established term, that's why I put it in quotes.

If we can't come up with better output suggestions, we should just close this as "good enough".

**Comment by epage** [comment]
For me, the main issue is that showing a sha isn't all that meaningful to the user but showing the version (assuming the repo isn't living at HEAD with a fixed version) at least provides some context.

So we could do:
- Show branch or tag if set
- Show version otherwise

As that is all meaningful but the inconsistency isn't great either.

Overall, I wonder if this would be worth the time and energy to hash out what to show, change cargo to get it to work, and write the tests.

I'm going to nominate this for closing.

**Comment by weihanglo** [comment]
Agree on closing, especially for consistency.

**Comment by epage** [comment]
With a second, I'm going ahead.

If there is a reason we should reconsider this, let us know!
