### ISSUE TITLE
cargo-install: build directory should be in $TEMPDIR

### ISSUE THREAD

**Issue by japaric** [rust-lang/cargo#2606]
and each instance of `cargo-install` should have its own build directory.

Right now `cargo-install` uses a `target-install` directory in `$PWD`. So you run into issues like these:

You don't have permission to write to `$PWD`:

```
$ cd /
$ cargo install cargo-graph
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading cargo-graph v0.2.2
error: failed to compile `cargo-graph v0.2.2`, intermediate artifacts can be found at `/target-install`

Caused by:
  failed to open: /target-install/release/.cargo-lock

To learn more, run the command again with --verbose.
```

Calling `cargo install` multiple times from the same directory will build each crate sequentially instead of in parallel (because the build directory gets locked -- without the lock things would be worse, so removing the lock is not a solution)

```
$ cargo install cargo-graph & cargo install cargo-count
[1] 28438
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Blocking waiting for file lock on the registry index
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Blocking waiting for file lock on the registry index
    Blocking waiting for file lock on crate metadata
    Blocking waiting for file lock on build directory
   Compiling rustc-serialize v0.3.19
(...)
```

If the build directory was `$(mktemp -d)` then you wouldn't have problem calling `cargo install` from a directory you don't permission to write to, and you could spawn several `cargo install` (from the same directory) that actually run in parallel.

Thoughts?

**Comment by alexcrichton** [comment]
The problem with tempdirs is that if you ctrl-c they end up lying around and they're hard to find to remove. I wonder though if Cargo could just try a few locations? For example if `$PWD` isn't workable because it's not writable, it could switch to a deterministic directory in `/tmp`. Otherwise if it fails it could switch to `cargo-install2` or something like that.

Although I guess it's just amounting to a tempdir that's slightly more readable...

Meh, I guess just using a tempdir seems fine to me!
