### ISSUE TITLE
Modifying a target specification file should recompile of all the relevant crates

### ISSUE THREAD

**Issue by japaric** [rust-lang/cargo#2616]
Currently it doesn't rebuild any crate.
### STR

```
$ cargo install xargo
$ git clone https://github.com/japaric/cu
$ git checkout 2f63509838b57af8b9bea890c02cfcc41fc74e32
$ xargo build --target stm32f100
   Compiling rlibc v1.0.0
   Compiling compiler-rt v0.1.0 (file:///home/japaric/rust/cu/compiler-rt)
   Compiling cu v0.1.0 (file:///home/japaric/rust/cu)

$ edit stm32f100.json  # add a newline or whatever

$ xargo build --target stm32f100 --verbose
       Fresh rlibc v1.0.0
       Fresh compiler-rt v0.1.0 (file:///home/japaric/rust/cu/compiler-rt)
       Fresh cu v0.1.0 (file:///home/japaric/rust/cu)
```
### Meta

```
$ rustc -V
rustc 1.10.0-nightly (b5ba5923f 2016-04-21)

$ cargo -V
cargo 0.11.0-nightly (867627c 2016-04-21)
```

> recompile all the relevant crates

Should everything be recompiled? Everything that was compiled with `--target $custom_target` must be recompiled. But, what about build scripts? I think they can't rely on the contents of `$custom_target.json` right now, so they probably shouldn't be recompiled/rerun.

cc @alexcrichton

**Comment by alexcrichton** [comment]
Ah yeah this is currently "expected" albeit not necessarily intentional behavior. Targets are completely opaque strings to Cargo (it doesn't try to parse or figure out what it is at all, so Cargo doesn't even know that the target spec is coming from a local file.

Cargo could probably leverage https://github.com/rust-lang/rust/pull/32847 however to add this to the fingerprint for all crates.

**Comment by ehuss** [comment]
Noted in #8085, when fixing this, the rustc_cache will also need to be updated when the spec changes.
