### ISSUE TITLE
cache crates index and downloaded crates for offline use

### ISSUE THREAD

**Issue by llogiq** [rust-lang/cargo#2654]
Using cargo (from a nightly) while offline leads to a network error while updating the crates index. I think in general cargo should cache the index and downloaded crates to allow for automatic offline use – perhaps issue a warning, but continue running.

**Comment by diwic** [comment]
Or perhaps we could add a `--no-update-index` switch or so that would just skip the "Updating registry" part and move on to the next part?

This would be helpful if you're offline, start a new project, and add build dependencies that are already downloaded (because you have other projects using them, so they already exist in `~/.cargo`.

**Comment by hexsel** [comment]
Maven has a -o ("offline") switch which will do its best to run with the current versions (even on things that are "snapshots" - i.e. running builds) and fail early if it absolutely can't.

That may reverse some of the "stability of builds" though, but since it'd be explicit, it may be a reasonable price to pay.

**Comment by llogiq** [comment]
I think the best solution would not *require* a command line switch (though adding one would certainly a good idea), but revert to offline usage if the package index cannot be reached and notify the user of this change. Also perhaps add some flag to the Cargo.lock that marks the dependencies as potentially outdated, so that cargo can remind the user to update once online.

**Comment by steveklabnik** [comment]
As Alex said elsewhere:

> To elaborate on this, Cargo precisely has a global cache of all crates and works offline. The precondition is that you must have fetched the crates from somewhere before you use them.
>
> To guarantee that a project works offline, you should git clone the source code and then run cargo fetch to populate the cache. After this point if Cargo attempts to update the registry or download something then that's a bug and should be filed.

Can you reproduce the scenario where this happens?

**Comment by llogiq** [comment]
Yes. And cargo fetch indeed works as advertised (though I need to be online for it to work).

**Comment by alexcrichton** [comment]
Yes, as @steveklabnik quoted Cargo already implements what this issue is. I believe what you specifically are asking for is covered by https://github.com/rust-lang/cargo/issues/1882, so I'm going to close in favor of that.

**Comment by llogiq** [comment]
:+1:
