### ISSUE TITLE
Proposal: Explicit External Dependencies and External Dependency Pinning

### ISSUE THREAD

**Issue by mitsuhiko** [rust-lang/cargo#2791]
I'm constantly running into issues with various Rust libraries where different dependencies have different versions of the same dependency themselves but whatever they depend on is part of the public API. I think it would make sense to explicitly mark dependencies which escape into public types specifically so that you can forcefully override those.

What this means in practice:

```
app
  depends on hyper ^0.9
  depends on multipart
    depends on hyper 0.8
```

Turns out in the above example `hyper` is part of the public API in multipart and `multipart` is perfectly happy to also compile against hyper 0.9 but what actually happens right now is that the app will compile against hyper 0.9.8 and multipart will compile against hyper 0.8.1 and then the rest of the compilation fails because the types are mismatching when passing a hyper request from app to multipart.

This would not be a concern if hyper was an internal dependency that never shows up in the public API of multipart. In that case holding on to hyper 0.8 as dependency might make more sense because it lowers the chance that it's broken since it would violate the semver dependency.

So what I'm proposing is that libraries that leak dependencies to the outside (as multipart does with hyper and hyper does with url, mime etc.) those dependencies should be specifically marked in the `Cargo.toml` and then another `Cargo.toml` should have the option to decide on the version to use for all of those manually.

In the above case soething like this in multipart:

```
[dependencies.hyper]
version = "^0.8"
external-dependency = true
```

And in the `Cargo.toml` of the app you could then do this:

```
[dependencies]
hyper = "^0.9"
multipart = "0.7"

[dependency-pinning]
"hyper + multipart.hyper" = "0.9.8"
```

**Comment by 3Hren** [comment]
> Turns out in the above example hyper is part of the public API in multipart and multipart is perfectly happy to also compile against hyper 0.9 but what actually happens right now is that the app will compile against hyper 0.9.8 and multipart will compile against hyper 0.8.1 and then the rest of the compilation fails because the types are mismatching when passing a hyper request from app to multipart.

Is that means that the generated symbols contain version number, for example `hyper__0_8_1::HttpRequest`, to cause compilation error? I mean if for example crate foo with version 0.1 contains struct
```rust
struct Foo { val: usize }
```

And the same struct in version 0.2 has different layout:
```rust
struct Foo { val: usize, more: usize };
```

Into which type of error that situation will lead? Compilation/linking/runtime crash?

**Comment by steveklabnik** [comment]
Both @alexcrichton and @wycats have some thoughts here; this is something they've been talking about for a while.

**Comment by chris-morgan** [comment]
NPM has the concept of [peer dependencies](https://nodejs.org/en/blog/npm/peer-dependencies/) to handle this sort of thing.

**Comment by alexcrichton** [comment]
Thanks for the issue @mitsuhiko! I'm gonna close this in favor of https://github.com/rust-lang/cargo/issues/2064 as it's out placeholder for the solution to this issue (albeit somewhat oddly named).

The plan @wycats and I have talked about is precisely this, where crates have a set of public and a set of private dependencies. Cargo would then require that subgraphs of connected public dependencies all must have the same version of a crate to successfully resolve. That is, your app would fail to compile even though the two semver version are incompatible, as because hyper is a public dependency it needs to be deduplicated.

Now the best fallback behavior here is probably for all dependencies to be public by default. Unfortunately that's not compatible with today's interpretation of Cargo.toml, but that's also why this will likely require an RFC!

In any case I'm gonna close this in favor of https://github.com/rust-lang/cargo/issues/2064, and perhaps we could continue discussion over there?

**Comment by aturon** [comment]
@mitsuhiko, are you interested in collaborating on an RFC in this direction?

**Comment by mitsuhiko** [comment]
Absolutely!

**Comment by aturon** [comment]
@mitsuhiko Just in case you don't see it on IRC, here's a doodle poll for picking a meeting time: http://doodle.com/poll/5787pmznm97u2938
