### ISSUE TITLE
Warn on the duplicate entry points for [lib] and [[bin]] (especially when one of them is implicit)

### ISSUE THREAD

**Issue by lifthrasiir** [rust-lang/cargo#2800]
In [this SO question](https://stackoverflow.com/questions/37984922/build-only-lib-target) Cargo tries to build _both_ library and executable out of a single source file (`src/main.rs`), which sounds very wrong to me. I think Cargo should warn on such cases.

**Comment by brson** [comment]
That specific example is really bad because from looking at it you don't expect the explicit "main.rs" to *also* be an inferred bin.

It is a nice and intended property of Rust that you can build both library and application from the same source, though I admit it's not a best practice.

I suppose I'd prefer that cargo warn when one of outputs is inferred but not when they are explicit.

**Comment by brson** [comment]
@alexcrichton Where in the source would someone look to fix this?

**Comment by alexcrichton** [comment]
Ah right, sorry I forgot to fill in the details here!

This would probably be done in `src/cargo/util/toml.rs` probably right after [this call to `normalize`](https://github.com/rust-lang/cargo/blob/401f0fc73fcc31aaeb92aa199d2c51d0fa9bbb24/src/cargo/util/toml.rs#L525-L532) where all the targets should be in one vector, if anything shows up twice should be good enough to warn about.

**Comment by arshiamufti** [comment]
I was looking around in the issue tracker for stuff I could work on and found this issue. I _think_ it's already been addressed in the PR addressed above? Should this be closed?

**Comment by alexcrichton** [comment]
Ah yes, I believe so!
