### ISSUE TITLE
Cargo fails to link to C functions with the `inline` attribute

### ISSUE THREAD

**Issue by Slabity** [rust-lang/cargo#2802]
Currently, cargo fails to link to C functions that use the `inline` attribute. If you create a crate with a C function that uses `inline`, the crate will compile successfully. However, if you try to use that crate to any binary or run a test on it, you will get undefined references to the C functions that use `inline`.

**Comment by alexcrichton** [comment]
Thanks for the report! This is probably related moreso to the compiler rather than Cargo (as Cargo is just calling the compiler), so this issue may be more appropriate for rust-lang/rust. Could you elaborate a bit with some code, however, that I might reproduce locally? It sounds like this may be intended behavior, but it'd be good to just confirm.

**Comment by Slabity** [comment]
Looks like the mistake was my fault. I was attempting to use a precompiled C header instead of linking to an actual library.

**Comment by alexcrichton** [comment]
Ok, thanks for the update, and glad it worked out!
