### ISSUE TITLE
stderr of build script is intercepted…

### ISSUE THREAD

**Issue by nagisa** [rust-lang/cargo#2816]
…thus essentially making any errors build build script reports silent.

**Comment by alexcrichton** [comment]
Thanks for the report! Right now it's the responsibility of build scripts to return an error (nonzero exit code) if an error actually happens, in which case Cargo will indeed forward the output to see. Otherwise on nightly Cargo you can pass `-vv` to see the streamed output of the build script (or `-v` to just see warnings), and there's a lengthy discussion of this over at https://github.com/rust-lang/cargo/issues/1106. I'm gonna close this as this is handled on nightly, though.
