### ISSUE TITLE
Stable channel contains nightly cargo build?

### ISSUE THREAD

**Issue by bjgill** [rust-lang/cargo#2882]
The stable channel [https://static.rust-lang.org/dist/channel-rust-stable.toml](https://static.rust-lang.org/dist/channel-rust-stable.toml) currently seems to have a nightly version of cargo (0.11.0-nightly (259324c 2016-05-20)) specified.

Is this intentional? If so, a mention in the documentation might reduce confusion.

**Comment by alexcrichton** [comment]
This is indeed a bit of an interesting fact about how we distribute Cargo today! Currently we don't actually have a non-nightly channel of Cargo like we do for Rust. Each Rust release just pins itself to some particular nightly build of Cargo and we ship it.

So in that sense this is intentional, but I'd be fine documenting it!

**Comment by ehuss** [comment]
This appears to have been fixed in rust 1.17.
