### ISSUE TITLE
[Replace]ing a path dependency with another path dependency gives no error message and causes a panic on the next run.

### ISSUE THREAD

**Issue by jessstrap** [rust-lang/cargo#2996]
Running cargo with this [Cargo.toml](https://github.com/jessstrap/servotk/blob/d13958758b6c20d107a46120c5f53d769a4a31f7/ports/servotk_sample/Cargo.toml) with this [Cargo.lock](https://github.com/jessstrap/servotk/blob/d13958758b6c20d107a46120c5f53d769a4a31f7/ports/servotk_sample/Cargo.lock) results in this [Cargo.lock](https://github.com/jessstrap/servotk/blob/d13958758b6c20d107a46120c5f53d769a4a31f7/ports/servotk_sample/Cargo.lock.after).
Running cargo a second time with the same Cargo.toml gets a panic with this message "thread 'main' panicked at 'a package was referenced twice in the lockfile', src/cargo/core/resolver/encode.rs:49".
The additions to Cargo.lock can be seen [here](http://pastebin.com/wUXVGui5).

**Comment by alexcrichton** [comment]
I believe the line "at fault" here is [the replace section](https://github.com/jessstrap/servotk/blob/d13958758b6c20d107a46120c5f53d769a4a31f7/ports/servotk_sample/Cargo.toml#L93). Cargo doesn't currently allow replacing a path dependency with another one because it doesn't historically have enough information to track this. In any case though this should produce a better error message!

**Comment by jessstrap** [comment]
@alexcrichton Should I file another issue as a feature request for 'path replaces path'?

**Comment by alexcrichton** [comment]
Sure!

**Comment by kellda** [comment]
#3148 was closed, maybe this one can also be closed ?

**Comment by ehuss** [comment]
Yea.  Also `[patch]` is the recommended way to override now, and it seems to handle replacing path dependencies.
