### ISSUE TITLE
#2919 breaks bootstrap for rustc when using --enable-rustbuild.

### ISSUE THREAD

**Issue by ahmedcharles** [rust-lang/cargo#3005]
rustc requires that the names of libraries have hashes, so that side by side installs work, so #2919 breaks that by no longer having the output of the build contain hashes.

**Comment by alexcrichton** [comment]
I think the solution here will be some way to just tell Cargo to "always put a hash in the file name". Disabling this by default I think is correct, but for the compiler where we're shipping things we care about it seems reasonable to have that.

I... wish we had unstable features in Cargo, but failing that some magical environment variable would be fine for now.

**Comment by ahmedcharles** [comment]
Philosophical question: What are the reasons that libraries other than the standard library should not support side by side install? It seems desirable for any given library, though I don't know enough to have strong feelings either way. I do think that it's important to document the reasoning, though.

Practical question: I looked at #2919 and I don't know which line of code actually effects the change in file names for outputs files. There's probably something I'm missing, but could you point out which parts of the PR actually impact the names if the files?

**Comment by alexcrichton** [comment]
> What are the reasons that libraries other than the standard library should not support side by side install?

Oh I think the only difference is that we're shipping binaries, whereas no other project is shipping Rust libraries. I wouldn't necessarily say that we think that other libraries *shouldn't* support sxs installs, Cargo certainly shouldn't hinder it!

The relevant code for this [is here](https://github.com/rust-lang/cargo/blob/4c219617274fe59f3b9d847e0e005ebc96a6bb2b/src/cargo/ops/cargo_rustc/context.rs#L316-L343) and specifically [this was changed](https://github.com/rust-lang/cargo/blob/4c219617274fe59f3b9d847e0e005ebc96a6bb2b/src/cargo/ops/cargo_rustc/context.rs#L333) to test `is_path()` rather than `id == resolve.root()`

**Comment by Eh2406** [comment]
https://github.com/rust-lang/rust/blob/master/src/bootstrap/builder.rs#L443
Claims to be a workaround for this. Perhaps that can be removed now?

**Comment by tamird** [comment]
@Eh2406 that workaround is still necessary - #3022 simply added the facility that makes that workaround possible.
