### ISSUE TITLE
"no `package` or `project` section found" for git dependency with workspace

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/cargo#3025]
For LALRPOP, I am using a setup like this:

- [Cargo.toml](https://github.com/nikomatsakis/lalrpop/blob/master/Cargo.toml) is the "workspace" project
  - [lalrpop/Cargo.toml](https://github.com/nikomatsakis/lalrpop/blob/master/lalrpop/Cargo.toml) is the lalrpop project
  - [lalrpop-util/Cargo.toml](https://github.com/nikomatsakis/lalrpop/blob/master/lalrpop-util/Cargo.toml) is the utility project

and so forth. Basically there is an empty workspace at the root, and crates in their own directories. But this setup doesn't work well with git dependencies:

```
Updating git repository `https://github.com/nikomatsakis/lalrpop.git`
error: Unable to update https://github.com/nikomatsakis/lalrpop.git

Caused by:
  failed to parse manifest at `/Users/nmatsakis/.cargo/git/checkouts/lalrpop-3c5328ed66fab364/master
/Cargo.toml`

Caused by:
  no `package` or `project` section found.
```

Or maybe this setup is not recommended? I thought it was one of the expected usage patterns for workspaces though.

**Comment by alexcrichton** [comment]
Yes unfortunately this was a bug in Cargo that was fixed [relatively recently](https://github.com/rust-lang/cargo/pull/2938), so it'll take some time to propagate out :(

In the meantime though yeah if you expect to have git dependencies I'd recommend not enabling workspaces there or recommending git dependencies only on nightly/beta (where the problem is fixed)
