### ISSUE TITLE
build.rustflags is passed twice (and rustc errors)

### ISSUE THREAD

**Issue by bluss** [rust-lang/cargo#3070]
If I use this in ~/.cargo/config, the flag is passed twice:

```toml
[build]
rustflags = ["-Cllvm-args=-x86-asm-syntax=intel"]
```

This does not apply to configuration directories stored directly under my project's root (using `projectname/.cargo/config`, the option is passed only once). There is only a single cargo config file involved in each scenario.

For this particular flag, it stops the build with an error:

```
$ cargo build
error: failed to run `rustc` to learn about target-specific information

Caused by:
  Process didn't exit successfully: `rustc - --crate-name _ --print=file-names -Cllvm-args=-x86-asm-syntax=intel -Cllvm-args=-x86-asm-syntax=intel --crate-type bin --crate-type rl
ib --target x86_64-unknown-linux-gnu` (exit code: 1)
--- stderr
rustc: for the -x86-asm-syntax option: may only occur zero or one times!
```

Also related: #3052, but this issue is for the specific bug of doubling the flag.

**Comment by alexcrichton** [comment]
The bug here appears to be [pretty deep in Cargo](https://github.com/rust-lang/cargo/blob/2ef3cdee92324d7dd024b6b431eb581505b37ebf/src/cargo/util/config.rs#L674-L708) when we're parsing config files. The logic there is to walk the directory tree up to the root of the file system, picking up configuration as we go along.

At the end, however, we [specifically look in the home directory](https://github.com/rust-lang/cargo/blob/2ef3cdee92324d7dd024b6b431eb581505b37ebf/src/cargo/util/config.rs#L699-L705) as well in case a build isn't hierarchically below that. This logic [has a guard](https://github.com/rust-lang/cargo/blob/2ef3cdee92324d7dd024b6b431eb581505b37ebf/src/cargo/util/config.rs#L699) to try to not parse a config file twice, but unfortunately that's not actually the right condition. As a result, configuration in the home directory is getting parsed twice, and it's duplicating lists.

The fix here is to probably just keep a hash set of visited directories, and check that for the home directory instead of a `starts_with` check. Should be a pretty easy fix though!

**Comment by retep998** [comment]
Probably would be a good idea to canonicalize each visited directory to ensure you don't visit the same directory twice due to symbolic links.

**Comment by jhbabon** [comment]
Hi! I'm pretty new to rust but I would like to try to contribute to cargo by fixing this issue if nobody else is working on it.

**Comment by jhbabon** [comment]
I went ahead and made the fix. If you have something better coming feel free to close it. I hope it helps https://github.com/rust-lang/cargo/pull/3078

**Comment by alexcrichton** [comment]
Thanks @jhbabon!

**Comment by jhbabon** [comment]
I think this issue can be closed, the PR has been merged.

**Comment by alexcrichton** [comment]
Thanks @jhbabon!

**Comment by bluss** [comment]
Thank you!
