### ISSUE TITLE
Underscores in names of the targets and crates

### ISSUE THREAD

**Issue by matklad** [rust-lang/cargo#3085]
Currently crate names are normalized by turning all the `-` into `_`. This however does not happen with target names and you can get

```
cargo run --example tutorial_02

error: no example target named `tutorial_02`

Did you mean `tutorial-02`?
```

Is this the intended, or should we treat `tutorial_02` and `tutorial-02` as the same target? I think that either behavior is OK, but I want this to be an explicit decision and not a random artifact of the current implementation. 

Downstream issue: https://github.com/intellij-rust/intellij-rust/issues/664

**Comment by alexcrichton** [comment]
This is currently intended, but I don't think that there's any real reason Cargo should make this distinction. I'd be fine relaxing Cargo's parsing and just interpreting these two as the same name!

**Comment by cyplo** [comment]
Would that be a good candidate for `help-wanted` ?

**Comment by epage** [comment]
Making target names `-` / `_` insensitive would be a breaking change because you can have targets differ by those.  Its a minor case, so maybe we'd be fine breaking it.  We could also say "change separators when no ambiguity".

However, do people run into this interactively (the downstream issue for this was about a bug in an IDE doing this for users)?  Without this being an end-user usability problem, working through these questions does not seem worth it to me.  I'm going to propose to the cargo team that we close this.

**Comment by weihanglo** [comment]
Given that is a breaking change as aforementioned, I second closing this. If there is any issue of it, don't hesitate and talk to us. Thank you.
