### ISSUE TITLE
Allow profile settings to be overridden with command line arguments or environment variables.

### ISSUE THREAD

**Issue by mystor** [rust-lang/cargo#3088]
Options specified in the `[profile]` section of the Cargo.toml file should be overridable from the command line, for example, it would be nice to be able to pass `--opt-level 2`, to set the optimization level to 2 even though the `[profile]` section specifies that `opt-level = 1` or similar. 

This would be useful for integrating cargo into existing build systems, as these build systems want to be able to control build configuration options for building rust libraries, without having to modify the Cargo.toml files for those libraries directly.

An alternative would be to allow overriding these properties with environment variables, similar to how properties in .cargo/config can be overridden with environment variables.

**Comment by ehuss** [comment]
I'm going to close this as it is now possible with the [config profiles](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#config-profiles) feature and environment variables.  Example: `CARGO_PROFILE_DEV_OPT_LEVEL=2 cargo run -Z config-profile` 

Stabilization is tracked at https://github.com/rust-lang/rust/issues/48683.

**Comment by agrover** [comment]
@ehuss can you point me at the documentation on setting environment variables that affect Cargo? The nightly docs talk about all the env variables Cargo sets, but I don't see where the example you gave is described.

**Comment by ehuss** [comment]
@agrover The env vars that cargo reads is at "[Environment variables Cargo reads](https://doc.rust-lang.org/nightly/cargo/reference/environment-variables.html#environment-variables-cargo-reads)". Settings in `.cargo/config` can be set via environment variables.  This is mentioned in two places ([1](https://doc.rust-lang.org/nightly/cargo/reference/environment-variables.html#environment-variables-cargo-reads) [2](https://doc.rust-lang.org/nightly/cargo/reference/config.html#environment-variables)), but several people have mentioned difficulty in finding that so it should probably be made more prominent.  I'm just reluctant to list them all, because it would end up duplicating the entire config list (which would likely get out of sync), and would add 30+ more variables to the list adding a lot of noise and drowning out the important ones.  I imagine the config-profile feature could include a pointer and example.
