### ISSUE TITLE
`cargo package` and `cargo publish` fail with custom target triples

### ISSUE THREAD

**Issue by jamesmunns** [rust-lang/cargo#3119]
Hey all, I was attempting to publish a crate that targets an ARM Cortex-M micro controller, and received the following errors:

``` bash
➜  teensy3-sys git:(master) cargo package --verbose
   Packaging teensy3-sys v0.1.0 (file:///Users/jamesmunns/Git/teensy3-rs/teensy3-sys)
   Archiving bindings.h
   ...
   Archiving teensy3-core/yield.cpp
   Verifying teensy3-sys v0.1.0 (file:///Users/jamesmunns/Git/teensy3-rs/teensy3-sys)
error: failed to verify package tarball

Caused by:
  failed to run `rustc` to learn about target-specific information

Caused by:
  Process didn't exit successfully: `rustc - --crate-name _ --print=file-names --crate-type bin --crate-type rlib --target thumbv7em-none-eabi` (exit code: 101)
--- stderr
error: Error loading target specification: Could not find specification for target "thumbv7em-none-eabi"
  |
  = help: Use `--print target-list` for a list of built-in targets
```

This can be reproduced by cloning https://github.com/jamesmunns/teensy3-rs, `cd teensy3-sys`, then `cargo package --verbose`.

I was able to then publish with `cargo package --verbose --no-verify`, but I would expect that cargo should follow the specification in `.cargo/config` (up one directory). I also tried copying the `.cargo` folder to the `teensy3-sys` folder, but no change in behavior.

Cargo publish behaves the same with a similar failure.

CC @SimonSapin

**Comment by jamesmunns** [comment]
Version information:

```bash
➜  teensy3-sys git:(master) ✗ cargo --version
cargo 0.13.0-nightly (9399229 2016-09-14)
➜  teensy3-sys git:(master) ✗ rustc --version
rustc 1.13.0-nightly (4f9812a59 2016-09-21)
```

**Comment by japaric** [comment]
Hmm, why is the packaging for the `thumb` target? Do you have a `.cargo/config` with `build.target` set to the `thumb` target? Some ideas you could try:

- Try to package for the host i.e. remove the default target from the .cargo/config. This may fail because non-x86 `asm!` and what not.
- Put the `thumb` target specification (the .json file) somewhere, point to that directory using `RUST_TARGET_PATH` (let me check that env var) i.e. export that variable and try to package using `xargo package` with the default target set to the `thumb` target.

**Comment by japaric** [comment]
All this would probably just work if the `thumb` targets were built-in targets! cc @alexcrichton @brson

**Comment by alexcrichton** [comment]
Thanks for the report! I think @japaric is right in that this is picking up `.cargo/config` to set the target, so you can work around this for now with `cargo publish --no-verify`. Also agreed that we should probably just ignore that configuration when publishing!

**Comment by alexcrichton** [comment]
This may not be *too* hard to tackle, but I'm not gonna tag E-easy yet as I'm not certain of the resolution.

**Comment by japaric** [comment]
@alexcrichton OTOH, this crate is meant to only ever by compiled for a certain embedded ARM target so it doesn't make sense to verify by compiling the crate for the host because the compilation will likely fail.

What I'm getting at is that there is an use case for "verify against this TARGET and not against the HOST" and picking up that target from .cargo/config seems reasonable but perhaps should be more explicit: Normally you would use `cargo publish --target $T` but if it picks up .cargo/config then show a warning/message saying "packaging/verifying for/against $T".

**Comment by alexcrichton** [comment]
@japaric ah yeah that's a good point! Seems reasonable to me then that we shouldn't ignore it and should just indicate that we're verifying against that.

In any case @jamesmunns I think the issue here is that the cwd is different on `cargo publish` and on `cargo build`. The custom target spec is then not picked up as part of `cargo publish`, unfortunately.

**Comment by jamesmunns** [comment]
@japaric and @alexcrichton I can verify that this is fixed, at least as of the latest nightly (at least with my specific target triple, since it is now included).

There may be a desire long-term to support arbitrary target-triples, but I am not sure what the effort is. For now, I am happy :)

```bash
➜  teensy3 git:(master) cargo package            
   Packaging teensy3 v0.1.3 (file:///Users/jamesmunns/Git/clean_test/teensy3-rs/teensy3)
   Verifying teensy3 v0.1.3 (file:///Users/jamesmunns/Git/clean_test/teensy3-rs/teensy3)
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling teensy3-sys v0.1.0
   Compiling teensy3 v0.1.3 (file:///Users/jamesmunns/Git/clean_test/teensy3-rs/teensy3/target/package/teensy3-0.1.3)
    Finished debug [unoptimized + debuginfo] target(s) in 1.28 secs
➜  teensy3 git:(master) cargo publish
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Packaging teensy3 v0.1.3 (file:///Users/jamesmunns/Git/clean_test/teensy3-rs/teensy3)
   Verifying teensy3 v0.1.3 (file:///Users/jamesmunns/Git/clean_test/teensy3-rs/teensy3)
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling teensy3-sys v0.1.0
   Compiling teensy3 v0.1.3 (file:///Users/jamesmunns/Git/clean_test/teensy3-rs/teensy3/target/package/teensy3-0.1.3)
    Finished debug [unoptimized + debuginfo] target(s) in 1.15 secs
   Uploading teensy3 v0.1.3 (file:///Users/jamesmunns/Git/clean_test/teensy3-rs/teensy3)
➜  teensy3 git:(master) rustc --version
rustc 1.14.0-nightly (098d22845 2016-10-13)
➜  teensy3 git:(master) cargo --version
cargo 0.13.0-nightly (5f2cc15 2016-10-13)
```

**Comment by carols10cents** [comment]
> I can verify that this is fixed, at least as of the latest nightly (at least with my specific target triple, since it is now included).
> 
> There may be a desire long-term to support arbitrary target-triples, but I am not sure what the effort is. For now, I am happy :)

I'm going to close this, since as far as I can tell there has been no desire expressed to support arbitrary target-triples :)
