### ISSUE TITLE
Should Cargo.lock be committed, or added to .gitignore?

### ISSUE THREAD

**Issue by ghost** [rust-lang/cargo#315]
There doesn't appear to be any documentation about the purpose of Cargo.lock and guidelines for handling it.

Should Cargo.lock be committed to a project's repository, or should it be added to .gitignore?

/cc nickel-org/nickel.rs#50

**Comment by AndreasHassing** [comment]
The answer in this FAQ describes the reasoning really well: http://doc.crates.io/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries

Just leaving this here, as Google'ing for "`Crate.lock gitignore`" leads to this issue.

**Comment by montao** [comment]
> 
> 
> This is [now documented](http://crates.io/guide.html), so I'm going to close this.

Link does not work. Maybe it is this now https://doc.rust-lang.org/cargo/guide/

**Comment by MarkelFe** [comment]
Actually, right now the link is this one [https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html](https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html). Here is the answer to the question:

> If you’re building a non-end product, such as a rust library that other rust packages will depend on, put Cargo.lock in your .gitignore. If you’re building an end product, which are executable like command-line tool or an application, or a system library with crate-type of staticlib or cdylib, check Cargo.lock into git.

**Comment by gorakhargosh** [comment]
What if you're using Bazel and a mono-repo that has both libraries and binaries?

**Comment by em-** [comment]
Since this turns up in web searches, here's the latest location for the relevant piece of documentation: https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html

**Comment by choleraehyq** [comment]
Cargo.lock not only specifies the specific versions of dependencies, but also provides the checksums of its dependencies for build system to verify. From this security aspect, maybe we need to commit Cargo.lock along with Cargo.toml?

Go team clearly point out this reason in doc https://go.dev/wiki/Modules#should-i-commit-my-gosum-file-as-well-as-my-gomod-file.

**Comment by weihanglo** [comment]
Please read the recent blog post ["Change in Guidance on Committing Lockfiles"](https://blog.rust-lang.org/2023/08/29/committing-lockfiles.html), and the [up-to-date guidance](https://doc.rust-lang.org/cargo/faq.html#why-have-cargolock-in-version-control).
See also <https://github.com/rust-lang/cargo/issues/8728>.

**Comment by binkley** [comment]
I read through the links provided in the comments, and @weihanglo 's posting was the only one to provide a currently active doc link: https://doc.rust-lang.org/cargo/faq.html#why-have-cargolock-in-version-control

**Comment by luto** [comment]
Current link: https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html

**Comment by createyourpersonalaccount** [comment]
With `cargo init --vcs git --lib` how come it's not ignored by default?

**Comment by ctjlewis** [comment]
You should check in your lockfiles. The customs of Rustaceans are so bizarre. We have always committed lockfiles in web/application development, that is how we can recover if we bump our packages and something silently breaks and you don't notice until later. As your dependency tree grows, the odds of this happening on an update grow exponentially.

If we don't record what versions of packages we were on for each checkpoint in the code's history then we are flying blind folks, we are no better than animals or savages if we do not do that. A frozen copy of the dependency tree is a *part* of the codebase, it's something you need to have to reproduce a local environment. You're hoping cargo will perfectly reproduce it by not checking it in, you're trusting your package manager. The hubris of this. Is it your first time installing packages? That shit is going to break.

Practically, our team ran into this problem many times, where we version something `3.4` and then the bump 3.4.7 has some dependency that *it* bumps and *that* breaks or conflicts with some other dependency and now you don't know where you were before because we have this bizarre practice here of not tracking our lockfiles. Well, I've had it. The repos *I* own will be committing them like a sane, civilized person.

You know, sometimes I think you guys are just freaky like that. It's about the thrill for you.

**Comment by epage** [comment]
FYI we changed our guidance in #12382 which was released for 1.74

**Comment by ctjlewis** [comment]
Oh, thank you @epage. The only doc I could find took no position, it was like, "do what's best for your project." I'm joking but I do think this is the right choice.

**Comment by epage** [comment]
If you are referring to [our FAQ](https://doc.rust-lang.org/cargo/faq.html#why-have-cargolock-in-version-control), then it isn't quite  "no position".  We found that people tend to be overly prescriptive to others with recommendations and we should allow for more nuance in the discussion, so our default stance is for people to commit it and we document the trade offs for those wanting to dig deeper into their decision.  Capturing nuance for that is hard.  Some will take our statement as too soft while if we strengthen it, people may read into it too strongly.
