### ISSUE TITLE
Bad call to `rustdoc` when `cargo test --package feature` when using features

### ISSUE THREAD

**Issue by TeXitoi** [rust-lang/cargo#3172]
TLDR: this (almost) minimal project doesn't work: https://github.com/TeXitoi/cargo_bug_feature_package

When using features, and calling `cargo test --package feature`, `--cfg` arguments are bad when calling `rustdoc`.

**Comment by TeXitoi** [comment]
Maybe a duplicate of #2539

**Comment by alexcrichton** [comment]
Right now `--cfg` flags are [passed here to rustdoc](https://github.com/rust-lang/cargo/blob/08738934e068583097253ff520ddef9fbf945c13/src/cargo/ops/cargo_test.rs#L148-L150)  which originates from [this field](https://github.com/rust-lang/cargo/blob/08738934e068583097253ff520ddef9fbf945c13/src/cargo/ops/cargo_rustc/compilation.rs#L44-L45) which are all [filled in here](https://github.com/rust-lang/cargo/blob/08738934e068583097253ff520ddef9fbf945c13/src/cargo/ops/cargo_rustc/mod.rs#L151-L164).

The bug here is that we're passing `root_pkg` to the calculations here, which doesn't work with the `--package` flag where we're actually testing something other than the root crate. I *think* this may be the same issue as https://github.com/rust-lang/cargo/issues/2539 because we [attempt to pass build script cfg values](https://github.com/rust-lang/cargo/blob/08738934e068583097253ff520ddef9fbf945c13/src/cargo/ops/cargo_rustc/mod.rs#L159), but that would require https://github.com/rust-lang/cargo/issues/2539 specifically being related to the `-p` flag which it currently doesn't mention.

I think we'll want to tweak this logic and perhaps just update `Compilation` to not only store the cfg values for the root package, but rather the entire crate graph. That way later on we can just look up the relevant piece in the hash table in `Compilation` instead of always picking the one `cfgs` value.

I'm going to tag this `E-easy` as I think it shouldn't be too hard to tackle, but if anyone works on this and needs some help feel free to ping me!

**Comment by jhbabon** [comment]
Hi @alexcrichton, I can take a look at this if no one has done it yet. (yes, I'm chasing `E-easy` tags in this project 😆 )

**Comment by alexcrichton** [comment]
@jhbabon sure! Let me know if you need any pointers!

**Comment by jhbabon** [comment]
Hi! Sorry for the delay on this. This is the fix I managed to do: https://github.com/rust-lang/cargo/pull/3242
