### ISSUE TITLE
cargo run can cause blocked waiting for file lock on git checkout

### ISSUE THREAD

**Issue by cardoe** [rust-lang/cargo#3209]
If you have git based crate dependencies in your `Cargo.toml` and you run `cargo run` in that project. You will not be able to do another `cargo build` until after the original `cargo run` has exited. Once the build step for the `cargo run` has completed their should be no need for a source lock.

ref #2627

**Comment by alexcrichton** [comment]
Yeah I've noticed this leaking in as well from time to time... something fishy is going on!

**Comment by matklad** [comment]
Could it be the git_lock: https://github.com/rust-lang/cargo/blob/02fed69e71806989a96ae372f5d0f7cbb9528c37/src/cargo/util/config.rs#L35 ?

**Comment by alexcrichton** [comment]
Right! Yes that'd do it.

@matklad what do you think about adding a method to `Config` which drops the lock? Basically once we're done compiling we can for sure drop the lock.

**Comment by matklad** [comment]
>@matklad what do you think about adding a method to Config which drops the lock?

Yep, that'd be the simplest solution possible for the problem at hand. However I'd try think if we perhaps can get rid of this lock altogether? 

We mainly need this lock because several versions of the git dependency can be checked out into the same location. If we make sure that the folder with git sources is append only, than we'd be able to lock only metadata files and only for the duration of the checkout, which should be both simpler and more parallel.

**Comment by alexcrichton** [comment]
Yeah I'd also be fine with a different strategy to get rid of the lock.

Another possible stopgap would be to have the `Config` store a weak pointer to the lock. Then whenever a lock is needed it attempts to upgrade that lock and otherwise acquires the lock if it couldn't upgrade. 

Just allows us to *not* have a "drop the locks" method but rather they fall out of scope naturally.

**Comment by matklad** [comment]
Weak ptr won't work, it'll bring back the deadlocks from #2987.

**Comment by alexcrichton** [comment]
Oh I mean still just one global lock, that lock is just held as a weak pointer in `Config` and a strong pointer in all the `Source` objects. That way we only acquire one lock (`Config` tries to upgrade it when it's requested) and it all goes out of scope naturally when the `Source` objects are dropped.
