### ISSUE TITLE
Dependencies across semver-incompatible versions not banned on crates.io.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/cargo#3225]
Not sure this bug belongs here, but I can't find where dependencies on `*` versions were banned.

The problem is that `*` is not the only way to depend on something in a way that they can respect semver and break you: we've had cases that showed up crater, IIRC, where `0.*` dependencies were on crates.io.

There's probably several ways to abuse semver constraints to cross a backwards incompatibility point.
If the semver constraints of a dependency allow both `a.p.x` and `b.q.y` where either:
* `a != b` or
* `a == 0 && b == 0` and:
 * `p != q` or
 * `p == 0 && q == 0 && x != y`

Then they're too loose to be published without risking later breakage by semver-abiding dependencies.

**Comment by alexcrichton** [comment]
cc @sfackler, I forget, but was this intentional as part of the RFC we accepted on this?

**Comment by sfackler** [comment]
This was intentional (see the last paragraph in https://github.com/rust-lang/rfcs/blob/master/text/1241-no-wildcard-deps.md#alternatives). I originally proposed banning all constraints unbounded from above but we limited that to just `*` for reasons that I can't fully remember but you can probably track down from the RFC discussion. I think at least part of it was the idea that a `*` constraint is probably just there because it was the easiest thing to do at the time, while a `> 0.0.0` or whatever constraint is a more concerted effort to do the wrong thing, and is pretty uncommon. The hope then was that banning `*` and having users yell at authors of `> 0.0.0` constraints would hopefully suffice.

**Comment by sfackler** [comment]
It's also not that uncommon for crates to intentionally have dependencies that span multiple major versions because the parts of the library they use didn't break. I've done this multiple times - for example, look at the constraints on `serde_json` and `uuid` for rust-postgres: https://crates.io/crates/postgres/0.12.0

**Comment by eddyb** [comment]
I suppose the problem is with versions "from the future". I couldn't find the RFC when I looked for it, but if it allows this, then I guess this is a non-bug?

**Comment by sfackler** [comment]
It doesn't violate the RFC at least. A follow up that makes these checks more strict would be potentially reasonable though.

**Comment by alexcrichton** [comment]
Ah yes, now I remember, thanks @sfackler! I that case this is working as expected, so closing.
