### ISSUE TITLE
Don’t lock git checkouts when none is used

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/cargo#3337]
Servo [now uses](https://github.com/servo/servo/pull/14381) a workspace instead of maintaining three `Cargo.lock` files, yay!

However, something regressed. I used to be able to run `./mach build` and `./mach build-geckolib` (which run `cargo build` with different `CARGO_TARGET_DIR`s on two different crates that are now member of the same workspace) at the same time. But now, the one started second prints:

```
    Blocking waiting for file lock on the git checkouts
```

and then does nothing until the other one terminates. This is despite `geckolib` not having any (recursive) git dependencies. I’m guessing that Cargo does this because there are git dependencies in the now-shared `Cargo.lock` file.

Could this lock be changed to only be acquired when it’s really needed?

**Comment by alexcrichton** [comment]
I believe this was fixed in https://github.com/rust-lang/cargo/pull/3213 which landed in a nightly [later than Servo's nightly](https://github.com/servo/servo/blob/555aa4055377fd085e0322a84175bbfc1382ff69/cargo-nightly-build), so perhaps that could be updated and this could be tested again to make sure?

**Comment by SimonSapin** [comment]
Yes, it looks like upgrading Cargo fixes this. Thanks!
