### ISSUE TITLE
`cargo uninstall` tries to delete executables that are running, which fails on Windows

### ISSUE THREAD

**Issue by FaultyRAM** [rust-lang/cargo#3364]
`cargo uninstall` doesn't take into account that the crate being uninstalled may in fact be running, and that attempting to delete such an executable will fail on Windows. Because removing the binary is the last step in the uninstall process, this leads to a phenonemon I dub "Schrödinger's crate", in which a crate is both installed and uninstalled; the executable still exists, so `cargo install` fails, but all installation metadata is gone, so `cargo uninstall` fails!

One way to cause this is via the Rusty Code plugin for VS Code; it depends on Racer, which can be installed via `cargo install` and is active while Rusty Code is active. Trying to `cargo uninstall` Racer in this situation leads to breakage as described above.

You can work around this by deleting the leftover executable after making sure it isn't running; `cargo install --force` also works.

Tested with the latest nightly Rust, installed via `rustup-rs`:

```
rustc 1.15.0-nightly (908dba0c9 2016-12-01)
binary: rustc
commit-hash: 908dba0c9477b7dd022a236cb1514ddfca9369f2
commit-date: 2016-12-01
host: x86_64-pc-windows-msvc
release: 1.15.0-nightly
LLVM version: 3.9
```

```
cargo 0.16.0-nightly (3568be9 2016-11-26)
```

**Comment by alexcrichton** [comment]
Hm so `cargo install` in theory is transactional in the sense that if it fails Cargo's still not in a "corrupt" state. Have you found though that after a failed `cargo uninstall` it's essentially in a corrupt state?

**Comment by FaultyRAM** [comment]
In this case no, at least as far as I can tell. The crate isn't listed in .crates.toml, and once the leftover executable is dealt with everything works as normal. It really does seem to be just that the executables get left behind.

**Comment by alexcrichton** [comment]
Sounds bad! If `cargo uninstall` fails Cargo should always leave everything in a consistent state.

**Comment by weihanglo** [comment]
If we focus on making the installed trakcer consistent, I believe this is not too hard to fix. A rough solution may look like

* For `paths::remove_file()` and `tracker.remove()` should go hand in hand.
* `tracker.save()` should be called at the end of `cargo uninstall`, so that at least removed files are still tracked on disk. 
* The behavior happens here: https://github.com/rust-lang/cargo/blob/20df9e40a4d41dd08478549915588395e55efb4c/src/cargo/ops/cargo_uninstall.rs#L139-L152

We can leave the issue of removing running executables to #3486.


@rustbot label +S-accepted +E-easy

**Comment by emanuellima1** [comment]
I would like to work on this issue. I'm devising a solution for it.

**Comment by linyihai** [comment]
@rustbot claim

As nobody focus on this, i will take a shot.
