### ISSUE TITLE
`failed to parse manifest at` error in Ubuntu 16.04

### ISSUE THREAD

**Issue by v1kn** [rust-lang/cargo#3378]
$ cat /etc/os-release
    NAME="Ubuntu"
    VERSION="16.04.1 LTS (Xenial Xerus)"

    $ rustc --version
    rustc 1.7.0

    $ cargo --version
    cargo 0.8.0 (built 2016-03-22)

Before running any `cargo` commands, inside `.bashrc`:

    export CARGO_HOME=$HOME/.local/cargo

Error message:

    $ cargo install --verbose ripgrep
        Updating registry `https://github.com/rust-lang/crates.io-index`
     Downloading ripgrep v0.3.2
    failed to parse manifest at `/home/$USER/.local/cargo/registry/src/github.com-88ac128001ac3a9a/ripgrep-0.3.2/Cargo.toml`

    Caused by:
    could not parse input as TOML
    .local/cargo/registry/src/github.com-88ac128001ac3a9a/ripgrep-0.3.2/Cargo.toml:43:9 expected a key but found an empty string
    .local/cargo/registry/src/github.com-87ac128001ac3a9a/ripgrep-0.3.2/Cargo.toml:43:9-43:10 expected `.`, but found `'`

**Comment by alexcrichton** [comment]
I believe this is complaining about [this line](https://github.com/BurntSushi/ripgrep/blob/6d346a09deefcd95bb15486b0288176099eb4469/Cargo.toml#L43) which uses single-quotes in key names rather than double quotes. This was added as a feature relatively recently in Cargo, so I think what you'll need to do here is upgrade the version of Cargo that you're using.

If that doesn't help though just let me know!

**Comment by v1kn** [comment]
Ok, thank You for the info.

**Comment by akalightowl** [comment]
Thank you, update cargo from source http://doc.crates.io/ and in new version all work fine.
