### ISSUE TITLE
Tracking issue for PR #3361

### ISSUE THREAD

**Issue by pwoolcoc** [rust-lang/cargo#3391]
Per @alexcrichton in [this comment](https://github.com/rust-lang/cargo/pull/3361/#issuecomment-266166225), I am opening a tracking issue for the plan to eventually change cargo to assume that a `build.rs` file in the same directory as a `Cargo.toml` file is a build script. Right now `cargo` just issues a warning when it sees a `build.rs` file in the same directory as a `Cargo.toml` file that lacks a `build = ...` value.

Original PR:
https://github.com/rust-lang/cargo/pull/3361

**Comment by pwoolcoc** [comment]
@alexcrichton hello again! now that 1.15 is out with this change, what do you think of completing the change on the current nightly? Assuming it gets in to 1.17, that would mean users would get the `build = false` warning for 2 stable releases before the behavior changes.

**Comment by alexcrichton** [comment]
Good question! @rust-lang/tools -- thoughts about whether we're far enough along to implement this change?

**Comment by nrc** [comment]
Could you clarify what exactly the change is? My understanding is that currently if `build = false` and there exists a build.rs in the project root, then we warn and we would change this to a hard error? Or does the warning happen when there is no `build` entry and a `build.rs` file and we would change this to silently accepting?

Is this a backwards incompatible change?

**Comment by alexcrichton** [comment]
@nrc sure yeah, the state of play is this:

* We'd like to automatically infer `build.rs` as the build script
* This is backwards-incompatible to projects which have `build.rs` but it's *not* a build script
* We added the ability to specify `build = false` to `Cargo.toml` to work around this. 
* Cargo currently warns if `build.rs` exists, isn't a build script, and `build = false` is missing.
* Older Cargos will reject `build = false` as an invalid manifest.

The concrete change to make here is to automatically infer `build.rs` as a build script unless otherwise configured. This would also entail removing the warning. Crates which have `build.rs`, it's not a build script, and *haven't* configured `build = false` will likely break.

A [preliminary](https://github.com/rust-lang/cargo/pull/3361#issuecomment-264966015) list of crates with `build.rs` but not having it as a build script were compiled. This may not be an exhaustive list.

**Comment by nrc** [comment]
How does Cargo know if build.rs is a build script or not?

To be clear, this is only crates with build.rs in the root? Or would this break for `src/foo/build.rs` too?

**Comment by alexcrichton** [comment]
Cargo does no inference based on file contents, just location. And yeah it's only `build.rs` at the root (next to `Cargo.toml`), which is quite rare in practice.

Cargo's proposed logic is that if `build.rs` exists next to `Cargo.toml` it's automatically inferred as a build script, no configuration necessary.

**Comment by nrc** [comment]
Thanks for the clarifications!

I think this is OK to go ahead with - we'll have had 2 whole warning cycles and the fix is pretty trivial.
