### ISSUE TITLE
Feature request: `cargo install --upgrade <binary>`

### ISSUE THREAD

**Issue by colemickens** [rust-lang/cargo#3496]
When using `pip`, I can run `pip install --upgrade azure-cli` to get the latest version of the `azure-cli` package built and installed (and thus the `az` binary gets updated if needed as well).

As far as I can tell, there isn't any way to do this with `cargo install` today.

At best, I can use `cargo install --list | grep <Something>` but that doesn't tell me if it's up-to-date.

Alternatively, `cargo install <something> -f` will force re-compile even if the binary is up-to-date and it's unnecessary.

Maybe there could be a `cargo install --upgrade <something>` functionality?

**Comment by alexcrichton** [comment]
I believe this is covered by https://github.com/rust-lang/cargo/issues/2082, but thanks for the report!

**Comment by dhardy** [comment]
Can this be re-opened please? #4981 says it simply uninstalls, then reinstalls.

I have the situation on CI that `cargo install --force` was used to force update, but is slow, sometimes to the point of [timing out the test](https://travis-ci.org/rust-lang-nursery/rand/jobs/347903509#L473).

I'll try [cargo-update](https://crates.io/crates/cargo-update) since --reinstall or --force is not a substitute for a real update command.

**Comment by sfackler** [comment]
How would `--upgrade` solve the problem that compiling cargo-web takes too long? It seems like it would be easier in that case to just pull the prebuilt binary: https://github.com/koute/cargo-web/releases.

**Comment by dhardy** [comment]
It doesn't always take too long. Travis nodes appear to be highly loaded; at least performance is quite variable and normally the build doesn't time out, it's just slow. The current solution using `install-update` works fine, although installing `cargo-update` itself is a bit hacky since it's necessary to quench the error on "already installed" (not an error by most standards).

Another reason to have a `cargo upgrade` option: to allow `--all`.
