### ISSUE TITLE
Using [target.*.dependencies] results in error about crate-type

### ISSUE THREAD

**Issue by ferrouswheel** [rust-lang/cargo#3512]
When using `[target.'cfg(unix)'.dependencies]` in my `Cargo.toml`, and then using `cargo run|test|build` I get a somewhat obtuse error:

    error: failed to learn about crate-type `dylib` early on

If I place the dependency I require directly in `[dependencies]` everything builds fine on linux (but this breaks other platforms).

- rustc 1.14.0 (e8a012324 2016-12-16)
- cargo 0.15.0-nightly (298a012 2016-12-20)

```
$ rustc --print cfg
target_os="linux"
target_family="unix"
target_arch="x86_64"
target_endian="little"
target_pointer_width="64"
target_env="gnu"
unix
debug_assertions
```

Project this occurs with is here: https://github.com/ferrouswheel/rust-sparkline

I currently have the `[target.'cfg(unix)'.dependencies]` bit commented out to get successful builds on travis. You should be able to reproduce by uncommenting that section and removing `lodepng` from `[dependencies]`.

There is an example failure here: https://travis-ci.org/ferrouswheel/rust-sparkline/jobs/189709678 (Note: I would expect that particular build to fail with a compile error, but it doesn't even get to compiling).

**Comment by alexcrichton** [comment]
I attempted to fix this in #3525 but unfortunately that won't work.

The problem here is that `lodepng` depends on a [precise version of `c_vec`](https://github.com/pornel/lodepng-rust/blob/d396d225c4ed9e8adfa1f6bc089d6673775345de/Cargo.toml#L16), and that historical version of `c_vec` was listed with:

```toml
[lib]
crate-type = ["dylib", "rlib"]
```

When Cargo is discovering the list of crate types to learn about it doesn't travel this dependency edge because it's platform-specific and Cargo doesn't know about platform-specific dependencies yet. That means that Cargo ends up not learning about the dylib crate type, but then later on we do indeed need it when compiling `c_vec`.

Unfortunately I'm not sure of the best way of how to solve this...

**Comment by pornel** [comment]
FWIF I've relaxed version of c_vec in lodepng.

but I've ran into the same problem myself with another crate where I need a static library on Windows only. The default (rlib?) doesn't seem to re-export symbols from C (compiled with the gcc build dep).

**Comment by philn** [comment]
I'm also interested in having this issue fixed.

**Comment by alexcrichton** [comment]
@philn @ferrouswheel I think this may be fixed on master versions of `cargo`, mind trying the nightly channel?

**Comment by philn** [comment]
Yes indeed it looks like this is fixed with cargo 0.23.0-nightly (8118b02ac 2017-09-14) at least. Thanks!

**Comment by alexcrichton** [comment]
Ok! In that case I'm going to close

**Comment by Xaeroxe** [comment]
I just ran into this since I hadn't updated my cargo.  Closed 9 days ago.  MRW: ![image](https://media.giphy.com/media/3oz8xtBx06mcZWoNJm/giphy.gif)
