### ISSUE TITLE
Cargo output calls default profile "debug"; in Cargo.toml it's called "dev"

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/cargo#3519]
[We noticed while working on the book](https://github.com/rust-lang/book/pull/373#discussion_r94247879) that it's a little bit strange that the output of `cargo build` calls the default profile "debug":

```
Finished debug [unoptimized + debuginfo] target(s) in 0.30 secs
```

but if you want to change the settings for that profile, in your `Cargo.toml`, it goes under `profile.dev`:

```
# The development profile, used for `cargo build`.
[profile.dev]
opt-level = 0      # controls the `--opt-level` the compiler builds with
...etc...
```

Can we change the output of cargo to match the profile, so that it looks like:

```
Finished dev [unoptimized + debuginfo] target(s) in 0.30 secs
```

Would this break anything?

**Comment by alexcrichton** [comment]
Sounds good to me to change the output! Want to send a PR?

**Comment by jtgeibel** [comment]
I've started looking into this.  It seems that simply updating the if statement at https://github.com/rust-lang/cargo/blob/master/src/cargo/ops/cargo_rustc/job_queue.rs#L200 will affect a lot of tests for other profiles and may blur the current distinction between build profiles and debug/release targets.

The 5 profiles appear to map to default targets as follows:

dev => debug
release => release
test => debug
bench => release
doc => debug

Also note that it is possible to run `cargo test --release` to build a release target of the test profile.  The same goes for `cargo doc --release`.  I do not believe there is a way to `cargo bench` with a debug target.

Most importantly, the target shown in the output matches the subdirectory under `target/` used for build artifacts.  Showing only the profile may create confusion as to which subdirectory the just completed build is stored in.  Would it make the most sense to display both the profile and target in the output line?  For example:

    Finished debug [unoptimized + debuginfo] target(s) for dev profile in 0.30 secs

Adding this info would require me to touch a lot of tests, so I want to make sure this makes sense before proceeding.

**Comment by alexcrichton** [comment]
@jtgeibel hm I wouldn't want the last line to get *too* wordy, but updating tests should be fine, it's just a s/debug/dev/, right?

**Comment by jtgeibel** [comment]
@alexcrichton Yeah, updating the tests is easy.  My point is more that I want to avoid conflating the concepts of targets and profiles.  Right now there are 2 targets (release, debug) and at least 5 profiles (release, dev, test, bench, doc).  It looks like I may have actually missed some profiles originally, such as: check, test_deps, bench_deps, and custom_build.  I'm not yet sure how the latter three are used.

The simplest fix of s/debug/dev/ would cause builds like `cargo test` and `cargo doc` to refer to dev in the output instead of debug (while the actual artifacts would still be found in `target/debug`).

The more complex change of *adding* the profile to the output will require a bit more massaging in the tests (not a problem) but I'm not sure which cases I would want to cover or if the needed information is currently available from `job_queue.rs`.

For now, I'm going to poke around the code some more to get a better feel for how everything fits together.  Longer term, I think we should either leave the output as-is or add additional output to cover the 5 common profiles covered in the `Cargo.toml` documentation (at the risk of making the output more wordy).

**Comment by sanmai-NL** [comment]
As a user, I do not think being a bit more specific as proposed results in being overly wordy here, @alexcrichton.

**Comment by alexcrichton** [comment]
@jtgeibel yeah it's true that internally Cargo has a whole litany of profiles, but most of those are never user facing. The way everyone interfaces with Cargo is through "dev or release" basically, so I think it's fine to just update the printing here to show dev instead of debug
