### ISSUE TITLE
Print build error while other jobs finish

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/cargo#3536]
When something goes wrong, Cargo prints
```
Build failed, waiting for other jobs to finish...
```
Then it does wait until everything finishes, and only then it prints the error message that it already knew about during that time. Meanwhile, I’m staring at it instead of starting to fix the issue since I don’t know yet what the issue is.

Could Cargo print the output of a failed job without waiting for other jobs to finish? (But still wait for those before exiting itself.)

**Comment by alexcrichton** [comment]
I believe what's happening here is that the output Cargo prints after this is all contained in the [returned error object](https://github.com/rust-lang/cargo/blob/6291619896fc6a83d619945148670b6420aa06ec/src/cargo/ops/cargo_rustc/job_queue.rs#L185) which is then printed way later in the stack once the error bubbles up to the very top. Naturally that takes awhile because we wait for other jobs to finish.

That being said it seems totally reasonable to me to print out the error immediately and then return a *different* error just saying "build failed". Should be a relatively easy bug to knock out for anyone interested!

Should b

**Comment by dgellow** [comment]
Hi guys. I want to contribute and this issue seems easy enough as a way to start.
How can I reproduce it?

**Comment by SimonSapin** [comment]
Hi @dgellow. Thank you for volunteering! I haven’t tried it, but I think something like this can reproduce:

* A "root" crate A that has two dependencies: B and C
* B contains invalid Rust code which causes a build error
* C has a build script that calls `std::thread::sleep` to make it wait a few seconds before exiting.

In current Cargo, building A should quickly show "Build failed, waiting for other jobs to finish...", then hang for a few seconds, then show the error message from B. In a Cargo that fixes this issue, the error message should we shown quickly and the build only hang after that.

Unfortunately, making this an automated test seems tricky.

**Comment by dgellow** [comment]
Ok 👌

**Comment by dgellow** [comment]
I was able to reproduce it following your instructions. I'll see if I can make the change you asked for :)

**Comment by dgellow** [comment]
What kind of error I am supposed to return?
I cannot find anything relevant in `cargo/util/errors.rs`.

**Comment by alexcrichton** [comment]
@dgellow you can create errors via the `human` function or the `bail!` macro (examples throughout the repo)

**Comment by dgellow** [comment]
Ok, I have something that works.

![screen shot 2017-01-25 at 18 23 52](https://cloud.githubusercontent.com/assets/2451004/22301615/ef8fe3be-e32b-11e6-8e51-d12ee3261e1f.png)


I think you will ask for some tests, any idea how I can test something like this?

**Comment by alexcrichton** [comment]
Eh it's probably ok to elide tests b/c this relies on a race condition, so I'm ok with just a manual audit.
