### ISSUE TITLE
Add a mode in which the cargo lock is disabled if it's known that cargo doesn't have to download/install anything

### ISSUE THREAD

**Issue by bzbarsky** [rust-lang/cargo#3594]
See https://github.com/servo/servo/issues/12984 for a situation in which this would be useful.

**Comment by alexcrichton** [comment]
Hm so in general this isn't possible because Cargo always needs a lock file to figure out what to build (e.g. some resolution of all the dependency constraints).

That being said, https://github.com/servo/servo/issues/12984 is a bug that should definitely be fixed! (perhaps just not through literally these means though).

IIRC we relaxed the locking scheme around git checkouts in Cargo awhile back, but it may not have been picked up by Servo maybe? Do you know what version of Cargo Servo is using?

**Comment by bzbarsky** [comment]
> IIRC we relaxed the locking scheme around git checkouts in Cargo awhile back

Oh.  Clearly, I should have retested this in a more recent servo before filing!  With a current tip servo checkout, the problem is gone.

Sorry for the noise...

**Comment by alexcrichton** [comment]
No worries! Thanks regardless for the report :)
