### ISSUE TITLE
cargo.exe, rustc.exe

### ISSUE THREAD

**Issue by Radu13** [rust-lang/cargo#3631]
Hey guys
I install rust and cargo last build, but when i open one of the executable, they quickly close without error code.
What's happening?

**Comment by alexcrichton** [comment]
When you say open, do you mean click on? These are intended to be command line applications so you'd have to run them in a terminal. Otherwise if an error dialog shows up then it may be related to missing DLLs, specifically the MSVC redistributables. Depending on what's happening, I can help point you in the right direction for the DLLs at least!

**Comment by Radu13** [comment]
I solved it, i needed nightly version of rust

**Comment by alexcrichton** [comment]
Ok glad it worked out!
