### ISSUE TITLE
Don’t rebuild dependencies in 'cargo publish'

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/cargo#3656]
Before publishing, `cargo publish` builds the newly packaged crate to make sure it can build correctly. This is good. But in doing so, it also rebuilds all of the crate’s dependency graph, even if a previous `cargo build` or `cargo test` run already did.

Could Cargo make it so that the build output of the crate being published (and maybe path dependencies) is not shared, but that of other dependencies is?

**Comment by matthewkmayer** [comment]
I'll give more details to my thumbs-up: in [Rusoto](https://github.com/rusoto/rusoto) we have about 75 crates that share many dependencies.  To publish them all, every crate recompiles all of its dependencies, even though they've already been compiled.  For example, if we were to publish two crates, `rusoto_sqs` and `rusoto_ecs` we'd run:

`cargo publish` in the `sqs` directory, then `cargo publish` in the `ecs` directory.  They both depend on `hyper` and `hyper` and all its dependencies get built for SQS, then ECS.

This manifests as a multi-hour build every time we publish a new version of Rusoto services.  If cargo could determine it already built that exact dependency it'd greatly speed up our release time. 👍

**Comment by scruffystuffs** [comment]
I just ran into this and I'd like to take a look at it.  New to cargo dev, so I'm not sure what I'll run into, but I'll see if we can't reuse the same logic from `cargo build`.

**Comment by scruffystuffs** [comment]
Ok, looked into it.  Looks like we rebuild because the build is part of a verify stage which uses an ephemeral workspace, instead of the pre-existing one.  [This comment](https://github.com/rust-lang/cargo/blob/12c107ade5a3b173cdac5d06c8ba92429fe93c74/src/cargo/ops/cargo_package.rs#L667-L668) gives a brief explanation.

Seems like we could copy the existing build output files into the new workspace and make use of `ops::compile_with_exec`'s existing caching features.  Also looks like this can be avoided by running with the `--no-verify flag`, but that skips the check for `build.rs` modifying files in the `src/` directory.

I have no idea what we should or shouldn't copy between the workspaces, so I'll put up a PR that moves everything, which should prove the concept.  Then we can haggle over details about what's safe to move.

**Comment by scruffystuffs** [comment]
Also, it looks like there's more discussion over on #4109.  Since that issue has more activity, should this one be closed?

**Comment by briansmith** [comment]
The difference between this issue (#3656) and the other (#4109) is that this issue (#3656) is only requesting that the dependencies not be re-compiled, whereas the other (#4109) is also asking that the crate itself be re-compiled. I left a comment at https://github.com/rust-lang/cargo/issues/4109#issuecomment-739061597 about why it is harder than it might first seem to avoid compiling the crate itself. I do think that it would be good to avoid recompiling the dependencies, but note that Cargo.lock is ignored during the recompilation.

I believe the right thing to do is have `cargo package`/`cargo publish` error or warn if the Cargo.lock isn't up to date with the very latest versions of all the dependencies. Then presumably the user would `cargo update` and then `cargo test` which would build all the dependencies. Then when they `cargo publish`/`cargo package` again, that build should re-use the cached builds of the dependencies.

**Comment by epage** [comment]
This is an area where #5931 could help.

**Comment by epage** [comment]
While there are minor differences (local vs non-local) I think this and #4109 are close enough that we should be having the conversation in one place and make one decision about what we do.  Closing this in favor of #4109.
