### ISSUE TITLE
Print & color build script warnings, even when build script panics

### ISSUE THREAD

**Issue by mystor** [rust-lang/cargo#3672]
Currently, when the build script panics, the stdout of the build script is written out to show what happened. However, this means that any warnings emitted during the build script (using cargo:warning= from #2630) won't be printed nicely like they are when the build script succeeds.

It would be nice if these warnings could be printed prettily even when the build script fails to execute due to a panic.

**Comment by alexcrichton** [comment]
Seems reasonable to me! Do you have a preference either before or after the standard error output?

**Comment by mystor** [comment]
I feel like putting the warning before the panic dump is a good idea, because conceptually the warnings were "emitted" by the build script before the build script "emitted" the panic. I'm open to other options though.

**Comment by alexcrichton** [comment]
Seems reasonable to me. Unfortunately I probably won't have time to implement this in the near future, but I believe the relevant loop is [this one](https://github.com/rust-lang/cargo/blob/c5679e21ef8c7deabce3911ce04ead338ff063be/src/cargo/ops/cargo_rustc/job_queue.rs#L139-L199). We likely just need to listen for more messages coming on  `self.rx` and print them out in the same fashion.

**Comment by aleksator** [comment]
I did some investigation on this and here's what I've found:

[The warnings get printed in emit_warnings() from `build_script_outputs` variable](https://github.com/rust-lang/cargo/blob/c67cd7a1a2f13868fe1a7ee03fc326eca3f1b0e6/src/cargo/core/compiler/job_queue.rs#L864), but when build script panics it is empty. Since it does not contain warnings or anything else, nothing gets printed at this point.

As to why that happens:
[`build_script_outputs` gets filled in `build_work()` function](https://github.com/rust-lang/cargo/blob/b8ab32ea31ba7b86c94aad041ead180ee0e63b73/src/cargo/core/compiler/custom_build.rs#L386-L389), but when a panic happens [an error is thrown in `exec_with_streaming()`](https://github.com/rust-lang/cargo/blob/e84a4ed6d02293034380761461b09241488070fe/src/cargo/util/process_builder.rs#L293-L297), so [`build_work()` quits early on question mark here](https://github.com/rust-lang/cargo/blob/b8ab32ea31ba7b86c94aad041ead180ee0e63b73/src/cargo/core/compiler/custom_build.rs#L362) and filling of `build_script_outputs` isn't reached.

The output with warnings is still [contained inside the error returned by `exec_with_streaming()`](https://github.com/rust-lang/cargo/blob/e84a4ed6d02293034380761461b09241488070fe/src/cargo/util/process_builder.rs#L296) and is printed later in stack trace in a raw form of  `--- stdout cargo:warning=*warning from build script*`.

At this point I would like to get the team's input on what would be the cleanest way to push warnings into `build_script_outputs` in unhappy path, and whether we would need to solve the resulting duplication of warnings in colored and raw forms.

**Comment by ehuss** [comment]
Yea, that's a little awkward.  I think what I would do is inside the [`stdout` callback](https://github.com/rust-lang/cargo/blob/b8ab32ea31ba7b86c94aad041ead180ee0e63b73/src/cargo/core/compiler/custom_build.rs#L354-L358), check for lines that start with `cargo:warning=` and stash the line into a Vec of warnings.  If `exec_with_streaming` returns an error, it can take those warnings and generate an empty `BuildOutput`, and set the `warnings` field and insert the `BuildOutput` into the map.  I think that should then get picked up by emit_warnings, but not interfere with anything else.

Also, an unrelated thing: it might be nice for build script warnings to be prefixed with the package name/version (the same way it is prefixed with `-vv`).  I notice that the warning doesn't indicate where it comes from, so that might be useful.

**Comment by aleksator** [comment]
@ehuss I've done the suggested implementation

> Also, an unrelated thing: it might be nice for build script warnings to be prefixed with the package name/version (the same way it is prefixed with -vv). I notice that the warning doesn't indicate where it comes from, so that might be useful.

Maybe worth creating a separate issue for this?

**Comment by ehuss** [comment]
> Maybe worth creating a separate issue for this?

Sure, posted #8018.
