### ISSUE TITLE
cargo install does not respect LDFLAGS

### ISSUE THREAD

**Issue by ChrisMacNaughton** [rust-lang/cargo#3694]
When the building system has LDFLAGS set, cargo / rustc should respect the system's LDFLAGS

**Comment by alexcrichton** [comment]
Right now Cargo respects RUSTFLAGS but that's the only env var for passing flags down. What sort of LDFLAGS are you thinking of?

Note that the exact linker that the compiler invokes isn't guaranteed to *not* change over time, so there's not always a valid interpretation of LDFLAGS even if it exists.

**Comment by sergiusens** [comment]
where are `RUSTFLAGS` documented? The linker flags we want to pass on are runpath/rpath related as well as the one that sets the linker loader the binary should use.

**Comment by alexcrichton** [comment]
@sergiusens it's [documented here](http://doc.crates.io/environment-variables.html#environment-variables-cargo-reads)

**Comment by ChrisMacNaughton** [comment]
expanding a bit on this, some issues we're having with getting this working: https://gist.github.com/ChrisMacNaughton/a81233e05995013ebb9a0c333c157b76

**Comment by paugier** [comment]
A simple question related to this issue.

I need to send the options `-Wl,-rpath,/data0/opt/miniconda3/envs/env_hg_rust/lib -Wl,-rpath-link,/data0/opt/miniconda3/envs/env_hg_rust/lib` to the linker.

Is it possible to do that with an environment variable (I don't control the cargo or rustc command)?

I can use `RUSTFLAGS` for things like `-L/data0/opt/miniconda3/envs/env_hg_rust/lib` but what about more advanced linker options?

**Comment by adam-azarchs** [comment]
I'm running into a related issue - we have `--coverage` (amongst other things) set in our `CFLAGS`.  For some build script builds this is resulting in link errors such as `undefined symbol: llvm_gcov_init` because `--coverage` isn't also being passed to the link step as well.  Leaving aside the question of whether or not `CFLAGS` should be having an effect on a build script build, there are several similar flags which will cause problems if used in `CFLAGS` (which usually applies because it's consumed by something like `cc::Build` in a build script) but not in `LDFLAGS`, for example `-fopenmp` or `-flto`.  Particularly in a context where `cargo` is being used as one step in a larger build process, honoring `CFLAGS` but not `LDFLAGS` can cause all kinds of problems.
