### ISSUE TITLE
[WINDOWS 10] `cargo install` fails with "filename, directory name, or volume label syntax is incorrect"

### ISSUE THREAD

**Issue by bddenhartog** [rust-lang/cargo#3787]
**Steps to reproduce**

- Install Windows 10 Pro
- Install rust via `rustup-init.exe` from the [official installation page](https://www.rust-lang.org/en-US/install.html)
- Run `cargo install --verbose rustfmt`

```
$ cargo install --verbose rustfmt
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: [2/-3] Could not find 'C:/Users/Username/;C:/Users/Username/;C:/Users/Username//.git-templates/' to stat: The filename, directory name, or volume label syntax is incorrect.
```

**Comment by alexcrichton** [comment]
Hm do you have a preexisting installation of git somewhere perhaps? It looks like something's getting picked up by libgit2 which it doesn't like.

**Comment by bddenhartog** [comment]
`git`-related things I have installed:

- `git` (for windows) installed from `git-scm.com`
- `git-lfs` (for windows) installed [from the github repository](https://github.com/git-lfs/git-lfs)
- `Microsoft Git Credential Manager for Windows`, installed [from the github repository](https://github.com/Microsoft/Git-Credential-Manager-for-Windows)

**Comment by alexcrichton** [comment]
Do perhaps have a configuration for a template store as well? That's what the error message seems to indicate at least?

**Comment by bddenhartog** [comment]
Well, yes, I have `init.templatedir` set to `$HOME/.git-template`. The contents in this directory are copied to the repository (if they don't exist) when the command `git init` is executed. This is a standard feature of `git`.

**Comment by alexcrichton** [comment]
Could you try commenting out that configuration to see if it's at fault?

**Comment by bddenhartog** [comment]
That seems to fix the issue - I can successfully run `cargo install --verbose rustfmt`, which downloads the dependencies and compiles successfully.

I'm not familiar enough with Rust or with the Cargo project to feel comfortable applying a patch myself without guidance, but one approach to fix this might be to reassign the `init.templatedir` value on a per-command basis:

```text
git -c init.templatedir="" <command>
```

You could, of course, also store the value, blow it away entirely via `git config --global --unset init.templatedir`, and reset it later on.

**Comment by alexcrichton** [comment]
Thanks for testing, this is very useful information! FWIW the OP was pretty confusing as it makes no indication of git being installed (or even git configuration), but that turned out to be quite important in reproduction.

Ok, though, now that we've identified the problem let's see how to fix it. If this is a bug it's likely to be in libgit2, the git library that Cargo uses for interfacing with git repositories. If the value of `init.templatedir` is `$HOME/.git-templates` then somehow libgit2 is going from that to `C:/Users/Username/;C:/Users/Username/;C:/Users/Username//.git-templates/` and attempting to look inside it. That looks more like a value in `PATH` so I'm not really sure where that would come from. Do you have any ideas?

It may also be worth poking around on libgit2's issue tracker and/or repo, they may have some indications about a bug here perhaps.

**Comment by carols10cents** [comment]
I looked at https://github.com/libgit2/libgit2 a bit and didn't see any issues related to `$HOME` being mis-expanded :-/

@bddenhartog Given this issue is rather stale at this point and lots of things may have changed, I'm going to close this. If this is still a problem, please open an issue with libgit2 since it seems as though the root cause is `init.templatedir` set to `$HOME/.git-template` but libgit2 expanding it to `C:/Users/Username/;C:/Users/Username/;C:/Users/Username//.git-templates/`. Thanks!

**Comment by bddenhartog** [comment]
@carols10cents sounds good to me!
