### ISSUE TITLE
List of default dependencies for all projects

### ISSUE THREAD

**Issue by SRGOM** [rust-lang/cargo#3793]
SBT has a list of default dependencies that are automatically included in all projects. I add a lot of debug related stuff there when I'm quickly starting on new stuff before any clean up. I'd love it if Rust had it too.... It's in `~/.sbt/0.13/global.sbt` if it matters.

**Comment by alexcrichton** [comment]
The recently landed [templates feature](https://github.com/rust-lang/cargo/pull/3004) may help here as well?

**Comment by SRGOM** [comment]
@alexcrichton Wow, that's  really nice feature. So I'm not familiar with any templating frameworks but it looks to me that one can create/use pre-created templates to generate files related to each project, including `Cargo.toml`. That sounds like a big deal. 

It actually does handle the usecase I mentioned in my original post ("...quickly starting on new stuff..."). 

However, the template feature requires one to manually add new crates to the projects already created, no way for a project to automatically reuse new dependencies.

Maybe I'll tell you about my workflow with sbt.

> Quickly cook up some scala code, no `build.sbt` in the directory.
> The following are added to my global.sbt already: 
> "com.lihaoyi" %% "pprint" % "0.4.3" (added yesterday)
> "com.lihaoyi" %% "sourcecode" % "0.1.2" 
> Use pprint.pprintln( ... ) in my code.
> Do `sbt run`
> I didn't even have to create a new project/file hierarchy.

> Go to project B. Already has it's own build.sbt (from 2 weeks back)
> using pprint.pprintln(... )
> `sbt run`

I can do quick and dirty stuff efficiently. 

I'm given to understand that the Rust team is very very busy and I'd rather have member variables in traits than this but figured I'll mention this so it can be tackled as a low priority if you guys like the idea.

**Comment by alexcrichton** [comment]
@SRGOM yeah I don't think it'd work precisely like that but in general the *precise same workflow* probably won't translate to Cargo (as it's designed differently)

**Comment by ehiggs** [comment]
The `quickstart` and `docopt` project here are good starts: https://github.com/rusttemplates

**Comment by aturon** [comment]
@SRGOM So in general we strive for `Cargo.toml` to contain *all* the information necessary to build a project, and this would be a bit of a departure from that.

However, what matters most is the Cargo.toml that gets published to crates.io, and it seems feasible to "inline" default dependencies during publication, if we did want this feature.

@alexcrichton To clarify, what @SRGOM is looking for is not really like templates, but more like an "include" file for the dependencies section of Cargo.toml. The key difference being that, if you edit the thing being included, that's reflected in all the projects.

@SRGOM note, however, that this kind of feature ends up raising a whole bunch of design questions, e.g. what happens if you end up with the same dependency listed in the default dep list and in the current project -- with different version ranges?

My sense is that this is a bit too niche of a workflow to justify adding it in addition to templates at this time. (However, @SRGOM, if you did want to pursue, working out a complete design and implementation would be a good step forward, and I can try to get you some mentoring help if you're interested).

I'm going to close in the meantime.

**Comment by SRGOM** [comment]
Sorry for being late here. Yes, @aturon you're right, this is very exactly what I'm trying to achieve. I understand your explanation and agree that this is a very niche problem. Okay to close, I wouldn't be able to help right now.. Thanks for discussing @alexcrichton and @aturon
