### ISSUE TITLE
Documentation on how to use cargo lib to find target directory

### ISSUE THREAD

**Issue by vityafx** [rust-lang/cargo#3829]
I want to create a external cargo subcommand. I've checked few existing external subcommands and they are using cargo, but very old one. I have tried to find any information about how can I use the cargo crate for, for example, finding `target` directory, but I was unable to find such information anywhere. After that I decided to find any information about the `cargo` crate but I could not: it does not exist it seems.

A few questions:

1. Why is it so?
2. How to find any information about it then?

**Comment by alexcrichton** [comment]
Thanks for the report! The crate isn't really intended to work well with newbies unfortunately right now in the sense that little-to-no effort has been put in to make it such (not that it can't be).

PRs with docs however would be most welcome!

**Comment by dwijnand** [comment]
Does this mean Cargo's programmatic API is meant to be backwards compatible?

**Comment by dwijnand** [comment]
> Does this mean Cargo's programmatic API is meant to be backwards compatible?

From https://github.com/rust-lang/cargo/issues/5955#issuecomment-417723058 and https://github.com/rust-lang/cargo/issues/5839#issuecomment-411008471, no, it's not.

**Comment by weihanglo** [comment]
Going to close this since I don't think we need an issue to track a specific API item.

For the past months, the Cargo team has been working on improving the API documentation. We moved parts of contributors docs to rustdoc (e.g., #11662, #11809, #11850), and added more intra-doc links (e.g., #11711, #12133). 

For my personal interest, I'd like to see more high-level concepts get documented, such as `Source` and `Resolver`.

Thank you for the report anyway!
