### ISSUE TITLE
Managing dependencies of crates inside a workspace

### ISSUE THREAD

**Issue by MaikKlein** [rust-lang/cargo#3931]
### Workspace Foo
* Crate A depends on `Bar`
* Crate B depends on `Bar`
* Crate C depends on `Bar`
* Crate D 

Where `Bar` is an external dependency that I also maintain. When I want to update to a newer version of `Bar`, I would have to change 3 Cargo.toml files, which is a bit cumbersome. It would be nice if I could specify the dependency in one place. Is this possible?

**Comment by alexcrichton** [comment]
Ah yes currently this isn't possible I believe. You can use something like `[replace]` during development but for actual publication the relevant Cargo.toml files all need to be updated individually

**Comment by jechas01** [comment]
I've got a similar use case, though I don't actually control the duplicated dependency, and I've got a bunch of them.

The obvious solution, to me at least (and anyone who's worked on a large maven project), seemed to be some sort of variable substitution a la #4221, but it looks like that's a no-go. From that conversation:

> we'd rather work on enhancing workspaces to support using one version of a crate across the workspace.

Is anything of that sort in the works?

My current (not very good) solution is to throw all external dependencies into a dedicated crate that then re-exports them so that they're at least all in one place. The downside is that now all of the external crates get built whenever any of my crates gets built, even if it needs only a subset, and it works poorly for macros, even with the accidentally-stabilized macro-reexport function.

I've looked into cargo-outdated and cargo-edit, but both seem more concerned with making sure that things are up-to-date, when I really care more about making sure that all of my crates *agree* on dependency versions.

**Comment by viktorchvatal** [comment]
What about changing Cargo to allow specifying dependencies and their settings like version, etc., in workspace Cargo.toml? These could be used as default parameters for dependencies in inner crates.

Workspace Cargo.toml could have default versions specified
```
[dependencies]
log = "0.3.9"
```
All inner crates could inherit version from workspace just by omiting version at all
```
[dependencies]
log = {}
```
or specify any other dependency version for the crate
```
[dependencies]
log = "0.4.5"
```

**Comment by sanmai-NL** [comment]
@alexcrichton:
> Ah yes currently this isn't possible I believe. You can use something like [replace] during development but for actual publication the relevant Cargo.toml files all need to be updated individually.

Why? Can you explain please? :slightly_smiling_face:

**Comment by alexcrichton** [comment]
For anyone interested in this issue I've [posted an RFC](https://github.com/rust-lang/rfcs/pull/2906) which I think will help resolve this. Feedback on the RFC would be most welcome!

**Comment by Igosuki** [comment]
This is called dependencyManagement in maven, it's a common feature of many build tools.

**Comment by mike-wilson-hudson** [comment]
Update for those landing here from a google search: @alexcrichton 's RFC (https://github.com/rust-lang/rfcs/pull/2906) was accepted and the tracking issue https://github.com/rust-lang/cargo/pull/8664 has serious momentum and is close to complete.

**Comment by tristanpemble** [comment]
[this is now supported in Cargo v1.64](https://doc.rust-lang.org/nightly/cargo/reference/specifying-dependencies.html#inheriting-a-dependency-from-a-workspace)
