### ISSUE TITLE
cdylib on Windows provides only the .dll without the associated .lib import library

### ISSUE THREAD

**Issue by cpralea** [rust-lang/cargo#3934]
On Windows, runing `cargo build` on a cdylib crate produces only the .dll in `target/{debug,release}` while the associated .lib import library is missing.

However, the following files are present under `target/{debug,release}/deps`:
- `<name>-<hash>.dll`
- `<name>-<hash>.dll.lib`
- `<name>-<hash>.dll.exp`
- `<name>-<hash>.pdb`

The cargo and rustc versions in use are:
- `cargo-0.17.0-nightly (f9e5481 2017-03-03)`
- `rustc 1.16.0 (30cf806ef 2017-03-10)`

(originally opened as https://github.com/rust-lang/rust/issues/41393)

**Comment by retep998** [comment]
The import library is hardcoded to the name of the dll at the time of linking, so since cargo tells rustc to tell the linker to name the dll `<name>-<hash>.dll`, that means the import library is hardcoded to `<name>-<hash>.dll`. Considering the user actually wants to have `<name>.dll`, this is a major blocker towards being able to use cdylibs. Cargo needs to *seriously* rethink how it handles naming output artifacts.

cc @alexcrichton
