### ISSUE TITLE
`cargo-check` doesn't wait for children on SIGTERM

### ISSUE THREAD

**Issue by fuine** [rust-lang/cargo#3950]
This is a possible duplicate of #2343 and #2525. To reproduce issue `cargo check` in project with several dependencies, with `target` directory initially removed. As `cargo` compiles dependencies send `SIGTERM` to the `cargo-check` process. On my machine this causes the process to exit to shell with the message `[1]    6350 terminated  cargo check`, but the messages from dependencies compilation appear, conflicting with the shell prompt. This issue is a plausible cause of the bug neomake/neomake#1216, which results in zombie processes and blocked repository. As I understand it this should not happen, and the parent process should wait for the children to finish, possibly signaling them to abort their work, but correct me if I'm wrong, as I don't know much about `cargo`'s internals.

**Comment by alexcrichton** [comment]
Thanks for the report! This is, however, intentional. Editors and IDEs that want to kill all of the processes that Cargo spawns should use `setsid` to place Cargo into its own process group, and then kill the process group (that's the typical way to do this on Unix).

Let me know though if you need assistance with that!
