### ISSUE TITLE
confusing error message when cargo build --all is run in the root of an empty virtual workspace

### ISSUE THREAD

**Issue by shahn** [rust-lang/cargo#3966]
I have a virtual workspace with a bunch of crates beneath it. The documentation states that that specifying members in the manifest is optional, and membership will be inferred if it's missing. This seems to be incorrect, as running `cargo build --all` in such a setup fails with the message `manifest path `<path/to>/Cargo.toml` is a virtual manifest, but this command requires running against an actual package in this workspace`. Compiling a crate beneath the root directory also gives the error message that the crate believes it is in a workspace, but it's not listed in members. I think the easiest fix is to clearly state that members is not in fact optional at all if you have any actual members, but the error message should also probably be improved to say that we simply didn't find any workspace members to build.

**Comment by alexcrichton** [comment]
Yeah I think we need to fix commands like `--all` to work against all manifests in a workspace, regardless of whether it actually contains targets or not.

This may require some internal refactorings, within Cargo, though, to support such a use case.

**Comment by RalfJung** [comment]
I just ran into this as well, with plain `cargo build` (no `--all`) and an empty `[workspace]` section. I first thought this means that I have to `cd` to the right directory, but adding `members = ["dir/here"]` fixed the problem.

So the error message is not just confusing, it is plain wrong: `cargo build` works just fine with a virtual manifest (assuming this means "a manifest not containing a project itself"). It just doesn't work with automatically inferred workspace members. I am rather confused now, TBH, because I thought without `--all`, it should not ever build other workspace members?
