### ISSUE TITLE
Imply `--all` argument for virtual manifest.

### ISSUE THREAD

**Issue by matklad** [rust-lang/cargo#4021]
If I run `cargo build` in a workspace, I often get:

```
error: manifest path `/home/user/projects/fall/Cargo.toml` is a virtual manifest, but this command requires running against an actual package in this workspace
```

The fix is to run `cargo build --all` instead. I think Cargo can figure this out automatically? 

If the current package is virtual, and we are running one of `--all` enabled commands, `--all` should be the default.

The fix would involve changing [this logic](https://github.com/rust-lang/cargo/blob/80f19a8e240577d90caf38503bb3034ac7dd630d/src/bin/check.rs#L83-L96) in all relevant commands (there's quite a bit of duplication:( ).

**Comment by alexcrichton** [comment]
👍

**Comment by rsertelon** [comment]
I've started to try to implement this. However, as I said in #4016, I'm a rust beginner and my code might not be idiomatic ;)

What I've tried for now is creating a method in `cargo::core::Workspace` to know if it's virtual or not, then simply used this method in the check for the `--all` flag. Like so:

```rust
pub fn is_virtual(&self) -> bool {
    match *self.packages.get(&self.current_manifest) {
        MaybePackage::Package(ref p) => false,
        MaybePackage::Virtual(..) => true
    }
}
```

and then instead of
```rust
let spec = if options.flag_all {
 // ...
}
```
I have this:
```rust
let spec = if options.flag_all || ws.is_virtual() {
 // ...
}
```

Does it seem sound to you? Or is there a better way for the `is_virtual()` method?

At first I thought of using the existing `current_opt()` method (and use the `is_none()` method of `Option`), but I thought the meaning of it wouldn't be explicit enough and might cause bugs somehow one day...
