### ISSUE TITLE
Look up crate directories by semantic version

### ISSUE THREAD

**Issue by infinity0** [rust-lang/cargo#4061]
At the moment cargo local directory registries [1] can support looking up a crate either by its name or its full version. It would be good if cargo could support looking them up by semantic version as well, then [cargo-vendor](https://github.com/alexcrichton/cargo-vendor) could add an option to generate directories like this.

This would make packaging rustc easier, since it would easier to spot incompatibilies between the vendored sources of different rustc versions (or other rust tarballs with "vendored" sources).

For example, if cargo wants foo-1.2 it would search for vendor/foo-1.2, vendor/foo-1, then finally vendor/foo. If cargo wants bar-0.4.5 it would search for vendor/bar-0.4.5, then vendor/bar.

Then `cargo-vendor`, when given a `--semantic-version` flag, would put (foo-1.2, foo-1.3, foo-0.4) in (vendor/foo-1.2, vendor/foo-1, vendor/foo-0.4).

[1] by that I mean the "replace-with" stuff, I don't know the proper term for it

**Comment by infinity0** [comment]
For the second case, if semantic versioning is being followed then everything should "still work" when one deletes the vendor/foo-1.2 directory.

**Comment by alexcrichton** [comment]
Thanks for the report! I think there's a few things here we may need to disentangle. The `cargo-vendor` subcommand actually lives in a [different repo](https://github.com/alexcrichton/cargo-vendor) rather than here (but not sure if this bug is for there). Additionally Cargo doesn't actually support just these two directory styles, it's just what `cargo-vendor` outputs today. A directory source in Cargo (where you're using vendored sources) doesn't actually care at all what the directory name is, it's irrelevant for loading crates. Instead Cargo will look at the `Cargo.toml` contained within and work with that.

Given that info,

> At the moment cargo local directory registries [1] can support looking up a crate either by its name or its full version. It would be good if cargo could support looking them up by semantic version as well, then cargo-vendor could add an option to generate directories like this.

The first part of this isn't quite true, so is this basically a bug for cargo-vendor to generate different directory names? If so that sounds ok to me!

**Comment by infinity0** [comment]
Oh ok, thanks for the correction. I'll go file this over at cargo-vendor, in that case.
