### ISSUE TITLE
Autobins, autotests, etc should respect gitignore

### ISSUE THREAD

**Issue by edmccard** [rust-lang/cargo#4184]
I like to put `scratch.rs` in .gitignore so I can have a `src/bin/scratch.rs` or `examples/scratch.rs` for running quick experiments, etc. in crates under development. It would be nice if `cargo test` (and probably any subcommand that should only be working on files that will be included by `cargo publish`) would respect .gitignore and, for example, not fail if there are errors in my `scratch.rs` file.

**Comment by weihanglo** [comment]
Triage: this is not only for `cargo test` test targets but all Cargo tests. This is not yet accepted but from the implementation perspective it is perhaps not really hard to get it done.

**Comment by epage** [comment]
Its unclear if the more meaningful request is for having `package.auto*` respect `.gitignore` or should respect `package.includes` / `package.excludes`.  I think the latter is more meaningful and correct.

The original request sounds like it wants inconsistent results.  They apparently want `.gitignore`d files to sometime be used by cargo so they can use this `scratch.rs` but at other times, have it not be used.  I can't think of a universal policy we could support with that but it'd need to be environment configuration (`.cargo/config.toml`).  I say environment rather than project (`Cargo.toml`) because this seems to be context sensitive to the user.

Even if the user actually wants consistent results, there are valid use cases for having targets that are excluded from packaging, like development-only targets that they don't want made available to `cargo install`.

I'm going to propose to the cargo team that we close this.  If there is a reason we should reconsider, let us know!

**Comment by weihanglo** [comment]
Second and close
