### ISSUE TITLE
Error message and docs for [replace] are misleading

### ISSUE THREAD

**Issue by nrc** [rust-lang/cargo#4212]
e.g., Cargo.toml:

```
[workspace]
members = [
    ...
]

[replace]
"rls-data" = { path = "data" }
```

The error here is that the package id is missing a version number (changing `rls-data` to `rls-data:0.7.0` fixed the problem). However, the error cargo gives is "no `package` or `project` section found.".

The documentation here is confusing too: [this section](http://doc.crates.io/manifest.html#the-replace-section) states "Each key in the [replace] table is a package id specification" where "package id specification" links to http://doc.crates.io/pkgid-spec.html where the version appears optional, both in the grammar and the examples.

**Comment by alexcrichton** [comment]
I believe this error comes from [this location](https://github.com/rust-lang/cargo/blob/534ce68621ce4feec0b7e8627cfd3b077d4f3900/src/cargo/util/toml.rs#L97-L166) where the logic looks like:

* Parse as a "real manifest"
* If that fails, parse as a "virtual manifest"
* If that fails, return the first error

It turns out in this situation both parsings fail, but the latter error is more relevant than the first, so we're throwing away the wrong error!
