### ISSUE TITLE
Variable substitution in cargo.toml

### ISSUE THREAD

**Issue by stepancheg** [rust-lang/cargo#4221]
While working with Cargo, editing version numbers is a bit annoying.

For example, I have a repository with two crates:

```
aaa version = 0.1.2
bbb version = 0.1.2 depends on aaa version = 0.1.2
```

When I incrementing version number, I need to edit version several times, which is as i said, annoying, because I constantly forget to update one of several version fields.

What think could solve this problem is something like substitution variables declared in `[workspace]` section. E. g.

```
[workspace.vars]
v = "0.1.4"
futures_v = "0.1"
```

```
version = "${v}"
[dependencies]
bbb = { path = "../aaa", version = "=${v}" }
futures = "${futures_v}"
```

**Comment by locka99** [comment]
I'm running in to a similar issue. I have a [workspace ](https://github.com/locka99/opcua/blob/master/Cargo.toml) with 7 sub configs. There a quite a bit of duplication in these files since crates share the same meta info, version, and some external and internal dependencies. Some of the duplication could be solved by using substitution variables or pushing up some of the values to the top level. 

It would certainly make packaging and publishing easier if I could just bump a number up in one file instead of doing it over many.

**Comment by ashleygwilliams** [comment]
hey @stepancheg thanks for filing this! in order to proceed with this, the team would need to decide whether this is a feature we would want to accept. 

@carols10cents is gonna throw this on the team agenda to discuss it! we'll follow up after that.

**Comment by carols10cents** [comment]
We discussed this in the cargo meeting, and we agree that it's is annoying to have to update the version number in multiple places. 

However, we don't think supporting variables in Cargo.toml is a great solution to this problem-- we'd rather work on enhancing workspaces to support using one version of a crate across the workspace.

Additionally, if you *do* want to have variables interpolated into your Cargo.toml, it's possible to do this with a tool external to cargo that would be run before building. 

So we don't think adding variable interpolation is something cargo should support. Thank you for the issue though! 🌞

**Comment by mieubrisse** [comment]
Just wanted to add a +1 to this old thread, since I'm hitting the same issue - when you have two crates that need the same version, you have to remember to keep them in sync. Java's Gradle has the `gradle.properties` file that gets sourced automatically for interpolation use in the `build.gradle` file; it'd be really cool to have something like this in Rust.

**Comment by locka99** [comment]
The workaround I use now is to use comments like this in all my crates:

```
version = "0.9.0" # OPCUARustVersion
```

Then it's relatively easy to search and replace on `0.9.0" # OPCUARustVersion` and change it to a new value.

**Comment by gilescope** [comment]
That's a tad hacky. Do not repeat yourself is a principle for a reason.
