### ISSUE TITLE
Is there a way to skip some submodules?

### ISSUE THREAD

**Issue by BusyJay** [rust-lang/cargo#4247]
Currently, cargo will populate all git submodule automatically and recursively. But sometimes not all submodules are needed, populate those unneeded modules (specially some large git repos) are just a waste of time. So is there a way to tell cargo to skip those submodules?

**Comment by alexcrichton** [comment]
Unfortunately we don't currently have a way of saying "exclude this submodule", but I could imagine interpreting the `exclude` key for this! (I don't think we do that today)

**Comment by dtolnay** [comment]
I noticed this for `syn` – syn-0.11.11.crate is 62k but .cargo/git/checkouts/syn-6f4912dca572d3ab is 2.8 gigs.

**Comment by BusyJay** [comment]
After #4837 is merged, it will be more slow to add large repository with a lot of optional submodules as dependency.

**Comment by whereistejas** [comment]
Is using `exclude` still the recommended way to ignore git submodules?

**Comment by dtolnay** [comment]
The recommended way is to not have submodules I believe. See https://github.com/dtolnay/syn/pull/183. Cargo fetches all submodules as part of checking out the repo, and reads the Cargo.toml *after* checking out the repo, so an `exclude` key in Cargo.toml wouldn't currently affect the submodule behavior.

https://github.com/rust-lang/cargo/issues/4247#issuecomment-312911391 proposes cloning the repo without submodules first, reading `exclude` from Cargo.toml, and fetching only submodules that are not excluded. As far as I know that is not implemented in Cargo which is why this issues remains open.

**Comment by Muscraft** [comment]
Do you mean that it doesn't skip a submodule that is a submodule of a skipped submodule?

```
- git repo
  - submodule (skipped)
    - submodule (updated)
```

**Comment by BusyJay** [comment]
No, I'm talking about skipping submodule that is a submodule of non-skipped submodule. For example, a native library may include tests framework as a submodule, so the layout becomes:
```
- rust binding repo
     - native library source
         - testing framework
```

Apparently, testing framework is not necessary for a rust binding library, but it will be cloned anyway.

**Comment by Muscraft** [comment]
#10717 only makes sure that submodules aren't updated according to `.gitmodules`. It might be a good idea to open this back up since it is related to pulling in submodules (as you described), not updating them.

**Comment by jsitnicki** [comment]
Updating, in Git lingo, means - cloning, fetching missing commits, and updating the work tree. All three things. I assume by pulling in you have cloning in mind? If so, the submodules with `update=none` will not be pulled in.

#10717 merely puts Cargo on par with how `git clone --recurse-submodules` or `git submodule update` behaves.

Now that the use case has been clarified, I realize I should have used "linked to" instead of "fixes" in the commit description.

**Comment by epage** [comment]
Note that #14605 was merged in 1.84 to reduce the per-build overhead of submodules.

In theory, this means the cost is mostly around
- Initial fetch
- Disk space

If there are any other performance issues, particularly per build, it would help to know about them.  If you want, you can use `CARGO_LOG_PROFILE` to get some insights into what is slow, see https://doc.crates.io/contrib/tests/profiling.html

**Comment by epage** [comment]
Also it might be good to document the `submodule.<name>.update = none` workaround in our [git dependency documentation](https://doc.rust-lang.org/nightly/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories)

**Comment by inferiorhumanorgans** [comment]
> Also it might be good to document the `submodule.<name>.update = none` workaround in our [git dependency documentation](https://doc.rust-lang.org/nightly/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories)

@epage Disabling submodules so that cargo doesn't go crazy is *quite a paper cut*.

In my case I have a crate that's got about 7 megabytes of data to be used by dependant crates and about eight hundred twenty megabytes of data used to regenerate the source.  And that nearly gigabyte of data changes periodically.  What a pain.

**Comment by weihanglo** [comment]
@inferiorhumanorgans the behavior is documented already (while not perfect): <https://doc.rust-lang.org/nightly/cargo/reference/specifying-dependencies.html#git-submodules>.

Sounds like you have the access to the crate repo. Mind sharing why this approach is not applicable to your case?

**Comment by inferiorhumanorgans** [comment]
@weihanglo It's the wrong approach because `cargo` shouldn't break or interfere with `git`.  I do have access to the crate but the issue is I'm not the only one.  Having a separate `git` workflow for when cargo is involved is quite the papercut vs the relative simplicity of disabling submodules (either as a boolean or a filter like the  `git` command line).
