### ISSUE TITLE
Cargo always runs hg on init

### ISSUE THREAD

**Issue by KillTheMule** [rust-lang/cargo#4327]
Originally posted [here](https://www.reddit.com/r/rust/comments/6pfn23/cargo_always_calling_hg_on_init/).

When initializing a new project with cargo, it seems cargo always calls the `hg` binary (and the git binary as well), even when used with the `--vcs none` or `--vcs git` flag. As mentioned in the reddit thread, maybe the offending line is https://github.com/rust-lang/cargo/blob/c3392142a74669deeddac3911292eaac93bf6783/src/cargo/ops/cargo_new.rs#L397

The problem I have with this is that `hg` in my environment is a totally different, very large application. I've worked around it by removing `hg` from my path, being thankful it is not in `/usr/bin`. Maybe cargo could be change to only run `hg` when it's really useful (for my naive version of "useful"), or mabe a flag could be added to keep cargo from doing it?

**Comment by sp3d** [comment]
It looks like there's a bug (or at least a redundancy) in [HgRepo::discover](https://github.com/rust-lang/cargo/blob/e934177fca2cbe20fed853328c36c9d8d11d477c/src/cargo/util/vcs.rs#L29) anyway:

`process("hg").cwd(cwd).arg("root").cwd(path).exec_with_output()?;`
is setting cwd twice, which would emit a warning if this were an options struct instead of builder pattern. Presumably it wants to do `.arg(path)` like the other examples do, or else it should avoid setting `.cwd(cwd)`.

**Comment by KillTheMule** [comment]
Someone got an even better workaround in the reddit thread, so it might not be too bad to leave that in. Close the issue if you feel the same :)
