### ISSUE TITLE
How does cargo-run know which paths to put in LD_LIBRARY_PATH?

### ISSUE THREAD

**Issue by SuperFluffy** [rust-lang/cargo#4362]
I would like to directly run an executable without going through `cargo run`. However, the executable needs to be dynamically linked against a `.so` library, the path to which contains a hash. For example, if I run the executable, I get:

````
 ./target/release/rotators 
./target/release/rotators: error while loading shared libraries: libopenblas.so.0: cannot open shared object file: No such file or directory
````

This is fixed by putting `LD_LIBRARY_PATH=target/release/build/openblas-src-e5936863f8c6d9e7/out/opt/OpenBLAS/lib`. But how can I know this path? How is this hash generated and how does `cargo run` know that it needs to put this path in the `LD_LIBRARY_PATH` env var?

I'd like to write a wrapper which mimicks `cargo run`'s behaviour.

**Comment by alexcrichton** [comment]
Do you know if it's possible to build openblas as a static library instead of a shared library? Typically when artifacts are in the output directory they're difficult to access at runtime as you're finding.

To answer your question, though, the hash here is an internal implementation detail of Cargo and isn't specified how it generates (it changes for various reasons over time).

**Comment by SuperFluffy** [comment]
Yeah, I think that's the way to go. `openblas-src` has a `static` feature. I will see if that solves the problem and then close this issue.

**Comment by SuperFluffy** [comment]
Using `openblas-src/static` is the way to go and essentially solves my problem.
