### ISSUE TITLE
Ignoring `--features` with `-p` parameter when running tests

### ISSUE THREAD

**Issue by aleksuss** [rust-lang/cargo#4407]
I try to tell cargo what feature use when testing package `package` with command like this:

`cargo test --features my_feature -p package --lib` 

but I get result the same if I run:

`cargo test -p package --lib`

But if I run tests with command:

`cargo test --features my_feature --manifest-path package/Cargo.toml --lib` 

Everything is ok.

**Comment by alexcrichton** [comment]
Thanks for the report! This is something wehre I think that Cargo can at the very least give better error messages. Right now when you specify `--features` it does it for the "target package" (the one specified by `--manifest-path` rather than the` -p` argument. 

Surprising behavior for sure! Tough to fix though :(. We should give a better error message regardless

**Comment by ehuss** [comment]
`-p foo --features foo_feat` when not in the foo directory should produce an error if `foo_feat` isn't defined in the local directory.  It should also produce an error in the root of a virtual workspace.
Closing as there are several other issues tracking selection of features in a worskpace, such as #5364, where we'll hopefully get a better story together.
