### ISSUE TITLE
Need a way of specifying features for dependencies with cargo install

### ISSUE THREAD

**Issue by kjeremy** [rust-lang/cargo#4555]
`cargo install diesel_cli --no-default-features --features "sqlite"` fails on my windows machine because a dependent crate `libsqlite3-sys` can't find the sqlite headers and libs.  However that crate has a feature "bundled" which will compile it's own version of sqlite.  I can get around this when running `cargo build` on my app with `diesel` as a dependency:

```
[dependencies]
diesel = { version = "0.16.0", features = ["sqlite"] }
diesel_codegen = { version = "0.16.0", features = ["sqlite"] }
libsqlite3-sys = { version="*", features=["bundled"]}
```

in the `Cargo.toml` of my app.  However there does not appear to be a way to do this using `cargo install`.

**Comment by spease** [comment]
I also just ran into this issue reinstalling diesel. I've also opened a ticket there requesting a bundled feature for diesel itself

**Comment by weihanglo** [comment]
You should be able to specify features for optional dependency. Something like `--features libsqlite3-sys/bundled`. (`-F` for short)

So it would look like:

```
cargo install diesel_cli --no-default-features -F sqlite -F libsqlite3-sys/bundled
```

Given this issue is quite old and should have been resolved already by both `diesel` side and Cargo, I am going to close it. If it is wrong, please leave a comment and we can check it again.
