### ISSUE TITLE
With cargo run, forward termination signal to child process on Windows

### ISSUE THREAD

**Issue by Boscop** [rust-lang/cargo#4575]
I'm using the [ctrlc](https://github.com/Detegr/rust-ctrlc) crate to catch Ctrl-C in my program but it doesn't work when it's started by `cargo run`, which defeats the purpose because I don't need to handle Ctrl-C in the release version, only during development.

Would it be possible for `cargo run` to also use the ctrlc crate and forward the termination signal to the child process?

**Comment by lukaslueg** [comment]
On unix-like systems, `cargo run` replaces itself with the child process using the `execve()`-family, so there is nothing to forward, the signal is delivered straight to your target process. It should™ just work unless `SIGINT` is masked for some reason. What OS are you on?

**Comment by Boscop** [comment]
Windows 8.1

**Comment by alexcrichton** [comment]
I don't personally know how to "forward signals" on Windows, but an implementation would be most welcome!

**Comment by retep998** [comment]
Cargo uses job objects when running any child processes, so when cargo exits all child processes are forcefully and automatically terminated. In order to be able to have your program respond to console control events when using `cargo run`, cargo would have to stop using job objects to forcefully terminate everything when it exits.

**Comment by retep998** [comment]
I believe the original issue was that when cargo received `CTRL_C_EVENT` it would not propagate automatically to child processes of cargo. An alternate way of solving this issue would be to abandon job objects and instead handle `CTRL_C_EVENT` during which we explicitly generate a `CTRL_C_EVENT` for every single child process which means cargo has to keep track of all its current child processes. It would certainly be more complicated, but it would allow child processes to decide how to respond to `CTRL_C_EVENT` instead of just being forcefully terminated.

**Comment by PENGUINLIONG** [comment]
I'm using `hyper`, `futures` and `ctrlc`. Every time I interrupt the process, the application sometimes failed to go through all the codes which ought to be executed before the process exits. But if I `cargo build` and then start with the built binary, those codes are always executed. Is that related to this issue?

**Comment by Boscop** [comment]
The Ctrl-C handler won't get triggered with `cargo run`, but it will when you run the exe manually.

**Comment by PENGUINLIONG** [comment]
@Boscop That's weird. I ran `cargo run` in Powershell in VS Code the Ctrl-C handler was actually triggered,  and was always triggered, except it doesn't finish its works sometimes.

**Comment by zachlute** [comment]
My above change, #6004 fixes this for cmd.exe shells, but it's still a problem for PowerShell (maybe I'll try to poke at that at some point?) and likely MSYS shells.

**Comment by Boscop** [comment]
@zachlute Thanks! So with your fix, a handler registered with the `ctrlc` crate should also be called when the exe being terminated was spawned by `cargo run`, correct? (Which didn't work before on Windows.)

**Comment by zachlute** [comment]
Yes, though there's also a caveat. This fixes it for raw cargo.exe runs, but my understanding is that when run through rustup it's probably still an issue because I'll have to make the same fix in rustup. Now that this has landed, I'll try to poke at that once it hits nightly and see what's up.

**Comment by Boscop** [comment]
@zachlute I usually run it through [`cargo watch -x run`](https://github.com/passcod/cargo-watch), will that work with `ctrlc`?

**Comment by Eh2406** [comment]
@zachlute what is the state of this, can this be closed now?

**Comment by zachlute** [comment]
My understanding of the status quo here is that this problem is, as mentioned above, fixed for cmd.exe shells (and likely PowerShells?), but not for MSYS shells, because as @alexcrichton mentions in #6004, those don't send Ctrl+C events and just get killed with `TerminateProcess`.

So uh...I think my answer is 'yes, this is fixed for most people'.

**Comment by Eh2406** [comment]
Ok I will close this for not, we can reopen if someone is having problems.
