### ISSUE TITLE
Cargo crashes powershell and cmd on Windows 10 upon building curl-sys (and maybe other things?)

### ISSUE THREAD

**Issue by Jragonmiris** [rust-lang/cargo#4585]
Yes, that is a very specific title.

I have a **fresh** install of Windows. I formatted all my drives and reinstalled Windows 10, so I doubt any environment weirdness is going on. I used `rustup` to install Rust and have confirmed this on the current stable and nightly (417c73891 2017-10-05). I have the MS Build Tools installed (so `cl` is present and everything).

After drilling through my dependencies, narrowing it down to 1, drilling down into THAT crate's dependencies, putting them in my `Cargo.toml` and repeating, I yielded this minimal example:

1. Run `cargo new close_ps`
2. Run `cd close_ps`
3. Change your Cargo.toml to the following:
```
[package]
name = "close_ps"
version = "0.1.0"
author = ["Zoe"]

[dependencies]
curl-sys = "0.3.13"
```

(Author and other fields can be whatever, doesn't matter).

4. Run `cargo build` (or `cargo test`, add `--release`, run `cargo rustc`, whatever -- doesn't matter), upon hitting `Compiling curl-sys` it will stick around for a few seconds and then Powershell or cmd (happens to both) will close.

As an extra peculiarity, Cargo's processes will hang around in the task manager for a while before exiting. Indeed -- this doesn't break the build tool! If, after the process exits, you go into the `target/debug` directory, the `.rlib` will be there. The compile appears to be successful; in my projects where I first noticed this bug, running the executables they produce or running tests with a completed build all execute successfully.

I'm filing this here instead of with `curl-rust` because no matter what that library is doing when building (within the bounds of deliberately non-malicious code), Cargo probably shouldn't be borking Powershell/cmd.  (Also, since `curl-rust` is Alex Crichton's, he'll see it either way and can make a better determination of if it should indeed be in `curl-rust`, :)). 

As an addendum, I've confirmed this happens down to `curl-sys = "= 0.2.0"` as well, but NOT `curl-sys = "^0.1"` (which resolves to `"0.1.35"`), so whatever is going on, it's something added between those two versions. I would have to guess whatever is happening is in the build script. It's likely not in any of the dependencies of `curl-sys` because I manually copied those into my `Cargo.toml` and it completed without issue.

It is NOT an issue of simply panicking. For one, if the build is completing the build script is working fine, and secondly, I verified a simple project with a `build.rs` that immediately panicked and it worked as expected.

**Comment by ehuss** [comment]
I felt like solving a puzzle today.

This isn't really a cargo bug.  Since cargo allows running arbitrary code in `build.rs`, it can do anything to your computer.

In this particular case, the `curl-sys` `build.rs` file runs the `git submodule` command (if there isn't a `curl/.git` file).  Run the following code outside of a git repo and it will cause the command window to close.

```rust
use std::process::Command;

fn main() {
    let output = Command::new("git").args(&["submodule", "update", "--init"])
                               .output().unwrap();
}
```

Ultimately git should not be closing the window. I didn't dig into why it does that (it's not unique to Rust, spawning that command in Python does the same).  I'm not sure if it's really necessary for `curl-sys` to run git during the build.   Perhaps it could do a better job of detecting if it is inside a git repo.  

As an aside, this isn't a problem with other terminals or shells such as Git Bash.  I personally use [ConEmu](https://conemu.github.io/) which also is immune.
