### ISSUE TITLE
What about deploying classic unix tools with cargo

### ISSUE THREAD

**Issue by posix4e** [rust-lang/cargo#4598]
I'm thinking

bsdtar
some of the classic zip tools
Grep
It might be nice if we could be a standard of how to deliver source, compile it and deploy it
I guess I have 3 questions

- If I start doing this is someone going to yank packages
- If not cargo what tool should someone use. Keep in mind almost all linux distro tools ship binaries not source. With docker, more and more people are looking for a way to distribute individual classic tools
- As far as I know there's no way to do this currently in c/c++ and we could make it easy

That being said I am sure it wasn't envisioned and we might want some changes to the crates.io webpage

- Some small webtweaks to let people know how to do this
- Some changes to the docs if we don't mind people doing this
- A link to an example

**Comment by carols10cents** [comment]
> If I start doing this is someone going to yank packages

No, so far the crates.io team hasn't yanked packages except for CoC or trademark issues

> If not cargo what tool should someone use. Keep in mind almost all linux distro tools ship binaries not source. With docker, more and more people are looking for a way to distribute individual classic tools

No idea!

> As far as I know there's no way to do this currently in c/c++ and we could make it easy

This is pretty far from cargo's prime purpose, which is to build rust code and manage rust dependencies.

> That being said I am sure it wasn't envisioned and we might want some changes to the crates.io webpage

Ah, I think a reason sgrif pointed you over here from crates.io's repo is that you didn't mention any changes to the crates.io website in [your original issue](https://github.com/rust-lang/crates.io/issues/1114).

I'm going to close this because we have plenty of work and not enough people to do the work just to support Rust projects; we're not going to have the bandwidth in the near future to support non-Rust projects officially.
