### ISSUE TITLE
Network operations for packages should be done in parallel

### ISSUE THREAD

**Issue by metajack** [rust-lang/cargo#467]
Currently this is serialized and is quite slow when you have many dependencies.

Note that I expect initial fetches to be slow, but this is the case where the git repos are all unchanged. This is happening to me all the time because I'm constantly failing builds while getting Servo ported over.

**Comment by alexcrichton** [comment]
Clarifying that I'd like to download packages in parallel in as well. I'd basically like to have the ability to perform all of our network operations in parallel, even if we don't necessarily take advantage of it by default.

**Comment by almereyda** [comment]
If multiple dependencies share the same origin and are served via HTTP/2, a parallelized network IO stack should be able to make use of multiplexing.

**Comment by ishitatsuyuki** [comment]
I'm planning to take this. Some insights:

The point of parallelizing (or multiplexing) is to reduce the impact of network latency. Multiple connections has its own pros and cons, but I'm planning to maintain only one connection per server, as they are supported below.

- https://crates.io/ (Heroku, used for redirects) probably have a correct HTTP 1.1 pipelining implementation.
- https://static.crates.io/ (S3 CloudFront, used for tarballs) supports H2.

Another thing I'd like to do is to add file sizes to `crates.io-index`, so we can know the total download size beforehand and display a united progress bar. I'm not sure if the migration can be done smoothly though.

**Comment by DCjanus** [comment]
Parallelizing download is fater, beacuse of `TCP congestion control`

If the TCP window size is large enough, when the server waits for the client to respond to an ACK, it still sends packets. But in the real world, most of the time, the TCP window size is not large enough, especially with a large number of short connections ( Because of `TCP slow start`).

There are two solutions:

1. `Multiplex`: When a connection waits for ACK, other connection can still be sent.
2. `HTTP/2` based on `QUIC`.

**Comment by ishitatsuyuki** [comment]
Close?

**Comment by dwijnand** [comment]
Because of #6005 (is the question-I'm not sure, myself)

**Comment by alexcrichton** [comment]
Ah yes, we can indeed close! There's also a [call for testing](https://internals.rust-lang.org/t/testing-cargos-parallel-downloads/8466/4) on internals.
