### ISSUE TITLE
Windows / Colors are displayed as codes

### ISSUE THREAD

**Issue by AndyBitz** [rust-lang/cargo#4722]
I'm on Windows 10 Build 16299.19

I've recently updated from cargo 0.20.0 to 0.22.0 and now I have the following issue.

Colors (especially green) are not displayed correctly under normal circumstances.
When I redirect `stdout` to a file everything seems to _almost_ work fine.

![cargo color bug](https://i.gyazo.com/2b3c73251850710f2f59ed23fa83c43e.png)

![compiler error message](https://i.gyazo.com/e73529b1a1f373eba52957ee779eb36d.png)

I've tried this with cargo 0.21.1 and had the same bug.
A VM with the same Windows Version did't have this problem.
An other device with an older windows version did't have this bug until I updated to the current version.

[Could the recent cmd.exe change be the problem?](https://blogs.msdn.microsoft.com/commandline/2016/09/22/24-bit-color-in-the-windows-console/)

The nightly version has the same bug. Only 0.20.0 seems to work normal.
This is the same for cmd, powershell and hyper (the terminal emulator I use).

I've posted this on [StackOverflow](https://stackoverflow.com/questions/47273198/color-codes-are-shown-instead-of-colors) before.

**Comment by alexcrichton** [comment]
Thanks for the report!

@BurntSushi you wouldn't happen to know what's going on here would you? We're using a [pretty thin wrapper](https://github.com/rust-lang/cargo/blob/master/src/cargo/core/shell.rs) over the termcolor crate

**Comment by AndyBitz** [comment]
Yes, termcolor seems to be the problem.
It replaced term after 0.20.0.

But I'm not sure why it only works when stdout is redirected.
It also seems to print wrong color codes when stderr is redirected to stdout.

```bash
cargo run --color always > output.txt 2>&1
```
`output.txt`
![term](https://i.gyazo.com/a2cc19309f8ebc0f377ed2eebe71c908.png)

**Comment by alexcrichton** [comment]
Do you have the `TERM` environment variable set? If so, do you know what its value is?

**Comment by AndyBitz** [comment]
Ahhh. It is `xterm-256color`. Setting it to nothing solves the problem.

**Comment by alexcrichton** [comment]
Ok that'd explain it! Do you know how come that variable is set? Should Cargo not be interpreting that environment variable?

**Comment by retep998** [comment]
https://github.com/BurntSushi/ripgrep/blob/2c84825ccbe2d42e0648b56a7d3289c5f5bcb9e5/termcolor/src/lib.rs#L176-L182

If `TERM` is set, then it will attempt to use ANSI codes even if the stdout/stderr it is writing to is a windows console. This is clearly the wrong behavior as the correct behavior is to unconditionally use the windows console API as the way to perform colors when stdout/stderr is a windows console. Even if the color choice is set to `ColorChoice::AlwaysAnsi`, even if `TERM` is set, stick to the windows console API!

That said, if you are writing to the windows console and you successfully set `ENABLE_VIRTUAL_TERMINAL_INPUT` via `SetConsoleMode` (or it was already set via `GetConsoleMode`), then and only then are you allowed to use Microsoft's flavor of ANSI escape codes. The supported escape codes in this case depend on the version of Windows 10, **not** the `TERM` environment variable!

**Comment by AndyBitz** [comment]
@alexcrichton Probably when working with hyper.js.

@retep998 so, termcolor needs to get fixed?

**Comment by alexcrichton** [comment]
@AndyBitz hm I'm a little confused then as to what's going on, it sounds like you're using a terminal emulator which claims to support ansi escape codes but it doesn't?

**Comment by BurntSushi** [comment]
I'm also confused. If you're setting `TERM` to something other than `dumb`, then you're declaring that your terminal supports ANSI colors.

**Comment by retep998** [comment]
@BurntSushi If you're writing to the windows console, then you *must* disregard what `TERM` says. Unless the console has the `ENABLE_VIRTUAL_TERMINAL_PROCESSING` mode enabled, ANSI escape codes will never work. This is the chain of logic that should occur:

* Call `GetConsoleMode`
* If `GetConsoleMode` fails then use ansi escape codes based on `TERM`,  the `ColorChoice`, and the name of the pipe.
* If `GetConsoleMode` succeeds and the current modes already have `ENABLE_VIRTUAL_TERMINAL_PROCESSING` then use Microsoft flavor escape codes.
* Otherwise call `SetConsoleMode` with the current modes or'd with `ENABLE_VIRTUAL_TERMINAL_PROCESSING`.
* If `SetConsoleMode` succeeds then use Microsoft flavor escape codes.
* Otherwise use the Windows console API for colors.

**Comment by AndyBitz** [comment]
Sorry for the confusion, I meant that when I worked on hyper the `TERM` variable (probably) got set globally and was therefore available in every terminal I used which caused cargo to display no colors everywhere.

Also I found [this](https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences) in the Microsoft docs, which is as @retep998 says.

**Comment by jacobmorzinski** [comment]
My own experience: my `TERM` is set to `msys` (not set by me, but set by GitHub's old "git shell" CLI package).  I haven't yet upgraded to GitHub's new desktop app, because the old "git shell" CLI package is stunningly useful and I don't want to break it.  I do confirm that removing `TERM` restores colors to cargo's windows console output, so I'm glad that I found this thread.

**Comment by AndyBitz** [comment]
I couldn't reproduce this with the latest version of cargo and rustc.
I'll assume that it got fixed and close the issue.
