### ISSUE TITLE
Include files of private sub crates (package.publish = false) in the package

### ISSUE THREAD

**Issue by iology** [rust-lang/cargo#4726]
Before #1565 is solved, is it possible to include verbatim copy of all sub crates with config `package.publish = false`? (excluding the ignored files)

```
[package]
publish = false
...
```

**Comment by iology** [comment]
I almost come up with a patch but this line of code gets me down for lack of context:

https://github.com/rust-lang/cargo/blob/abd137ad14a8f352b48f24b11c3995d716deb260/src/cargo/util/toml/mod.rs#L494

I need to check package.publish and strip the path only if the package is not allowed to be published. Any help?

**Comment by est31** [comment]
I think the very reason for `package.publish = false` is to force cargo to *not* publish stuff.

**Comment by iology** [comment]
@est31 I know. But now people are mixing published sub crates with private sub crates. If cargo insists on publishing all sub crates, then `package.publish` will become quite useless.

**Comment by iology** [comment]
@est31 Ah, "publish" has two meanings here: a) publish to the registry; b) publish along with the root crate.

I want to support (b) and forbid (a). Better ideas?

**Comment by iology** [comment]
Ok, the patch is small but the only thing missing left is local cyclic dependencies. I'm back to #4242 

Hope I can sort everything out and apply the logic for `package.publish = true` too.

**Comment by est31** [comment]
@iology I don't know but many people type `publish = false` to prevent their code from being uploaded to crates.io, e.g. because it is proprietary. Now they absolutely don't want it to be uploaded! If now there is a condition like the one you want they'd probably be quite surprised to learn about it. Therefore I don't think this feature should really be added, or if its added it should be enabled by something different than `publish=false`.

**Comment by iology** [comment]
@est31 Say, root crate A is to be published, and it depends on sub crate B (publish=false, path="./B"), it is reasonable to upload B too, otherwise B should not be placed there. Why would this be a surprise?

**Comment by est31** [comment]
@iology if you do `publish=false` for your crate you usually have a strong reason to not get your crate public by accident. It is less about not uploading the crate directly to crates.io. I guess the question boils down to what `publish=false` should mean.

To give you an use case where this might bite people: maybe crate B is a super secret company crate while crate A is an open source crate that uses B to have some proprietary extensions. Now you want to publish A but you forget to remove the extensions, e.g. because you forgot to switch branches or something. Then you publish it and suddenly B is visible to the world!

**Comment by iology** [comment]
@est31 If you really want to keep those private, you can change the default registry with `./.cargo/config` (and for every branch). Since by default `publish=true`, **only you** but cargo can make you safer.

Given your extreme use case, I would rather need more than one manifest keys to solve the problem. The real world examples are like this: package A has reusable module1, module2, module3... in their own crates, and crates for tests. It makes people sad that some packages have to make their test crates published to the registry for better modularity.

**Comment by est31** [comment]
> It makes people sad that some packages have to make their test crates published to the registry for better modularity.

It does not make me sad that I won't have to download your test code (which may be quite large) if I just want to build your crate :)

**Comment by iology** [comment]
Maybe you think "publish (to registry)" = "public". I do not. "module=true" could be ok too. I'll come up with a patch.

**Comment by jonhoo** [comment]
I assume this should be closed given that https://github.com/rust-lang/rfcs/pull/2224 was postponed?
