### ISSUE TITLE
patch sometimes fails, I think due to versioning issues

### ISSUE THREAD

**Issue by nrc** [rust-lang/cargo#4772]
Apologies for the rather vague bug report, I'm not clear on what is going on.

This occurs in the Rust repo. There is a `patch` line in the workspace toml file:

```
[patch."https://github.com/rust-lang/cargo"]
cargo = { path = "tools/cargo" }
```

Then in the rls toml file, there is the dependency `cargo = { git = "https://github.com/rust-lang/cargo" }`.

I would expect that whenever building the RLS, the Cargo dep would be replaced by the local version of Cargo as specified by the `patch` line.

However, it seems that this is not always the case. I think because of versioning. E.g., if the version of Cargo in the GH repo is 0.25.0, and the version in the Rust repo is 0.24.0, then Cargo builds both versions (and both have entries in Cargo.lock), and the RLS uses the GH version, rather than the local version.

**Comment by alexcrichton** [comment]
I think this is because Cargo by default would pick the greatest version for the RLS if a `cargo update` is run (as there's no version constraint), but the `src/tools/cargo` folder is also a member of the workspace so it's included as well. If you execute, though, `cargo update --precise 0.24.0 -p cargo:0.25.0` I think it'd work? That'd basically take RLS's dependency on Cargo back to what's in tree instead of trying to pick up what's in the git repo.

**Comment by nrc** [comment]
The update worked, but then building gave `error: failed to resolve patches for `https://github.com/rust-lang/cargo``

`cargo update` fixed that, but then trying the downgrade gave `error: Unable to update https://github.com/rust-lang/cargo#0.24.0`

**Comment by alexcrichton** [comment]
Hm this may be a case where a `cargo update` may be too aggressive? When updating the rls in the main repository could the original `Cargo.lock` be used and then `cargo update -p` to update dependencies selectively?
