### ISSUE TITLE
Build tests during `cargo package`

### ISSUE THREAD

**Issue by lukaslueg** [rust-lang/cargo#4805]
The Fedora people have recently packaged 200+ Rust-crates for the upcoming Fedora release. I've talked to them regarding problems related to packaging Rust-crates for distribution through Fedora and one of the problems that came up was "Tests are sometimes missing files".

Indeed, while Cargo does build the final crate once as part of `cargo package`, the tests are not checked. While there is no policy about whether to include tests in the final crate at all, Cargo could at least discover, build and possibly execute tests as part of `cargo package` and by implication `cargo publish`. If test-assets are not included on purpose, failure to build/execute the tests using the crate becomes explicit, advising the maintainer to exclude those tests from the crate as well.

**Comment by ritiek** [comment]
I'd like to work on this.

Should we override the default behavior and introduce `--no-test` to skip them (optionally) or just introduce an optional `--run-tests`?

**Comment by alexcrichton** [comment]
Thanks for the offer @ritiek! To me at elast though it's not clear how we may wish to approach this. I believe there's at least a few (unsure how many) crates which specifically exclude files related to tests when publishing and it'd be best to avoid breaking those workflows. Additionally the fact that building/running tests may be split indicates to me that this is a very tricky feature because it would *only* work for crates that support a bare `cargo test` which certainly isn't all of them, many crates have test suites that are scripted elsewhere or require a number of external resources.

It may be best to get information from @rust-lang/cargo about directions to take here before diving into an impementation. I would personally recommend an unstable feature that's opt-in for now, but it's not clear to me personally how we'd eventually want to expose this.

**Comment by wycats** [comment]
@alexcrichton it seems like we would like to determine whether we think that "published crates should have working tests that should pass on dependents' machines" is a constraint we would like.

If so, there are probably other things we would want to do, like warn people when they exclude tests from Cargo, and possibly add an opt-in mode where Cargo runs the tests for crates the first time they are downloaded.

If we don't want to go down this path, this would seem like a half-measure that is more likely to annoy people than to provide the desired value.

**Comment by alexcrichton** [comment]
A good point! I would personally need to be convinced that this is a constraint we should pick up myself, but others may feel differently!

**Comment by lukaslueg** [comment]
A less constraining approach would be to run the equivalent of `cargo check --tests` on the untared crate and warn if that fails. This, however, would cause endless warnings for people who don't want or can't include the artifacts required to run the tests from the packaged crate, tricking them into excluding them altogether and forgetting about it.

The way to go now seems to be to back off and wait for more experience with cargo in different build-environments.

**Comment by wycats** [comment]
@lukaslueg I'd be very happy to circle back around on this issue once we have more experience 😄
