### ISSUE TITLE
'cargo test' fails when programs in examples/ subdirectory have dependencies

### ISSUE THREAD

**Issue by dwrensha** [rust-lang/cargo#4827]
I have a library with examples in an [`examples` subdirectory](https://github.com/capnproto/capnp-rpc-rust/tree/768f74aa702a7360ec037e7f3eb952e04572848a/examples). The examples have their own `Cargo.toml` and `build.rs` files. Recently, I started seeing errors when running `cargo test` from the library's root directory, because Cargo was trying to build the examples but was ignoring the `Cargo.toml` files.

I've resorted to this workaround: https://github.com/capnproto/capnp-rpc-rust/blob/768f74aa702a7360ec037e7f3eb952e04572848a/Cargo.toml#L27

On IRC, `panicbit` suggested:

> At any rate, I think an simple rule for cargo to follow would be to simply ignore any dirs and subdirs that contain a Cargo.toml

As another workaround, I could rename my directory to something other than `examples/`. Unfortunately, that would break a bunch of documentation links.

**Comment by alexcrichton** [comment]
Nah this seems like a fine feature to add to me!

FWIW this is because Cargo now thinks that `examples/foo/main.rs` is an example called `foo`. (the `main.rs` is required there as an exact name). If you rename `examples/pubsub/main.rs` to `examples/pubsub/src/main.rs` I believe Cargo won't be building the examples automatically for the parent project. (although that's not as great of a solution as just ignoring dirs with `Cargo.toml` in them.

**Comment by epage** [comment]
Note: there is now also `package.autoexamples = false`

Unsure how safe it would be for us to stop auto-discoverying some packages (if a `Cargo.toml` is present).  Since we have a way to turn auto-discovery off, I lean towards sticking with just that.  I propose that we close this.

**Comment by weihanglo** [comment]
Thanks for triaging such an old issue. Agree with you on `package.autoexamples = false` approach. Closing.
