### ISSUE TITLE
It should be an error to have [patch] in Cargo.toml that's not in a workspace root

### ISSUE THREAD

**Issue by Boscop** [rust-lang/cargo#4947]
It should be an error to have [patch] in Cargo.toml that's not in a workspace root because it has no effect and may lead people to think that they are patching when they are not.

**Comment by exrook** [comment]
I just spent some time running in to this issue wondering why my [patch] section had no effect. I see now that it is briefly mentioned in the documentation [here](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#overriding-dependencies), but it would be nice to at least have a warning that the section is being ignored. I'd be happy to submit a patch if someone could point me in the right direction to start from. :)

**Comment by alexcrichton** [comment]
Oh awesome @exrook! Currently workspace validation [happens around here](https://github.com/rust-lang/cargo/blob/aa06d7c0eb2e3ea4f3ec37608733e47244c1fb5c/src/cargo/core/workspace.rs#L516-L677) and I think we'd want to start off with a warning (to avoid breaking older projects), but I suspect the fix for this would go around there
