### ISSUE TITLE
During cargo publish, verify that src directory is not modified by the build.rs

### ISSUE THREAD

**Issue by matklad** [rust-lang/cargo#5073]
A common pitfall when doing `build.rs` code generation in Rust is to write generated files directly to `/src`. It may seem fine on the first blush, but it does cause problems when you use such crate as a dependency, because there's an *implicit* invariant that sources in `.cargo/registry`  should be immutable. Breaking this invariant sometimes is fine, but sometimes leads to pretty bewildering bugs:

- https://github.com/abonander/mime_guess/issues/31 
- https://github.com/lalrpop/lalrpop/issues/272

So, I think we, first of all, should formally declare and document that build scripts should not modify stuff outside of `OUT_DIR`. We can enforce this rule during pre-flight check in `cargo publish`, by making the directory with sources read-only before the build. That is, in [this line](https://github.com/rust-lang/cargo/blob/6468ba28ffae7888195be5017e159d1e4ebd3475/src/cargo/ops/cargo_package.rs#L286), we should add an equivalent of `chown ua-w -r dst`.

**Comment by matklad** [comment]
Hm, I've tagged this E-mentor, but we haven't really discussed if we want this feature at all. Will bring it up the next cargo team meeting.

**Comment by dwijnand** [comment]
(btw is the [[I-nominated]](https://github.com/rust-lang/cargo/labels/I-nominated) flag meant for these situations?)

**Comment by matklad** [comment]
We've discussed this on the meeting and we do want this feature, hence feature-accepted label.

We've figured out a better strategy to detect this error than making `src` readonly. During `publish`, we can calculate a checksum before and after we run `cargo build`, and complain if they don't match. That way, we'll be able to give a precise error message, which is much better than `build.rs` panicking with `PermissionDenied`. 

I think `DirectorySource` in Cargo calculates checksums of directories, so it might be useful. Alternatively, `PathSource::fingerprint` method could be used: it computes mtimes and not checksums, but `mtimes` are probably even better, because we will be able to point which files exactly are modified.

**Comment by dwijnand** [comment]
This can be closed now: it's been fixed with https://github.com/rust-lang/cargo/pull/5584/.

**Comment by kingwingfly** [comment]
Hello, I meet a problem due to this:

I'm working on a crate, and need generate code in src only for doc test. 

For example, I generate code in `src/test_utils/mod.rs`, and use it in doc test: 
```rust
# #[path = test_utils/mod.rs]
# mod test_utils;
use test_utils::xxx
```
But I cannot publish it recentlty:
```
error: failed to verify package tarball

Caused by:
  Source directory was modified by build.rs during cargo publish. Build scripts should not modify anything outside of OUT_DIR.
  Changed: /home/louis/rust/.cargo/target/package/fav_utils-0.0.1/src/proto/bili.rs

  To proceed despite this, pass the `--no-verify` flag.
```
I tried add `#[cfg(test)]` ahead of `Codegen`, then it can be published. However, the `Codegen` can never run during develop.

```rust
// build.rs

// This can generate code but cannot be publish 
fn main() {
    println!("cargo:warning=Generate some code");
}

// This can publish but cannot generate code
fn main() {
    #[cfg(test)]
    println!("cargo:warning=Generate some code");
}
```

It will be so kind if anyone can give me a suggestion.

**Comment by epage** [comment]
Is there a reason you are generating into `src/` rather than `$OUT_DIR` like encouraged at https://doc.rust-lang.org/cargo/reference/build-script-examples.html#code-generation ?

**Comment by kingwingfly** [comment]
Thanks! I learnt this way when using `tonic`.

> Is there a reason you are generating into src/ rather than $OUT_DIR
Yes. For example:
```rust
// lib.rs
pub trait Foo: MessageFull + Trait {}     //  `MessageFull` is a trait impl by generated Code
pub trait Bar: MessageFull + Trait  {}    // Assume `Trait` needed, and should be manually impl
```
Now I need write doc test for `Foo` and `Bar`.

Since `MessageFull` is hard to manually impl, so I can only generate it instead of create one in my test. Lets generate struct `TestMsg` which impl `MessageFull` for doc test.

And `TestMsg` should impl `Trait`, or I cannot impl `Foo` for it. However, if I don't included the generated code in src, I cannot receive code hint or auto completion when impl `Trait` for `TestMsg`, it's not convenient. 

Instead, I can do this:
```rust
// src/lib.rs
#[cfg(test)]
mod test_utils;

pub trait Trait {}

// src/test_utils/mod.rs
mod impls;
mod generated;

// src/test_utils/impls.rs
use super::generated::TestMsg;
#[cfg(test)]
use crate::Trait;
#[cfg(not(test))]
use my_package_name::Trait;

impl Trait for TestMsg { ... }    // This way, I can get auto completion and code hints
```
Then I can impl `Foo` and `Bar` in doc tests in the way I mentioned before.

In conclude, I need impl a Trait for generated data structure, and also want to include it for code hint and auto completion, so maybe the only way is to put it in src instead of using `include!` macro.

**Comment by kingwingfly** [comment]
Maybe I can put generated code and impls in an integration test folder `tests/common`, and use #[ path = "../tests/common" ] instead of putting it in src/ . Thank you for your inspiration.

**Comment by kingwingfly** [comment]
But there's one more situation I meet:

I have a `xx_core` crate that defines many traits useful. And in another crate `xx_utils`, I need impl those trait for the data structures generated. 

In this situation, generated code is part of the crate. Although files are the same before and after build and `Codegen` changed nothing, `cargo publish` still reject this situation.

**Comment by kingwingfly** [comment]
I suddenly understood, How silly I am!!!

I can generated it in `OutDir`, and `include!` it, and then impl `Trait`s on it!!!

I'm sorry wasting your time!
