### ISSUE TITLE
Hyphen in crate name rejected for target i686-unknown-linux-gnu

### ISSUE THREAD

**Issue by joshlf** [rust-lang/cargo#5082]
[This commit](https://github.com/ezrosent/allocators-rs/pull/135/commits/a8259ae71374bffffacceb758bf154c70e629fb8) tries to run cargo tests with the `i686-unknown-linux-gnu` target, but encounters [this error](https://travis-ci.org/ezrosent/allocators-rs/jobs/331385101#L548) on Travis:

```text
+cargo test --target i686-unknown-linux-gnu
error: failed to parse manifest at `/home/travis/build/ezrosent/allocators-rs/alloc-fmt/Cargo.toml`
Caused by:
  library target names cannot contain hyphens: alloc-fmt
```

When running on x86_64, the crate name is not rejected.

cc https://github.com/carllerche/travis-rust-matrix/issues/4

**Comment by alexcrichton** [comment]
> +echo 'name="alloc-fmt"'

Is this a bug in your CI perhaps?

**Comment by joshlf** [comment]
I don't follow - what's relevant about the line `echo 'name="alloc-fmt"'`?

And I'm using [travis-rust-matrix](https://github.com/carllerche/travis-rust-matrix) with `ARCH=i686`. Also submitted this issue [there](https://github.com/carllerche/travis-rust-matrix/issues/4), but the maintainer suggested it might be a cargo bug.

**Comment by ehuss** [comment]
I think the issue is that when the code in https://github.com/carllerche/travis-rust-matrix/blob/master/test sets up a cross compile it naively creates a new Cargo.toml with the `[lib]` name set to the name of the package.  This isn't allowed, it must be underscores.  I would say that shell script needs to be changed to change dashes to underscores on [this line](https://github.com/carllerche/travis-rust-matrix/blob/df450e9556b1d732399b8a56f396eec14d9d88bd/test#L94).

**Comment by joshlf** [comment]
Oh awesome @ehuss ; great find! Thanks!
