### ISSUE TITLE
Cargo can't determine the terminal width on MSYS terminals 

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/cargo#5124]
I'm not really sure what the API is to do this, but because Cargo can't determine the width here it doesn't print out fancy progress bars which is sad!

**Comment by alexcrichton** [comment]
cc @BurntSushi, you wouldn't know how to do this would you?

**Comment by BurntSushi** [comment]
Sadly, no idea. The tty hack is about as far as my knowledge of MSYS goes. :-(

**Comment by alexcrichton** [comment]
Ah well, worth a shot! I made an [attempt here](https://github.com/alexcrichton/cargo/commit/26d9ab4d4ce957d70d0979e7c4aedcbb211606f5) but it turns out although `COLUMNS` is an env var in the shell it's not an env var in the Rust process (for whatever Reason)

**Comment by ehuss** [comment]
I took a little look at this.  Due to the way Cygwin/msys handles the console, it can be quite difficult to get the correct information.  Opening "CONOUT$" with `CreateFileA` gets close, but only really works with Cygwin's conhost or ConEmu, but doesn't work with mintty (it always returns 80 columns).  Internally Cygwin uses shared NT objects to communicate TTY information, so we can't easily access that without linking to cygwin's libc.  If you want to tweak your attempt, instead of using `GetStdHandle`, you can do something like this:

```rust
let h = winapi::um::fileapi::CreateFileA("CONOUT$\0".as_ptr() as *const CHAR,
    GENERIC_READ | GENERIC_WRITE,
    FILE_SHARE_READ | FILE_SHARE_WRITE,
    ptr::null_mut(),
    OPEN_EXISTING,
    0,
    ptr::null_mut()
);
```

And then you can use that handle with `GetConsoleScreenBufferInfo` when you know it is an msys pty.

One workaround would be to use ANSI escape sequences to communicate with the terminal (something like "\x1b7\x1b[r\x1b[999;999H\x1b[6n\x1b8").  However, that seems kinda gross to me and doesn't work very well.  Ugh.

**Comment by alexcrichton** [comment]
Ah thanks for looking into this @ehuss! It may be the case that we could just detect a tty and assume 80 columns as well

**Comment by ehuss** [comment]
> we could just detect a tty and assume 80 columns as well

That sounds reasonable to me!

**Comment by kip-13** [comment]
This solution exists in nightly dist ?

**Comment by ehuss** [comment]
> This solution exists in nightly dist ?

Unfortunately, no.  I can take another look at a solution.
