### ISSUE TITLE
Cross compiling error message about unsupported crates is not helpful

### ISSUE THREAD

**Issue by Microwave89** [rust-lang/cargo#5238]
I'm trying to cross-compile Rust applications and libs for bare metal ARM Cortex M3 Blue Pill eval board.
I enter "cargo build --target {some-custom-target-from-.json-specification-file} -vv"
I keep getting error "cannot produce bin for {some-app} as the target {some-custom-target-from-.json-specification-file} does not support these crate types"

With -vv option at least it should be displayed:
1. Where are these crates that are attempted to be built for my app (full path!)
2. What the claimed bad crate type is (what is a "crate type" in the first place?)
3. Possibly links to open issues that explain why this particular crate cannot be built, or what is wrong with the custom target specification

At least with the .json target files we are supposed to have the opportunity to compile for custom archs as long as the LLVM backend supports it.

Kind Regards,

Micel Whave

**Comment by lukaslueg** [comment]
The `crate-type` here is "bin", so an executable, almost certainly from the main crate (either the binary itself or it's build-script). The error message is slightly misleading by referring to "crate types" in plural...

In the end, cargo refers to your main crate and does not know how to build executables for the target.

**Comment by matklad** [comment]
If anyone wants to work on this, the code is here: https://github.com/rust-lang/cargo/blob/715fc78caa832223a3404925a829e18c7832703a/src/cargo/ops/cargo_rustc/context/mod.rs#L763

I think we really just need to tweak error message here, because 1) and 2) kinda already present there, but not clear. I don't think we can do 3 in any reasonable way, because Cargo just doesn't have that info.

So the error message might say something like 

    cannot compile `foo` package, because target `bar` does not support the `baz` crate type

Specifically, I think 

1) get rid of wrong pluralization, by doing it properly
2) make sure it clear that `bin` is a name of the crate type, and not just bin in general. To do this, I think adding `crate type` word in the error message, avoiding `these` and having back ticks around the crate type would help. 


I do *not* think we should print the path to the package: we print the name of the package already, and, if it's the current package, the directory is basically `pwd`. If it is a dependency, it lives somewhere in `./cargo/registry` and is probably not interesting.

**Comment by rleungx** [comment]
I'll take it.
