### ISSUE TITLE
Allow `-r` as short form for `--release`, e.g. `cargo build -r`

### ISSUE THREAD

**Issue by Boscop** [rust-lang/cargo#5311]
Please allow `-r` as short form for `--release`.
So that one could write: `cargo build -r`/`cargo b -r`, `cargo run -r`/`cargo r -r`, `cargo b --examples -r` etc.

(Also, it would make sense to introduce `-e` as short form for `--example` and `-es` as short form for `--examples`, and `-t` as short form for `--target`.)

**Comment by ExpHP** [comment]
You know what?  The lack of short flags is one of my favorite things about `cargo`.  Because in any program with short args, that's what people use (and therefore what people teach, and what people are taught), and I eventually forget what they all mean and I begin just copying them recklessly from previous invocations because it's easier than taking 10 seconds to grep for them all in the documentation in order to figure out which ones I no longer need.

> `-es`

I sincerely hope you intend to run the example `examples/s.rs` with that flag.  Long arguments beginning with a single hyphen are pure sacrilege.

**Comment by Boscop** [comment]
Yea, then it should be `--es` but that's rare enough that it doesn't need a shortcut (hence in parens).
But `-r` for `--release` makes sense because it has to be typed quite often..

**Comment by dwijnand** [comment]
If the problem is `--release` is long to type I would suggest aliases and tab completion.  If tab completion isn't working well enough let's fix that.  If we should have more aliases out-the-box, let's discuss that.  I don't use `--release` but I setup a while ago in my `~/.cargo/config`:

```toml
[alias]
br = "build --release"
rr = "run --release"
```

But, to me, `cargo build -r` looks like it's going to do some kind of additional recursion in its building.  So I don't think it's a good idea to add.

(And `cargo build --es` looks like it's going to build the code with... spanish translations or something)
