### ISSUE TITLE
Add a --no-examples switch to cargo test

### ISSUE THREAD

**Issue by faulesocke** [rust-lang/cargo#5387]
`cargo test` has an `--examples` switch which checks "that all examples compile". However, this seems to be the default when running `cargo test`, which makes the switch effectively a no-op.

But sometimes when I do refactoring, I first wan't to check whether all library tests run and then I want to fix the examples. Therefore, having a `--no-examples` switch would be really helpful.

**Comment by joshtriplett** [comment]
This seems reasonable. If you'd be interested in writing a PR, we'd likely accept it.

**Comment by ehuss** [comment]
`--examples` is not a no-op.  It tests only examples, nothing else.

One approach to skip examples is to do `cargo test --lib` which will just do unit tests.

Starting in Rust 1.27 (beta), you can also do unit tests and integration tests (without examples) with `cargo test --tests --lib`.

**Comment by joshtriplett** [comment]
@ehuss Thanks for the clarification! In that case, perhaps what we need here is just an added sentence in the documentation, pointing people to the relevant options.

**Comment by ehuss** [comment]
@joshtriplett I've been thinking for a while now about writing more detailed documentation about the default target and profile selection, and how target options like `--tests` work.  I'm not sure how extensive it would be, or where it would live.  I'd be reluctant to put it in `--help` since most commands already have a long stream of unorganized paragraphs.  I was thinking maybe a new chapter in the Cargo Book.  But if it is buried away somewhere where nobody will see it, it might not be useful.  I haven't gotten very far in organizing my thoughts, though.  I was thinking about hitting up the cargo team and/or docs team to see what people thought, but I haven't gotten around to it.

**Comment by faulesocke** [comment]
@ehuss Thank you very much! Shall I leave the issue open for tracking possible documentation changes or shall I close it?
