### ISSUE TITLE
cargo check --tests fails to compile macros in examples

### ISSUE THREAD

**Issue by kornelski** [rust-lang/cargo#5397]
Running `cargo check --tests` on https://github.com/nickel-org/nickel.rs unexpectedly can't find macros. However, `cargo test --all` compiles fine. 

> warning: unused `#[macro_use]` import
 --> examples/https.rs:1:1
  |
1 | #[macro_use] extern crate nickel;
  | ^^^^^^^^^^^^
  |
  = note: #[warn(unused_imports)] on by default

> error: cannot find macro `middleware!` in this scope
  --> examples/integration_testing.rs:90:22
   |
90 |     server.post("/", middleware! { |req, res|
   |                      ^^^^^^^^^^

> error: cannot find macro `lazy_static!` in this scope
   --> examples/integration_testing.rs:279:9
    |
279 |         lazy_static! {
    |         ^^^^^^^^^^^

* `cargo check --tests` fails to compile examples
* `cargo check --examples` does compile examples, but with warnings
* `cargo build --examples` compiles examples without warnings

**Comment by matklad** [comment]
cc @ehuss it looks like something that would be fixed by #5384

**Comment by ehuss** [comment]
I investigated this some more.  `nickel.rs` has a special set of integration tests for their examples.  In particular, the one that errors out (`integration_testing`) uses `include!` to pull in the example into their testing framework.

I think this can be closed.  With #5464 things should work better.  `cargo check --tests` no longer checks examples directly, so it will no longer generate an error.  The warning is legitimate (it looks like they removed SSL support since it was dropped from hyper, but didn't remove the https example which requires the ssl feature which no longer exists!).

**Comment by kornelski** [comment]
Thank you for checking this.
