### ISSUE TITLE
Passing more flags to rustc

### ISSUE THREAD

**Issue by vosen** [rust-lang/cargo#544]
This is kind of a followup to #60. I've been eyeing [cargo integration with Visual Studio](https://github.com/PistonDevelopers/VisualRust/issues/3) and after asking on IRC I want to propose more flags for inclusion in Cargo.toml:
1. `--cfg`, it's a commonly used rustc feature
2. `--C` or at least `--C link-args`. It's required for passing -mwindows (compile as a Windows Desktop app, no console output) and for passing resources (icons, executable manifests) to the gcc.
3. `-W`, `-A`, `-D`, `-F`, four lint control flags, projects will want to set stricter/more relaxed baselines across code-base.

**Comment by wizeman** [comment]
It seems that cargo either passes `-g` to rustc (when `debug=true`) or `--cfg ndebug` (when `debug=false`).

Personally, I'd really like my release build to have both `-g` and `--cfg ndebug`, because I really care about runtime speed (i.e. I don't want `debug_assert!()` macros to run in my release build) and I care about being able to debug my programs, but I don't care about the size of the resulting binary.

It seems that I cannot do this with the current cargo manifest format, but if I could control which options to pass to rustc, then I could easily do it.

**Comment by sfackler** [comment]
@wizeman Can't you just tweak the release profile? http://doc.crates.io/manifest.html#the-[profile.*]-sections

```toml
[profile.release]
debug = true
opt-level = 3
```

**Comment by nstoddard** [comment]
Unless something like this is implemented, starting in beta it will probably become impossible to use Cargo to compile a program with -mwindows, at least without using the `hide_window` workaround described above. We really shouldn't have to use a workaround like that. Plus, that technique doesn't work for specifying icons. As far as I can tell, there's no alternative to link_args for that.

Currently you can use the #[link_args] attribute for this, but I'm pretty sure it'll stop working in beta (since it's behind a feature gate). Without Cargo support for link_args, you'll have to run `rustc` directly in order to use its `-C link_args` option. I don't think we should force people to run `rustc` directly if we don't have to.

**Comment by alexcrichton** [comment]
@nstoddard using `-C link-args` isn't necessarily super stable and we would probably want a better solution for passing `-mwindows` to the linker regardless (e.g. what happens when it starts being linked with msvc instead of gcc?).

**Comment by deontologician** [comment]
> 1. --cfg will manifest itself with features 
@alexcrichton could you expand on this? I would like to have different features compile with different --cfg options enabled, but it doesn't seem possible now

**Comment by alexcrichton** [comment]
@deontologician for each activated feature `foo` Cargo will pass `--cfg 'feature="foo"'`. More information can also be found here: http://doc.crates.io/manifest.html#the-[features]-section

**Comment by sfackler** [comment]
@alexcrichton you'd still want to pass other kinds of cfgs to e.g. disable logging with `--cfg log_level="error"`

**Comment by alexcrichton** [comment]
Ah yes good point, features certainly don't cover all the use cases, just some :)

**Comment by larsbergstrom** [comment]
We have a few additional scenarios from Servo:

1) Debugging perf regressions in rustc, so we'd like to be able to add `-Z time-passes` and `-Z time-llvm-passes` to all rustc invocations, no matter which of the various feature targets we're using.

2) Probably being able to pass `-F` to forbid a certain class of lints / overrides, unconditionally, across all feature targets

3) Tweaking level of debug info at every optimization level

Note that those are off the top of my head, just things we've wanted to do in the last couple of weeks. I would much rather see you prohibit the specific rustc flags that you don't want people to pass through rather than one-by-one enable subsets from the vast array of flags that do not jeapordize your platform-independent compilation goals.

**Comment by Manishearth** [comment]
cc me

**Comment by alexbool** [comment]
and me

**Comment by gsingh93** [comment]
> 1. --cfg will manifest itself with features

I've always thought of features as a subset of cfg, not the same thing. There could be some cfg options that aren't declared as features in a Cargo.toml file.

**Comment by aidanhs** [comment]
Interested in this.
I'm currently playing with statically linked binaries (i.e. so `ldd` returns `not a dynamic executable`) and have it working, but it requires both manipulation of rustc arguments and custom invocation of the system linker. So I guess this extends a little beyond the current issue description.
Is cargo intended to allow building every possible rust project, or is is a 99% thing?

**Comment by gsingh93** [comment]
Should this be closed now that https://github.com/rust-lang/cargo/issues/595 is implemented?

**Comment by alexcrichton** [comment]
I believe so, thanks @gsingh93!

@aidanhs you may be interested in the MUSL support that was recently added, but it looks like you already ran across it elesewhere :)

**Comment by tiffany352** [comment]
Why can't cargo just have an option for setting the subsystem and providing resource files, if uninterested in allowing arbitrary linker flags to be passed? Is there an ideological preference against platform-specific options in Cargo.toml?

`cargo rustc` is insufficient for this task. Setting options like the subsystem and providing resource files are something you want to do as part of the normal build process, when you run `cargo build`. It's not an esoteric feature, it's something that is frequently done on Windows. Almost all of the GUI applications you will use on Windows are win32 subsystem, instead of console subsystem. It is inappropriate for desktop applications to use the console subsystem, because it creates a spurious and distracting console window.

Currently, setting the subsystem is usually attained by creating a custom script which wraps the linker, and then telling cargo to use that linker with `.cargo/config`. This is not a good solution.

Cargo could do something like this instead:

    [windows]
    subsystem = "windows" # remove the console, set entry point to WinMain
    entrypoint = "default" # override entry point so that the user does not have to write a WinMain
    appcontainer = false # windows 8 app store sandboxing
    resource = "something" # resource files

**Comment by alexcrichton** [comment]
Yeah there's a number of locations where that kind of configuration can be located, and some of those actually seem like they'd be more applicable as crate attributes rather than Cargo options (e.g. you'd want them even if you were running `rustc` by hand)

**Comment by Ticki** [comment]
This was referred in https://www.reddit.com/r/rust/comments/40l6t8/windowed_applications_with_rust/

**Comment by dhardy** [comment]
@gsingh93 @alexcrichton as I understand it #595 implements the `cargo rustc` command as a `cargo build` extension, but doesn't allow passing custom arguments to `rustc` when testing (aka `cargo test`)?

**Comment by alexcrichton** [comment]
@dhardy oh to do that you can do:

```
cargo rustc --profile test --test foo -- --my-args
```

**Comment by dhardy** [comment]
@alexcrichton this still doesn't run tests though, and due to the hashes in the binary names finding the binaries to run is not trivial. Is there an easy solution to build and run all integration tests?

**Comment by alexcrichton** [comment]
Well for that you may be able to use `RUSTFLAGS`, but no there's no "pass just this argument to all unit tests and please still run them" command.
