### ISSUE TITLE
Don't try to run library example

### ISSUE THREAD

**Issue by matklad** [rust-lang/cargo#5474]
It is possible to have an example, which is a library and not a binary. trying to  `cargo run` this example tries to execute `rlib`, which does not make sense at all. Instead, this should error cleanly.

Here's a reproducible example

```
~/tmp/hello master*
λ ls -T
drwxr-xr-x   - matklad  3 May 20:08 .
.rw-r--r--  46 matklad  3 May 20:07 ├── Cargo.lock
.rw-r--r-- 146 matklad  3 May 20:07 ├── Cargo.toml
drwxr-xr-x   - matklad  3 May 20:06 ├── examples
.rw-r--r--  33 matklad  3 May 20:06 │  └── foo.rs
drwxr-xr-x   - matklad  3 May 20:06 └── src
.rw-r--r--  95 matklad  3 May 20:06    └── lib.rs

~/tmp/hello master*
λ cat Cargo.toml
[package]
name = "hello"
version = "0.1.0"
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]

[[example]]
name = "foo"
crate_type = ["lib"]


~/tmp/hello master*
λ cargo run --example foo
   Compiling hello v0.1.0 (file:///home/matklad/tmp/hello)
warning: function is never used: `foo`
 --> examples/foo.rs:3:1
  |
3 | fn foo() {}
  | ^^^^^^^^
  |
  = note: #[warn(dead_code)] on by default

    Finished dev [unoptimized + debuginfo] target(s) in 0.19 secs
     Running `target/debug/examples/libfoo.rlib`
error: could not execute process `target/debug/examples/libfoo.rlib` (never executed)

Caused by:
  Permission denied (os error 13)
```

I think that `is_example` check in the code, linked above, should be replaced with `is_bin_example`, and perhaps `CompileFilter::target_run` should be adjusted as well. 

The tests for this should go to `tests/testsuite/run.rs`

**Comment by patriksvensson** [comment]
@matklad I can take this one before I do #5426.

**Comment by patriksvensson** [comment]
@matklad What should the expected behavior be when trying to execute an example library? I let `TargetKind::ExampleLib(..)` return false from `CompileFilter::target_run` but this only prevents the target from being run. Should we show a better error message here such as `example target 'foo' is a library and cannot be executed.`? I could (if I understand correctly) bail inside the `Compile::target_run` filter if trying to run an example library target, but that feels somehow wrong.

A lot of questions, but just want to get the expectations right for this one. First time I've read through the Cargo code so it's probably a lot I'm misunderstanding here. Please feel free to correct me in that case. Any input is appreciated.
