### ISSUE TITLE
cargo install fails from local git checkout

### ISSUE THREAD

**Issue by kjeremy** [rust-lang/cargo#5495]
If I clone diesel from https://github.com/diesel-rs/diesel and enter the `diesel_cli` directory and attempt to `cargo install --path .`  from there it fails to pick up a local dependency from the repo and fails to install.  See: https://github.com/diesel-rs/diesel/issues/1683 for more information.

**Comment by alexcrichton** [comment]
Thanks for the report! This is currently because `cargo install` doesn't respect workspace information. Right now it looks like the diesel crates require workspace information to work as they're relying on `[replace]` (I think?)

@sgrif would it be possible to switch diesel's internal dependencies to `path` dependencies? That way this would naturally work as well as depending on git verisons of diesel

**Comment by dwijnand** [comment]
Is it desired that `cargo install` respects workspace information?

**Comment by alexcrichton** [comment]
I think it makes sense for git and path deps yeah, but not for crates.io

**Comment by nixpulvis** [comment]
We just refactored our project to make use of workspaces, but now we don't seem to have a replacement for our install from git instructions: `cargo install --git https://github.com/jwilm/alacritty`. Original issue in jwilm/alacritty#2378.

Making matters a bit worse, is that the error message isn't very clear:

```
Caused by:
  multiple packages link to native library `freetype`, but a native library can be linked only once

...
```

I could see `cargo install --git https://github.com/jwilm/alacritty --package alacritty` being a solution for our use case anyway. This also follow from #3691, unless I'm missing something.
