### ISSUE TITLE
Warn on duplicate artifact creation

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/cargo#5524]
With a workspace such as in this repository: https://github.com/Mark-Simulacrum/cargo-issue-5524, running Cargo check on stable results in the following metadata being generated.

I believe that Cargo should try to detect the situation where duplicate artifacts will be generated and stop compilation; however, I'm not sure it's possible to do this well. I think even a heuristic that checks for lib/bin entries with the same `name` across the workspace would be sufficient for most of the benefits, though.

It's worth noting that I think this has only become an issue (at least for cargo check) since https://github.com/rust-lang/rust/pull/49289, which made `rustc --emit=metadata` emit metadata for bin targets. It might be enough to make change to rustc to disambiguate binary and lib metadata in the filename. In a way, this might be a regression, but I'm not sure.

```
$ find target -type f -name '*rmeta' | xargs ls -trl # stable 1.26
-rw-r--r-- 2 mark mark 1058 May 11 21:35 target/debug/libfoo.rmeta
-rw-r--r-- 2 mark mark 1058 May 11 21:35 target/debug/deps/libfoo-a9f370a27c2df2eb.rmeta
```

However, on beta, the following occurs:
```
$ find target -type f -name '*rmeta' | xargs ls -trl # beta 1.27
-rw-r--r-- 1 mark mark 1221 May 11 21:36 target/debug/deps/libfoo-11803c32bdc69a09.rmeta
-rw-r--r-- 2 mark mark    0 May 11 21:36 target/debug/libfoo.rmeta
-rw-r--r-- 2 mark mark    0 May 11 21:36 target/debug/deps/libfoo-f0bc89da5bcecba3.rmeta

```

cc @alexcrichton -- do you think this ought to be marked as a regression? It's confusing behavior that has only become a problem since 1.27, but I don't know whether it really warrants regression-like tracking.

**Comment by alexcrichton** [comment]
Yeah sort of like rlibs I think we could just avoid uplinking these altogether

**Comment by dwijnand** [comment]
I think if someone were to detail how to "avoid uplinking these altogether" it might expedite a fix here. 🙂

**Comment by ehuss** [comment]
@dwijnand It's not clear (to me) how safe it is to change these behaviors.  Like #6131 where someone was manually running rustc to link against rlibs created by cargo, the location of the rlibs is not easy to determine (generally need to slurp the json output to get the correct `deps` location).  If someone has some tool which looks at the rmeta files, removing them might make things more difficult for them.  I think `rls-analysis` does the [correct thing](https://github.com/nrc/rls-analysis/blob/3431cbda48795f3f37b57965d62e1dffe82f8edb/src/loader.rs#L79-L110), but it would be good to double-check if it would be impacted as it is the primary user.

In fact, I would imagine `rls-analysis` is the *only* user, so if it still works it should be fine.  It would be good to know if any other tool expects those files to exist.

The decision on what to hardlink is done [here](https://github.com/rust-lang/cargo/blob/4d45a904d4c98b6979beac2e046e7b01c4d3165b/src/cargo/core/compiler/context/compilation_files.rs#L207-L227).   The code relevant to rmeta and bin files is [here](https://github.com/rust-lang/cargo/blob/4d45a904d4c98b6979beac2e046e7b01c4d3165b/src/cargo/core/compiler/context/compilation_files.rs#L247-L259).  Essentially `link_stem` should return None if `unit.mode.is_check()`.  Also, the comment about "non-lib targets" in `calc_outputs` should be removed since it is no longer true (although a new comment should be added that it uses the term `lib` even for binary targets, which is somewhat confusing).

**Comment by ehuss** [comment]
@nrc I was under the impression that rls read the `rmeta` files somewhere, but I don't see that anywhere.  Are they used anywhere by rls?  I believe rustdoc reads them, but does anything else?

**Comment by ehuss** [comment]
Oh, and as a side note, it might be nice if `calc_outputs` also checked if any of the paths it computes are duplicated and warn or error, since that would likely indicate a bug in cargo.
