### ISSUE TITLE
indicate in cargo build whether incremental is in use

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/cargo#5542]
When we print a string like:

```
Finished dev [unoptimized + debuginfo] target(s) in 35.37s
```

it might be nice to say include `incremental` in that string?

**Comment by Eh2406** [comment]
With the progress on `incremental` would this still add value?

**Comment by eddyb** [comment]
I've just spent my day telling different people about `CARGO_INCREMENTAL=1` (and the `.cargo/config.toml` `incremental = true`, which is probably a better semi-permanent solution), and none of them were aware that release mode had it disabled.

So I think it would be useful to say `incremental` or `non-incremental` so that there's at least a hint.

**Comment by epage** [comment]
For me, there are so many different factors people might want to be present in their output and our output is already very verbose.  I would lean towards not adding this and finding what we can remove.

I'm going to propose to the cargo team that we close this.

**Comment by weihanglo** [comment]
Second.
