### ISSUE TITLE
Test harness flag --nocapture appears to disable some output coloring

### ISSUE THREAD

**Issue by Phrohdoh** [rust-lang/cargo#5553]
### Versions

```
cargo 1.26.0 (0e7c5a931 2018-04-06)
rustc 1.26.0 (a77568041 2018-05-07)
```

### Issue

This is pretty simple to repro.

1) Have a crate with tests
2) Run `cargo test`, observe *colored* `test <name> ... ok` (for example)
3) Run `cargo test -- --nocapture`, observe *uncolored* `test <name> ... ok`
4) Notice that in both cases the `Doc-tests <crate>` and `Running target/debug/...` were colored

**Comment by ajyoon** [comment]
I think this may be more of a rustc discussion, see https://github.com/rust-lang/rust/blame/master/src/libtest/lib.rs#L976. The `nocapture` flag is passed directly to the test runner generated by rustc, and it seems like rustc explicitly decides not to automatically color when that flag is passed, I'm guessing because you wouldn't want the autocoloring code trying to color stdout.

In the meantime, you can easily work around this with: `cargo test -- --nocapture --color always`

**Comment by alexcrichton** [comment]
Thanks for the report! I think this is an issue though for rust-lang/rust where the test harness lives rather than Cargo (which just forks out to the libtest test harness)
