### ISSUE TITLE
Cargo feature name validation inconsistent with crates.io

### ISSUE THREAD

**Issue by iliekturtles** [rust-lang/cargo#5554]
See https://github.com/rust-lang/crates.io/issues/1395 for original discussion. tl;dr: crates.io validation is working as desired and Cargo needs to be stricter.

Cargo's feature name validation is inconsistent with crates.io and should reject feature names that are not "mostly rust identifiers." Currently Cargo will accept feature names that are rejected by crates.io during `cargo publish` and `cargo publish --dry-run` doesn't detect the issue.

```sh
$ cargo publish
...
   Uploading uom v0.18.0 (file:///S:/uom)
error: api errors: invalid upload request: invalid value: string "1.20.0", expected a valid feature name
 containing only letters, numbers, hyphens, or underscores at line 1 column 931
```

Cargo should reject the feature name `1.20.0` prior to attempting to publish.

**Comment by MaulingMonkey** [comment]
Just ran into this with features named `"*"`, `"android::view::KeyEvent"`, etc. when publishing a set of related crates in tandem - and of course only my last crate failed to publish as a result.

Would [core::Summary::new](https://github.com/rust-lang/cargo/blob/0c891a0091a6c658c8a34df6098f31499ba0a8d9/src/cargo/core/summary.rs#L36) be a sane location to add more validation?  I assume I'd need to pass in a `Config` or `Shell` so I can emit a warning instead of a fatal error (as that'd be a breaking change for any offline, unpublished projects)?

**Comment by epage** [comment]
Added this to #4377, closing in favor of that
