### ISSUE TITLE
Need a way to bundle up the crate components into a deb, rpm, tar, zip, or installer

### ISSUE THREAD

**Issue by trink** [rust-lang/cargo#557]
*cargo package*? to invoke a package maker command (e.g., cpack, fpm, etc)

**Comment by icorderi** [comment]
+1 on both features. 
@alexcrichton do you know of any ongoing efforts on this?

A `cargo install foobar` is far more convenient and clean than:
```
git clone foobar.git, 
cd foobar
cargo build --release
ln -s target/release/foobar /usr/local/bin/.
```
> modulo error checks...

We will probably need the siblings too, `cargo uninstall foobar`, `cargo upgrade foobar`. 

While we are at it: 
- `cargo view foobar` for checking details on an installed package and, 
- `cargo list` for the list of packages, versions installed
- `cargo upgrade`, latest and greatest for all the installed crates.

`cargo package foobar` would be the manual way, allowing one to deploy without _cargo_ on the target.

**Comment by alexcrichton** [comment]
@icorderi I'm unaware of any current efforts in implementing this. I'd personally like to see something like this go through an RFC to get broader discussion and visibility as this sort of feature is often quite thorny.

**Comment by alexcrichton** [comment]
Lots has happened since this was first opened, and over time it's become clear that Cargo itself is unlikely to bundle commands such as this. With `cargo-install` now it's quite easy for these to develop externally and get installed by local users, and if they turn out to have widespread usage we can certainly reconsider inclusion!
