### ISSUE TITLE
No documentation in `cargo` crate root API reference

### ISSUE THREAD

**Issue by mitchmindtree** [rust-lang/cargo#5675]
Currently there is no documentation at all within the root of the `cargo` crate API reference - see [docs.rs/cargo](https://docs.rs/cargo).

Some sort of guidance for developers on how to get started with using the crate, initial setup (e.g. creating a `Config`), where to look for certain common patterns and an overview of what each module contains would be a massive help. As a new user of the cargo crate API I have found it very difficult to navigate, spending the last two hours attempting to work all this out in order to solve #5674 to no avail just yet.

I certainly understand that documentation is a non-trivial task, however I just thought I would start an issue for tracking this and share my experience as I surely cannot be the only one who has run into this.

**Comment by dwijnand** [comment]
This issue generalises on the older #3829 docs issue.

**Comment by weihanglo** [comment]
A module doc was added since <https://github.com/rust-lang/cargo/pull/11019> and got improved in <https://github.com/rust-lang/cargo/pull/11809>. You can also find the nightly API doc on <https://doc.rust-lang.org/nightly/nightly-rustc/cargo>!

Thanks for the issue. We are aware of the doc quality and continue making it better!
