### ISSUE TITLE
test cleanup: Add a default template for Cargo.toml

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/cargo#5743]
Lots of the verbosity in Cargo's test suite right now is from producing the same blank `Cargo.toml` over and over again. Ideally though we could just omit this entirely and Cargo's test suite would fill in a reasonable default!

For example if `Cargo.toml` is omitted then we should have a blank "pretty reasonable" `Cargo.toml` inserted in its absence.

**Comment by alexcrichton** [comment]
Sort of! Those manifests are *super* old and nowadays a default manifest wouldn't have `[lib]` or `[[bin]]`, but other than that I think that's the main idea here. Ideally we wouldn't even need `.file("Cargo.toml", manifest())` but rather it'd just happen automatically if `Cargo.toml` isn't created

**Comment by dwijnand** [comment]
Alright!

Eventually, to avoid the state to organically reoccur, we might want invest in 1 or a few clippy lint(s) 😄.

**Comment by alexcrichton** [comment]
Ok great! That's surprisingly few tests :)

I think that's ok and we could add a flag to temporarily disable this and use it in those tests? I suspect the tests could also be tweaked to deal with the existence of a root `Cargo.toml`

**Comment by dwijnand** [comment]
Meta-interesting! I almost didn't post my comment because it didn't really have a conclusion. Because my take on it was more along the lines of "well if 19 existing tests fail, how many have I invalidated by doing this?", i.e should we really be doing this. I'm probably overly conservative (read: paranoid).

I'll try and make the suite pass locally and push my proposal for review.

**Comment by alexcrichton** [comment]
Ok sounds good to me!
