### ISSUE TITLE
fetch_platform_specific_dependencies etc fails for non-x86 architectures

### ISSUE THREAD

**Issue by infinity0** [rust-lang/cargo#5864]
From #5349 @bmwill 
See e.g.

- https://buildd.debian.org/status/fetch.php?pkg=cargo&arch=arm64&ver=0.28.0-1%7Eexp1&stamp=1532885555&raw=0
- https://buildd.debian.org/status/fetch.php?pkg=cargo&arch=ppc64el&ver=0.28.0-1%7Eexp1&stamp=1532885494&raw=0

**Comment by bmwill** [comment]
This doesn't seem to be directly due to the fetch tests introduced in #5349, but rather due to the fact that the cross_compile module doesn't support platforms other than x86 (https://github.com/rust-lang/cargo/blob/master/tests/testsuite/support/cross_compile.rs#L111).  Looking at some of the other tests in the testsuite that rely on the cross_compile module, they simply do an early return if it has been disabled (e.g. https://github.com/rust-lang/cargo/blob/master/tests/testsuite/install.rs#L1049).  So it looks like the simplest way to fix this would be to do the same with the two failing fetch tests.  Give me a bit and I'll write up a short PR for that.

**Comment by bmwill** [comment]
Forgot to include the special phrase "fixes #5864" in #5870 

@alexcrichton would you mind closing this issue?  Unless you'd like to wait for @infinity0 to verify that #5870 indeed fixes the issue on their platform.

**Comment by alexcrichton** [comment]
Sure thing sounds good to me! If it's still an issue we can always reopen!
