### ISSUE TITLE
Problem with dependencies and subfolders on Windows

### ISSUE THREAD

**Issue by cyberpunkbln** [rust-lang/cargo#5882]
Hello,

i have following problems:

I want to use the repo
https://github.com/th0rex/libui-rs.git
with all crates only from this repo and with the feature static on the sub-crate ui-sys

when i use following in cargo.toml from my own testapp

```
[dependencies]
iui = { git = "https://github.com/th0rex/libui-rs.git" }
```
cargo loads from the repo and saves his correctly in .cargo\checkouts but in .registry\src\ he loads the sub-crate iu-sys-0.1.3 from the original repo https://github.com/LeoTindall/libui-rs.git ?

the iu-sys-0.1.3 in the checkout and in the registry/src  are different.

if have experimented with the path and clean cloned the https://github.com/th0rex/libui-rs.git repo
and deleted .cargo and removed the cargo-directive link in cargo toml from ui-sys

```
[dependencies.iui]
version = "0.3.0"
path = "e:\\Development\\Rust\\libui-rs-static\\iui\\"

[dependencies.ui-sys]
version ="0.1.3"
path = "e:\\Development\\Rust\\libui-rs-static\\ui-sys\\"	
features = ["static"]
```

Now now don't  compiles correctly the local ui-sys (no target folder)  with the features static but he wants to compile the original ui-sys too and breaks with the well know error "please compile static if xou don't have restricted licenced msvc:)".

```
Compiling ui-sys v0.1.3
Compiling ui-sys v0.1.3 (file:///E:/Development/Rust/libui-rs-static/ui-sys)
```

I check this when i code an special "Hey not the right file" and "horray the right file" in the different cmakefile.txt error-msgs.

Can anybody say me how i can this prevend in an fresh cargo-project and only with cargo-directive without path? Or with path?

thx

**Comment by ehuss** [comment]
Since that fork of `iui` has the dependency listed as `ui-sys = "0.1.3"` it is grabbing the version listed on crates.io.  You'll need to override that dependency in your `Cargo.toml` file.  It should look something like this:

```toml
[dependencies]
iui = { git = "https://github.com/th0rex/libui-rs.git" }

[patch.crates-io]
ui-sys = { git = "https://github.com/th0rex/libui-rs.git" }
```

It looks like the th0rex fork is maybe designed to be compiled with the gnu toolchain on Windows (it uses the flag `-Wno-c++11-narrowing` which is not a valid flag for msvc).  You might need to install that version of rustc (`rustup install stable-x86_64-pc-windows-gnu`) and use that instead (either set a rustup override or manually specify the version on the command line).  However, I tried that and got other link errors that I'm not familiar with.  I suggest you contact the author of that fork for help.

**Comment by cyberpunkbln** [comment]
@ehuss 
Thanx its functioned very well, now can i try to test the th0rex-repo.

Yes you are right, this ist the ui-sys bugfix for all user of the gnu toolchain mingw64. I don't use MSVC why it is an Microsoft-Licence and i don't know what i must install on the VC-Community-2017 big/huge Installsoftware that are only that what i need and no other, too compile all FFI-Projects. And the 2015 let me don't choose that i don't want to send all my datas to microsoft in the setup. I have read "you aknowledege to send ......" and i have installed the gnu mingw toolchain:).

Now i have seen that the th0rex-repo don't resolve the problem with the libui-rs and mingw64/32. It compiles great, when i don't use code for libui and the libui seems static linked in the exe but when i use code from libui examples he stops with a big compile/gcc warning;).

Thank you for your answer, now i can better use crates.
