### ISSUE TITLE
Can't pass flags to the compiler

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/cargo#60]
# Updated description

Arbitrary flags cannot be passed through to the compiler.
# Original Description

-O has to be the default.

**Comment by prdoyle** [comment]
+1 for "-C prefer-dynamic".  Anybody figured out the right way to do that yet?

**Comment by alexchandel** [comment]
Ugh, I need a `-C ban-dynamic`. @buster @prdoyle The big hello world is due to [rust#22159](https://github.com/rust-lang/rust/issues/22159). If you hack out allocation, it comes down to 4k (on OS X x64). Bear in mind though that the 500 kB is the amortized cost of jemalloc & friends: larger executables will have much better mileage / far fewer bytes per LOC than small ones because of this.

**Comment by prdoyle** [comment]
Sure, I get that it will be amortized, but it would be nice if Rust could be used for small programs too, even if they allocate some memory.

**Comment by alexchandel** [comment]
@prdoyle jemalloc could definitely use some optimization. I can't imagine how all 500kB could be necessary for a single malloc. Though many heap allocations could be optimized out. Yet on most platforms Rust programs are dynamically linked to the system library (glibc/libSystem/kernel32/etc), which uses 5-10MB of process memory. If we had our own system library, then a 500kB runtime wouldn't be so bad. Especially since with static linking & LTO, most programs would use a fraction of that.

**Comment by MarkSwanson** [comment]
+1 for LTO; we're thinking of building small shared objects in rust and deploying them inside Linux containers that have tight memory restrictions.

**Comment by huonw** [comment]
One can get LTO [by customising the relevant `profile`](http://doc.crates.io/manifest.html#the-[profile.*]-sections).

**Comment by maxlapshin** [comment]
This is very nice, but: https://github.com/lavrin/erlang-rust-nif/issues/3
cargo cannot compile under MacOS X without adding specific flags.

**Comment by alexcrichton** [comment]
@maxlapshin would `cargo rustc` suffice for your use case?

**Comment by zjjott** [comment]
Holy cargo....
>It should be noted that the design of cargo is currently to explicitly not allow arbitrary flags. It is very easy to have compilations go awry very quickly, 

I just want to know,a project like servo,how to use cargo for minimize version using `prefer-dynamic` args?

**Comment by PeteX** [comment]
I found this bug and got confused, so I thought I'd add a note for the benefit of other visitors.  As of November 2016 it's perfectly possible to pass arbitrary flags to rustc.  If you want to use dynamic libraries, for example, you can do either:

`cargo rustc -- -C prefer-dynamic`

or

`RUSTFLAGS='-C prefer-dynamic' cargo build`

Hope this helps someone!

**Comment by mulkieran** [comment]
@PeteX It helped me, thanks!

**Comment by learnopengles** [comment]
There also seems to be flags like CARGO_TARGET_{target-triple in all caps and with "-" replaced by "_"}_LINKER which are still needed if, for example, you want to cross-compile the tests.

**Comment by Manishearth** [comment]
> It should be noted that the design of cargo is currently to explicitly not allow arbitrary flags. It is very easy to have compilations go awry very quickly, and packages specifying flags for themselves is likely a decision that should not be up to the author but rather the builder.



I think this is a good argument for published dependencies, but less so for toplevel Cargo.tomls. We already have profiles for this, and ideally they'd be able to specify more. You can always override things via `.cargo/config` or editing the Cargo.toml.


This becomes frustrating because IDEs no longer work with projects forced to use `RUSTFLAGS` as part of their build process (e.g. Servo) since their build process is more than `cargo build`. At best they don't work, at worst they clobber builds to boot.
