### ISSUE TITLE
`cargo new` uses incorrect terminology: project

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/cargo#6056]
```console
C:\Users\steve\tmp> cargo new bar
     Created binary (application) `bar` project
```

We went with "package" over project, which is why `Cargo.toml`s have `[package]` in them. We should fix this message (and any others) to use "package" instead of "project."

**Comment by dwijnand** [comment]
> (and any others)

There's work to do in the docs too..

![image](https://user-images.githubusercontent.com/344610/45768256-4ebb0200-bc34-11e8-87de-a8ee13309e9f.png)

**Comment by zachlute** [comment]
So, I started working on this, because it seemed like pretty straightforward grunt work. And for the most part it is. But there are a couple of weird things:

1. There are sub-commands like `verify-project` and `locate-project` that probably can't change for backwards compatibility reasons. But it seems like they should just be aliases for `verify-package` and `locate-package`, which don't exist.
2. There are awkward linguistic constructs like the fact that a 'package' is a thing you can 'package', so talking about how Cargo 'makes packages, packages them, etc.' sounds super weird.

Anyway, there are a LOT of references, so I'm going to focus on just cleaning up the egregious stuff and we can go from there. Will likely do it as several PRs because it's pretty separable.

**Comment by zachlute** [comment]
Okay, those two PRs should get the bulk of places that needed to be updated.

I only updated strings/comments/docs and not any actual code unless it was just internal variable names because it's unclear to me how much we're interested in changing code to use the name 'package' and how changing things like `NewProjectKind` affects any 'public' API, but I'm happy to do additional work there if that's desired.

**Comment by ehuss** [comment]
This seems to be sufficiently completed to me, thanks @zachlute!
