### ISSUE TITLE
Appveyor minimal versions not testing on expected version

### ISSUE THREAD

**Issue by ehuss** [rust-lang/cargo#6087]
The appveyor config currently downloads rust 1.28, but that version is never used.  The default toolchain is set to "nightly", and the call to `cargo check` does not select a toolchain.

I'm not certain why the minimal-version feature needs to be tested on an older version of rust.  Since it's already being tested on travis, maybe the install of rust 1.28 can just be removed?

Also, `OTHER_TARGET` is never used in that job, so perhaps that can also be skipped (remove `OTHER_TARGET` from the matrix entry, and add `if defined OTHER_TARGET` to the install).

**Comment by alexcrichton** [comment]
Ah oops!

The thinking with using a fixed version of Rust is that minimal versions breaks over time if Rust continues to get updated due to minor changes in rustc breaking older crates (which have since published a newer version). We wanted to head off this sort of breakage by pinning rustc in addition to dependencies.
