### ISSUE TITLE
"cargo run --path"

### ISSUE THREAD

**Issue by tshepang** [rust-lang/cargo#6142]
The utility of `cargo install --path` makes me wish we had a `cargo run --path` as well... very helpful for testing functionality without needing to install. Do others have the same wish?

**Comment by crumblingstatue** [comment]
Please clarify what you want to happen.
As far as I understand, `cargo install --path foo` installs crate `foo` from a local directory containing the source code. Do you just want to run `foo` without installing it? Why not just go into its local directory and do `cargo run` there?

Is changing directories such an inconvenience that cargo needs to do it for the user?

**Comment by tshepang** [comment]
It is indeed inconvenient having to change dirs just to run (a fresh) executable.

**Comment by tshepang** [comment]
Actually that works, even if awkward... thanks @alexcrichton

**Comment by alexcrichton** [comment]
Ok, great!

**Comment by JoKalliauer** [comment]
> Is changing directories such an inconvenience that cargo needs to do it for the user?

Changing directories is an impossibility, since https://github.com/JoKalliauer/cleanupSVG/blob/master/render.sh uses different external svg2png-convertion and of them uses cargo, so the input and output-files should be kept in place (relative path) and the following renderer should be started also from the original path.

the manifest-path does not link to the path, but to the file "Cargo.toml" directly:
`cargo run --manifest-path ~Documents/GitHub/resvg/Cargo.toml --release -- in.svg out.png`

**Comment by ryankurte** [comment]
i think this also comes up when you're cross compiling packages, `--manifest-path` gets you into the directory but `.cargo/config` seems to still be loaded from wherever the command is executed (rather than from within the package)

**Comment by epage** [comment]
For `.cargo/config` see also https://github.com/rust-lang/cargo/issues/2930.  One workaround that has been talked about is https://github.com/rust-lang/cargo/issues/10098 but that would mean the program wouldn't be running from the desired CWD.
