### ISSUE TITLE
Plugin dependencies in workspace cause main crate (and its deps) to be needlessly rebuilt

### ISSUE THREAD

**Issue by crumblingstatue** [rust-lang/cargo#6143]
I have a project that has a main application, and several dynamically loadable plugins for it.

The dependencies require `plugin=true` in the `[lib]` section of their `Cargo.toml` in order to behave correctly (they need to link libstd dynamically among maybe other things).

A reduced test case can be found at https://github.com/crumblingstatue/cargo-plugin-repro .

If you build it with `cargo build --all` to build the main application and all the plugins, it will generate the executable in `target/debug`, as expected.

Now if you try to run it with `cargo run`, it will rebuild the main application, and all of its dependencies, despite it already having been built, and placed in `target/debug`.

This is not a big deal for the reduced test case, but it's a huge deal for my main application, which has many dependencies that take a very long time to build.

Removing `plugin=true` makes the issue disappear.

**Comment by ehuss** [comment]
I think I see what is happening (the `used_in_plugin` map is getting confused because things are used both for plugins and normal targets).  

@crumblingstatue The `plugin` setting is intended for compiler plugins only.  Writing application plugins is a bit tricky because the rust ABI is not stable.  If you need to dynamically link plugins, I would recommend using cdylib and `extern "C"`.  Another approach is to use some sort of IPC between processes.
