### ISSUE TITLE
Do not invoke the test runner when calling cargo bench and harness=false

### ISSUE THREAD

**Issue by lu-zero** [rust-lang/cargo#6156]
Benchers such as criterion have custom options that are not available to the test runner.

**Comment by alexcrichton** [comment]
I'm not sure I understand the context for this issue, can you elaboate? All Cargo does is execute a binary, so are you saying Cargo shouldn't execute a binary?

**Comment by alexcrichton** [comment]
@lu-zero can you provide a standalone example? `harness = false` works locally for me.

**Comment by lu-zero** [comment]
Sure, [here](https://github.com/lu-zero/testcase-benchmark) the minimal testcase

**Comment by alexcrichton** [comment]
@lu-zero I think you're seeing the benchmark for `src/lib.rs`, you'll want to say `bench = false` in the `[lib]` section.

**Comment by lu-zero** [comment]
I had to sprinkle it around all the `[[bin]]` sections as well, but did the trick :)

Now, could we make this the default behavior ?

**Comment by dwijnand** [comment]
What's the default behaviour change?  That `harness=false` under `[[bench]]` makes `cargo bench` not run lib and bins benchmarks?  If I understood correctly, that doesn't sound right.  So maybe I _didn't_ understand correctly.  🙂

**Comment by lu-zero** [comment]
It is right. 

If you are using criterion, you would not expect to have another runner being used by default.

**Comment by epage** [comment]
It is reasonable to have a mixture of different harnesses, built-in and otherwise.  The main issue here is more that there isn't a stable bench harness.

I feel like solving this issue is not aligned with longer term goals (stable bench harness, separating the concerns of harnesses and runners, etc).  I'm going to close this.  If there is a reason we should re-evaluate this, let us know!


Note that #6945 would help lower the boilerplate involved in this issue until things have improved otherwise.

**Comment by lu-zero** [comment]
in order to support mix&match we'd need something more complex to pass arguments to the different runners, as long that's available the workaround default behavior suggested stops being needed.
