### ISSUE TITLE
No explaination of what should a workspace do with Cargo.lock.

### ISSUE THREAD

**Issue by LEXUGE** [rust-lang/cargo#6172]
There's no explaination of how to deal with `Cargo.lock` in [book](https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html).
I think it should be covered to explain it clearly for freshmen just like me.

**Comment by LEXUGE** [comment]
> Thanks for the report! The same [overall rationale](https://doc.rust-lang.org/nightly/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries) for Cargo.lock applies to workspaces as normal crates, but we should more explicitly call this out for sure!

So, workspace should provide Cargo.lock as long as it contains binary?

**Comment by alexcrichton** [comment]
Ah not necessarily, it depends on your project. If it's intended to mostly be libraries then you won't want a Cargo.lock because consumers of your library aren't using Cargo.lock. If, however, it's just for your usage and no one else is depending on it externally, then it probably makes sense to use Cargo.lock to ensure reproducible builds and such betwee revisions (and track regressions).

While this often correspond to binary/library, that isn't always the case!

**Comment by LEXUGE** [comment]
Thank you!
And, will `cargo publish` push the Cargo.lock to crates.io ?

**Comment by mqudsi** [comment]
> Uh... I think we've got some bugs on that in Cargo so `Cargo.lock` doesn't always make its way to crates.io

@alexcrichton any chance you could expound on this, as I am wondering the same thing? [I have a crate for rust developers](https://github.com/neosmart/securestore-rs/) in a workspace that contains both a library and a binary for configuring the payload processed by the library. The binary is *technically* compatible with older versions of the library due to API stability but generally should be used in lock-step.

Can the `Cargo.lock` file be symlinked into the binary subdirectory, and if so, would it be used by `cargo publish`?

**Comment by ehuss** [comment]
@mqudsi I'm not sure what you mean by "symlinked".  Lock files shouldn't be symlinked in general.    If you have a binary in your package, `cargo publish` will try to include the `Cargo.lock` file automatically.  You can check what will be included by running `cargo package --list`.

**Comment by mqudsi** [comment]
Thanks @ehuss.
