### ISSUE TITLE
Marking Cargo.lock as generated

### ISSUE THREAD

**Issue by nipunn1313** [rust-lang/cargo#6180]
Our code review tool (phabricator) will automatically hide changes to files that are marked as generated (via detecting the text `@generated` in the file)

It would be convenient if Cargo.lock had `// @generated` in the file, or some customizable comment to this effect.

I *think* we can configure phabricator to avoid this issue, but it seems also reasonable to have Cargo's defaults play nicely with phabricator's defaults.

**Comment by alexcrichton** [comment]
I agree! I do regret at this point at least not having a comment at the top saying it's automatically generated. FWIW historically changing the lock file encoding is somewhat difficult because we don't want to roll it out immediately causing stable/nightly cargos to thrash on what the lock file should look like. In that sense the implementation here would take awhile to stabilize, but would look like:

* Implement support in Cargo to preserve the comment at the top of the file. That is, if Cargo sees a comment at the top of a lock file, it preserves it.
* Let this support ride the trains and bake on stable for a release or two
* Update Cargo to emit a comment by default at the top

I think we can definitely figure out how to craft a comment that covers popular systems like GitHub, Phabricator, GitLab, etc, to automatically flag the file as generated.

@dwijnand would you perhaps be interested in kicking off the implementation here?

**Comment by dwijnand** [comment]
So I had a look and I think this will have to wait for the switch from the `toml` crate to the `toml_edit` crate, as only the latter will preserve comments when deserialising/parsing.

**Comment by alexcrichton** [comment]
Oh FWIW I don't think we need to block on that per se, we already have custom serialization for the lock file (as we want it formatted a particular way) and we could relatively easily cache the first lines that appear with `#` as well to "preserve" the top-level comment

**Comment by dwijnand** [comment]
Hmm, ok let me see if I can figure that one.
