### ISSUE TITLE
cargo package does not obey .gitignore on crate in sub directories

### ISSUE THREAD

**Issue by Marwes** [rust-lang/cargo#6188]
**Problem**
Running `cargo publish`/`cargo package` on a crate in a sub-directory cargo errors because of uncommitted files despite the files being .gitignored. It does not matter if the file is gitignored at the top-level or in the crate's own directory.

**Steps**
1) Create a directory structure as 

```
.git/
.gitignore
crate/
    .gitignore
    Cargo.toml
    test.bak
    # etc
```

Where .gitignore contains

```
*.bak
**/*.bak
```

or any combination thereof

2) Run `(cd crate && cargo package)`

**Notes**
Current workaround is to do `git clean -fxd` before releasing (which clears a bit to much).

```
cargo --version --verbose
cargo 1.31.0-nightly (5dbac9888 2018-10-08)
release: 1.31.0
commit-hash: 5dbac98885199bbd7c0f189d7405b5523434d1e3
commit-date: 2018-10-08
```

**Comment by alexcrichton** [comment]
This is probably due to how we detect subcrates and such and I think at least something along the chain ignores gitignore entirely by accident. The relevant code for this is all [roughly around here](https://github.com/rust-lang/cargo/blob/efb7972a095bcd043dfd55edca3a3fd1590b34c8/src/cargo/sources/path.rs#L89-L250)
