### ISSUE TITLE
Allow place holders in build.target-dir

### ISSUE THREAD

**Issue by ensc** [rust-lang/cargo#6210]
I would like to configure `CARGO_TARGET_DIR` globally so that build happens on a faster/larger partition than `${HOME}` (usually on NFS).

Setting 

```
[build]
target-dir = "/home/ensc/.cache/cargo"
```

in global `~/.cargo/config` causes bad effects because builds of different software packages are mixed in a single directory.

It would be nice when `target-dir` accepts some place holders like

```
[build]
target-dir = "/home/ensc/.cache/cargo/%X"
```

where `%X` can be

- `%C` ... the hash of the directory with `Cargo.toml`
- `%P` ... the full path of the directory with `Cargo.toml`
- `%N` ... the `package.name` (seems to be difficult with recent code)

**Comment by joseluis** [comment]
`%H` ... the hostname

This would be useful in my case, since I work in the same project on different architectures, and I need to have separate target-dir per system.

I currently use `CARGO_TARGET_DIR="$(echo "target-$(hostname)")"` but this has the disadvantage of the target-dir being created in the working directory, instead of the root directory, which is annoying.

I really miss solution for having a custom target-dir name relative to the root of the project, not the current working directory.

**Comment by phiresky** [comment]
Solved this for myself by putting this in my ~/.zshrc

```zsh
autoload -Uz add-zsh-hook
function cargo_target_chpwd {
	local dir=$PWD:t # just the last path component of the project
	export CARGO_TARGET_DIR=~/.cache/cargo-target/$dir
}
add-zsh-hook chpwd cargo_target_chpwd
cargo_target_chpwd # initial shell start
```

Basically just resets the cargo target dir on every dir change.

Same should be possible for other shells.

**Comment by epage** [comment]
As this is attempting to solve the same problem as #11156, I'm going to close in favor of that.  Though the title of #11156 is more specific, the discussion has broadened to how to solve the need.  If there is a reason we should re-evaluate this, let us know!
