### ISSUE TITLE
Progress Bar doesn't update new lines with Git Bash (MINGW64?)

### ISSUE THREAD

**Issue by khionu** [rust-lang/cargo#6223]
### Steps to reproduce
1) Open Git Bash on Windows in crate directory
2) Do not adjust the window
3) Run `cargo build`

### Result
https://files.khionu.net/ss/2018-10-26_19-11-11.gif

Note, this does not occur after making the window larger

**Comment by ehuss** [comment]
This should be fixed in 1.31 (sorta, it's [locked at 60 columns](https://github.com/rust-lang/cargo/pull/6122)). If you make your terminal over 120 characters wide, it should work. Another option is to set TERM=dumb environment variable, although that will also disable color. Apologies, I hadn't considered backporting this into 1.30.

**Comment by khionu** [comment]
I've confirmed that this is fixed on nightly. Could this be backported as a patchfix?

**Comment by alexcrichton** [comment]
Thanks for the confirmation! This'll be in 1.31 and if a 1.30.1 release happens we can consider putting this in there too.
