### ISSUE TITLE
Problems with cross build bootstrap Cargo on NetBSD/sparc64 

### ISSUE THREAD

**Issue by MartinHusemann** [rust-lang/cargo#6226]
This is a bit tricky to reproduce (and you probably will not want to bother), but I'd be happy to get some advice where to look and dig deeper myself.

A bit of background: since the official binaries for NetBSD/sparc64 do not include Cargo, we try to cross compile a full bootstrap kit for rust 1.29.2. This kit does not work, and the failure is strange:

/usr/pkgobj/lang/rust/work/rust-bootstrap/bin/cargo build --manifest-path
/usr/pkgobj/lang/rust/work/rustc-1.29.2-src/src/bootstrap/Cargo.toml --frozen
error: failed to parse manifest at
`/usr/pkgobj/lang/rust/work/rustc-1.29.2-src/src/tools/clippy/Cargo.toml`

Invoking the cargo command manually shows:

  the cargo feature `edition` requires a nightly version of Cargo, but this is the `stable` channel

The toml file clearly requests "edition", it starts with:

cargo-features = ["edition"]

[package]
name = "clippy"
version = "0.0.212"

However, it works fine for the amd64 bootstrap cargo, and that one even claims to be older:

amd64:
        cargo 1.28.0 (96a2c7d16 2018-07-13)
 
sparc64: 
        cargo 1.29.0

(that is output of /usr/pkgobj/lang/rust/work/rust-bootstrap/bin/cargo --version)

I notice that the (official) amd64 bootstrap cargo has a hash and a date, while the cross build one does not. I assume there is something wrong with the bootrap cargo, but I have no idea what and where to look. Does this ring a bell?

How to reproduce: on a NetBSD sparc64 machine check out pkgsrc (HEAD)
 and then go to lang/rust and do "make".

Is the "edition" feature conditionally compiled into cargo and we are missing the proper setting somewhere?

**Comment by ehuss** [comment]
`x.py` in the rust build system sets the environment variable `RUSTC_BOOTSTRAP=1` to overcome this.  That should work on 1.28 and 1.29.  See also rust-lang/rust#52935.

**Comment by alexcrichton** [comment]
Indeed it looks like this may be more related to rust-lang/rust, so I'm going to close this

**Comment by he32** [comment]
Hm, not so fast...

I should perhaps note that I'm producing the "unofficial" bootstrap kits for the NetBSD ports using the powerpc, sparc64 and earmv7hf processor types (the latter of which hasn't been tested yet, AFAIK).  All these bootstrap kits are produced the same way, from the same sources, using, presently, rust 1.29.2.  The build is done using `x.py dist`, and the bootstrap kit bits are picked up from `build/dist/` after the build completes.

Also, the cross-compiled (from NetBSD/amd64) powerpc bootstrap kit works just fine, and is able to build rust natively, again using `x.py dist`.  Cargo from the powerpc bootstrap kit when run as `cargo --version` reports `cargo 1.29.0`, which is identical to what the sparc64 version reports, ref. above.

So... Isn't it so that `x.py` already sets the `RUSTC_BOOTSTRAP=1` environment variable?  It certainly seems to be the case, ref. `src/bootstrap/bootstrap.py`'s `build_bootstrap` function.

So apparently something is "different" with the sparc64 bootstrap kit, and Martin is asking for hints where to start looking.

**Comment by MartinHusemann** [comment]
OK, you were right. The bootstrap rustc gets a SIGBUS.
I guess I'll just give up on this language and on firefox. Too much pain.
