### ISSUE TITLE
Failure to package on FAT-family filesystems

### ISSUE THREAD

**Issue by khionu** [rust-lang/cargo#6238]
**Problem**
Packaging on FAT-family filesystems fails on attempting to set the Modified Time.

**Steps**
1) Run `cargo package` on a FAT32 or exFAT filesystem

**Possible Solution(s)**
Take advantage of the flag added [here](https://github.com/alexcrichton/tar-rs/commit/f442964da22bce0c66aad004e01bf6d4fb3adeb9).

**Comment by alexcrichton** [comment]
To add some more context, this started out as https://github.com/alexcrichton/filetime/issues/30, went to https://github.com/alexcrichton/tar-rs/issues/169, and culminated in https://github.com/alexcrichton/tar-rs/commit/f442964da22bce0c66aad004e01bf6d4fb3adeb9. 

The problem here is that not all filesystems allow configuring the mtime (for whatever reason), but Cargo tries to set the mtime of files when it extracts them from a tarball. Cargo doesn't actually really need to do that though, so it should be easy enough to simply call `set_preserve_mtime(false)` on tarball extraction
