### ISSUE TITLE
What exactly is `.cargo-ok` and why is `Cargo.toml` modified?

### ISSUE THREAD

**Issue by dpc** [rust-lang/cargo#6340]
I am working on a tool that would verify the integrity of cargo packages and check it against community maintained cryptographicaly signed review records. It works by calculating a recursive checksum of the whole package directory tree and comparing it with signed checksum by authors and other users.

The problem is that cargo packages on disk are different than what was uploaded originally.

It's not a show-stopper, but it is limiting me somewhat: first I am unable to make sure that `crates.io` (or any other package server) did not mess with the package since the checksum is different pre-download from the post-download.

Second, I am not sure how to treat `.cargo-ok`. Is it part of the source code or not?

Ideally, it would be great if I could somehow get the source code in the original (pre-upload) state. Second best option would be to at least limit number of modifications. Could the `.cargo-ok` be stored somewhere else entirely?

**Comment by alexcrichton** [comment]
Good questions! The `.cargo-ok` file is [created here](https://github.com/rust-lang/cargo/blob/c93e84716d279cdff11304cef627f8eb72dd7e9a/src/cargo/sources/registry/mod.rs#L427) and serves as a marker for "cargo has fully extracted the tarball and the directory is ready to go". This is done because currently Cargo unpacks directly into the destination directory, and if Cargo is ctrl-c'd halfway through we want to be able to recover the next time Cargo is run. 

When you mention that `Cargo.toml` is modified, what do you mean relative to? Relative to the package on crates.io? Or relative to the original source git repository?

FWIW nowadays Cargo will try to insert a `.cargo-vcs.json` into each published crate indicating the git sha the publish came from.

**Comment by dpc** [comment]
@bluss I wasn't aware of the `Cargo.toml.orig`. Is it the local cargo on publishing, or crates.io after receiving?

**Comment by bluss** [comment]
The Cargo.toml.orig one is the one in the repository, how it looks to me when I publish that crate. I can see that cargo contains the code for doing this rewriting, so I think it's all client side.

**Comment by bluss** [comment]
The Cargo.toml.orig file isn't used to build anything (again, surely not, but is that a correct assumption?) so it seems futile to verify that file. Instead maybe verify the translation to Cargo.toml (a tougher task).

**Comment by dpc** [comment]
The goal of my project is to cryptographicaly verify the content hasn't change since public reviewed it. This is to give people confidence that even the author of the package, or crates.io have tampered with it. It might be especially useful for high trust code like Bitcoin/cryptocurrency projects: https://github.com/rust-bitcoin 

I think I'm fine with verifying the "post-processed" package, however I wish I could get some commitment that cargo/crates.io will avoid changing the structure of the directory. From my perspective it would be best if the extracted package looked exactly like the one uploaded by the author, and added metadata and control information like `.cargo-ok` lived in a different directory.

**Comment by alexcrichton** [comment]
I'm not really sure about future plans for Cargo, but rewriting `Cargo.toml` was motivated to fix various scenarios one way or another. I think it seems reasonable though to say that Cargo will always keep the original file if it's modified on publish, so perhaps that could work?
