### ISSUE TITLE
Switch to pretty_env_logger?

### ISSUE THREAD

**Issue by dwijnand** [rust-lang/cargo#6348]
https://github.com/seanmonstar/pretty-env-logger is pretty.  Anyone feel for or against switch to it?

**Comment by Eh2406** [comment]
👍 from me, and I would be ok fixing #6189 at the same time.

**Comment by alexcrichton** [comment]
I'm personally a fan of `env_logger` due to how minimal it is where this isn't really an oft-used feature of Cargo that we want to pay a lot for in terms of dependencies, compile time, code size, etc. Along those lines I think I'd personally prefer to stick with `env_logger` today, but I don't feel too strongly!

**Comment by dwijnand** [comment]
@alexcrichton what if I feature flag it?  My usecase is when debugging cargo in tree anyways 😄

**Comment by alexcrichton** [comment]
Seems plausible to me!
