### ISSUE TITLE
Request: make `cargo test` trigger a warning if there's unused Rust code in tests directory

### ISSUE THREAD

**Issue by jamescostian** [rust-lang/cargo#6379]
I wanted to write integration tests for some code, so I created a `tests` directory and wrote some tests in it. But some of my tests were written in a *subdirectory* of `tests` - e.g. `tests/foo/bar.rs` - and they were all ignored. It took me quite a while to figure out that my tests weren't even running. After I made `tests/foo/mod.rs`, I still had to add `mod foo` to some file in `tests` - another easy mistake to make, that results in zero warnings.

But even after fixing those issues, I still wouldn't be very safe. If I were to create `tests/foo/uh_oh.rs` then that file wouldn't be executed (because I didn't update `tests/foo/mod.rs`) and, again, I won't receive any warnings that my tests aren't running. I'm not sure if this is the right place for this issue (perhaps clippy is a better fit for finding this problem?), but I do think that this behavior is surprising

**Comment by dwijnand** [comment]
I'm all for finding good ways to "test the tests".  But isn't this more of a general problem around programming in Rust?  I think it makes sense to having some kind of linting/doctor tool for rust sources in general (and then find ways to use that in cargo).

So in that light, I'm inclined to close this.  But let me know your thoughts!

**Comment by ehuss** [comment]
Cargo may be the best situated to discover this, since it knows which files are used and the structure of the targets. However, it may be difficult or impossible to do due to conditional compilation. Modules can be disabled with cfg attributes among other things, and it would be difficult to reliably get an exhaustive list.  If you want to hack something together, you can try to run `cargo check --all-targets` and then read all the dep-info files (`target/debug/deps/*.d`) to see which files were used and compare to the list of files on the filesystem.  However, it will miss all disabled modules.
