### ISSUE TITLE
Cargo fix errors

### ISSUE THREAD

**Issue by termhn** [rust-lang/cargo#6390]
**Problem**
Running `cargo fix` on `rendy` fails on two files. Asks to report but with full output.

**Steps**
Clone rustgd/rendy, run `cargo fix`.

**Notes**

Output of `cargo version`: cargo 1.31.0 (339d9f9c8 2018-11-16)

Full output: https://gist.github.com/termhn/f02fdee4b79563c47a1238a558a916aa

**Comment by ehuss** [comment]
Thanks for the report. This looks to be due to a bad suggestion in the rust_2018_compatibility lints previously reported at https://github.com/rust-lang/rust/issues/56327.  You can remove the `dyn` keyword [here](https://github.com/rustgd/rendy/blob/8eecae13a3c75e927e412b074b27e2521e8316a5/wsi/src/lib.rs#L63) and [here](https://github.com/rustgd/rendy/blob/8eecae13a3c75e927e412b074b27e2521e8316a5/factory/src/factory.rs#L381) to work around it, or not use the `rust_2018_compatibility` lints.

**Comment by termhn** [comment]
👍 After adding the `edition = "2018"` and re-running cargo fix, then compiling, I ended up needing to re-add those `dyn`s to make it happy.
