### ISSUE TITLE
Is there a way to run cargo doc and only get the documentation for direct dependencies of my project? 

### ISSUE THREAD

**Issue by arthmis** [rust-lang/cargo#6421]
**Describe the problem you are trying to solve**

Whenever I run cargo doc, it builds the documentation for all the dependencies of the project. The problem is that I don't want all the documentation for every crate. I only want the documentation for the crates that are direct dependencies of my project and not the dependencies of my project's dependencies. 

**Describe the solution you'd like**

I would prefer if the default behavior of cargo doc only builds the documentation for my project and its direct dependencies.

**Comment by alexcrichton** [comment]
There isn't currently, but a flag could be added!

**Comment by dwijnand** [comment]
Plausible flag names?  `--direct-deps-only`?

**Comment by lazypassion** [comment]
Is there a reason cargo doc builds the documentation for every dependency of the project and not only the direct dependencies?

**Comment by ehuss** [comment]
This may be a duplicate of #2025.

**Comment by yuyoyuppe** [comment]
I'd like to help implementing this, but I wonder what is the expected behavior of links which refer to the "undocumented" crates? some options OTOH:
- make them lead to a special "not documented" page
- transform the links so they refer to the official docs.rs page

I'm not yet familiar how the `doc` command works, so maybe those links won't be generated in the first place. 

I also wonder if it's possible to avoid building the documentation of the indirect dependencies entirely, not just hiding after the fact, since building them is a time-consuming process.

**Comment by ehuss** [comment]
Closing as a duplicate of #2025.
