### ISSUE TITLE
Allow dependencies to lock to yanked libraries if no unyanked versions are available.

### ISSUE THREAD

**Issue by Lymia** [rust-lang/cargo#6558]
Yanking a crate can break unrelated crates that are published on crates.io that depend on it, especially if it uses `=1.0.0` dependencies or similar. While binaries can rely `Cargo.lock`, libraries do not have a similar mechanism.

e.g. if `foo=1.0.0` depends on `bar>=0.0.1`, but `bar=0.0.1` is yanked in favor of `bar=0.1.0`, this effectively yanks `foo`, because any attempts to build it without a preexisting lock file will result in `bar` not being resolved for `foo`. Therefore, if `bar` was a common dependency, this has the potential to effectively yank a large portion of the crates.io ecosystem until those dependencies are updated.

Allowing dependencies to lock yanked versions if there are no unyanked versions it's compatible with would cover many of the use cases of #4225 and make the crates.io ecosystem more resilient against `left-pad` style issues.

I understand that yanking is meant for malicious releases and serious security bugs. However I find it equally problematic that someone who owns a dependency of a crate can effectively also yank all their reverse dependencies, so I feel that something like this definitely warrants discussion.

**Comment by jonas-schievink** [comment]
Yeah this would be nice. We've had our production build break once, because all semver-compatible versions of a dependency were yanked. Granted, we should've checked in the Cargo.lock since this is a binary, but this could just as well happen when running CI for a library crate (where Cargo.lock is recreated on each build).

**Comment by Stebalien** [comment]
This just hit several rust crates due to https://github.com/bitvecto-rs/funty/issues/7. Unfortunately, lockfiles aren't sufficient if you need to release a tree of inter-dependent _libraries_.

**Comment by epage** [comment]
Since this was created, the recommendation around lockfiles has changed, see https://doc.rust-lang.org/nightly/cargo/faq.html#why-have-cargolock-in-version-control

While this acknowledges #4225 as an alternative, I'm going to close this issue in favor of that issue so we can discuss the problem holistically in one place.
