### ISSUE TITLE
Optional dependencies causing build process to break during download phase on musl, static, target

### ISSUE THREAD

**Issue by jeromegn** [rust-lang/cargo#6566]
**Problem**
I've been trying to compile my crate as a static binary on a musl target (on alpine). It worked fine for one of our member crate ([create_snapshot](https://github.com/superfly/fly.rs/tree/master/create_snapshot)), but it doesn't for the member crates with more dependencies because some of them require proc macros.

These may be in optional dependencies. However, the build stops short at the "download" stage which downloads all dependencies optional or not. Meaning my build will fail even if it may not have to compile any crate which use proc macros.

**Steps**
1. Pull down the [static-binary branch](https://github.com/superfly/fly.rs/tree/static-binary) of fly.rs
2. `docker build .` (will compile V8 with musl and build all our dependencies)

**Possible Solution(s)**
Check for procedural macros in dependent crates at compile time, not in the download phase.

**Notes**

I'm using static libc and libstdc++ (since I need to bind to a C++ library), but that seems fine since I can compile the `create_snapshot` crate statically.

Because I needed a libstdc++, I couldn't just cross-compile since I needed it to be compiled with musl, which is not the case on platforms other than alpine linux (afaict)

Output of `cargo version`: cargo 1.31.0
OS: alpine:edge via a Docker image
Target: x86_64-linux-alpine-musl (not cross-compiling)

**Comment by ehuss** [comment]
This is unrelated to the download phase.  What is happening is that after everything is downloaded, Cargo is doing some analysis to figure out the outputs each crate will create.  Since you have `RUSTFLAGS="-C target-feature=+crt-static"` it is causing an error because that flag is incompatible with proc-macros.

What you can do is add `--target x86_64-alpine-linux-musl` to the cargo command-line.  This will cause it to treat host dependencies (proc-macros and build scripts) differently, and they will not pick up the flag.

Another alternative (I think) is to use the command `cargo rustc -- -C target-feature=+crt-static` which will pass the given flag only to the final build step.

**Comment by jeromegn** [comment]
Your first solution did fix it. I didn't think the target would be meaningful since I'm building on a host that matches that target. I thought it would implicitly use that target parameter.

(I haven't tried the alternative)

This is indeed a different issue, closing.

Thanks!
