### ISSUE TITLE
Cargo new should not git init when already in a git repository

### ISSUE THREAD

**Issue by tomaka** [rust-lang/cargo#664]
Sometimes I use `cargo new` to build a sub-package inside another package (useful for macros for example), but `cargo new` automatically creates a new git repo even if you are already in a Cargo project with a git repo.

**Comment by cal97g** [comment]
Cargo should not create a git repository at all. Now I have to remove .git from all the projects I just inited so I can create a proper repo according to specifications I actually want.

**Comment by ChrisDenton** [comment]
I believe you're looking for the `--vcs` option. This can also be set in a [Configuration file](https://doc.rust-lang.org/cargo/reference/config.html).

**Comment by cal97g** [comment]
> I believe you're looking for the `--vcs` option. This can also be set in a [Configuration file](https://doc.rust-lang.org/cargo/reference/config.html).

Thanks, that is useful. However, I had no idea that cargo is making assumptions about my repository config, just because I hadn't yet created a git repository in the root of my folder doesn't mean that cargo should assume what I want and create one.

It's doing things I'm not asking for, which tools should never do. If anything, there should be a `--with-git` flag to make it explicit.
