### ISSUE TITLE
When a proc_macro creates files in the crate root, each consecutive call to `cargo build` run the compiler only if build.rs exists

### ISSUE THREAD

**Issue by Llaurence** [rust-lang/cargo#6793]
**Problem**

When proc_macros write files in the project root, consecutive calls to `cargo build` run the compiler only if `build.rs` exists.

By consecutive I mean no change to the source code, or any other file in the crate. The only changes are made by the execution of proc_macros.

**Steps**

In this example: https://github.com/Llaurence/cargo-rerun, the proc_macro `makk` writes a file `cat.jpg` in the crate root, and then `println!` a string.
Notice that when `cargo build` is run twice in a row, the string is printed twice.

Now remove `build.rs`. Running `cargo build` doesn't print the string anymore.

**Possible Solution(s)**

**Notes**

Output of `cargo version`:

```
cargo 1.35.0-nightly (0e35bd8af 2019-03-13)
```

Linux x64

**Comment by ehuss** [comment]
This is to be expected.  When a build script does not emit any `rerun-if-*` statements, it assumes any change to any file in the project will trigger a rebuild.  You can read more about build scripts at https://doc.rust-lang.org/cargo/reference/build-scripts.html.  One technique to restrict what triggers a rebuild is to print `cargo:rerun-if-changed=build.rs` so that the build script only re-runs if itself is changed.

**Comment by Llaurence** [comment]
Alright. Thank you for the detailed answer!
