### ISSUE TITLE
Borrow checker doesn't work 

### ISSUE THREAD

**Issue by mkbanchi** [rust-lang/cargo#6890]
**Problem**
Build of a package through `cargo build` doesn't fail when code violates borrowing rules.

**Steps**
1. Create a new package with `cargo new test_pkg`;
2. Edit `main.rs` with classic code violates borrowing rules:
```
fn main() {
    let mut x = 5;
    let y = &mut x;
    *y += 1;
    println!("{}", x);
}
```
3. Build with `cargo build`: build succeded.

**Notes**

Output of `cargo version`: cargo 1.33.0 (f099fe94b 2019-02-12)

Compiling `main.rs` with `rustc main.rs` fails (as expected) with error E0502.

**Comment by sfackler** [comment]
Cargo builds your crate with the 2018 edition, where the non-lexical lifetime support makes this code legal.

**Comment by mkbanchi** [comment]
Thank you for your comment, i missed that. But why, by default, non-lexical lifetimes support is enabled for `cargo` and not for `rustc`?

**Comment by sfackler** [comment]
`cargo new` puts an `edition = "2018"` line in your Cargo.toml which causes cargo to pass `--edition 2018` to rustc.

**Comment by ehuss** [comment]
Yea, this is expected behavior.  You can read more about non-lexical lifetimes [here](https://doc.rust-lang.org/nightly/edition-guide/rust-2018/ownership-and-lifetimes/non-lexical-lifetimes.html).  Also, the most recently nightly (1.36.0) now includes NLL in the 2015 edition, so your example will work without the `--edition` flag.
