### ISSUE TITLE
[[bin]] stanza of Cargo.toml not documented well

### ISSUE THREAD

**Issue by jweinst1** [rust-lang/cargo#6913]
**Problem**

In various crates on github, i have seen that the `[[bin]]` stanza in Cargo.toml can be used to specify executables that will be installed upon installing the crate, such as

```toml
[[bin]]
bench = false
path = "src/main.rs"
name = "rg"
```
Except, that stanza is not documented well on https://doc.rust-lang.org/cargo/reference/manifest.html it mentions it as specifying an executable, but not anything about where that executable is installed, or that it's even put on the PATH. I think this would be an important knowledge point because it's relevant to how executables can be used after installing a crate, instead of doing `cargo build` and `cargo run`.

**Steps**

1. Go to https://doc.rust-lang.org/cargo/reference/manifest.html
2.
3.

**Possible Solution(s)**

Document the following

1. More info on how executables are installed, should be similar in explanation to make install from cmake.
2. What the `[bin]` stanza means and how it relates to executables getting put on the PATH.

**Notes**

Output of `cargo version`: Not applicable , docs related

**Comment by ehuss** [comment]
Seems reasonable to have a short note to indicate that `[[bin]]` and `[[example]]` targets can be used with `cargo install`.

Just FYI, the documentation for installation is on the [cargo install](https://doc.rust-lang.org/cargo/commands/cargo-install.html) page, which explains where binaries are installed.

I have a long-term goal to split up the manifest.md page into separate pages since it is somewhat disorganized. One of those pages would be "Cargo Targets" which would have detailed information about the different target kinds, and might do well to include this.

**Comment by jweinst1** [comment]
I see, makes sense.

Basically I am approaching this from a stand point of _"I want to make a cli program people can use from their terminal, how can I do this so it's installed correctly?"_ 

Once I found out that if the `[bin]` is specified they can just install the crate and be ready to go that was a huge buy in for me to choose rust for some of my side projects over C++, as with C++ you need to have cmake, xcode cli tools (if on mac), run several commands, make sure the cmake install prefix is correct, etc. etc.
