### ISSUE TITLE
interaction with sccache changed, all deps rebuilt when calling "cargo build" twice

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/cargo#6976]
````
cargo 1.36.0-nightly (c4fcfb725 2019-05-15)
release: 1.36.0
commit-hash: c4fcfb725b4be00c72eb9cf30c7d8b095577c280
commit-date: 2019-05-15
````

When using sccache (via `RUSTC_WRAPPER`), running `cargo build ; cargo build` will cause all dependencies to be rebuilt even if nothing changed between the two "cargo build" runs.
(I'm not very sure what is actually happening, since the second run is consistently faster than the first run)
````
cargo clean ; cargo build ; cargo build

   Compiling serde v1.0.80
   Compiling ryu v0.2.7
   Compiling itoa v0.4.3
   Compiling serde_json v1.0.39 (/home/matthias/vcs/github/serde_json)
    Finished dev [unoptimized + debuginfo] target(s) in 4.43s
   Compiling itoa v0.4.3
   Compiling serde v1.0.80
   Compiling ryu v0.2.7
   Compiling serde_json v1.0.39 (/home/matthias/vcs/github/serde_json)
    Finished dev [unoptimized + debuginfo] target(s) in 1.48s
````
This is not the case when sccache is not used or when `RUSTC_WRAPPER` is unset:
````
   Compiling serde v1.0.80
   Compiling ryu v0.2.7
   Compiling itoa v0.4.3
   Compiling serde_json v1.0.39 (/home/matthias/vcs/github/serde_json)
    Finished dev [unoptimized + debuginfo] target(s) in 11.65s
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
````

According to my bisect, 6b28a0c0505f19a574a44bffdeccbc07a2d25980 is the commit that caused this strange behaviour.

**Comment by matthiaskrgr** [comment]
Just to be clear, the ticket is about none-pipelined compilation (unless there is something that turned it on by default that I missed).

**Comment by lzutao** [comment]
Is this related to #6978 ?

**Comment by alexcrichton** [comment]
I was personally unable to reproduce this yesterday, @matthiaskrgr can you detail how to reproduce this? (for example what version of sccache, what project, perhaps a minimal example, etc)

**Comment by ehuss** [comment]
I'm able to reliably reproduce it.  I'm fairly certain this is because Cargo is now producing both rlib and rmeta files, even when pipelining is not enabled.  Sometimes sccache detects it (presumably some kind of race?), but usually the rmeta files don't get created.  I would think this issue needs to be filed on sccache?  Unless @alexcrichton wants to change it so that Cargo can handle rmeta files mysteriously disappearing.  There was a similar issue in the Clippy repo where it was deleting rmeta files, causing everything to be rebuilt (already fixed https://github.com/rust-lang/rust-clippy/pull/4115).

**Comment by matthiaskrgr** [comment]
I use sccache from the git repo https://github.com/mozilla/sccache , commit ce983d5d1b8d35c71e6b99a6a9b17ed17a6dad1a
build it in release mode and copy it into ~/.cargo/bin/

I have RUSTC_WRAPPER set as /home/matthias/.cargo/bin/sccache

I can repro for example building https://github.com/serde-rs/json at 5b5f95831d9e0d769367b30b76a686339bffd209
````
 matthias@t470  ~/vcs/github/serde_json   master  cargo build
   Compiling ryu v0.2.7
   Compiling serde v1.0.80
   Compiling itoa v0.4.3
   Compiling serde_json v1.0.39 (/home/matthias/vcs/github/serde_json)
    Finished dev [unoptimized + debuginfo] target(s) in 4.16s
 matthias@t470  ~/vcs/github/serde_json   master  cargo build
   Compiling itoa v0.4.3
   Compiling ryu v0.2.7
   Compiling serde v1.0.80
   Compiling serde_json v1.0.39 (/home/matthias/vcs/github/serde_json)
    Finished dev [unoptimized + debuginfo] target(s) in 1.13s
````

**Comment by alexcrichton** [comment]
Ah thanks for confirming @ehuss and for the extra info @matthiaskrgr. If this is an issue with `sccache` then I think yeah we can move it to that repository, and it sounds like that's the case?

**Comment by luser** [comment]
[I looked into this briefly ](https://github.com/mozilla/sccache/issues/436#issuecomment-496520149) and found that sccache isn't caching the rmeta outputs, but there's an existing workaround that pointed to https://github.com/rust-lang/rust/issues/54852 and testing shows that rustc does not in fact list the rmeta filename when calling it with `--print=file-names`, so that is likely the underlying issue!

**Comment by matthiaskrgr** [comment]
This has been fixed on the sccache side :+1:
