### ISSUE TITLE
Workspace: unable to control version dependencies

### ISSUE THREAD

**Issue by lostman** [rust-lang/cargo#7067]
**Problem**

I've been looking for best practices for maintaining Cargo workspace dependencies. I would like to control which crates/versions are allowed. I came across this passage:

https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html#depending-on-an-external-crate-in-a-workspace

> Notice that the workspace has only one Cargo.lock file at the top level of the workspace rather than having a Cargo.lock in each crate’s directory. This ensures that all crates are using the same version of all dependencies.

However, this is not what I observed in practice.

**Steps**
```
==> Cargo.toml <==
[workspace]
members = [
    "a", "b"
]

==> a/Cargo.toml <==
[package]
name = "a"
version = "0.1.0"
edition = "2018"

[dependencies]
libc = "0.2.54"
rand = "0.3.23"

==> b/Cargo.toml <==
[package]
name = "b"
version = "0.1.0"
edition = "2018"

[dependencies]
libc = "0.2.55"
rand = "0.6.4"
```

```
$ cargo build
   Compiling autocfg v0.1.4
   Compiling libc v0.2.58
   Compiling rand_core v0.4.0
   Compiling rand_core v0.3.1
   Compiling rand_jitter v0.1.4
   Compiling rand_hc v0.1.0
   Compiling rand_isaac v0.1.1
   Compiling rand_xorshift v0.1.1
   Compiling rand_pcg v0.1.2
   Compiling rand_chacha v0.1.1
   Compiling rand v0.6.5
   Compiling rand v0.4.6
   Compiling rand_os v0.1.3
   Compiling rand v0.3.23
   Compiling a v0.1.0 (/tmp/rs-cargo-workspace/a)
   Compiling b v0.1.0 (/tmp/rs-cargo-workspace/b)
```
Questions:
1. Why did Cargo chose to install `rand v0.6.5`?
2. Why are there multiple versions of `rand` but only a single `libc`?
3. Why `libc` version is neither of those specified?

**Possible Solution(s)**

**Notes**

Output of `cargo version`:
```
cargo 1.36.0-nightly (759b6161a 2019-05-06)
rustc 1.36.0-nightly (372be4f36 2019-05-14)
```

**Comment by ehuss** [comment]
Cargo only unifies semver-compatible versions.  So if one package specifies `1.0` and another specifies `1.1`, they will both use the most recent `1.x.y` version.  However, a third package specifies `2.0`, then it will use the most recent `2.x.y` version without affecting the other two.

Versions before `1.0` are treated a little differently.  In your example, `0.6` is considered incompatible with `0.3`, so they are not unified.  `libc` is unified because `0.2.x` is compatible with all other `0.2` versions.

As for why `libc` chose a newer version, when you specify a version in `Cargo.toml`, without a qualifier it is a "caret requirement" which means it will pick the newest version available that is compatible.

You can read more about this here: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html

**Comment by basvandijk** [comment]
Thanks for this explanation!

There's still one thing unclear to me: 
I understand why `rand-0.6.5` is installed; because `b` depends on `rand = "0.6.4:`. I also understand why `rand-0.3.23` is installed; because `a` depends on `rand = "0.3.23"`.

What I don't understand is why `rand-0.4.6` is installed. Where is this dependency coming from?

**Comment by ehuss** [comment]
Ah, `rand` is a tricky example.  `rand 0.3` has a [dependency on `rand 0.4`](https://github.com/rust-random/rand/blob/84dffa9999dcc58eb6e3145ecd9e3f9e3a2c4e92/Cargo.toml#L25).  This is a "forwards compatibility" trick some crates employ.  This allows `rand 0.3` traits to be compatible with `rand 0.4` because `rand 0.3` just reexports the 0.4 traits.  This is helpful in complex crate graphs where you have multiple crates depending on different versions of rand, but you want them to work together.   This is typically done with traits where the trait is backwards compatible, but the types (structs, etc.) have changed in a backwards incompatible way.

**Comment by lostman** [comment]
@ehuss Thanks for explaining this! However, I still don't understand the meaning of:

> This ensures that all crates are using the same version of all dependencies.

In this example `a` and `b` use different versions of `rand` though.

**Comment by ehuss** [comment]
Yea, that sentence in isolation kinda ignores the complexity of crate resolution.  What I think it's trying to say is that if one workspace member specifies `rand = "0.3.19"` and another member specifies `rand = "0.3.22"`, they'll both resolve to `0.3.23` (or whatever the latest version is).

If you'd like, please file an issue at https://github.com/rust-lang/book/issues that the section on workspaces isn't clear on semver compatibility in Cargo, and how Cargo tries to select the latest "compatible" versions.  It does seem like explanation of how that works is only documented at https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html, so it might help to have more emphasis on it (either in the book, or maybe in the [Cargo Guide](https://doc.rust-lang.org/nightly/cargo/guide/index.html)).

**Comment by basvandijk** [comment]
@ehus thanks for the great explanation. Cargo's dependency resolution is advanced!

**Comment by lostman** [comment]
Likewise, thanks @ehuss
