### ISSUE TITLE
Private repositories: how?

### ISSUE THREAD

**Issue by sebolio** [rust-lang/cargo#7074]
I come from `nodejs` where you have private repositories in `NPM`, however i'm unable to find a way to achieve this in rust/cargo
 
Is there a way to set up private repos on some config file?
 
**Notes**

**Comment by alexcrichton** [comment]
Thanks for the report! You depend on private repositories as you would other normal git repositories (with a git url). Authentication is performed natively in Cargo with `ssh-agent`, and otherwise if that doesn't work you can configure the `net.git-fetch-with-cli` option to `true` to use the `git` CLI which has other authentication methods as well.
