### ISSUE TITLE
cargo fetch --offline should report an error

### ISSUE THREAD

**Issue by nrc** [rust-lang/cargo#7085]
It seems to do nothing and return success at the moment. I would expect it to do the same thing as `cargo publish --offline` which returns an error.

**Comment by ChristianWitts** [comment]
Successfully erroring out for me if I have something that needs to be fetched that I don't have in local cache.

```shell
$ cargo version
cargo 1.36.0 (c4fcfb725 2019-05-15)
```

**Comment by ehuss** [comment]
I'm going to close, since I think this is working as intended. There are a few different scenarios for how `cargo fetch` interacts with `--offline`:

1. Registry hasn't been downloaded at all. This displays an error: 
   ```
   error: no matching package named `bitflags` found
   location searched: registry `crates-io`
   required by package `foo v0.1.0 (/Users/eric/Temp/foo)`
   As a reminder, you're using offline mode (--offline) which can sometimes
   cause surprising resolution failures, if this error is too confusing you
   may wish to retry without the offline flag.
   ```
2. Registry is downloaded, but it does not have the requested version:
   ```
   error: failed to select a version for the requirement `bitflags = "^1.3.3"`
   candidate versions found which didn't match: 1.3.2, 1.3.1, 1.2.1, ...
   location searched: crates.io index
   required by package `foo v0.1.0 (/Users/eric/Temp/foo)`
   As a reminder, you're using offline mode (--offline) which can sometimes
   cause surprising resolution failures, if this error is too confusing you
   may wish to retry without the offline flag.
   ```   
3. Registry is downloaded, but the .crate file hasn't been downloaded. This displays the error: 
   ```
   error: failed to download `bitflags v1.3.2`

   Caused by:
     attempting to make an HTTP request, but --offline was specified
   ```
4. Registry is downloaded and the .crate file is downloaded: Succeeds without output. This is the same as the online mode.

I'm *guessing* that this was a consequence of 4. I think not returning an error is probably the right behavior just to maintain symmetry with the online mode (and since there isn't a specific reason to forbid it). If on the off chance you can remember if this was something different, feel free to reopen.
