### ISSUE TITLE
Deprecate replace?

### ISSUE THREAD

**Issue by nrc** [rust-lang/cargo#7092]
I don't see any good reason to have `replace` and `patch` and it is confusing that we have two features that do the same thing in subtly different ways.

**Comment by nrc** [comment]
We'd obviously take a long time to deprecate and probably can't remove the feature until the next edition.

**Comment by alexcrichton** [comment]
Generous 👍 from me, this was always the initial intention but we never got around to doing it. I'd be game to do this at any time!

**Comment by est31** [comment]
I can vaguely recall `replace` having some capabilities that `patch` doesn't but can't remember any specifics.

**Comment by ehuss** [comment]
The primary problem with `[patch]` that I'm aware of is that you cannot target different versions (#6169) whereas you can with `[replace]`.  I'm not sure if it is possible to support that, or how important it is.  Would that be a blocker to deprecating?

There are also some bugs (https://github.com/rust-lang/cargo/issues?q=is%3Aopen+is%3Aissue+label%3AA-patch), particularly around patching git dependencies (such as #5478 and #4509).  Not being able to switch branches seems particularly not good.  

I don't know enough the judge how important these issues are.

**Comment by alexcrichton** [comment]
I think that's something we do want to support in `[patch]`, just haven't had a chance to add yet! I just posted a [strawman syntax](https://github.com/rust-lang/cargo/issues/6169#issuecomment-509245566) and I suspect it would be pretty uncontroversial to add support for it. It's a good point about git repos, though! I suspect that `[replace]` suffers from basically the same issues though.

I personally think there's enough bugs and usage issues with `[replace]` that it's not worthwhile to keep around. We should definitely be funneling all development of features/fixes into `[patch]` instead of `[replace]`

**Comment by workingjubilee** [comment]
There are error messages emitted that still point to `[replace]` that should probably point to using a `[patch]` table instead.

**Comment by akien-mga** [comment]
> There are error messages emitted that still point to `[replace]` that should probably point to using a `[patch]` table instead.

Indeed, I saw that so I made a PR: #9533.

**Comment by elibroftw** [comment]
I was reading https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#the-replace-section, and I'm completely dumbfounded with how to force the use of a specific version of a dependency that is also required by a sub dependency that is from git.

I'm trying to use https://github.com/tauri-apps/tauri-plugin-window-state, however, it breaks my build since one of its sub-dependencies is broken.
The plugin depends on a version of tauri that is not the same as the one I depend on which depends on the broken wry.

The docs says replace is deprecated, but why is this issue still open then? 
There are plenty of simple examples, but nothing demonstrating flexibility.

**Comment by epage** [comment]
Replace was marked as deprecated in #7733, so I take it this is resolved?  If there is something I'm missing, let us know so we can re-open this.
