### ISSUE TITLE
SSL connect error

### ISSUE THREAD

**Issue by i-cant** [rust-lang/cargo#7096]
**Problem**
Can't download any crates
```
  [35] SSL connect error (schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) - The revocation function was unable to check revocation because the revocation server was offline.)
```
**Steps**

1. Add a dependency in Cargo.toml
2. Build

**Possible Solution(s)**
Build in WSL

**Notes**
Windows 10 x64 1809
Output of `cargo version`:
`cargo 1.37.0-nightly (4c1fa54d1 2019-06-24)`

**Comment by alexcrichton** [comment]
Thanks for the report! This is a transient error that sometimes shows up on Windows. You can set `http.check-revoke = false` in config (or `CARGO_HTTP_CHECK_REVOKE=false` in env) to ignore the error as well.

**Comment by qazman** [comment]
Please someone should help me to resolve this issue

error: failed to fetch into: /home/qazman/.cargo/git/db/sui-6ac459c53b1b685a

Caused by:
  network failure seems to have happened
  if a proxy or similar is necessary `net.git-fetch-with-cli` may help here
  https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli

Caused by:
  SSL error: unknown error; class=Ssl (16)

**Comment by qazman** [comment]
Please someone should help me to resolve this issue, after installing rust and cargo, I get this error while trying to install the sui binary. Please someone should help

error: failed to fetch into: /home/qazman/.cargo/git/db/sui-6ac459c53b1b685a

Caused by:
network failure seems to have happened
if a proxy or similar is necessary net.git-fetch-with-cli may help here
https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli

Caused by:
SSL error: unknown error; class=Ssl (16)

**Comment by Eh2406** [comment]
An issue that was closed five years ago is not an appropriate place to ask for help. None of the research that was done back then will be relevant to helping you now. If you have a new problem, open a new issue. Also in that issue document the things you have tried, for example the suggestion made by the error message you pasted, or either of the suggestions from Alex in this issue. Explain why they did not work and what happened when you tried them.
