### ISSUE TITLE
Uses up lots of AppVeyor time

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/cargo#7101]
All rust-lang projects are sharing a single AppVeyor build slot, and Miri is regularly waiting for >1h to get one, so I am trying to figure out where all that time is going. ;)

It seems to me cargo is one offender here, because currently AppVeyor runs three times on every PR: it runs in the PR, then it runs on the `auto`  branch, and then when bors pushes the final thing to `master` it runs *again*. Is that really necessary? Do you think you could reduce this?

In Miri we decided to basically have AppVeyor only on the `auto` and `try` branches, that reduces it to once-per-PR. Maybe that is not appropriate for Cargo though since you want to see AppVeyor state in the PR itself; then maybe you could find a way to not also run AppVeyor when bors lands the change on `master`? That run is entirely redundant. (The travis config does `branch != master OR type = pull_request` to avoid that, but I don't know the AppVeyor equivalent of this.)

**Comment by ehuss** [comment]
master builds are already skipped: https://github.com/rust-lang/cargo/blob/a3b46ff42fa9e4db34a142d9482e75f970a801fe/appveyor.yml#L7

**Comment by RalfJung** [comment]
Oh they are, sorry! I was looking for some kind of conditional in the control part of the file, similar to Travis.

**Comment by ehuss** [comment]
I'm going to close this since I don't think there are any actionable changes we can make here.  Running the test suite on PRs is very useful, and Cargo is only using 1 job which runs for about 18 minutes, and our PR traffic is pretty low.  Although I'm always happy to find ways to cut down on CI time, I can't think of anything we can easily do for now.

I would recommend reviewing all the other projects, though.  For example, I notice clippy runs on master when it is probably not necessary (since they use bors).  They should probably add a manual exit the same way cargo's is defined.  There is no way AFAIK to completely skip the job, but it should only run for a few seconds.

I don't have a complete list of `rust-lang-libs` projects, it might be good to find out who all shares that account, and if they have multiple jobs if they can cut PR's down to 1 job like how rust-lang/rust worked (and have only the bors auto branch do all jobs).

**Comment by RalfJung** [comment]
> I'm going to close this since I don't think there are any actionable changes we can make here. Running the test suite on PRs is very useful, and Cargo is only using 1 job which runs for about 18 minutes, and our PR traffic is pretty low. Although I'm always happy to find ways to cut down on CI time, I can't think of anything we can easily do for now.

Fair.

> I would recommend reviewing all the other projects, though.

Yeah, I am on that. Unfortunately I cannot view the queue, so whenever Miri times out (because we didn't get a slot in 2h) I am stabbing in the dark to guess which project is causing the load.

> it might be good to find out who all shares that account, and if they have multiple jobs if they can cut PR's down to 1 job like how rust-lang/rust worked (and have only the bors auto branch do all jobs).

Miri has two jobs, because it is very sensitive to 64bit vs 32bit differences, and I don't know how to cross-compile things on Windows. But it's auto- (and try-) only, not in PRs, which works for us.
