### ISSUE TITLE
Impossible to use `build --all` and `test --all` together with `--features`

### ISSUE THREAD

**Issue by sdroege** [rust-lang/cargo#7218]
**Describe the problem you are trying to solve**

On the CI I'd like to build/test all crates in my workspace with specific feature sets.

`--all-features` is not an option because some features are conflicting with each other, but otherwise it would work.

Building each crate individually and specifying the relevant `--features` is an option but increases build times considerably.

Creating a dummy subcrate that depends on all the other crates with the corresponding features is not an option as that does not allow running tests, or building all examples/tests/bins of the other crates (`--examples`, etc)

**Describe the solution you'd like**

`cargo build --all --features crate1/feature1,crate2/feature2` should build all crates in the workspace and enable the corresponding features of the subcrates.

Same thing for `cargo test --all --features ...`.

**Comment by sdroege** [comment]
> Building each crate individually and specifying the relevant `--features` is an option but increases build times considerably.

As discussed on Discord, testcase for the increase of build times. Problem is that building e.g. `gstreamer` and then `gstreamer-base` individually with the same features causes `gstreamer` to be built twice (and build times are approximately the same).

Can be reproduced with https://gitlab.freedesktop.org/gstreamer/gstreamer-rs, simply run

```sh
cd gstreamer && cargo build --features=v1_16
cd gstreamer-base && cargo build --features=v1_16
```

Some relevant output of the cargo fingerprinting calculations below

 first build of gstreamer:

```
[...]
[2019-08-07T15:23:43Z DEBUG cargo::core::compiler::fingerprint] write fingerprint (6d53d60cace9aee6) : /home/slomo/Projects/rust/gstreamer-rs/target/debug/.fingerprint/gstreamer-78c2685dd0a6cd29/lib-gstreamer-78c2685dd0a6cd29
```

second build from gstreamer-base:

```
[2019-08-07T15:24:02Z INFO  cargo::core::compiler::fingerprint] fingerprint error for gstreamer v0.15.0 (/home/slomo/Projects/rust/gstreamer-rs/gstreamer)/RunCustomBuild/Target { ..: custom_build_target("build-script-build", "/home/slomo/Projects/rust/gstreamer-rs/gstreamer/build.rs", Edition2015) }
[2019-08-07T15:24:02Z INFO  cargo::core::compiler::fingerprint]     err: failed to read `/home/slomo/Projects/rust/gstreamer-rs/target/debug/.fingerprint/gstreamer-a5a7c9fbee41f48d/run-build-script-build_script_build-a5a7c9fbee41f48d`
[2019-08-07T15:24:02Z INFO  cargo::core::compiler::fingerprint]   cause: No such file or directory (os error 2)
[2019-08-07T15:24:02Z DEBUG cargo::core::compiler::fingerprint] fingerprint at: /home/slomo/Projects/rust/gstreamer-rs/target/debug/.fingerprint/gstreamer-e7e6fddf87e1bac8/build-script-build_script_build-e7e6fddf87e1bac8
[2019-08-07T15:24:02Z INFO  cargo::core::compiler::fingerprint] fingerprint error for gstreamer v0.15.0 (/home/slomo/Projects/rust/gstreamer-rs/gstreamer)/Build/Target { ..: custom_build_target("build-script-build", "/home/slomo/Projects/rust/gstreamer-rs/gstreamer/build.rs", Edition2015) }

[...]

[2019-08-07T15:24:17Z DEBUG cargo::core::compiler::fingerprint] write fingerprint (576af547ea283993) : /home/slomo/Projects/rust/gstreamer-rs/target/debug/.fingerprint/gstreamer-d9fbb7020cd90fcc/lib-gstreamer-d9fbb7020cd90fcc
```

**Comment by sdroege** [comment]
Also related https://github.com/rust-lang/cargo/issues/5364

**Comment by sdroege** [comment]
Happens with latest nightly and 1.38 btw

**Comment by ehuss** [comment]
I took a look, and there are a few reasons why `gstreamer-base` builds `gstreamer` differently:

- `gstreamer-base` should re-export the same features to `gstreamer`. Otherwise `gstreamer` will be built with a different feature set.  Something like this:
   ```toml
    v1_10 = ["gstreamer/v1_10", "gstreamer-sys/v1_10", "gstreamer-base-sys/v1_10"]
    v1_12 = ["gstreamer/v1_12", "gstreamer-sys/v1_12", "gstreamer-base-sys/v1_12", "v1_10"]
    v1_14 = ["gstreamer/v1_14", "gstreamer-sys/v1_14", "gstreamer-base-sys/v1_14", "v1_12"]
    v1_14_1 = ["gstreamer/v1_14", "gstreamer-sys/v1_14", "gstreamer-base-sys/v1_14_1", "v1_14"]
    v1_16 = ["gstreamer/v1_16", "gstreamer-sys/v1_16", "gstreamer-base-sys/v1_16", "v1_14_1"]
    ```
- Unfortunately `num_traits` and `num_integer` get built with different features.  When built from `gstreamer` they have the `default` and `std` features set because they are a dependency from `serde-pickle` which defines them that way.  When built from `gstreamer-base`, they don't have any features set because `serde-pickle` isn't part of `gstreamer-base`.  This is an oft-reported problem with dev-dependencies causing features to infect regular dependencies (#1796).  `-Zavoid-dev-deps` is one way to work around this (#5133).  The only other way I can think of is to just allow default features in `num-rational`, but that may not be what you want.

One way to diagnose this kind of stuff is to run `cargo build -v`, and then for each command, diff the command-line arguments between two different invocations. You can quickly see when different commands have different `--cfg` arguments. If the metadata of a dependency is different, then you repeat the process for those dependencies.

**Comment by sdroege** [comment]
Thanks for debugging this. I don't see how to solve that on my side though without changing behaviour in an undesirable way. The first one is clear and fine, the second is a bit problematic :)

**Comment by TriplEight** [comment]
I also faced a similar issue in a CI of a big workspace project. I have some tests that are only run when you `cd crate.dir; cargo test --workspace --no-default-features --feature myfeature`. And this obviously requres the whole project to be compiled for a handful of those tests. That's because `--feature` cannot be run in the root of a virtual workspace.

And I tried to optimize that, lining all the small tests after the main `cargo test --workspace`, but they are recompiling a third of a project and ruining the cache usage for this job.

The [thing](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#package-features) that worked for me was `-Zpackage-features --features myfeatureA,myfeatureB` which works from the root of the virtual wsp, does not require recompiling the parts of the project before the tests, hence does not ruin the cache, almost perfect. But it comes with the new rust everyday, which would force the cache recreation every day. 

In the other words, when https://github.com/rust-lang/cargo/issues/5364 ?

**Comment by weihanglo** [comment]
This is seemly resolved since `-Zpackage-features` has been stabilized in 1.51. You can use the exact syntax `package-name/feature-name` to `--features/-F` flag.

Going to close this. If I understand something or there is still something unresolved, please tell us.
