### ISSUE TITLE
cargo fetch always redownloads git repo if it fails to parse rev

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/cargo#7266]
**Problem**
````toml
[package]
name = "dep"
version = "0.1.0"

[dependencies]
cargo-cache = { git = "https://github.com/matthiaskrgr/cargo-cache",rev ="bla"}

````
**Steps**
If I run `cargo fetch`, it seems that the repo is always redownloaded even if it is already present in the cargo download cache (` ~/.cargo/git/db/cargo-cache-16826c8e13331adc`).
Finding the rev will fail right after:
````
error: failed to load source for a dependency on `cargo-cache`

Caused by:
  Unable to update https://github.com/matthiaskrgr/cargo-cache?rev=bla

Caused by:
  revspec 'bla' not found; class=Reference (4); code=NotFound (-3)
````
 

**Possible Solution(s)**
Don't reclone the repo since it is already present.

Output of `cargo version`:
`cargo 1.38.0-nightly (e853aa976 2019-08-09)`

**Comment by alexcrichton** [comment]
Attempted this in https://github.com/rust-lang/cargo/pull/7272 but turns out this directly conflicts with https://github.com/rust-lang/cargo/pull/5110. Since handling corrupt repos gracefully is generally the higher priority here, I'm going to close this because I think unfortunately there's not much we can do.
