### ISSUE TITLE
Allow specifying alternate sources for dependencies

### ISSUE THREAD

**Issue by codyps** [rust-lang/cargo#733]
When using a package manager that uses source code as the "package", we need to grab source at a different step than build.

Also, at times it's necessary to patch dependencies, which being able to point to a raw directory would allow.

I imagine we'd provide some mapping between "url#hash" and "directory".

One possibility would be to allow Cargo.lock to be edited to point to new locations/urls/hashes which don't match Cargo.toml without automatically re-updating it (and blowing away those changes).

**Comment by fxdave** [comment]
@alexcrichton Is there a way of doing this, but for git dependencies?

I've got a workspace that contains member crates. And several member crates have a dependency using a git url, however that dependency crate is also in my workspace, so I want to overwrite it with my local path without touching the member's Cargo.toml. And I don't want to override it inside the member, because that is valid if somebody clones that member alone.

```
member/Cargo.toml <- this has the dependency as git url
common-lib/* <- this is the local version of that dependency
Cargo.toml <- I want to override it here to my local path
```

**Comment by weihanglo** [comment]
Hello @fxdave, this issue is quite old and the approach here might not be what you want. Without any further detail, it sounds  [`[patch]`](https://doc.rust-lang.org/nightly/cargo/reference/overriding-dependencies.html#the-patch-section) can help you get through it. I'd suggest taking a look. It works with both `Cargo.toml` and `.cargo/config.toml`
