### ISSUE TITLE
cargo rustc -- --crate-type cdylib stopped working

### ISSUE THREAD

**Issue by lu-zero** [rust-lang/cargo#7339]
Right now on stable `cargo rustc -- --crate-type cdylib` correctly produces the cdylib.
Nightly fails since cargo tries to pass the dependencies as `.rmeta` instead of `.rlib`.

**Comment by alexcrichton** [comment]
This is due to pipelining support being added to Cargo, but this was never really intended to work and/or going to work. Crate type output is so intrusive that Cargo needs to know about it, so `cargo rustc` can't be used to update the crate types via the CLI (which Cargo doesn't parse, it just forwards to rustc)
