### ISSUE TITLE
In a `cargo build`, make note of when check steps finish

### ISSUE THREAD

**Issue by djahandarie** [rust-lang/cargo#7355]
I occasionally use a develop <=> `cargo build` cycle to get my feedback (instead of `cargo check`). This is because in the case something does check out, I want it to indeed build.

However, while debugging errors, I have some minor anxiety staring at the terminal output wondering if the change I made worked or not, trying to tell from timing whether it has actually succeeded and has moved on to building or not.

I'd appreciate knowing when `cargo build` is done with the steps that `cargo check` normally does and has moved on to actually building things.

(Implementation-wise this *could* require rustc changes but filling a ticket here first given that this is the place I want the UX experience.)

**Comment by epage** [comment]
This seems similar enough to #7265 that I'm going to close in favor of that so we have one place to discuss this and have an aligned way of changing the output, rather than trying to design two incompatible UXs separately.  If there is something I missed as to why this needs to be kept open on its own, let us know!
