### ISSUE TITLE
Finer-grained overrides in .cargo/config

### ISSUE THREAD

**Issue by jmesmon** [rust-lang/cargo#736]
As mentioned in #733, Local overrides via .cargo/config path = [ "foo" ] override all dependencies with the same name, even if they have different versions.

This contrasts the behavior when a project with a dep on one version of a library (A) also depends on anther lib (B) that pulls another version of the library A. In that case, both versions are included in the build.

Given the above, it will probably be useful to allow overrides on a finer grained basis.

**Comment by weihanglo** [comment]
Cargo supports [`[patch]` in Cargo configuration](https://doc.rust-lang.org/nightly/cargo/reference/config.html#patch) since 1.56. This should cover the use case.

As this is an old issue and dependency overriding has evolved since then, I am going to close this. If it is wrong or your scenario is yet covered, please let us know. Thank you!

**Comment by sanmai-NL** [comment]
@weihanglo Does `[patch]` not override all dependencies with the same name?

**Comment by weihanglo** [comment]
Yes. It would respect the version and the source where the dependency comes from.
