### ISSUE TITLE
-Z timings: no graph for rust-analyzer build

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/cargo#7388]
repo: https://github.com/rust-analyzer/rust-analyzer

I was running
`cargo clean ; RUSTC_WRAPPER="" ~/vcs/github/cargo/target/release/cargo build --release -Ztimings  --all-targets`
but there was no graph displayed in the html summary:

![ra_timings](https://user-images.githubusercontent.com/476013/65271075-bc865c00-db1c-11e9-9ddf-a84cf0d1ce95.png)

cargo 3596cb86b2e87dd9b9c1bb90d4a9d73ec2c1512f
rustc 1.39.0-nightly (eb48d6bde 2019-09-12)

**Comment by alexcrichton** [comment]
Could you gist the html file as well? If you open the JS console are there any errors showing up there as well?

(I just build rust-analyzer and got some graphs so I wasn't able to trivially reproduce it at least)

**Comment by matthiaskrgr** [comment]
Here's the html: https://gist.github.com/matthiaskrgr/5941caa4217343abbea4a566f644cfc6 

There were some errors in the js console but I'm not sure if they were coming from the report page:
````
nsLoginManager: searchLogins: `formActionOrigin` or `httpRealm` is recommended 7 LoginManager.jsm:467:13
uncaught exception: Object
uncaught exception: Object
uncaught exception: Object
uncaught exception: Object
Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.
uncaught exception: Object 4
TypeError: Argument 1 of PrecompiledScript.executeInGlobal is not an object. ExtensionContent.jsm:554:25
TypeError: can't access dead object
uncaught exception: Object
Error: UrlbarInput: Should have a UrlbarResult since pageproxystate != 'valid' and valueIsTyped == false UrlbarInput.jsm:1056:15
Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.
Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.
Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.
uncaught exception: Object 
````

**Comment by alexcrichton** [comment]
Ok looks like I'm getting a JS error, and it's just an obscure `NS_ERROR_FAILURE` (that's literally the whole exception message) which happens on [this line](https://github.com/rust-lang/cargo/blob/3596cb86b2e87dd9b9c1bb90d4a9d73ec2c1512f/src/cargo/core/compiler/timings.js#L265).

I suspect the issue is that the canvas is requested to just be simply too big, its width is `25100` and height is `6682`, and that's probably hitting some "reasonable limit" for the maximum width of a canvas or something like that.

I set the slider to as low as it could go, refreshed the page, and the graph rendered. Probably just means we need to do some more massaging with the scaling to ensure that it doesn't scale absurdly large like this.

(cc @ehuss)
