### ISSUE TITLE
Regression in finding crates during doc tests

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/cargo#7472]
### Problem

A couple of my crates' builds started failing at nightly-2019-10-03. I don't have a chance tonight to dig into what is going wrong, but I figured I would report it early since this appears to be a regression.

https://github.com/rust-lang/cargo/pull/7417 looks possibly related.

### Steps

`cargo clean && cargo test` in either https://github.com/serde-rs/json or https://github.com/dtolnay/quote. They both work on nightly-2019-10-02 but fail on nightly-2019-10-03, in different ways.

**serde_json:** https://travis-ci.org/serde-rs/json/jobs/592841446

```console
...

   Doc-tests serde_json
error[E0463]: can't find crate for `serde_derive` which `serde` depends on
   --> /home/travis/build/serde-rs/json/src/lib.rs:325:1
    |
325 | extern crate serde;
    | ^^^^^^^^^^^^^^^^^^^ can't find crate
```

**quote:** https://travis-ci.org/dtolnay/quote/jobs/592846455

```console
...

---- src/ext.rs - ext::TokenStreamExt::append_all (line 20) stdout ----
error[E0460]: found possibly newer version of crate `proc_macro2` which `quote` depends on
 --> src/ext.rs:19:1
  |
2 | extern crate quote;
  | ^^^^^^^^^^^^^^^^^^^
  |
  = note: perhaps that crate needs to be recompiled?
  = note: the following crate versions were found:
          crate `proc_macro2`: /home/travis/build/dtolnay/quote/target/debug/deps/libproc_macro2-e61df99964fc712a.rlib
          crate `proc_macro2`: /home/travis/build/dtolnay/quote/target/debug/deps/libproc_macro2-e61df99964fc712a.rmeta
          crate `proc_macro2`: /home/travis/build/dtolnay/quote/target/debug/deps/libproc_macro2-37a3c8079ede86c5.rmeta
          crate `quote`: /home/travis/build/dtolnay/quote/target/debug/deps/libquote-9e0852a9faf16dfb.rlib
```

**Comment by ehuss** [comment]
Yea, it is definitely due to #7417.  The [`trybuild`](https://github.com/serde-rs/json/blob/master/tests/compiletest.rs) test recursively invokes cargo which causes some crates to be rebuilt due to the addition of [RUSTFLAGS](https://github.com/dtolnay/trybuild/blob/master/src/rustflags.rs).  These partially recompiled crates are no longer compatible with the original run, but they have the same hash.

I don't think there has been much consideration made for running cargo within tests.  Would it be possible for `trybuild` to use a dedicated target directory?

**Comment by dtolnay** [comment]
Thanks! That makes sense, sorry about the noise. I will fix trybuild to use an independent target directory.
