### ISSUE TITLE
Error trying to build over WSL path

### ISSUE THREAD

**Issue by bmc-msft** [rust-lang/cargo#7511]
**Problem**
When trying to build a project over a WSL mount, cargo is unable to lock Cargo.lock and generates an error

**Steps**

1. Install rust in Windows
2. Checkout a simple rust project in WSL (such as /tmp/testing)
3. In powershell, change directories to `\\wsl$\<Distro>\tmp\testing`, then run `cargo build`

PS Microsoft.PowerShell.Core\FileSystem::\\wsl$\Ubuntu\tmp\testing> cargo build --release
error: failed to lock file: \\wsl$\Ubuntu\tmp\testing\Cargo.lock

Caused by:
  Incorrect function. (os error 1)
PS Microsoft.PowerShell.Core\FileSystem::\\wsl$\Ubuntu\tmp\testing>

**Possible Solution(s)**

**Notes**

Output of `cargo version`:

cargo 1.40.0-nightly (a429e8cc4 2019-10-04)

**Comment by guanqun** [comment]
I can reproduce this issue. The root cause is that it's not allowed to acess file (here, locking file) via `\\wsl$\<Distro>`, from Microsoft's doc, it's more likley a network sharing thing, or implemented via `9p` server. I double the locking api from `winapi` is implemented or even available.

It's purely a platform specific issue, and related to how files within WSL can be accessed in Win app.
