### ISSUE TITLE
Sync cargo commands between "cargo --help" / rust-lang.org

### ISSUE THREAD

**Issue by trevordmiller** [rust-lang/cargo#7597]
**Describe the problem you are trying to solve**
Currently it isn't clear what options cargo has. For example, I just learned about `cargo fix`, `cargo fmt`, `cargo clippy`, `cargo audit` etc. which are awesome! But it would have been nice to know about them when I got started learning Rust.

**Describe the solution you'd like**
A consistent list of cargo options for `cargo --help` and `rust-lang.org`. Something like:

<img width="439" alt="image" src="https://user-images.githubusercontent.com/5497885/68982304-a8c94000-07c3-11ea-86e1-44dcad079285.png">

**Notes**

### `cargo --help` (missing things like `cargo fix`, `cargo fmt`, `cargo clippy`, `cargo audit` etc.)

```sh
...
Some common cargo commands are (see all commands with --list):
    build       Compile the current package
    check       Analyze the current package and report errors, but don't build object files
    clean       Remove the target directory
    doc         Build this package's and its dependencies' documentation
    new         Create a new cargo package
    init        Create a new cargo package in an existing directory
    run         Run a binary or example of the local package
    test        Run the tests
    bench       Run the benchmarks
    update      Update dependencies listed in Cargo.lock
    search      Search registry for crates
    publish     Package and upload this package to the registry
    install     Install a Rust binary. Default location is $HOME/.cargo/bin
    uninstall   Uninstall a Rust binary
```

### `cargo --list` (missing descriptions for all options)

<img width="520" alt="image" src="https://user-images.githubusercontent.com/5497885/68982176-335d6f80-07c3-11ea-99c1-23bbf1176756.png">

### rust-lang.org (inconsistent)

"Getting started" section

<img width="1225" alt="image" src="https://user-images.githubusercontent.com/5497885/68982205-52f49800-07c3-11ea-9690-c33d88d29980.png">

"Tools" section (has `cargo doc` but not the other two for example)

<img width="1269" alt="image" src="https://user-images.githubusercontent.com/5497885/68982232-6dc70c80-07c3-11ea-8970-0dd99f35811d.png">

**Comment by epage** [comment]
`cargo --help` and [Getting Started](https://www.rust-lang.org/learn/get-started) serve the role of providing a summary.  They each target slightly differently needs which is why their lists are different.

Both of them link out to where you can find exhaustive list of commands.

The ["Tools" section](https://www.rust-lang.org/tools) is higher level, talking about major tools.  In this case, its referring to `rustdoc` when saying "cargo doc" since that is how most people will interact with it.  The blue section just above what was screenshotted is for cargo.

btw `cargo --list` only has descriptions for built-in commands.  Those missing them are for plugin commands.

Seeing as the cargo related parts to this have the necessary bread crumbs to help users, I'm going to go ahead and close this.  I could see creating a separate issue for `cargo --list` showing descriptions for more commands.  I could also see creating an issue against the website to link to cargo from the cargo section of the "Tools" page.
