### ISSUE TITLE
Cargo uses .cargo/config of workspace from which it is excluded

### ISSUE THREAD

**Issue by stevenroose** [rust-lang/cargo#7620]
So we have a big cargo workspace, let's say in `/workspace/`. We have `/workspace/vendor` and `/workspace/.cargo/config` which points crates-io to this vendor directory. In `/workspace/Cargo.toml` we exclude one directory from the workspace:
```toml
exclude = [
    "excluded"
]
```

So, when I go into `/workspace/excluded` and I try to run `cargo build`, I'm getting these kind of errors:
```
error: failed to select a version for the requirement `libc = "^0.2.62"`
  candidate versions found which didn't match: 0.2.50
  location searched: directory source `/workspace/vendor` (which is replacing registry `https://github.com/rust-lang/crates.io-index`)
required by package `excluded v0.1.0 (/workspace/excluded)`
perhaps a crate was updated and forgotten to be re-vendored?
```

So it seems that the source replacement from `.cargo/config` is seen as totally separate from the workspace concept. This if of course very annoying and I would consider it a bug. A directory excluded from the workspace should not use configs that are set in the workspace directory.

**Comment by sfackler** [comment]
Cargo searches all parent directories for a `.cargo` directory, whether or not they're part of the workspace IIRC.

**Comment by stevenroose** [comment]
Correct. In my opinion that doesn't make sense. Somehow vendor directories should be linkable with workspaces instead of entirely independent.

**Comment by epage** [comment]
As the config is an environment config, rather than a project config, this is working as expected.  This is a common point of confusion though and we have many other issues tracking this.  Closing in favor of #2930 so we consolidate conversations about the config lookup rules

See also #12738 for tracking efforts in finding ways to store settings in the project that is currently only supported in the environment.
