### ISSUE TITLE
SIGUSR1 when using cargo on OSX

### ISSUE THREAD

**Issue by Lapz** [rust-lang/cargo#7711]
**Problem**

After making changes to a binary and then using cargo run the crate is built but when running it I get a `[1] 15041 killed RUST_BACKTRACE=1 cargo run tox/src/test.tox` within the terminal. Running cargo run again works perfectly fine also running the binary directly is fine.

**Steps**

* git clone https://github.com/Lapz/tox-rewrite
* Make change 
* run `cargo run  tox/src/test.tox`

or 
[view it here](https://imgur.com/kyGrsxo)

**Backtrace**
```
* thread #2, stop reason = signal SIGUSR1

frame #0: 0x00007fff63c14916 libsystem\_kernel.dylib\`\_\_psynch\_cvwait + 10

libsystem\_kernel.dylib\`\_\_psynch\_cvwait:

\->  0x7fff63c14916 <+10>: jae    0x7fff63c14920            ; <+20>

0x7fff63c14918 <+12>: movq   %rax, %rdi

0x7fff63c1491b <+15>: jmp    0x7fff63c113b7            ; cerror\_nocancel

0x7fff63c14920 <+20>: retq
```

**Possible Solution(s)**

**Notes**

Output of `cargo version`:

`cargo 1.41.0-nightly (626f0f40e 2019-12-03)`
`macOS Catalina 10.15.1`
`ZSH`

**Comment by ehuss** [comment]
Hm, I'm unable to reproduce this.

Are you sure it is dying due to SIGUSR1?  It looks like from the image you posted, it says `[1]    29527 killed     cargo run tox/src/test.tox`.  Normally `killed` means SIGKILL.

Can you reproduce it outside of vs code? Can you make sure you don't have anything else running (`cargo watch`, any vs code triggers, rls or rust-analyzer, no sccache, no cargo/rust environment variables, etc.).  Also, maybe try setting `ulimit -c unlimited` to generate a core file when it dies?

**Comment by Mark-Simulacrum** [comment]
FWIW, SIGUSER1 is the kill used by jobserver on shutdown; it shouldn't propagate to the end user though.

**Comment by ehuss** [comment]
I'm going to close this for inactivity and no repro.  If you're able to put together a reproduction, feel free to reopen or file a new issue.
