### ISSUE TITLE
CI failing on rust-1.41.0

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/cargo#7714]
https://dev.azure.com/rust-lang/473adcf1-6656-4c7e-9337-c393e7e0431c/_apis/build/builds/16115/logs/100

I suspect this is a result of the recent extern-private work but it's not entirely clear to me why the branch is failing (and master presumably isn't).

**Comment by ehuss** [comment]
I can't tell from the link what the context is.  Is this related to https://github.com/rust-lang/rust/pull/67351?

That is a "nightly" test. Those should be disabled on rust-lang/rust via [`CARGO_TEST_DISABLE_NIGHTLY`](https://github.com/rust-lang/rust/blame/99b89533d4cdf7682ea4054ad0ee36c351d05df1/src/bootstrap/test.rs#L232-L234).  This helps with making unstable changes that require updates on both side which are impossible to do in one PR.

**Comment by Mark-Simulacrum** [comment]
From [this](https://dev.azure.com/rust-lang/cargo/_build/results?buildId=16115&view=results) build here.

**Comment by ehuss** [comment]
Oh, sorry, I misunderstood.  This is the rust-1.41.0 branch on *cargo*.  Indeed it is quite common for the beta branch to get broken because of issues like this, thanks for the heads up!  We often backport test changes, but in this case the change is quite large.  It's a little unfortunate that the cargo update has taken more than a week to merge.  I considered raising the priority, but I didn't think any of the changes really *needed* to get on beta, and there seemed to be a lot of contention for bors time.  

I'll disable the test.

**Comment by Mark-Simulacrum** [comment]
I agree it's a bit unfortunate -- we've been having CI trouble with Chocolatey as well which probably helps explain some of the slowness there.

**Comment by ehuss** [comment]
Fixed in #7716.
