### ISSUE TITLE
Tracking issue for config-cli

### ISSUE THREAD

**Issue by ehuss** [rust-lang/cargo#7722]
Implementation: #7649
Original proposal: #6699
Documentation: https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#config-cli

**Summary**

Adds `--config` CLI option to pass config options to any command.

**Unresolved issues**

* [X] Make TOML restricted to `KEY=VALUE`. Will need updates to the toml crate to make that possible. DONE: #10176
* [X] Make `--config PATH` work has a shorthand for `--config 'include="path"' DONE: #7901

**Comment by jyn514** [comment]
A use case for this: docs.rs wants to pass `RUSTFLAGS` without having the spacing interpreted by the shell: https://github.com/rust-lang/docs.rs/pull/1057

**Comment by Nemo157** [comment]
Is it not possible to specify registry sources via this? I wanted to migrate from using `registry-index` sources in [_Publishing crates to IPFS_](https://gist.github.com/Nemo157/d9efafac719ead283282d2346f018987) so that I could test it with https://github.com/rust-lang/cargo/pull/8890, but trying to use this flag to define the registries it doesn't seem to be picked up:

```console
> cargo -Zunstable-options '--config=source.bs58_cli_0_1_0_anyhow.registry="http://127.0.0.1:8080/ifps/QmP6KmpjQrYpYyeXGqAvmrw45dPoKvmKeTqTanmSqJGJKz"' '--config=source.bs58_cli_0_1_0_bs58.registry="http://127.0.0.1:8080/ifps/Qmb2PJ9vMALRFmQjLDQbcNHYUvcFc96XzKMwAhBMEECxzb"' '--config=source.bs58_cli_0_1_0_paw.registry="http://127.0.0.1:8080/ifps/QmNkJbrmpjJErbX9fTpSSQYb7Ky1Qnpg47QptfMcVQUwBx"' '--config=source.bs58_cli_0_1_0_structopt.registry="http://127.0.0.1:8080/ifps/Qmbh5sZbKezvYq2ESVhbnymqs7VKMTaz7yXUaoMi9tBjJp"' update --manifest-path /tmp/ipfs-registry.bs58-cli-0.1.0.yIgXKp/bs58-cli-0.1.0/Cargo.toml
error: failed to parse manifest at `/tmp/ipfs-registry.bs58-cli-0.1.0.yIgXKp/bs58-cli-0.1.0/Cargo.toml`

Caused by:
  no index found for registry: `bs58_cli_0_1_0_anyhow`
```

**Comment by Nemo157** [comment]
:facepalm: ignore that, I was using the wrong config key.

**Comment by dancrossnyc** [comment]
Curious if there's any updated status on this? It would be really great to get stabilized!

**Comment by ehuss** [comment]
There's no update. There's still an unresolved issue noted above that needs someone to work on it.

**Comment by jonhoo** [comment]
I'll add what I think is a pretty compelling use-case for this: passing `-Zinstrument-coverage` for coverage testing. It requires leaving any existing rustflags intact since things like linker flags (`-Clink-args`) may be required for the crate to build in the first place, which using `RUSTFLAGS` doesn't do (https://github.com/rust-lang/cargo/issues/5376) but `--config='build.rustflags = ["-Zinstrument-coverage"]'` does (https://github.com/rust-lang/cargo/issues/5376#issuecomment-977284288).

For the unresolved issue, some guidance on exactly what you're imagining would be helpful @ehuss. Specifically, why do you think that restriction is necessary in the first place? Alternatively, could we just parse into a `toml::Value` and then check that it only contains one actual entry?

**Comment by ehuss** [comment]
The restriction is to just constrain the format so that it has a straightforward syntax.  That way, someone wouldn't be able to pass in comments or `[bracketed.tables]` or newlines or anything like that.  It already parses to a `toml::Value` and checks for one value.

**Comment by jonhoo** [comment]
👍 
Implemented in https://github.com/rust-lang/cargo/pull/10176

**Comment by jonhoo** [comment]
Now that #10176 has been merged, I think the unchecked box can be ticked!

**Comment by michalmuskala** [comment]
What are the plans for stabilising those features? My use case is using vendored dependencies on CI (while using "live" dependencies locally). Configuring this through an extra argument to cargo commands with `--frozen --config vendor_config.toml` rather than overriding the `.cargo/config.toml` file and using `--frozen` is very, very convenient and significantly less error prone.

This becomes even more powerful, when I realised `cargo vendor` outputs the necessary config on stdout (while logging progress on stderr), so using `cargo vendor > vendor_config.toml` to update the file "just works"

**Comment by jonhoo** [comment]
@ehuss In my opinion `config-cli` can be stabilized as-is. I think that's also where we arrived at [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/246057-t-cargo/topic/config-cli/near/269318224). I think there are improvements we could land that are related to this one (like `config-include`/#7723), but I don't think those are blockers for `config-cli`.

**Comment by jonhoo** [comment]
@ehuss Gentle nudge on this.

**Comment by ehuss** [comment]
Ah, sorry for the confusion. I was expecting you or someone to post a stabilization PR. Perhaps you were expecting an FCP first. I'll go ahead and kick that off.

@rfcbot fcp merge

@rust-lang/cargo This is a proposal to stabilize the `--config` CLI option. This option allows one to pass a configuration setting using TOML syntax. The documentation is [here](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#config-cli). 

I'll also propose that this also include the ability to pass `--config PATH` to specify the path of a config file to load. That is technically part of the config-include unstable option, which I'm not proposing to stabilize right now. I think supporting `--config PATH` is potentially useful, and I don't have any design concerns about it. config-include on the other hand has questionable utility, and may perhaps need more consideration.

@jonhoo or whoever wants to stabilize this, the general steps for stabilizing something is outlined in https://doc.crates.io/contrib/process/unstable.html#stabilization. To support `--config PATH`, it will require a small change in the code. I think this cane be done by changing [these two lines](https://github.com/rust-lang/cargo/blob/dba5baf4345858c591517b24801902a062c399f8/src/cargo/util/config/mod.rs#L1173-L1174) to instead call `self.load_file(…)`.

**Comment by Nemo157** [comment]
I see two issues with the `--config PATH` extension:

* It seems potentially confusing as to whether it replaces the "lookup `.cargo/config`" logic or just includes over top of it (see https://github.com/rust-lang/cargo/issues/9769 for usecases that want to override this logic).

* There is also the ability to use its edgecases to override the config that is loaded:

  ```
  > touch 'build.target-dir="target"'
  > cargo build --config 'build.target-dir="target"' -Z unstable-options
  ```

  This does not apply the requested config because it loads the empty file instead.

These could both be mitigated by using a separate flag like `--config-include PATH` for the feature.

**Comment by ehuss** [comment]
I'm not sure I see how it can be confusing, as `--config` is documented as merging onto the existing config.  Would documentation be sufficient to resolve your concern?  The intent to is to have a uniform CLI experience.  The override order can be derived from the order of the CLI flags easily when it uses just one flag.  I'm not sure if clap has gained the ability to group the order of multiple flags, but I'm not aware of it being able to do that.  If it were separate flags, I think that would be confusing as to try to determine which order they are evaluated.

I'm not terribly concerned about filenames that happen to be valid TOML syntax. Do you expect that to happen in practice? Why would someone create such a thing?

I understand that config file discovery is an important issue.  However, I don't think this would be in opposition to whatever solution is done for that.

**Comment by ehuss** [comment]
@fcpbot concern restricted-values

I am thinking it might be good to prevent setting some sensitive values. We have been moving towards discouraging placing things like tokens on the command-line since they can more easily be leaked that way.  

I think the only keys that would be sensitive are `registry.token` and `registries.*.token`. There are other keys that could potentially include things like passwords like a URL, but I don't think it needs to go that far.

Do other people think it would be good to at least prevent tokens?  Is that overkill?

The `--token` CLI option exists today, and the user can leak with that, but I think in some distant future it would be good to deprecate that option.  Users can also leak by setting environment variables on the command-line, but there's only so much we can do to prevent that. Hopefully in the future there will be better authorization mechanisms.

**Comment by ehuss** [comment]
@rcpbot concern restricted-values

I always mistype that.

**Comment by ehuss** [comment]
@rfpbot concern restricted-values

Mistypes galore.

**Comment by ehuss** [comment]
@rfcbot concern restricted-values

Sorry, mistypes galore.

**Comment by jonhoo** [comment]
I think having a restricted list like that makes a lot of sense! I'll try to find some time to update with that change 👍

**Comment by jonhoo** [comment]
@ehuss Implemented that in https://github.com/rust-lang/cargo/pull/10580

**Comment by ehuss** [comment]
@rfcbot resolve restricted-values

Thanks @jonhoo!

**Comment by jonhoo** [comment]
@ehuss Do you want me to send a stabilization PR for this?

**Comment by ehuss** [comment]
Yes, please!
