### ISSUE TITLE
Unexpected behavior: cargo rustc -- --emit=llvm-ir

### ISSUE THREAD

**Issue by JOE1994** [rust-lang/cargo#7765]
**Problem**
* **Description of bug**
  Running `cargo rustc -- --emit=llvm-ir` does not produce output IR. Instead, a warning message **"warning: ignoring emit path because multiple .ll files were produced"** is printed out.
  I expected that running `cargo rustc -- --emit=llvm-ir` would produce an llvm-ir output file.
* **Environments that I tested to reproduce problem**
  * Windows 10 OS, rustc 1.42.0-nightly (0de96d37f 2019-12-19), cargo 1.41.0-nightly (626f0f40e 2019-12-03)
  * Ubuntu WSL, rustc 1.42.0-nightly (0de96d37f 2019-12-19), cargo 1.41.0-nightly (626f0f40e 2019-12-03)

![image](https://user-images.githubusercontent.com/10286488/71771538-b91bb280-2f0a-11ea-9cea-84a662cde454.png)

**Steps**

1. Set up a minimal Rust project as the image above.
2. Run `cargo rustc -- --emit=llvm-ir`

**Possible Solution(s)**
This is not a solution, but running `rustc src/main.rs --emit=llvm-ir` worked as I expected in both the environments that I tested; **llvm-ir** output was generated as a file.

**Notes**

Output of `cargo version`: cargo 1.41.0-nightly (626f0f4 2019-12-03)

**Comment by ehuss** [comment]
The `.ll` files should be in the `target\debug\deps` directory.  (That's where all output goes.)

You may want to turn off incremental compilation (in the profile, or env var), since that changes how rustc splits the code generation (causing multiple files). It is a known issue that incremental causes this: https://github.com/rust-lang/rust/issues/48147

The warning is a false-positive (https://github.com/rust-lang/rust/issues/49801), `rustc` just seems to be confused when there are multiple `.ll` files.

**Comment by JOE1994** [comment]
Thank you for the clarification 👍
