### ISSUE TITLE
No way to unset environment variables

### ISSUE THREAD

**Issue by rossmacarthur** [rust-lang/cargo#7790]
**Describe the problem you are trying to solve**

I would like to unset environment variables when tests are run.

I need this because I have tests for a CLI program (it uses structopt) and if the environment I'm running in has certain environment variables set it can interfere with the tests.

**Describe the solution you'd like**

I first tried to remove the environment variables in a build script using `std::env::remove_var("VAR")` but that didn't work.

Then tried to do this in a build script using `cargo:rustc-env=VAR=` however this still sets it to an empty string. So a similar option like `cargo:rustc-remove-env=VAR` would be nice. Of course a way to run some code before tests are run could also solve this.

So now I have to remove the environment variables in every test :/

**Comment by lukaslueg** [comment]
FWIW there has been discussion about this in #4505 and #4557, specifically [this](https://github.com/rust-lang/cargo/pull/4557#issuecomment-334307773)

**Comment by ehuss** [comment]
I'm going to close in favor of #4505 since it mostly the same thing.

I would recommend writing something in your tests that spawns your CLI with the environment you desire.  Cargo's own test suite does this ([here](https://github.com/rust-lang/cargo/blame/972b9f55a72e3eae21c826b2f806c753696ef2ec/crates/cargo-test-support/src/lib.rs#L1716-L1744)).
