### ISSUE TITLE
Make `--release` default (at least for dependencies)

### ISSUE THREAD

**Issue by kud1ing** [rust-lang/cargo#784]
Is there a reason why building (dependencies) with full optimization is an opt-in?

I can imagine it will lead to many "Rust is slow" complains, as in:
> A: It's rather nice to work with, but it's a bit too slow for me to actually use.
> B: If you are using Cargo, you need --release to get the full optimization.

http://www.reddit.com/r/rust/comments/2kp1di/presenting_rustimage_v01/clnihza

**Comment by tanadeau** [comment]
I've created an issue in rust-lang/rfcs for a similar problem with direct rustc usage (https://github.com/rust-lang/rfcs/issues/777). It would be nice to have a message when using non-release builds that optimizations are turned off so that beginners (especially from JIT'ed/interpreted languages) know that "fast code" isn't the purpose of the default build.

**Comment by dotdash** [comment]
I agree with @kud1ing on this one. Having to endure slow code in the dependencies just because I want to debug _my_ code is rather unfortunate. Just consider how much fun it would be if you also had to build LLVM without optimizations just because you want to an unoptimized build of rustc. For me, building your dependencies without optimizations is often a "last resort" for debugging, when I consider that the dependency itself might be broken.

**Comment by pornel** [comment]
@tomaka Perhaps the default should be to optimize the dependencies _and_ keep their symbols? Of course debug info won't be as accurate for an optimized dependency, but that's not as important as for one's own code.

**Comment by kud1ing** [comment]
Another "Rust is slow" story: http://www.reddit.com/r/rust/comments/2x6652/experiences_migrating_a_go_project_to_rust/

**Comment by tbu-** [comment]
@kud1ing Complaining about the status quo like this is not necessarily good – you can't see if the other option would raise similar problems with users about the even slower compilation speed.

**Comment by kud1ing** [comment]
@tbu-: To me this issue is a suggestion to imrpove a problem that many people encounter. Backed by experience reports. Can you point out which part should be improved?

**Comment by tbu-** [comment]
I want to say that if you introduce a new problem by fixing the "problem that people encounter", then you might generate a new "problem that people encounter".

It is known that this is a problem, that however does not mean that the other problem (longer compilation times) isn't a "problem that people encounter", you just don't see that *yet*, because it's not yet changed.

**Comment by kud1ing** [comment]
Well that's natural to me. First you identify a problem and agree that it's a problem worthwhile to solve. Then you try a solution and see that the solution is correct or even worth it.

I think this proposal right now is between step 1 and 2.
I'd be interested in @alexcrichton current view on this. I think i can not add much to make my point. Close it if you like.

**Comment by tomaka** [comment]
Even if it's not made default, I'd still appreciate if there was a way to compile the dependencies in release.

If I compile the program I'm currently writing in debug mode, it takes ~10 seconds to compile but has a loading screen of around ~20 seconds. If I compile it in release mode, it takes ~30 seconds to compile but the loading screen is almost instant.

If dependencies were compiled in release mode, I would get the best of the two worlds: 10 seconds to compile and an almost-instant loading screen.

**Comment by kud1ing** [comment]
If you look at Haskell's cabal or Node's npm etc., you'll see that package managers are not only used by developers to build the software they are writing, but it's also a means for users of software to download, compile and install it.

People are used to commands like `foo install bar`. I don't want cargo to be the exception, where you get dog-slow software unless you keep remembering to always add a "--release".

**Comment by huonw** [comment]
The defaults for the hypothetical `cargo install` command are orthogonal to the defaults for the `cargo build` command. (I would be quite surprised if many people wanted `cargo install` to not default to `--release`.)

**Comment by kud1ing** [comment]
A decision " use `--release` for software someone just wants to use" would affect both `build` and `install`.

**Comment by steveklabnik** [comment]
No, it would be for `install`. If you're building yourself, then you need
to understand what the build does.

**Comment by globin** [comment]
At least I definitely more often need shorter build times and easier "debugability" when building as 99% of the time I'm building while developing and relying on test and/or typecheck.

For `install` I agree that optimisations should be enabled by default. They are currently on my install branch.

**Comment by kud1ing** [comment]
> If you're building yourself, then you need to understand what the build does.

I can't follow. When i am using third party libraries i almost never want to build the non-release, unless they are really buggy.

**Comment by steveklabnik** [comment]
(to be clear, my comment was just about a regular build, not dependencies. I'm not sure how I feel about their setting)

**Comment by kud1ing** [comment]
I think that one wants the dependencies optimized most of the time. I am not sure about one's own code. Longer build times are a downside. People publishing unoptimized benchmarks suck too.

**Comment by tanadeau** [comment]
I created #1309 a while ago to log the profile so that at least people can say the've been warned.

**Comment by alexcrichton** [comment]
@kud1ing 

>  I'd be interested in @alexcrichton current view on this. I don't think i could add much to this discussion to make my point. Close it if you like.

I agree with your analysis here. This is a real problem, but I'm not sure that we've settled on quite the right solution just yet.

I think that the gist of #1309 that @tanadeau is proposing is quite promising, however.

---

@tomaka 

> Even if it's not made default, I'd appreciate if there was a way to compile the dependencies in release.

I very much agree! I have opened #1359 on this topic.

**Comment by lahwran** [comment]
I like the idea of *cargo* reminding me that I built something in debug mode and not fast mode, not just *rustc* reminding me. It would also be nice for cargo to point out to me that it puts release binaries elsewhere, because even knowing I needed --release to get fast code, my benchmarks were skewed because I was running the debug binary in target/projectname, not the release one in target/release/projectname. It was off by a factor of 10, and was enough slower that I did a major refactor for performance - which did end up doubling speed once optimizations were on, but that's 0.25 sec vs 0.13 sec, so w/e.

**Comment by alexcrichton** [comment]
@lahwran that's actually another separate issue as well! 

https://github.com/rust-lang/cargo/issues/785

**Comment by luser** [comment]
`--release is significantly slower to build, and every other compiler I know of defaults to no-opt.`

@huonw : I submit that this is not a fair analogy. `cargo` is not a compiler, it is a *build system*. Many projects' build systems default to building with optimization by default (Firefox included) so that the resulting binaries are usable for their intended purpose, and require passing extra flags to get an unoptimized build (`--disable-optimize` for Firefox) or a build with extra assertions (`--enable-debug` for Firefox).

It's fine for `rustc`, which *is* a compiler, to default to building without optimization (like most other compilers), but the argument for `cargo` is not as straightforward.

**Comment by kud1ing** [comment]
Just for reference, people still trip over this: https://www.reddit.com/r/rust/comments/4tikmf/why_is_my_forth_virtual_machine_written_in_rust/

**Comment by pornel** [comment]
FWIW, people [also forget to add `-O` to `gcc`](https://github.com/bdaehlie/lossy-compression-test/pull/2/commits/4a28c5ef9746768efdc35b2c1b8d06478e73cb15), so the fact that other compilers don't optimize by default may not be the best decision for them either.

**Comment by qm3ster** [comment]
I have a question about `cargo install`. Where is the `--release` profile that is used to install binaries to my system?
I am asking in order to make sure that my binaries are installed with `lto = true`

**Comment by ehuss** [comment]
If you want to experiment with a nightly unstable feature, you can use [config overrides](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#config-profiles).  The easiest way is probably to use an environment variable like this:

```bash
CARGO_PROFILE_RELEASE_LTO=true cargo +nightly install NAME -Z config-profile
```

**Comment by qm3ster** [comment]
@ehuss Am I correct to understand that `-Z config-profile` is required for cargo to pay attention to `CARGO_PROFILE_RELEASE_LTO=true` being in the environment?

**Comment by ehuss** [comment]
> Am I correct to understand that -Z config-profile is required for cargo to pay attention to CARGO_PROFILE_RELEASE_LTO=true being in the environment?

@qm3ster correct.

**Comment by dagit** [comment]
People are still getting hung up on this: https://www.reddit.com/r/rust/comments/g8tebx/rust_handling_fewer_requests_per_second_than_node/fopimx2/

**Comment by kornelski** [comment]
Yeah, this is a recurring problem. In user forums there are also people showing up from time to time asking why Rust is slow, and half of the time it's just the `--release` flag.

**Comment by kornelski** [comment]
Now cargo has build-override feature that could be used to build deps in release mode. But I'm not sure anymore whether that's the good default, because then users could wonder why the app is fast in general, except their own code is slow.

So maybe this should be fixed with clearer messaging. Perhaps one-time-only message to avoid annoying regular users.

Currently Cargo prints:

>   Finished dev [unoptimized + debuginfo] target(s) in 15.19s

which is perhaps too subtle. What if it was a bit more explicit:

>   Finished dev [unoptimized + debuginfo] target(s) in 15.19s
> warning: unoptimized build is SLOW. Build with `--release` to make it fast.

**Comment by timmyjose** [comment]
I've read all the comments in here, but the main issue in my opinion is that `--release` must be made default because apart from absolute beginners, debugging is not the normal state, running fast optimised code is. And yes, I'm talking during development. *If* something goes wrong, then one may use `--debug` to switch to debug mode. That is why practically all other languages offer release mode equivalents as the default and the programmer has to explicitly opt into debug mode. 

Right now, an alias works fine, but I strongly feel that this default should be in the compiler itself.

**Comment by epage** [comment]
"must" is a strong statement.  There are a lot of different cases and they depend on the size of the program, the developer workflow, the tests, and how everything is broken down.  When you start getting into large, pure-Rust applications, the test times and runtimes can push people to doing release builds.  There are still a lot of people on the other side of things, like myself, where I spend most of my time in the edit-build-test cycle and want fast compile times.  I notice the build times when I run my benchmarks and would appreciate any help with it (like #2234) to avoid those slow release builds.

Something missing from this discussion is handling of path dependencies.  Generally they are developed with their dependents, so should be debug by default, rather than release?  However, some large applications will be just a single workspace and you can still run into wanting them built in release mode.  I'm having a hard time seeing one true answer for this so this falls back to what case you should optimize for.  Personally, I would lean towards developer productivity of new and independent developers rather than the large applications.

**Comment by timmyjose** [comment]
> personally, I would lean towards developer productivity of new and independent developers rather than the large applications.

That is the main argument being brought about in the comments here though albeit in support of release rather than debug. Most complaints from people new to Rust (from the linked threads) seem to be about Rust execution being slow rather than the edit cycle.
