### ISSUE TITLE
prints clippy warnigs from cache during normal "cargo build"

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/cargo#7867]
**Problem**
While building rustc, I have observed, that when running clippy (`./x.py clippy`) and than running a normal build afterwards (`./x.py build`), some of the clippy warnings will be printed from the message cache, although clippy is not executed during `x.py build`.
 

**Steps**

1. x.py clippy
2. x.py build

Looks like the clippy messages are retrieved from the cache when they are not supposed to.

**Notes**

Output of `cargo version`:
rustc repo @ 4ff8fb9cb210a9f06e0eafc364bd12de2b67f087
cargo version `cargo 1.42.0-nightly (9d32b7b01 2020-01-26)`

**Comment by ehuss** [comment]
I think it is because `cargo clippy` also enables clippy when building build dependencies.  Those build dependencies are reused with `cargo build`.  This normally doesn't come up because build dependencies are normally not local path packages. 

I think with #7533 it'll get fixed because it would modify the metadata hash so that it won't share the built dependencies with `cargo build`.

**Comment by ehuss** [comment]
Closing in favor of https://github.com/rust-lang/cargo/issues/8143 and https://github.com/rust-lang/rust-clippy/issues/3837.
