### ISSUE TITLE
Build and download in parallel

### ISSUE THREAD

**Issue by SRGOM** [rust-lang/cargo#7908]
Hello, 

If it's alright, I'd like to propose a feature. (selfishly... :) ).

I'm not always on fast connection and I would love if building and downloading could be done in parallel.

Currently, I believe the following happens- cargo downloads a crate and then recursively traverses the dependency graph. What could be great is if a crate registry stored direct dependency information for each version of a crate. (I'm sure there are more complications but just to get the discussion started...), and there was an API to get this information. `cargo` would recursively use this information to build a graph and get all the `"leaves"`. It then downloads those leaves first and compiles them. Before downloading inner nodes. Or the complete graph itself could be on the crate registry...?

Ultimately I feel like not all of us have great internet at all times and this could be something that would benefit a lot of us. This also brings down the perceived compilation time and hopefully changes the impression, which IMHO counts too, in general usage.

**Comment by ehuss** [comment]
Thanks for the suggestion!  I can sympathize, as my connection is kinda slow, too.  Unfortunately I think this would be a Herculean effort to rework Cargo to support this. There are certain post-processing steps that are done after building the compilation graph, and those require knowing the entirety of the graph, and all packages must be downloaded to get the required information. I'm not sure how much information is missing from the index, but it could result in bloating it somewhat, and we don't have any precedent for retroactively updating it.

I'm going to close this, since it is unlikely to happen.  Although it would be nice, I don't think it is feasible today.

**Comment by SRGOM** [comment]
My knowledge is limited so please pardon me if I sound insistent but as a somewhat alternative proposal wouldn't it be enough to only mass download `cargo.toml` files in a top-sort fashion? This should be way cheaper and once the dependency graph is built, download the full crates (and build in parallel)

**Comment by epage** [comment]
Some thoughts that came up in #15997.

If someone is looking for us to re-evaluate our answer on this, it would help to understand what your use case is and the impact this has on it.  This can help us weigh the complexity in getting their to the gains and allow us to explore other options to get similar gains, like #2526.

As for the implementation, on top of the work within the compilation graph, we'd also need to resolve #15834.
