### ISSUE TITLE
Allow programs to detect which cargo version called them

### ISSUE THREAD

**Issue by xd009642** [rust-lang/cargo#7976]
Brief context here: https://github.com/clap-rs/clap/issues/1733 basically if creating something like a cargo subcommand crate I'd like a way to detect if my tool was launched with anything like `+nightly`

**Comment by ehuss** [comment]
The toolchain overrides are implemented by the rustup wrapper, not Cargo.  Rustup already sets the `RUSTUP_TOOLCHAIN` environment variable, so you should be able to use that.   Also, rustup modifies `PATH` and uses the `RUSTUP_TOOLCHAIN` value so that the override is "sticky".  Running cargo or rustc commands from a cargo wrapper should just magically use the correct version.  I'm not sure why you want the toolchain, but usually it should not be needed.

**Comment by xd009642** [comment]
Oh didn't know about that, cool that should solve it. And because my tool ends up use `std::process::Command` to build the tests for a project with some extra flags etc so for some features nightly may need to be propagated down.

I was using cargo as a library to avoid this but that caused it's own issues with nightly features
