### ISSUE TITLE
Add longPathAware to the app manifest on Windows

### ISSUE THREAD

**Issue by MOZGIII** [rust-lang/cargo#7986]
**Describe the problem you are trying to solve**

On Windows, when the directory where the project files are located is too long, cargo fails with various file-related errors.

**Describe the solution you'd like**

Rust should handle long path ok. We just have to add a `longPathAware` to the app manifest:
https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file

```xml
<application xmlns="urn:schemas-microsoft-com:asm.v3">
    <windowsSettings xmlns:ws2="http://schemas.microsoft.com/SMI/2016/WindowsSettings">
        <ws2:longPathAware>true</ws2:longPathAware>
    </windowsSettings>
</application>
```

**Notes**

This issue only occurs if the file paths cargo wants to touch are too long.
This happens with paths like these:
```
C:\Users\User\AppData\Local\Yarn\Cache\v6\.tmp\19aa03367eb9c4791798fcfbbdd8d7d4.e2c16fa02b2d9250fe13c2054c37a11aef5c0da3.prepare\native\target\x86_64-pc-windows-msvc\release\.fingerprint\semver-parser-dc26c18a352c24f5\lib-semver_parser-dc26c18a352c24f5.json
```

**Comment by ehuss** [comment]
I think this would be a very hard problem to solve, if not impossible.  Some issues I can think of:
* Rust doesn't have a way to embed the app manifest AFAIK.
* The default registry key needed for that is OFF, so I don't think it would help most people.
* All the windows-interfacing APIs (in C and Rust) would need to be audited/updated for the larger constant.
* All of rustc and cargo would need to handle this.
* IIRC, MSVC's linker can't handle long filenames, so it probably wouldn't work even if we tried.
* Many other tools would not be able to handle these paths.
* We could maybe try to use canonicalized UNC paths everywhere, but I think that would be very difficult and problematic. We already have problems with UNC paths on various filesystems. They are also not user-friendly, so would probably need some abstraction that could show different representations.

**Comment by MOZGIII** [comment]
Thanks for the response! Maybe there's a workaround I could apply to handle this? Like setting a custom `CARGO_TARGET_DIR` - would that work? I think it should work...

**Comment by victoryang00** [comment]
It could be disable by the regedit.msc. so just stopping checking it in the cargo for windows'll be fine.

**Comment by RoguePointer80** [comment]
> Rust doesn't have a way to embed the app manifest AFAIK.

If your CI has the MSVC toolsets installed, you have all that you need. Don't have them? Here is [the direct download link](https://download.visualstudio.microsoft.com/download/pr/44fbb1ed-c06e-41c9-bc39-3d7f2083d61b/f860b197d3b8c07a1e59a49df13244a034b4a56693087bd8aabc440d9f989c7b/vs_BuildTools.exe).

> The default registry key needed for that is OFF, so I don't think it would help most people

But for the people who DO have it on, it would help. In my opinion, that's a pretty good start! And when developers start seeing that their colleague got it working, they will ask "hey dude, what did you do?", and soon their IT department will turn the switch on for all new dev computers.

> All the windows-interfacing APIs (in C and Rust) would need to be audited/updated for the larger constant.

If your windows-interfacing APIs are still using a static 260-char buffer, it's past time to fix that code. All Windows APIs have a way to query the required buffer length. The typical way is calling the function with a 0-length buffer, and the return code is the required length. Any skilled Windows developer should know that.

> All of rustc and cargo would need to handle this.

Yep. Let's start with this tool (this issue is about Cargo, right?).  When it's done, other executables will copy the solution. Lead by example!

> IIRC, MSVC's linker can't handle long filenames, so it probably wouldn't work even if we tried.

Have you tried? Or are you assuming other tools *might* not work as an excuse not to try? How will the situation improve if every maintainer used the argument "tool X is not updated, so I'm not updating tool Y" ?  I strongly believe that if everyone does their part, the ecosystem will quickly improve for everybody.

> Many other tools would not be able to handle these paths

Maybe they already do, but unless cargo is updated, we'll never know. And what's the worst-case here? That cargo supports it, and we find out that a downstream tool gives an error. Then we can create an issue and a PR for that downstream tool, and keep making progress.

> We could maybe try to use canonicalized UNC paths everywhere

Good point, excellent explanation. This is not a very good solution. The manifest solution seems a better approach.

**Comment by nitsky** [comment]
I just ran into this issue because I have a crate with a long name, over 100 characters each, so the path to the crate's location in the `target` folder exceeds the 260 character limit. Because of this, even `cargo build` fails. Does anyone following this issue know of any workarounds?

**Comment by eladkarako** [comment]
with a slightly less awkward namespacing (in an example).

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?> 
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0"> 
  <application xmlns="urn:schemas-microsoft-com:asm.v3"> 
     <windowsSettings>  <dpiAware      xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true/PM</dpiAware>                        </windowsSettings> 
     <windowsSettings>  <dpiAwareness  xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">PerMonitorV2,PerMonitor</dpiAwareness>    </windowsSettings> 
     <windowsSettings>  <longPathAware xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">true</longPathAware>                      </windowsSettings> <!-- also requires registry editing since this feature is disabled in the OS by default. https://docs.microsoft.com/en-gb/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd#enable-long-paths-in-windows-10-version-1607-and-later  --> 
     <windowsSettings>  <gdiScaling    xmlns="http://schemas.microsoft.com/SMI/2017/WindowsSettings">true</gdiScaling>                         </windowsSettings> 
     <windowsSettings>  <heapType      xmlns="http://schemas.microsoft.com/SMI/2020/WindowsSettings">SegmentHeap</heapType>                    </windowsSettings> 
  </application> 
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3"> 
    <security> 
      <requestedPrivileges> 
        <requestedExecutionLevel level="asInvoker"            uiAccess="false" /> 
   <!-- <requestedExecutionLevel level="highestAvailable"     uiAccess="false" /> --> 
   <!-- <requestedExecutionLevel level="requireAdministrator" uiAccess="false" /> --> 
      </requestedPrivileges> 
    </security> 
  </trustInfo> 
  <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1"> <!-- without it, apps will run in windows vista compatibility in windows 7.   https://docs.microsoft.com/en-us/windows/win32/sbscs/application-manifests#compatibility --> 
    <application> 
      <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}"></supportedOS> <!-- Windows 10/11  /  Windows Server 2016/2019  --> 
      <supportedOS Id="{1f676c76-80e1-4239-95bb-83d0f6d0da78}"></supportedOS> <!-- Windows 8.1    /  Windows Server 2012 R2    --> 
      <supportedOS Id="{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}"></supportedOS> <!-- Windows 8      /  Windows Server 2012       --> 
      <supportedOS Id="{35138b9a-5d96-4fbd-8e2d-a2440225f93a}"></supportedOS> <!-- Windows 7      /  Windows Server 2008 R2    --> 
      <supportedOS Id="{e2011457-1546-43c5-a5fe-008deee3d3f0}"></supportedOS> <!-- Windows Vista  /  Windows Server 2008       --> 
    </application> 
  </compatibility> 
</assembly> 
```

**Comment by mshaikhcool** [comment]
> don't get your hopes up,
as far as I can tell, at least for explorer.exe,
on Windows 10 Enterprise Preview build 19044.1200.210812-1726.21H2 - August 2021
you, still, can not handle path with length longer than 260 (actually 258) characters.

that's because No version of windows's  `Explorer.exe` embeds `longPathAware` in it's manifest file.
`longPathAware` has to  embedded per executable. 
 If `explorer.exe` embeds `longPathAware` in it's manifest, legacy executables that don't embed in the manifest will simply fail to launch from long path. That's the reason Win32 Long Paths registry key is off by default. 

Manifest files are an integral part of Modern Windows. **A system programming lang like Rust shouldn't do dilly-dally in this space.**

**Comment by mshaikhcool** [comment]
@ehuss as @RoguePointer80 addresses your points, and regarding Registry Key off by default point,  you should know the person installs a system programming lang like in the first place will most likely be A Developer, not a average-joe. so this point is moot.

First of all , Rust shouldn't call undocumented apis.
secondly, NT UNC(\\?\) paths are designed to be used by the Subsystems and KMDF Drivers, not user mode programs like Rust.
Third, that leaves the only way , that is to use embedded manifests per executables.
Fourth, all of these you listed above apparently are  assumptions that seem to come from  not using windows regularly.

**Comment by mshaikhcool** [comment]
@nitsky see this post https://gal.hagever.com/posts/windows-long-paths-in-rust/

**Comment by eladkarako** [comment]
Edit:  
possibly great news.  

I had excellent results using additional entry in the manifest called <code>gdiScaling</code> (along with existing <code>dpiAwareness</code> and <code>dpiAware</code>),  
the gdiScaling is not a drop-in solution (sometimes mdi forms acts weird due to being scaled into their containing parents and get cropped), each app acts different, the rule of thumb is to try an look if it looks fine,  
and it does! no blur as far as I can see.

<details><summary>this is the manifest, and a patched exe you may drop locally and see it yourselves</summary>

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?> 
<!-- August 2021. Elad Karako. --> 
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0"> 
<!-- a segment for identity, optional (you don't need it, unless you know you need it). --> 
<!-- 
  <assemblyIdentity 
      name="Microsoft.Windows.Shell.calc" 
      processorArchitecture="x86" 
      version="5.1.0.0" 
      type="win32"/> 
  <description>Windows Calc</description> 
--> 
<!-- apply the current Windows-theme to the controls of the application, if possible. --> 
  <dependency> 
    <dependentAssembly> 
      <assemblyIdentity name="Microsoft.Windows.Common-Controls" 
        version="6.0.0.0" publicKeyToken="6595b64144ccf1df" 
        type="win32" processorArchitecture="*" language="*"></assemblyIdentity> 
    </dependentAssembly> 
  </dependency> 
  <application xmlns="urn:schemas-microsoft-com:asm.v3"> 
     <windowsSettings>  <dpiAware                           xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true/PM</dpiAware>                        </windowsSettings>     <!-- https://docs.microsoft.com/en-us/windows/win32/sbscs/application-manifests#dpiaware --> 
<!-- <windowsSettings>  <printerDriverIsolation             xmlns="http://schemas.microsoft.com/SMI/2011/WindowsSettings">true</printerDriverIsolation>             </windowsSettings> --> <!-- for apps that initiate printing (such as Chrome, MS-word, Paint.Net), calls printer driver from within a sandbox so if it crashes it does not really effects the app itself or the OS, not really needed. unspecified value tend to work fine in either classic or shared manner (shared is default win W7+).  https://docs.microsoft.com/en-us/windows/win32/sbscs/application-manifests#printerdriverisolation --> 
<!-- <windowsSettings>  <highResolutionScrollingAware       xmlns="http://schemas.microsoft.com/SMI/2011/WindowsSettings">true</highResolutionScrollingAware>       </windowsSettings> --> <!-- ** DO NOT USE!!!!!! **  crashes apps in W10! should increase resolution in mouses that supports high DPI (1200 and such) but even putting it in the manifest - regardless of value WILL CRASH THE APP in W10+!!!  manually look in entries in: https://docs.microsoft.com/en-us/windows/win32/sbscs/manifest-file-schema#code-try-0 --> 
<!-- <windowsSettings>  <ultraHighResolutionScrollingAware  xmlns="http://schemas.microsoft.com/SMI/2011/WindowsSettings">true</ultraHighResolutionScrollingAware>  </windowsSettings> --> <!-- ** DO NOT USE!!!!!! **  crashes apps in W10! should increase resolution in mouses that supports (very) high DPI (1200 and such) but even putting it in the manifest - regardless of value WILL CRASH THE APP in W10+!!!  manually look in entries in: https://docs.microsoft.com/en-us/windows/win32/sbscs/manifest-file-schema#code-try-0 --> 
     <windowsSettings>  <dpiAwareness                       xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">PerMonitorV2,PerMonitor</dpiAwareness>    </windowsSettings>     <!-- improve 'dpiAware', can specify both. should help scale up legacy apps. https://docs.microsoft.com/en-us/windows/win32/sbscs/application-manifests#dpiawareness --> 
     <windowsSettings>  <longPathAware                      xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">true</longPathAware>                      </windowsSettings>     <!-- windows 10 only, override MAX_PATH (260) character limit in various windows APIs to allow 32k characters, paths are getting weird, although it is handled by the windows API so legacy apps should be fine too.   also requires registry editing since this feature is disabled in the OS by default. not a good idea to turn this ON since you might take files in sd-card or portable HD elsewhere and won't be able to copy or read stuff.   https://docs.microsoft.com/en-gb/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd#enable-long-paths-in-windows-10-version-1607-and-later  --> 
     <windowsSettings>  <gdiScaling                         xmlns="http://schemas.microsoft.com/SMI/2017/WindowsSettings">true</gdiScaling>                         </windowsSettings>     <!-- makes graphic programs such as ones that takes screenshots have bad functionality with larger-DPI (ease of access), since it also enlarges the controls in sub containers, and somtimes breaks the UI, for non-graphic-programs it might improve scale text and standard controls in apps, prevents blur. useful if you are using non 100% DPI for example in 'ease-of-access'. https://docs.microsoft.com/en-us/windows/win32/sbscs/application-manifests#gdiscaling --> 
<!-- <windowsSettings>  <activeCodePage                     xmlns="http://schemas.microsoft.com/SMI/2019/WindowsSettings">UTF-8</activeCodePage>                    </windowsSettings> --> <!-- changes a legacy program from default Windows code page 1252 to UTF-8, might mess-up display.     https://docs.microsoft.com/en-us/windows/win32/sbscs/application-manifests#activecodepage   https://docs.microsoft.com/en-us/windows/apps/design/globalizing/use-utf8-code-page#code-try-1   --> 
     <windowsSettings>  <heapType                           xmlns="http://schemas.microsoft.com/SMI/2020/WindowsSettings">SegmentHeap</heapType>                    </windowsSettings>     <!-- change windows heap API to use a modern implementation, windows 10+ only.                         https://docs.microsoft.com/en-us/windows/win32/sbscs/application-manifests#heaptype                                                                                                          --> 
  </application> 
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3"> 
    <security> 
      <requestedPrivileges> 
        <requestedExecutionLevel level="asInvoker"            uiAccess="false" /> 
   <!-- <requestedExecutionLevel level="highestAvailable"     uiAccess="false" /> --> <!-- best to avoid! use either 'asInvoker' or 'requireAdministrator'.  if you want to use this one - essentially the cases are bi-functional application, use if program can manage most of its functionality (such read only protected files/registry) but can work in write mode when user has admin right, dialog for admin details will be shown on demans, and if not providing admin-auth the specific action fails but the app can still run. --> 
   <!-- <requestedExecutionLevel level="requireAdministrator" uiAccess="false" /> --> <!-- use if program requires admin-access. standard user gets credentials dialog for admin-account-details. won't start the app without some admin-auth-details. --> 
      </requestedPrivileges> 
    </security> 
  </trustInfo> 
  <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1"> <!-- without it, apps will run in windows vista compatibility in windows 7.   https://docs.microsoft.com/en-us/windows/win32/sbscs/application-manifests#compatibility --> 
    <application> 
      <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}"></supportedOS> <!-- Windows 10/11  /  Windows Server 2016/2019  --> 
      <supportedOS Id="{1f676c76-80e1-4239-95bb-83d0f6d0da78}"></supportedOS> <!-- Windows 8.1    /  Windows Server 2012 R2    --> 
      <supportedOS Id="{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}"></supportedOS> <!-- Windows 8      /  Windows Server 2012       --> 
      <supportedOS Id="{35138b9a-5d96-4fbd-8e2d-a2440225f93a}"></supportedOS> <!-- Windows 7      /  Windows Server 2008 R2    --> 
      <supportedOS Id="{e2011457-1546-43c5-a5fe-008deee3d3f0}"></supportedOS> <!-- Windows Vista  /  Windows Server 2008       --> 
    </application> 
  </compatibility> 
</assembly> 
 ```
patched using my manifest tool (see above).  

patched exe.
[SubtitleEdit.exe.zip](https://github.com/rust-lang/cargo/files/7108762/SubtitleEdit.exe.zip)

</details>

as far as I can see only thing needed is to slightly modify the manifest for the project,  
and re-build, or patch existing build with mt.exe (ms manifest tool), long file support is optional. 

click for 1080p

![Untitled1](https://user-images.githubusercontent.com/415238/132071570-f21b0917-5aa9-4ce1-a350-bb60f2cf3e02.png)  

![Untitled2](https://user-images.githubusercontent.com/415238/132071576-d56afef3-bb12-4193-9438-9a3927d47a1b.png)

compare it with original screenshots (before the manifest patching) and it looks pretty much the same, just the text is more clear.

**Comment by eladkarako** [comment]
> that's because No version of windows's `Explorer.exe` embeds `longPathAware` in it's manifest file.

🤔  
🤩 Ha! you are right.  

W10 supports side-by-side manifest by default so I don't even need a <a href="https://gist.github.com/eladkarako/d24d5ed3c917ef230b0fc990104f9fe6#file-manifest-prefer-external-side-by-side-file-over-internal-resource-reg">registry patch like w/ windows 7, to make it favor a side-by-side manifest over the embedded one!</a> I'll just export the embedded manifests from explorer exe/dll/mui, patch them and place them in the same folder as the file with .manifest suffix. after a reboot explorer should have ~32k max length of characters :]
If anyone is planing the same, would not touch the exe (I.E. patch it with mt.exe) due to continues OS-checksum (<a href="https://github.com/eladkarako/manifest/">although can be done easily</a>).
overall - Super Easy, Barely An Inconvenience.

**Comment by mshaikhcool** [comment]
> I'll just export the embedded manifests from explorer exe/dll/mui, patch them 

Wah ! Clever. forgot about SxS manifest support. I'm afraid about that "Patch part"  i.e the post-patching consequences here, especially about touching core executables

**Comment by ChrisDenton** [comment]
`rustc` has been [using an application manifest file](https://github.com/rust-lang/rust/commit/7255bc63387eacd097e960800a05299c93e57d4d) for a while now (since 1.63). There have yet to be any reported issues.

A manifest allows setting more than just `longPathAware`. rustc sets the supported OSes and also sets the code page to UTF-8. It's implemented as a build script which leverages MSVC's link.exe to do the actual embedding (alternatively, `.cargo/config.toml` might be used). So it's actually easy to do for that target.

I think at a minimum cargo should set the OSes it supports so as to avoid unnecessary compatibility shims. I'd also advocate for setting the other two options even if they're less likely to be needed in Rust itself (due to using the UTF-16 APIs).

**Comment by ehuss** [comment]
Closing as #13131 has added a manifest. That is just the beginning of long-path support. See the meta tracking issue at #9770, and #13141 for some more examples of what still doesn't work.

For people hitting the issue in git clones, be sure to check out #13020 which has more information (in short, add `core.longpaths=true` to your git config).

**Comment by mati865** [comment]
This issue has been solved only for MSVC targets, should the same be done for Windows GNU?

**Comment by ChrisDenton** [comment]
Last I looked (which was awhile ago) that was more complicated because gnu didn't have linker arguments for adding a manifest so you either had to use a post-build step to edit the binary or else manually construct an object file with the right tables and link them (which is a much more involved process). Maybe that's changed though.

**Comment by mati865** [comment]
Oh, that could be a problem, we would nee to use LLD to circumvent it.
