### ISSUE TITLE
Feature request: clone only last commit for index repository

### ISSUE THREAD

**Issue by aristarh2704** [rust-lang/cargo#7995]
Now, at first cargo running, it download full crate.io repository. It takes many time and sometimes it's happens unsuccessfully . It's needed for cloning only last commit, for time and memory preserve

**Comment by aristarh2704** [comment]
Already more than 3 times cargo cannot update repository

**Comment by ehuss** [comment]
I don't think this will be possible today. GitHub has asked other registries in the past to not do that due to issues on their servers.  Additionally, I believe our git implementation doesn't support shallow clones.  See also #2452, #1171, #5597, and [RFC 2789](https://github.com/rust-lang/rfcs/pull/2789).

We periodically squash the index history to reduce the size.  Thanks for the ping, though, it looks like we need to squash it again.

I'm not sure if you have particularly poor connectivity to github from where you are, but if you do perhaps there is a vpn or mirror you can use?

**Comment by aristarh2704** [comment]
I can use cargo config for fetching repository with CLI. In which case, it's possible fetch only last commit
