### ISSUE TITLE
cargo install with specific yanked version gives confusing "not found" error

### ISSUE THREAD

**Issue by ehuss** [rust-lang/cargo#8171]
`cargo install` with a specific version that has been yanked gives a slightly confusing error:

```
> cargo install cargo-tarpaulin --version 0.10.1
error: could not find `cargo-tarpaulin` in registry `https://github.com/rust-lang/crates.io-index` with version `=0.10.1`
```

I think maybe it would be good to at least mention that it is yanked.

This is similar to #4260, where specified as a dependency also says "no matching version". In general, the yanked crates become invisible to resolution, and I'm wondering if maybe it should at least provide a hint.

**Comment by Eh2406** [comment]
This is going to be hard to fix. The code [literally filters](https://github.com/rust-lang/cargo/blob/8a0d4d9c9abc74fd670353094387d62028b40ae9/src/cargo/sources/registry/index.rs#L408) out yanked crates. So the resolver code has know way to know that the yanked crates existit. This is done that way because the resolver is already too complicated and hard to understand, it has to intrinsically solve `NP-Hard` problems. So a `O(n)` filter is a grate win on the code complexity budget.

The one thought I had while writing this up is that in making the error message we [re-query the registry](https://github.com/rust-lang/cargo/blob/45ad3f9986f71a1fe7ce0dbea84551b2da57eab6/src/cargo/core/resolver/errors.rs#L190-L306) several times to generate the `versions found` section. Maybe we can have that query include yanked versions, somehow.

**Comment by ehuss** [comment]
For `install`, I was specifically thinking the install code could re-query, similar to what it does [here](https://github.com/rust-lang/cargo/blob/90931d9b31e8b854522fed00916504a3ac6d8619/src/cargo/ops/cargo_install.rs#L500-L528).  I agree that #4260 would be much harder.
