### ISSUE TITLE
Put `Cargo.lock` in exclude field for library crate

### ISSUE THREAD

**Issue by lzutao** [rust-lang/cargo#8231]
The <https://doc.rust-lang.org/nightly/cargo/guide/cargo-toml-vs-cargo-lock.html> talks about 
the need between Cargo.lock for library crates. And that page suggests ignore
`Cargo.lock` in `.gitignore`. I think rather than putting `Cargo.lock` in `.gitignore`, put it in the [exclude field](https://doc.rust-lang.org/nightly/cargo/reference/manifest.html#the-exclude-and-include-fields) instead. This has few advantages:
* There are people don't use git.
* Checking in `Cargo.lock` for taking advantages of CI caching.

**Comment by lzutao** [comment]
Concern: Is Cargo.lock overridden by docs.rs when publishing?

**Comment by ehuss** [comment]
Sorry, I don't understand what this is asking.  Putting it in `exclude` wouldn't have any effect for a library-only package. 

I think if you are using another VCS, it's fairly easy to adapt the instructions to whatever you are using, I don't think that is a strong concern.

There are drawbacks for a library-only package to check-in `Cargo.lock`. Since all other users won't be locked to that dependency set, you'll be testing something different from what everyone else uses. If you're advanced enough to be concerned with CI caching, I imagine you should be able to figure out whether or not using `Cargo.lock` is right for your project. I wouldn't want to make that recommendation, particularly for newer users.

**Comment by ehuss** [comment]
Closing since putting in exclude probably would not have the desired effect.  There are advantages and disadvantages to checking in Cargo.lock, and I think the current advice still holds.
