### ISSUE TITLE
"dep-info invalid" when trying to compile Servo

### ISSUE THREAD

**Issue by mikedilger** [rust-lang/cargo#8298]
**Problem**

cargo check is giving me this output
````sh
error: dep-info invalid
note: this is an unexpected cargo internal error
note: we would appreciate a bug report: https://github.com/rust-lang/cargo/issues/
note: cargo 1.45.0-nightly (cb06cb269 2020-05-08)
````

Since it explicitly wants me to file a bug report, I am dutifully doing so.

**Steps**

For me, all I did was:

1. Pull servo from https://github.com/servo/servo (master is currently at 14303bd651e248e6e7a73759d622658088f9ddf1)
2. run 'cargo check'

That probably wont reproduce it for you because if it did, none of the Servo devs would be able to work, which probably isn't happening.

**Possible Solution(s)**

I suppose there might be data in my ~/.cargo from previous versions of cargo that just ain't playing nicely.  But it is out of my depth to speculate on a solution.

**Notes**

Output of `cargo version`:  
cargo 1.45.0-nightly (cb06cb269 2020-05-08)

My system is ArchLinux, amd64

**Comment by mikedilger** [comment]
I see dep-info is related to fingerprints which are in target directories.  I had a target/ directory from June 20 2019, last time I played with servo.  cargo clean fixed this.

I kept the old target directory in case anyone cares to pursue this.

**Comment by ehuss** [comment]
Thanks for the report.  I'm able to repro, so no worries about that.

There is an assumption that the fingerprint directories have the rustc version in the hash, and thus backwards incompatible changes to the fingerprint formats are automatically handled when upgrading the version of rust.  However, not all fingerprint hashes include the rustc version in the hash.  I'm rather surprised this is the first report of this, since around that time (mid June 2019) there was a backwards incompatible change made to the fingerprint format. 

I'll take a look at a fix.  Backwards incompatible changes are rare, but it definitely shouldn't barf on it.

**Comment by ehuss** [comment]
Repro:

```bash
cargo new --lib foo
cd foo
echo "[lib]" >> Cargo.toml
echo 'crate-type = ["dylib"]' >> Cargo.toml
cargo +nightly-2019-05-14 build
cargo +nightly-2020-05-30 build   
```
