### ISSUE TITLE
cargo run --release --example doesn't use release profile

### ISSUE THREAD

**Issue by seanmonstar** [rust-lang/cargo#831]
The `--release` isn't looked at if the `--example` flag exists in `cargo run`. I'd expect it to use the release profile, or at least, warn that it isn't.

**Comment by rndr** [comment]
i was not expecting `--release` be ignored with `--example` either.
fix to this looks trivial and it does not look like this issue was noticed.
@alexcrichton?

**Comment by alexcrichton** [comment]
This is likely due to [this line](https://github.com/rust-lang/cargo/blob/5443813c6dcc7c11dd4e80195c46498a5a033ff3/src/bin/run.rs#L54) which sets the profile to "test" without ever setting the optimization level (which is normally derived through "release").

In general Cargo's internal handling or profiles/targets is pretty messy, and I've been meaning for quite some time to overhaul it to fix bugs like this, but sadly I've been largely tied up with the standard library now.
