### ISSUE TITLE
cargo run -p and cargo test -p uses different working directories

### ISSUE THREAD

**Issue by keepsimple1** [rust-lang/cargo#8340]
**Problem**

In a workspace setting, it seems that `cargo test -p` and ` cargo run -p` are using different working directory:
- `cargo test -p <package>` uses the package directory as the default directory, while
-  `cargo run -p <package>` uses the workspace directory as the default directory. 

**Steps**

1. create a new cargo workspace with one package `foo` inside.
2. create a text file `bar.txt` in `src/` inside the package `foo`.
3. create a test inside the package `foo` that read the file `bar.txt` using path `src/bar.txt`.
4. In the main function of package `foo`, also read the file `bar.txt` using path `src/bar.txt`.
5. `cargo test -p foo` will run successfully (i.e. able to read `bar.txt`).
6. `cargo run -p foo` will fail (cannot find `bar.txt`).

**Possible Solution(s)**

`cargo test -p` and `cargo run -p` should use the same default working directory. IMO, both should use the package directory (not the workspace directory) as the default directory.

**Notes**

Output of `cargo version`:
cargo 1.43.0 (2cbe9048e 2020-05-03)

**Comment by ehuss** [comment]
I think it is somewhat intentional that `run` uses the current directory.  This allows you to go to a different directory, and run a command as-if you run it in that location.  It would also be a breaking change, so it would likely be too disruptive to change.

We have been talking about adding a `-C` argument that would change the current directory, though you would need to pass a path instead of a package name.

**Comment by keepsimple1** [comment]
@ehuss any ideas why `test` uses a different approach ?

**Comment by ehuss** [comment]
Presumably, that allows tests to reliably access paths from the package they are defined in.

**Comment by ehuss** [comment]
I'm going to close this, as this is expected behavior and unlikely to change.  In the future, the `-C` argument may be an alternative approach to getting the desired behavior.
