### ISSUE TITLE
Cargo build fails with StreamError on Windows 10

### ISSUE THREAD

**Issue by kapil-ms** [rust-lang/cargo#8371]
Hi

I am compiling my project using `cargo build` on Windows 10. I also have `RUST_BACKTRACE=1` set. I get the following error and no more stack trace. 

rustc version `1.44.0 (49cae5576 2020-06-01)`

```
Compiling app v0.1.0 (D:\app)
error: Stream Error: The stream is too short to perform the requested operation.
error: could not compile `app`.

Caused by:
  process didn't exit successfully: `<redacted>` (exit code: 0xc000001d, STATUS_ILLEGAL_INSTRUCTION)

Process finished with exit code 101
```

Any help is appreciated. Thanks

**Comment by alexcrichton** [comment]
Thanks for the report! It looks like `<redacted>` there is rustc, is that right? If so I think this is a rustc bug rather than a Cargo bug. You'll want to try to reduce the Rust code in question down to report a bug to upstream rust-lang/rust. Unfortunately "rustc crashes" isn't too actionable for others to help fix it. If you can attach a debugger and get a backtrace or provide code to reproduce, that will be very helpful for the compiler team!
