### ISSUE TITLE
Enable features on an indirect dependency exposed via public API

### ISSUE THREAD

**Issue by jhpratt** [rust-lang/cargo#8413]
**Describe the problem you are trying to solve**
Enable a feature on an indirect dependency (that is exposed in public API)

**Describe the solution you'd like**
Something like the following?

```toml
sha2 = { version = "0.9", features = ["digest/more_lengths"] }
```

This would require explicit knowledge of the dependencies. This is admittedly not the best of ideas, but could be limited to situations where the type is only in the public API. I've no idea how that would interact with Cargo, however.

**Notes**
This would be analogous to enabling features of direct dependencies in a crate's features listing, though it wouldn't require the intermediate crate to re-export features.

**Comment by ehuss** [comment]
I think for now it is intentional that this is not allowed. Features of transitive dependencies are intended to be private implementation details, not exposed as part of the API unless explicitly re-exported by the package. 

In this example, if you want to enable features on the `digest` package, you can explicitly list it as a dependency within your own package.

Closing as this is intended behavior, and there are other ways to express the desired features.  I realize controlling features of deep dependencies can sometimes be awkward, but I don't think this is the approach we would likely go with.
cc #2821 #3058

**Comment by bergkvist** [comment]
I just ran into this issue because I wanted to build a project as wasm. The project had the following dependency:
```toml
rand_core = { version = "0.6.4", features = ["getrandom"] }
```
This gives me the following error:
```
Compiling getrandom v0.2.10
error: the wasm*-unknown-unknown targets are not supported by default, you may need to enable the "js" feature. For more information see: https://docs.rs/getrandom/#webassembly-support
```
Naturally, I then try to enable the js-feature in getrandom:
```toml
rand_core = { version = "0.6.4", features = ["getrandom", "getrandom/js"] }
```
But this gives me the error message:
```
error: failed to parse manifest at `/home/tobias/unrepoed/threshold-ecdsa-dkls-wasm/Cargo.toml`

Caused by:
  feature `getrandom/js` in dependency `rand_core` is not allowed to contain slashes
  If you want to enable features of a transitive dependency, the direct dependency needs to re-export those features from the `[features]` table.
```

Most package maintainers won't check what features exist in all their dependencies so that they can re-export the useful ones.

**Comment by bergkvist** [comment]
While the above would be an intuitive and convenient way of specifying transitive dependency features, the workaround in my case was to explicitly specify the transitive dependency:
```toml
rand_core = { version = "0.6.4", features = ["getrandom"] }
getrandom = { version = "*", features = ["js"] }
```

**Comment by epage** [comment]
FYI part of this confusion comes from a dependencies being implicitly treated as features.  We are going to be removing support for that in the 2024 edition.  See https://github.com/rust-lang/rfcs/pull/3491

**Comment by LDeakin** [comment]
> FYI part of this confusion comes from a dependencies being implicitly treated as features. We are going to be removing support for that in the 2024 edition. See [rust-lang/rfcs#3491](https://github.com/rust-lang/rfcs/pull/3491)

Now that Rust 2024 exists, is it feasible to support specifying features of indirect dependencies (as initially proposed in this issue)?

**Comment by epage** [comment]
I've not caught up on what my comment was referring to but that change was deferred and *if* we did anything in this direction, we'd need public/private dependencies stabilized for a sufficient time so we'd know which deps can be referenced in a semver-safe way.
