### ISSUE TITLE
invalid type: string "debuginfo", expected enum Strip

### ISSUE THREAD

**Issue by lzutao** [rust-lang/cargo#8450]
**Problem**

I added this to `~/.cargo/config` to try out `strip` feature:

```toml
cargo-features = ["strip"]
[profile.release]
strip = "debuginfo"
```

After that I ran `cargo clean` in a crate.

I expected to see this happen: 
* Clean successfully
* Error about not be able to add the above part in `~/.cargo/config`, only in `Cargo.toml`

Instead this happened:
```bash
% cargo clean
error: error in /home/lzutao/fork/rust/rustup/.cargo/config: could not load config key `profile.release`

Caused by:
  error in /home/lzutao/.cargo/config.toml: could not load config key `profile.release.strip`

Caused by:
  invalid type: string "debuginfo", expected enum Strip
```

Output of `cargo version`: cargo 1.46.0-nightly (fede83ccf 2020-07-02)

**Comment by ehuss** [comment]
@GabrielMajeri do you think you'd have a chance to look at this?  I *think* the issue is that Cargo is calling [visit_string](https://github.com/rust-lang/cargo/blob/fede83ccf973457de319ba6fa0e36ead454d2e20/src/cargo/util/config/de.rs#L92) instead of `visit_enum`.  I think the solution is to add an implementation of `deserialize_enum`, and remove the enum forward from [here](https://github.com/rust-lang/cargo/blob/fede83ccf973457de319ba6fa0e36ead454d2e20/src/cargo/util/config/de.rs#L202). That would then need figure out what to do based on the type.  A string would call `visit_enum(s.into_deserializer())`. And it would need to be careful to handle environment variables and such.  (I'm not certain that's the solution, but that's how I would start.)

If not, that's ok, just let me know.  Sometimes serde can be a little mind bending.

**Comment by GabrielMajeri** [comment]
@ehuss I'l look into it.
