### ISSUE TITLE
`cargo init` fails when git has a template configured

### ISSUE THREAD

**Issue by mawis** [rust-lang/cargo#8533]
**Problem**
I have a template for new git repositories configured with `git config --global init.templateDir '~/.git-template'`. Within `~/.git-template` there is the content of `/usr/share/git-core/templates` with an added file `HEAD` of the following content:

```
ref: refs/heads/main
```

The purpose of this template is to use `main` instead of `master` for the default branch after running `git init`.

Since having this template active, `cargo init` is failing to create new projects:

```
matthias:source/ $ cargo init radius-pap-decrypt  
error: Failed to create package `radius-pap-decrypt` at `/home/matthias/source/radius-pap-decrypt`

Caused by:
  failed open for writing - '/home/matthias/source/radius-pap-decrypt/.git/info/exclude' is locked: Permission denied; class=Os (2); code=Locked (-14)
```

After running the command, there is only a newly created folder `$projectname/.git/info`, no other files are generated.

*Expected outcome:* New project should have been created. Files like `Cargo.toml` should exist within the new project folder. Nor error message should have been produced.

**Steps**
1. `git config --global init.templateDir '~/.git-template'`
2. `cp -r /usr/share/git-core/templates ~/.git-template`
3. `echo "ref: refs/heads/main" > ~/.git-template/HEAD`
4. `cargo create new-project`

**Notes**

Output of `cargo version`:

```
cargo 1.45.0 (744bd1fbb 2020-06-15)
```

OS is NixOS 20.04 (i.e. Linux). `rustup` is installed as a NixOS package, `cargo` is installed using `rustup`

```
rustup 1.21.1 (1970-01-01)
```

**Comment by ehuss** [comment]
Hm, I can't seem to reproduce the issue. Perhaps there is a permissions problem for that file? You might want to check the ownership and permissions (mine is 0644).

**Comment by mawis** [comment]
Thanks. You were right. The files in the template didn't have write permission for the user.

**Comment by daveman1010221** [comment]
Re-open, please: this behavior is incorrect, and the assumptions around file writability are flawed.

Cargo currently fails during cargo init if a file like .git/hooks/commit-msg exists but is not writable. This stems from Cargo attempting to create the file with O_CREAT | O_EXCL, which fails with EACCES when the file exists and is read-only. It then surfaces a misleading error about the file being “locked.”

This behavior assumes:

- That Cargo must be able to write to .git/hooks/* — which is not true
- That existing hooks should be writable — which is a dangerous and invalid assumption

Why this is a problem:

- It breaks system-level Git configurations. I use a global init.templatedir with pre-installed hooks, some of which are compiled ELF binaries (e.g., commit-msg). These hooks are intentionally not writable for security and integrity reasons. This is standard practice.
- It violates Git's contract. Git does not require hooks to be writable or modifiable after init. Nor does it assume ownership of them beyond copying from the template directory. Cargo should not either.
- It creates a false conflict. Cargo’s logic shouldn’t attempt to create files that already exist and don’t need to be overwritten.

Minimum viable fix:

Cargo should check whether the file already exists, and if so, skip creation and move on. Attempting to O_CREAT|O_EXCL when the file is already present and correct is unnecessary and harmful.

Alternatively, handle EACCES or EEXIST as a soft failure if the file is already present — especially when Cargo has no need to modify it.
Summary:

Hooks do not need to be writable. Forbidding read-only hook binaries breaks valid, secure, and reproducible Git workflows. The current behavior is incorrect, overly aggressive, and should be fixed.

Happy to help with a patch or further clarification if needed.

For reference, here is the error I see when running 'cargo init' on a completely new folder, due to my git hooks being installed:

cargo init
    Creating binary (application) package
error: Failed to create package `env_diff_tui` at `/home/djshepard/Documents/projects/env_diff_tui/.`

Caused by:
  failed open for writing - '/home/djshepard/Documents/projects/env_diff_tui/.git/hooks/commit-msg' is locked: Permission denied; class=Os (2); code=Locked (-14)
