### ISSUE TITLE
cargo prints unrelated warnings on cargo install --git

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/cargo#8619]
**Problem**

When `cargo install`ing a gitrepo project, cargo prints warnings of the workspace in the current cwd altough the workspace is completely unrelated and not touched.

**Steps**

1. cd into the rustc repo @ 43bec40138bab10c08ac916bff2f2f81b2b70669
2. `cargo install --git https://github.com/matthiaskrgr/cargo-cache cargo-cache`
3. During install, cargo will print 
```
warning: patch for the non root package will be ignored, specify patch at the workspace root:
package:   /home/matthias/vcs/github/rust/src/tools/rls/Cargo.toml
workspace: /home/matthias/vcs/github/rust/Cargo.toml
    Updating git repository `https://github.com/matthiaskrgr/cargo-cache`
```
although the current workspace/cwd is completely unrelated to the `cargo install` command.

**Possible Solution(s)**

**Notes**

Output of `cargo version`:
```
cargo 1.47.0-nightly (ab32ee88d 2020-08-10)
release: 1.47.0
commit-hash: ab32ee88dade1b50c77347599e82ca2de3fb8a51
commit-date: 2020-08-10
```

**Comment by ehuss** [comment]
I believe this is due to [this code](https://github.com/rust-lang/cargo/blob/f03698b3f90f6f4429d38c69e296349079df2b18/src/bin/cargo/commands/install.rs#L84-L90) which uses the workspace to provide better error messages for flags like `--bin` without an argument. That should probably be restructured somehow, though I'm not sure how.  Maybe only build and pass in the workspace if `--path` is used (otherwise pass in None)?

**Comment by Rustin-Liu** [comment]
Can I working on this?

**Comment by ehuss** [comment]
@Rustin-Liu Go ahead!  Let me know if you have any questions.

**Comment by ehuss** [comment]
Oh, wait, I just noticed there's already a PR open for this.  Sorry about that!

**Comment by Rustin-Liu** [comment]
> Oh, wait, I just noticed there's already a PR open for this. Sorry about that!

Got it. Thanks!
