### ISSUE TITLE
cargo 0.47 is missing Manifest::targets_mut()

### ISSUE THREAD

**Issue by lu-zero** [rust-lang/cargo#8689]
Cargo 0.46.1 and cargo master (0.49) do expose it.

Is it possible to have it in cargo 0.47.1?

**Comment by ehuss** [comment]
We talked about this in the Cargo team meeting.  Although we don't object to publishing a patch release, none of us are willing to put the work into making that happen. Since most of this is done by the release team anyways, you will need to convince them to make a release (they can be reached on zulip I believe).  Generally the API is unstable, and so by nature it will change from release to release, so any tools using it should be prepared for that.

**Comment by Mark-Simulacrum** [comment]
I keep forgetting that versions are off-by-one here, but I don't think the release team is going to do a stable point release this cycle (it's also rather late in the cycle. I note that you have not talked about 0.48 (i.e., current beta cargo). If that doesn't have it, I would strongly recommend submitting a PR to the beta branch of Cargo now.

**Comment by lu-zero** [comment]
I fixed the problem at 0.46 times (9c8544a3dc), a 0.46.1 appeared with it in, current git seems to have it. Somehow 0.47 does not have it for reasons I'm not clear of.

**Comment by Mark-Simulacrum** [comment]
Looks like the 0.48 branch does have it (https://github.com/rust-lang/cargo/blob/rust-1.47.0/src/cargo/core/manifest.rs#L435).

**Comment by lu-zero** [comment]
If 0.48 gets released soon I guess it makes sense to skip 0.47
