### ISSUE TITLE
Cargo ingores branch in .gitmodules when fetching submodules of dependencies

### ISSUE THREAD

**Issue by turbocool3r** [rust-lang/cargo#8802]
**Problem**
Cargo ingores branch in .gitmodules when fetching git submodules of crate dependencies. The branch fetched is always master. I excepted cargo to fetch the branch I specified in .gitmodules.

**Steps**

1. `mkdir tmp; cd tmp`
2. `mkdir sub; cd sub; git init; cd ..`
3. `cargo init test-dep --lib; cd test-dep`
4. Create `.gitmodules` file and insert the following contents:
```
[submodule "sub"]
	path = sub
	url = file://<path to tmp>/sub
	fetchRecurseSubmodules = false
	branch = not-master
```
5. `cd ..`
6. `cargo init test-leaf; echo "test-dep = { git=\"file://$($(realpath test-dep)\" }" >> test-leaf/Cargo.toml; cd test-leaf`
7. `cargo update`
This should fail since there is no "not-master" branch in sub but instead this succeeds. Creating the "not-master" branch does not affect the result.

**Possible Solution(s)**
Check the branch property in .gitmodules.

**Notes**

Output of `cargo version`: cargo 1.49.0-nightly (79b397d72 2020-10-15)

```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H2
```

**Comment by Eh2406** [comment]
does this happen with https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli set? If so it is a bug in libgit2.

**Comment by turbocool3r** [comment]
Yes

> does this happen with https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli set? If so it is a bug in libgit2.

Yes

**Comment by alexcrichton** [comment]
This is a longstanding issue in Cargo and has basically always been how submodule fetching works, for better or for worse. Cargo currently fetches all branches/references (slow), rather than respecting the `.gitmodules` configuration. I think this would be pretty easy to fix, but it's unfortunately a breaking change as well and I'm not sure how many projects it will affect, so we'll need to tread carefully.

**Comment by turbocool3r** [comment]
Is it possible that this will be fixed in the near feature? Seems like it's impossible to make cargo use the right branch even if I explicitly specify a commit from that branch that is not present in master for a submodule. The only workaround I could think of is creating a fork of both the dependency and the submodule using the required branch as master which isn't exactly the best way to handle that.

**Comment by alexcrichton** [comment]
Oh hm I may be misunderstanding. I thought that Cargo's behavior today was that it fetched all branches of submodules, so the only "bad" behavior is that fetches may take longer. It sounds like you're saying though that we're not fetching a branch so the fetch is failing because the commit wasn't fetched? If so that's definitely a serious bug we should fix!

**Comment by ehuss** [comment]
I'm also a bit confused what exactly the issue here is.

AFAIK, the `branch` field in `.gitmodules` is only used when running `git submodule update`.  It doesn't indicate which branch the submodule is actually pointing to.  The submodule points to an OID which is what cargo checks out.

The following example checks out the submodule for the given branch `foo`.

```
mkdir tmp
cd tmp
mkdir sub
cd sub
git init
git checkout -b foo
touch foo
git add foo
git commit -m test
cd ..
cargo new --lib test-dep
cd test-dep
git submodule add -b foo file://$(realpath $(pwd)/../sub) sub
git add Cargo.toml src
git commit -m test
cd ..
cargo new test-leaf
cd test-leaf
echo "test-dep = {git=\"file://$(realpath $(pwd)/../test-dep)\"}" >> Cargo.toml
cargo update
```

**Comment by turbocool3r** [comment]
The problem somehow disappeared itself. Sorry for the inconvenience.
