### ISSUE TITLE
Crate names unable to have digits

### ISSUE THREAD

**Issue by InfRandomness** [rust-lang/cargo#8829]
**Describe the problem you are trying to solve**
Today, we had a project for uni, we could use any programming language to solve the problem and I wanted to use Rust as the language to solve the problem, unfortunately, in the specifications, we were told we needed the compiled binary that needed to be named "101Pong". So I tried creating a crate with that name, and cargo didn't let me do it.

**Describe the solution you'd like**
I'd like to see an option that can let one force the name of the crate even tho it is not authorized to have a crate with digits in front of the name, (I will not upload that crate to anywhere except a private GitHub repository), this would be great so that person doesn't have to use an external tool (like make/Makefile) to invoke the compilation process and then rename the binary from an authorized name to a non-authorized name

**Notes**

**Comment by ehuss** [comment]
You can change the name of the binary in `Cargo.toml` by setting the `name` field:

```toml
[[bin]]
name = "101Pong"
```

The associated filename would default to `src/bin/101Pong.rs` or you can explicitly set the filename like `path = "src/main.rs"`.

I think it is unlikely we would change it to allow *package names* to start with numbers due to the problems that could cause, but I think it would be good to add this tip to the `cargo new` error message.

You can learn more about Cargo targets and default filenames at https://doc.rust-lang.org/cargo/reference/cargo-targets.html.

**Comment by InfRandomness** [comment]
Okay, thanks for the tip, I wanted to be able to name my directory and crate the same name the exercise was but I guess I won't be able to

**Comment by joao-conde** [comment]
@ehuss is this supposed to be an open issue? or is the OP request not meant to be possible at all?

**Comment by ehuss** [comment]
@joao-conde This issue is open to track updating the error message.  I have posted #9098 to close this.
