### ISSUE TITLE
cargo test suite fails if default branch is not master

### ISSUE THREAD

**Issue by bk2204** [rust-lang/cargo#8863]
**Problem**
Running `cargo test` in the cargo repository fails many tests if the user has set the default branch to something other than `master`.

**Steps**

1. git config --global init.defaultBranch dev
2. cargo test
3. Notice failures

**Possible Solution(s)**
When using Git in a test suite, it's necessary to set `HOME` to a controlled location and to also set `GIT_CONFIG_NOSYSTEM` to avoid reading the system configuration file; otherwise, the global or system configuration files can break tests.  Cargo probably needs to set these values during setup in the test suite; this is probably not the only configuration option that will have the effect of breaking tests.

**Notes**

Output of `cargo version`:

```
cargo 1.47.0 (f3c7e066a 2020-08-28)
```
(Note that this is not the version being tested, about which this report is being made.)

Debian GNU Linux amd64/sid, rustc 1.47.0, cargo repository revision 2af662e22177a839763ac8fb70d245a680b15214.

**Comment by ehuss** [comment]
Thanks for the report!  The tests run in a sandbox with a custom HOME, but I believe the issue is that the index created for each test is built outside of the sandbox.  The git repo is created around [here](https://github.com/rust-lang/cargo/blob/2af662e22177a839763ac8fb70d245a680b15214/crates/cargo-test-support/src/git.rs#L125-L130).  It definitely would be good to have the tests ignore outside settings, though I'm not sure the easiest way to do that.  #7944 recently added a special-cased fix for the `cargo new` tests, but a more general solution would be nice!  It looks like libgit2's testsuite manually calls [`cl_sandbox_set_search_path_defaults`](https://github.com/libgit2/libgit2/blob/2a51679005285e4e5f8642dd86dc35b46de772c1/tests/clar_libgit2.c#L584-L603) to control the search paths.
