### ISSUE TITLE
cargo test with arguments doesn't work as expected, causing tests failed (with clap crate)

### ISSUE THREAD

**Issue by up9cloud** [rust-lang/cargo#8916]
**Problem**

The arguments for cargo test are actually not belong to the binary, but they are passed to it.
It causes unexpected behavior.

See also: https://github.com/clap-rs/clap/discussions/2187

**Steps**

```console
$ cat Cargo.toml 
[package]
name = "a"
version = "0.0.1"
edition = "2018"
[dependencies]
clap = "2.33"
```
```console
$ cat src/main.rs 
fn test_a() {
    let _matches = clap::App::new("a").get_matches();
    assert!(true);
}
```
```console
$ cargo test -- --nocapture
    Finished test [unoptimized + debuginfo] target(s) in 0.12s
     Running target/debug/deps/a-3805593461b4c059

running 1 test
error: Found argument '--nocapture' which wasn't expected, or isn't valid in this context

USAGE:
    a-3805593461b4c059

For more information try --help
error: test failed, to rerun pass '--bin a'
```

**Possible Solution(s)**
#### Not obligatory, but suggest a fix/reason for the bug, -->
Consume the `cargo test` specific arguments and not pass them to the binary.
#### or ideas how to implement the addition or change -->
Redesign the arguments for different programs:

Examples:
1. Use `--` to seperate: `cargo test test_a --nocapture -- --version --debug`,

- The part before `--` is for the cargo-test (`test_a --nocapture`)
- The part after `--` is for the binary (`--version --debug`)

2. Something like rsync -e: `cargo test test_a --nocapture --args="--version --debug"`

- All are for cargo-test (`test_a --nocapture --args="--for-binary"`)
- The value of --args is for the binary (`--version --debug`)

**Notes**

Output of `cargo version`:

**Comment by ehuss** [comment]
Sorry, I'm a bit confused what you are trying to do here.  It is expected behavior that arguments are passed to the test executable.  If you want to write tests using clap, I would suggest not parsing the process arguments directly, but instead passing them in manually with something like [`get_matches_from`](https://docs.rs/clap/2.33.3/clap/struct.App.html#method.get_matches_from).  You can probably grab the arguments from the process using `env::args_os` and skipping until a `--` separator, and then pass in the result.

**Comment by up9cloud** [comment]
@ehuss Any suggestion for those questions?

1. How do I test my program with the args not allowed by cargo test? for example:

```console
cargo test -- --config=local.json
```

2. How do I test my program having same names of options from cargo test?

```console
cargo test -- --format=template.json
```

3. How do I setup clap that I can ignore all possibilities that cargo test brings into my program? 

```console
cargo test -- -h
...
```

**Comment by ehuss** [comment]
It's a very unusual way to test arguments on the command-line, since they are global every test will see the same arguments, and requires manually passing in the arguments.  Tests are usually self-contained, and provide the values they need within the test.  It doesn't look like there is a way to make the libtest harness ignore the arguments.  Here are several options for you.

### No harness
Disable the harness in `Cargo.toml`:
```toml
[[test]]
name = "foo"
harness = false
```
And then in `tests/foo.rs`:
```rust
// Run with: cargo test --test foo -- --config=abc
fn main() {
    let matches = clap::App::new("a")
        .arg_from_usage("-c --config=<FILE> 'Sets a configuration file to use'")
        .get_matches();    
    println!("{:?}", matches.value_of("config"));
}
```

### Self-contained values
Usually, in a test, you don't pass arguments in on the command-line, but instead embed them in the test like this:

```rust
#[test]
fn foo() {
    let args = ["a", "--config", "abc"];
    let matches = clap::App::new("a")
        .arg_from_usage("-c --config=<FILE> 'Sets a configuration file to use'")
        .get_matches_from(&args);    
    assert_eq!(matches.value_of("config"), Some("abc"));
}
```

### Executing a binary
Write an integration test that launches your binary (using `std::process::Command`), and passes the arguments to the process, and verify its behavior.  That's what Cargo itself does (see https://doc.crates.io/contrib/tests/writing.html#basic-test-structure).

Considering this is unrelated to Cargo, please follow up with any other questions on how to write tests or use clap to one of the user forums (such as [urlo](https://doc.crates.io/contrib/tests/writing.html#basic-test-structure)).

**Comment by up9cloud** [comment]
@ehuss Thanks for the solutions. Those are really helpful!

I'm gonna to close this and move to forums.
