### ISSUE TITLE
maturin develop

### ISSUE THREAD

**Issue by JeanSyFr** [rust-lang/cargo#8972]
Hello I am trying to follow exactly the same steps on this website https://github.com/eclipse-zenoh/zenoh-python in order to get started with zenoh

every thing work till i get this message when I execute this command 
```

> maturin develop
An I get the following message
(zenoh) PS C:\zenoh\cargo> maturin develop
💥 maturin failed
  Caused by: Cargo metadata failed. Do you have cargo in your PATH?
  Caused by: Error during execution of `cargo metadata`:  Downloading crates ...
error: failed to download `wasi v0.9.0+wasi-snapshot-preview1`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `C:\Users\jeana\.cargo\registry\src\github.com-1ecc6299db9ec823\wasi-0.9.0+wasi-snapshot-preview1\Cargo.toml`

Caused by:
  no targets specified in the manifest
  either src/lib.rs, src/main.rs, a [lib] section, or [[bin]] section must be present
```

I have checked basics things like path, the existance of mentionned files ...etc.

I would appriciate if someone can help me please !

Thank you in advance.

**Comment by Eh2406** [comment]
What do you get when you run `cargo -V`? I get `cargo 1.48.0`. I think that error may be related to an older Cargo trying to read a newer manifest. On the other hand it does have a [`src/lib.rs`](https://docs.rs/crate/wasi/0.9.0+wasi-snapshot-preview1/source/src/lib.rs), so that does not fit. Maybe it did not unpack correctly? What happens if delete `wasi-0.9.0+wasi-snapshot-preview1` folder in `C:\Users\jeana\.cargo\registry\src\github.com-1ecc6299db9ec823\`?

**Comment by ehuss** [comment]
Ping @JeanSyFr were you able to figure out the issue?  It sounds like the cache may have gotten corrupted somehow, but if you're able to clear the cache and reproduce it, please let us know.

**Comment by epage** [comment]
Without any updates on this in over a year, I'm going to go ahead and close this.  If more information becomes available, let us know!
