### ISSUE TITLE
`cargo fix --edition` needs fixing for Rust  2021

### ISSUE THREAD

**Issue by m-ou-se** [rust-lang/cargo#9047]
The job of `cargo fix` is getting more complicated, as it will need to handle fixes between three editions instead of two.

See https://github.com/rust-lang/cargo/pull/8922#issuecomment-754711396

- [ ] Figure out what to do.
- [ ] Implement that.

(To be updated later. Just filing this issue to make sure we won't lose track of this.)

**Comment by alexcrichton** [comment]
From the PR linked, I think there's two questions we'll want to answer:

* What should `cargo fix --edition` do if you're on the "latest edition". The latest edition may be 2018 as  2021 is in development, and it may be 2021 once it's stabilized. Currently `cargo fix --edition` if you're already in the 2018 edition prints an error saying you should switch to 2015.

* What should `cargo fix --edition` do if you're in the 2015 edition? Should it attempt to jump directly to the 2021 edition? Or should it do everything necessary to switch to 2018, and then recommend going to 2021?

**Comment by alexcrichton** [comment]
Ok we discussed this in the cargo meeting today and our conclusions were basically that `cargo fix --edition` would *always* move you into the next edition, regardless of everything else. This means if you execute `cargo fix --edition` and you're in 2015, it always tries to move you to 2018. If you're in 2018 and Cargo has support for 2021, then it will try to move you to 2021 (even if support is gated and/or unimplemented in rustc at the time). 

 This also solves the question about jumping multiple editions because we'll always be moving only one edition at a time. So I think the fix in Cargo will basically be to implement the "what is the next edition" function to return 2021 when the current edition is 2018, and then we'd fix up tests to account for that new behavior.

We also figured that the current error of "you're in the latest edition you can't fix further" can probably get turned into a warning. Additionally we may wish to review the output of the command to ensure it's clear what edition is being migrated from and which edition is being migrated to.

**Comment by ehuss** [comment]
Another thing we discussed is to have `cargo fix --edition -Zunstable-options` work on 2018 to run the 2021 migration during the time that 2021 is still unstable.  That should help to be able to to test it which IIUC is not currently possible.
