### ISSUE TITLE
Stack overflow on circular dependency

### ISSUE THREAD

**Issue by thibault-martinez** [rust-lang/cargo#9073]
**Problem**

`cargo check --release` crashes with stack overflow.
```
thread 'main' has overflowed its stack
fatal runtime error: stack overflow
```

**Steps**

1. `git clone https://github.com/thibault-martinez/bee.git`
2. `cd bee/`
3. `git checkout cargo-stack-overflow`
4. `cargo check --release`

**Notes**

`cargo 1.49.0 (d00d64df9 2020-12-05)`

There is a circular dependency `bee-tangle`->`bee-snapshot`->`bee-ledger`->`bee-tangle`.

**Comment by alexcrichton** [comment]
Thanks for the report! This is a bug in the implementation we have that checks for cycles from the resolver -- https://github.com/rust-lang/cargo/blob/a73e5b7d567c3036b296fc6b33ed52c5edcd882e/src/cargo/core/resolver/mod.rs#L1003-L1064 -- and has been there for a very long time. Turns out your project is structured *just* right (and named just right b/c we sort things) to trigger this!

I'll take a look at how we can fix our cycle detection.
