### ISSUE TITLE
Should warn on optional dep not used in any feature

### ISSUE THREAD

**Issue by gdesmott** [rust-lang/cargo#9088]
Cargo could raise a warning when user defines an optional dependency which is not part of any feature.

I've been confused for a while trying to figure out why building my single feature project with `--all-features` was working while building it with `--features=my-feature` was not. Turned out I forgot to include one optional dep with the feature. Such warning would have prevent me from doing such stupid mistake. :)

**Comment by jplatte** [comment]
I think it was an intentional design choice to have optional crates exposed as features of their own. But maybe once the two namespaces are separated, that could be changed such that an optional dependency can *only* be activated through an explicitly declared feature.

In the current situation however, if you want a feature `foo` that (only) activates the dependency `foo`, there's no good way to express that other than making the dependency optional *without* creating an explicit feature. (you can rename the dependency and create a feature with the original dependency name that activates the dependency, but that's pretty ugly)

**Comment by epage** [comment]
We are removing implicit features in Edition 2024 and warning the user that the dependency is unused.

Closing in favor of the tracking issue: #12826
