### ISSUE TITLE
Cargo set environment variables provided by build scripts randomly when running tests

### ISSUE THREAD

**Issue by hyd-dev** [rust-lang/cargo#9100]
Discovered in https://github.com/rust-lang/miri/issues/1661#issuecomment-765968857 by @RalfJung.

**Steps**
1. Setup a workspace like this:
```bash
cargo new --lib cargo-bug --vcs none
cd cargo-bug/
echo 'proc-macro-crate = { path = "proc-macro-crate" }
[lib]
doctest = false
[workspace]' >> Cargo.toml
cargo new --lib proc-macro-crate --vcs none
cd proc-macro-crate/
echo '[lib]
proc-macro = true
[dev-dependencies]
cargo-bug = { path = ".." }' >> Cargo.toml
cd ..
echo 'fn main() { println!("cargo:rustc-env=CRATE_TARGET={}", std::env::var("TARGET").unwrap()) }' > build.rs
echo '#[test]
fn target() {
    assert_eq!(env!("CRATE_TARGET"), "i686-unknown-linux-musl");
    assert_eq!(std::env::var_os("CRATE_TARGET"), None);
}' > src/lib.rs
```
2. Run `cargo clean && cargo test --workspace --target i686-unknown-linux-musl -vv` (with `--jobs 1` optionally).
3. The test always fails with (the random) one of the following messages (on `x86_64-unknown-linux-gnu`):
```
thread 'target' panicked at 'assertion failed: `(left == right)`
  left: `Some("i686-unknown-linux-musl")`,
 right: `None`', src/lib.rs:4:5
```
```
thread 'target' panicked at 'assertion failed: `(left == right)`
  left: `Some("x86_64-unknown-linux-gnu")`,
 right: `None`', src/lib.rs:4:5
```

**Version info**
```
cargo 1.51.0-nightly (783bc43c6 2021-01-20)
release: 1.51.0
commit-hash: 783bc43c660bf39c1e562c8c429b32078ad3099b
commit-date: 2021-01-20
```

cc @ehuss

**Comment by ehuss** [comment]
Hm, I take back what I said.  It looks like it is randomly picking environment variables.  The issue is that [these lines](https://github.com/rust-lang/cargo/blob/c3abcfe8a75901c7c701557a728941e8fb19399e/src/cargo/core/compiler/compilation.rs#L261-L265) do not differentiate based on the correct parameters.  I'll try to take a look at that soonish.

**Comment by RalfJung** [comment]
> As for the environment variables being set during cargo test and cargo run, that's a surprise to me. It looks like it has behaved that way ever since it was introduced in #3929.

The thing is (as you noted in your last comment) -- cargo is inconsistent wrt. *which* env vars it sets during `test`+`run`; sometimes it's the host build script, sometimes the target build script.

> The issue is that these lines do not differentiate based on the correct parameters.

Yeah, looks like [all build script env vars are put into that `HashMap`](https://github.com/rust-lang/cargo/blob/50cc40bc895414bbe21c46a3626c385d2440d6e9/src/cargo/core/compiler/context/mod.rs#L260) and then it's a game of chance which one "wins" during `test`/`run?

**Comment by alexcrichton** [comment]
Hm that's probably a bug that it's set at runtime for the test in addition to compile-time for the test executable. But yeah I agree with @ehuss's assessment that we probably can't back this out now and the bug is around those lines since the targete-process-execution is much less precise than the build itself.
