### ISSUE TITLE
Git Dependencies Won't Work in Cargo.toml on Arch Termux

### ISSUE THREAD

**Issue by billyb2** [rust-lang/cargo#9150]
**Problem**
Whenever I have a git repository as a dependency in my Rust program. I get this error:
https://pastebin.com/iq6Cae5f

**Steps**
1. Create a new cargo project
2. Add `rusttorrent = {git = "https://github.com/sebastiencs/rustorrent.git"}` to Cargo.toml dependencies
3. Run cargo build

**Notes**

Output of `cargo version`:

cargo 1.49.0 (d00d64df9 2020-12-05)

I'm currently running Rust on an Arch Linux install in a proot container in Termux (confusing, I know, it's just to have a full arch install on the go with me). Almost eerything else in Rust seems to work perfectly fine, I've been working on a Rust based TCP server with no issues so far.

Running the latest stable version of Rust
 stable-aarch64-unknown-linux-gnu - rustc 1.49.0 (e1884a8e3 2020-12-29)

**Comment by ehuss** [comment]
I have not seen that error before.  Have you tried deleting the git cache?  It should be located in the cargo home directory, usually `~/.cargo/git/`.  I'm wondering if something somehow left behind a file that is unexpected.  Looking at the libgit2 source code, it seems to use locks with the file extension `.lock`, but I don't see it creating ones with numbers like `0001` at the end.

If you delete the cache and it continues to happen, maybe consider using [`net.git-fetch-with-cli`](https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli) to use the `git` CLI to fetch instead of cargo's built-in version.

**Comment by Eh2406** [comment]
I am going to close for now. If you can make a MCVE please open a new Issue!
