### ISSUE TITLE
Error: linking with `cc` failed: exit code: 1

### ISSUE THREAD

**Issue by tvallotton** [rust-lang/cargo#9251]
**Problem**

I have a project that doesn't compile on Apple Silicon. I don't know if the problem persists on other hardware. I asked [a question](https://stackoverflow.com/questions/66556519/cannot-compile-rust-project-linking-with-cc-failed) on stack overflow and at least one user could reproduce the issue. If you clone my repository https://github.com/tvallotton/cryptomkt-rs and try to compile it it will work fine. However, I cannot get it to build when I use it as a dependency. Strangely, the original fork builds just fine (https://github.com/gallegogt/cryptomkt-rs). The only differences between the two is that I also used tokio and async_trait.

**Steps**
To reproduce the bug add the following to the Cargo.toml file of a new cargo project:
```toml
[dependencies.cryptomkt]
version = "0.3.0"
git = "https://github.com/tvallotton/cryptomkt-rs"
```

**Possible Solution(s)**
 Initially, I believed it was due to missing xcode tools. But updating and reinstalling xcode didn't work. A user on stackoverflow suggested to post an issue here. 

**Notes**

Output of `cargo version`:
cargo 1.50.0 (f04e7fab7 2021-02-04)
cargo 1.52.0-nightly (970bc67c3 2021-03-07)

I am using macOS Big Sur version 11.0.1 with an M1 chip

**Comment by ehuss** [comment]
I don't think this is anything specific about M1, it's just the behavior on macOS in general.

The crux of the issue is that both `cryptomkt` and `hyper` are defined as a `dylib`. In general, I recommend to not do that. Dylibs can be difficult, and are not well supported.

In this case, I think it is a complex case of a diamond dependency interacting with generics.  For example, `hyper` and `reqwest` both use and re-export types from `http`.  `cryptomkt` uses types from `reqwest` that involve types from `http`.

The reason it works in the checkout vs the dependency is that Cargo does not issue the `prefer-dynamic` for dylibs in a workspace, but it does for non-workspace members.  (Incidentally, while looking at that, I discovered a bug 😄 )

**Comment by tvallotton** [comment]
You were right, I changed ``crate-type`` to ``staticlib`` and my problems were gone. I didn't know about this concept of static and dynamic libraries. I'll look it up to avoid trouble in the future. As I'm not sure if I should close the issue, feel free to close it yourself. I cannot thank you enough.
