### ISSUE TITLE
problem of git proxy

### ISSUE THREAD

**Issue by surechen** [rust-lang/cargo#9284]
**Problem**
I use github through a proxy :
http.proxy=socks5://127.0.0.1:1080
https.proxy=socks5://127.0.0.1:1080

When I use cargo-audit by command "cargo audit", I get error :

Fetching advisory database from https://github.com/RustSec/advisory-db.git
error: couldn't fetch advisory database: git operation failed: unknown http scheme 'socks5'; class=Http (34)

**Steps**

1. cargo audit.

Output of `cargo version`:
1.50.0

**Comment by ehuss** [comment]
Hi!  `cargo audit` is a third party plugin.  Maybe try moving the issue to their repository? I think it is https://github.com/rustsec/cargo-audit

**Comment by surechen** [comment]
> Hi! `cargo audit` is a third party plugin. Maybe try moving the issue to their repository? I think it is https://github.com/rustsec/cargo-audit

Hi, thanks for answering. I have ased in cargo-audit, this is the answer from commiter :
"
It's possible the git client in its current form doesn't have SOCKS5 support.

It's repurposed from Cargo, so it'd be good to look if there are similar Cargo issues for this.
"
https://github.com/RustSec/cargo-audit/issues/336#issuecomment-801598288

**Comment by ehuss** [comment]
I'm not familiar with how `cargo audit` uses cargo.  Cargo's git client supports SOCKS proxies.  A bug was fixed in 1.51 where it was not detecting the proxy configuration in `.gitconfig` properly.  Setting the proxy via cargo's config, or using the HTTP_PROXY or HTTPS_PROXY environment variable should trigger it to use the proxy, or having `cargo audit` use 1.51.  More information about setting Cargo's proxy support is at https://doc.rust-lang.org/nightly/cargo/reference/config.html#httpproxy.

**Comment by ehuss** [comment]
Without more information, I'm going to close this issue.  Hope you were able to work through the issue, and perhaps indeed it was the config issue fixed in 1.51.  If you have more issues, I suggest following up with the cargo-audit tracker or maybe try one of the [user forums](https://users.rust-lang.org/).
