### ISSUE TITLE
Clarify docs for new --features CLI?

### ISSUE THREAD

**Issue by matklad** [rust-lang/cargo#9305]
Hey, I am reading the docs at https://doc.rust-lang.org/nightly/cargo/reference/features.html#command-line-feature-options, and I am feeling confused about two things. The docs say

> the package-name/feature-name syntax can be used to specify features for specific workspace members.

But then, [in the next section](https://doc.rust-lang.org/nightly/cargo/reference/features.html#resolver-version-2-command-line-flags), the example uses dashes rather that `/`:

`cargo build -p foo -p bar --features foo-feat,bar-feat`

Additionally, I've noticed that, in the workspace root with a virtual manifest, the name of the package can be omited and `--features f` activates `f` for all packages in the workspace that have the said feature.

**Comment by ehuss** [comment]
Hm, yea, I can see how that is confusing.  The intent was to indicate that it allows "bare" features without the slash. I wanted to emphasize that you can specify features that only exist in at least one package.  It's intended as a convenience so it doesn't require the more verbose form.

I'm not sure how to make it clearer without describing a sample workspace layout.  Also, I was reluctant to go into details in the "Command-line feature options" section because the behavior in different scenarios will depend on whether it is using resolver 1 or 2.  Perhaps it should describe the 2 behavior, and then have a small callout about the limitations of version 1?

If you want to open a PR with suggestions, it would be appreciated!
