### ISSUE TITLE
Cargo run should use the cargo config specified for the package

### ISSUE THREAD

**Issue by Andy-Python-Programmer** [rust-lang/cargo#9354]
Currently if we run:

```sh
$ cargo run --package example_kernel
```

And we have example_kernel as a workspace member in cargo.toml and there is a cargo config file in `example_kernel/.cargo/config.toml` with the following:
```toml
[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64-aero_os.json"

[profile.dev]
panic = "abort" # Disable stack unwinding on panic

[profile.release]
panic = "abort" # Disable stack unwinding on panic
```
It will use the standard configs not the one defined in `example_kernel/.cargo/`

I would like cargo to use that config file not the standard configs as we are in a package. I cannot define a config file in the root as I only want for example the kernel package to be no std and have alloc while the bootloader without alloc and the builder to **include** std.

**Comment by ehuss** [comment]
Thanks for the report!  Yea, this can be confusing, since cargo always uses the current working directory to find configuration files.  This is mostly the same as issue #2930, so I'm going to close in favor of that.  Unfortunately it is not so simple to change the behavior since it could break existing workflows, so the path forward is not exactly clear.
