### ISSUE TITLE
Building tests for a binary crate in a virtual workspace doesn't work.

### ISSUE THREAD

**Issue by JoshOrndorff** [rust-lang/cargo#9361]
I'm working on this repository: https://github.com/purestake/moonbeam

It contains several crates. Some of them have tests, and some don't (yet). Most of our crates are libraries, but one (`moonbeam` which lives in the `node` directory) is a binary application. The `moonbeam` binary depends directly or indirectly on the library crates in the repo as well as several external dependencies. The root `Cargo.toml` is a virtal workspace.

**Problem**

The issue is with building the tests in the binary crate `moonbeam`. I expect `cargo test` to build all tests in the virtual workspace including `moonbeam` and all the libraries. I expect `cargo test -p moonbeam` to build just the tests in the `moonbeam` crate. However, when I run `cargo test -p moonbeam` I get a build error that I do not get when I just run `cargo test`

**Steps**

I've created a CI job to demonstrate this clearly and you can see it's output here https://github.com/PureStake/moonbeam/runs/2343542484 Notice I ran several cargo commands that build correctly before the `cargo test -p moonbeam` that fails.

You can also reproduce yourself.
1. git checkout https://github.com/purestake/moonbeam
2. cd moonbeam
3. cargo test (this will take a while, but the build will ultimately succeed)
4. cargo test -p moonbeam to see the failure

**Comment by ehuss** [comment]
This is caused by using different features.  The features selected in a workspace depend on which packages are being built.  In this particular case, `rand 0.5.6` is being built with the `i128_support` and `rand_core 0.4.2` is built with `alloc` and `std`. Rand doesn't seem to like that combination.

You can inspect the features with `cargo tree`.  In the root of the workspace:

```
cargo tree -p rand:0.5.6 -f '{p} {f}'
rand v0.5.6 alloc,cloudabi,fuchsia-cprng,i128_support,libc,std,winapi
├── libc v0.2.91 align,default,extra_traits,std
└── rand_core v0.3.1 alloc,std
    └── rand_core v0.4.2 alloc,std
```

and then in the `node` directory:

```
cargo tree -p rand:0.5.6 -f '{p} {f}'
rand v0.5.6 i128_support
└── rand_core v0.3.1
    └── rand_core v0.4.2 alloc,std
```

If you want to see what is enabling the features, you can use the `-i` flag with `-e features`.  For example:

`cargo tree -i rand:0.5.6 -f '{p} {f}' -e features` shows how the features are set on rand in the workspace.
`cargo tree -i rand:0.5.6 -f '{p} {f}' -e features -p moonbeam` shows how the features are set on rand when building just moonbeam.

**Comment by JoshOrndorff** [comment]
Thank you very much for the help and detailed explanation. It seems this is not a cargo bug so much as a learning opportunity for me, so I'll close this for now. (Might be back with more questions though).

cc @girazoki
