### ISSUE TITLE
About the cargo versions installed by `rustup update` and the ones released on this repo.

### ISSUE THREAD

**Issue by hongyi-zhao** [rust-lang/cargo#9593]
On Ubuntu 20.04, I installed Rust according to the [guidance](https://doc.rust-lang.org/book/ch01-01-installation.html) as shown below:
```
$ curl -x socks5://127.0.0.1:18888 --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
$ rustup update
$ cargo --version 
cargo 1.52.0 (69767412a 2021-04-21)
```
As you can see, I updated to the cargo version `1.52.0`. But the latest released cargo version in this repo is [0.53.0](https://github.com/rust-lang/cargo/releases/tag/0.53.0). I'm very confused on this issue.

Any hints will be highly appreciated.

Regards,
HY

**Comment by ehuss** [comment]
Cargo is released in two ways, one as a binary which is part of the Rust release (which is installed by Rustup).  That follows 1.xx versioning.  The other way is as a library published on crates.io.  Since the library is permanently unstable, it follows a 0.xx versioning scheme.  Due to the history of how Cargo was originally developed, the minor version just happens to be one off (partially because Rust had a 1.0 release whereas cargo started with 0.1, and if you bump the minor version of both, cargo-the-library's minor version will always be one ahead).

**Comment by ehuss** [comment]
Closing, hopefully that answered your question.
