### ISSUE TITLE
cargo-package ignores sub-directories containing Cargo.toml

### ISSUE THREAD

**Issue by tmplt** [rust-lang/cargo#9643]
**Problem**

I am trying to publish a crate which builds adhoc crates during run-time. For this reason, I `include_dir::include_dir!("assets/libadhoc")`. This `assets/libadhoc/` contains a `Cargo.toml` which is then written to disk and modified during run-time. However, on a `cargo publish` this directory is not copied to `target/package/`, even with `package.include = ["*"]` in the parent `Cargo.toml`.

**Steps**

```console
$ cargo init --bin project && cd project
$ mkdir assets
$ touch assets/Cargo.toml
$ cargo package --list
Cargo.toml
src/main.rs
```

**Possible Solution(s)**

I figure `**/Cargo.toml` are ignored for a reason, but this is not documented in [cargo-package(1)](https://doc.rust-lang.org/cargo/commands/cargo-package.html). I suggest an amend.

Further, I cannot find a way to override this behavior. I suggest making that possible. Alternatively/additionally, I suggest adding an environmental variable that points to the generated `target/package/project-0.1.0/` so that I can copy the files myself.

For now, I'll rename the file to `not-Cargo.toml` and rename it during run-time so that I can publish my crate.

**Notes**

Output of `cargo version`: cargo 1.52.0 (69767412a 2021-04-21)

**Comment by gdesmott** [comment]
I'm having [a similar problem](https://github.com/gdesmott/system-deps/issues/45) with [system-deps](https://crates.io/crates/system-deps). My tests use a bunch of sub-directories containing a `Cargo.toml` which are not included in the package.

I think it's because cargo package [does not recurse in dir containing a Cargo.toml](https://github.com/rust-lang/cargo/blob/master/src/cargo/sources/path.rs#L403). While it makes sense for the default, it should be overridable using the [package.include field](https://doc.rust-lang.org/cargo/reference/manifest.html#the-exclude-and-include-fields) but it's not at the moment.

**Comment by weihanglo** [comment]
I'll close this in favor of <https://github.com/rust-lang/cargo/issues/8597>, as this seems a duplicate. Thank you for the input and MRE!
