### ISSUE TITLE
Download links for pre-built binaries

### ISSUE THREAD

**Issue by nmattia** [rust-lang/cargo#9733]
**Describe the problem you are trying to solve**

I'm trying to find download links for `cargo` and `rustc`. Now everything seems to be handled by `rustup` but I do need precompiled binaries to be used in an airgapped system. I know that rustup is downloading them from somewhere, but I can't find where!

A download page would be much appreciated.

**Comment by ehuss** [comment]
Standalone installers are listed here: https://forge.rust-lang.org/infra/other-installation-methods.html#standalone-installers

Otherwise, getting the files downloaded by `rustup` is not a simple process. They are inferred from a manifest system (such as https://static.rust-lang.org/dist/channel-rust-stable.toml).  I don't believe that interface or system is documented, as it is an internal part of rustup.  However, if you just need a one-off, it's not too hard to see how the links inside are organized.

An alternative is to use rustup to download outside of your airgap, and then to compress the `.rustup` and `.cargo` directories and transfer those over.

**Comment by nmattia** [comment]
Thanks, that's great! I landed on that page during my research but somehow didn't read that section. 👌

**Comment by nmattia** [comment]
Actually, is there any documentation on how to use those installers? I'm looking at the Darwin ones, and while I can extract with `pkgutil` and run the executables, I'm not sure what each executable expects (i.e. I guess `cargo` expects `rustc` in its PATH, and `rustc` my expect `stdlib`s and `target`s in some specific directory, etc).

**Comment by ehuss** [comment]
I don't think there is any specific documentation other than one comes in the installer.  I think in general, you only need to set PATH to the location of the binary if you don't already have it (I think it defaults to `/usr/local/bin`).

**Comment by nmattia** [comment]
Thanks! To clarify, this mostly worked but I also had to install the targets:

``` shell
    pkgutil --expand rust.pkg $install_dir
    cp -r $install_dir/rust-std.pkg/Scripts/rust-std-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib $install_dir/rustc.pkg/Scripts/rustc/lib/rustlib/x86_64-apple-darwin/
```

**Comment by nmattia** [comment]
Ok, I do have one more issue. I'm trying to install the `wasm32-unknown-unknown` target, and I assumed this would be as easy as the `x86_64-apple-darwin` one. However, after downloading https://static.rust-lang.org/dist/2021-07-29/rust-std-1.54.0-wasm32-unknown-unknown.tar.gz and running

``` shell
cp -r $wasm32/rust-std-wasm32-unknown-unknown/lib/rustlib/wasm32-unknown-unknown/lib $install_dir/rustc.pkg/Scripts/rustc/lib/rustlib/wasm32-unknown-unknown/
```

I'm still getting 

```shell
error[E0463]: can't find crate for `core`
  |
  = note: the `wasm32-unknown-unknown` target may not be installed
```

with `cargo build --target wasm32-unknown-unknown`.

Any pointers?

**Comment by nmattia** [comment]
Figured it out:

``` shell
$ cp -r $wasm32/rust-std-wasm32-unknown-unknown/lib/rustlib/wasm32-unknown-unknown $install_dir/rustc.pkg/Scripts/rustc/lib/rustlib/
```

Thanks!
