### ISSUE TITLE
cargo update does not pull in updated dependencies

### ISSUE THREAD

**Issue by lopopolo** [rust-lang/cargo#9756]
**Problem**

**Steps**

1. clone `git@github.com:artichoke/artichoke`
2. Run `cargo outdated` and observed there are dependency updates available

    ```
    $ cargo outdated
    Name                            Project  Compat  Latest  Kind    Platform
    ----                            -------  ------  ------  ----    --------
    aho-corasick->memchr            2.3.4    ---     2.4.0   Normal  ---
    artichoke-backend->bstr         0.2.15   ---     0.2.16  Normal  ---
    artichoke-backend->regex        1.4.6    ---     1.5.4   Normal  ---
    bindgen->regex                  1.4.6    ---     1.5.4   Normal  ---
    bstr->memchr                    2.3.4    ---     2.4.0   Normal  ---
    cexpr->nom                      6.2.1    ---     6.1.2   Normal  ---
    nom->memchr                     2.3.4    ---     2.4.0   Normal  ---
    parse-zoneinfo->regex           1.4.6    ---     1.5.4   Normal  ---
    regex->aho-corasick             0.7.15   ---     0.7.18  Normal  ---
    regex->memchr                   2.3.4    ---     2.4.0   Normal  ---
    rustyline->memchr               2.3.4    ---     2.4.0   Normal  ---
    scolapasta-string-escape->bstr  0.2.15   ---     0.2.16  Normal  ---
    spinoso-env->bstr               0.2.15   ---     0.2.16  Normal  ---
    spinoso-regexp->bstr            0.2.15   ---     0.2.16  Normal  ---
    spinoso-regexp->regex           1.4.6    ---     1.5.4   Normal  ---
    spinoso-symbol->bstr            0.2.15   ---     0.2.16  Normal  ---
    ```
3. Run `cargo update` and observe the lockfile is not changed.

**Possible Solution(s)**

**Notes**

Output of `cargo version`:

```
cargo 1.54.0 (5ae8d74b3 2021-06-22)
```

**Comment by ehuss** [comment]
I believe this is because `nom` has a [tight requirement](https://github.com/Geal/nom/blob/6.2.1/Cargo.toml#L57-L59) on `memchr`.  Other packages, like `regex 1.5.4` has a requirement of [at least 2.4](https://github.com/rust-lang/regex/blob/1.5.4/Cargo.toml#L112-L115).  `nom` is blocking the update of the other packages.  I don't know why nom would set an upper bound like that. It's generally discouraged to do that since it causes problems like these.

I also noticed that some of the `spinoso` packages have some strange requirements, like `"1, >= 1.4.3"` for regex in `"spinoso-regexp"`.  That can be simplified to be just "1.4.3".  I don't think those affect this issue, though.

**Comment by lopopolo** [comment]
Ahh thanks for that. It's unfortunate that `nom` being used in a proc-macro blocks updates of deps used in real code.

The spinoso requirements are specified that way so @dependabot doesn't bump the constraints in `Cargo.toml` on minor version bumps while still maintaining the proper minimum version that the crate requires (e.g. so that CI with a minimal-versions lockfile passes).
