### ISSUE TITLE
failed to remove file `target/debug/tmp`

### ISSUE THREAD

**Issue by tmandry** [rust-lang/cargo#9783]
A couple of crates are failing to build in 1.55 that passed in 1.54 (rust-lang/rust#87749):

- https://crater-reports.s3.amazonaws.com/beta-1.55-1/beta-2021-08-01/gh/hrafnskogr.rshell/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.55-1/beta-2021-08-01/gh/max-block.dev-cli/log.txt

In the first one, the `tmp` crate is used, but not the second. But both are failing to remove the file `tmp`.

Not sure if this is spurious or what. I haven't reproduced it yet. Also maybe related to https://github.com/rust-lang/cargo/issues/6313#issuecomment-898023334.

**Comment by ehuss** [comment]
Oh my, not sure how I didn't think about that.  This is caused by #9375, and any project that has a `tmp` binary target will fail to run tests.

**Comment by joshtriplett** [comment]
Ah, makes sense. Sounds like we need to move the tmpdir's location to be something that can't conflict with a valid target binary name.

**Comment by joshtriplett** [comment]
We discussed this in today's @rust-lang/cargo meeting, and we decided to move this to `target/tmp` (and prohibit having a custom profile named `tmp`, to avoid conflicts).

**Comment by digitaldutch1** [comment]
I had this issue suddenly out of nowhere yesterday,turns out norton was the issue, i had some popups and by accident clicked something wrong.
To test if that is the case go to your norton app and shut it down and than test if the error is gone.
if that works than you have to add your map into the exclude list of norton and than turn norton on again.
