### ISSUE TITLE
cargo-tree lists bogus features when features reference dependencies

### ISSUE THREAD

**Issue by sayrer** [rust-lang/cargo#9794]
When a crate activates a feature in a dependency, the output shows the crate name as a feature.

When I run `cargo tree` on [tokio](https://github.com/tokio-rs/tokio) like this:
`cargo tree --edges=features --target=x86_64-pc-windows-msvc --prefix=none --format="{p}|{f}|" | grep tokio`

I get this result:
`tokio v1.10.0 (/path/to/tokio-rs/tokio/tokio)|bytes,default,fs,full,io-std,io-util,libc,macros,memchr,mio,net,num_cpus,once_cell,parking_lot,process,rt,rt-multi-thread,signal,signal-hook-registry,sync,test-util,time,tokio-macros,tracing,winapi| `

I don't think `mio` or `winapi` should be there.

In the Cargo.toml, there are a few features that reference `mio` and `winapi`, like this:
```
process = [
  "bytes",
  "once_cell",
  "libc",
  "mio/os-poll",
  "mio/os-util",
  "mio/uds",
  "signal-hook-registry",
  "winapi/threadpoollegacyapiset",
]
```

Output of `cargo version`:
`cargo 1.54.0 (5ae8d74b3 2021-06-22)`

**Comment by ehuss** [comment]
I believe this is expected behavior.  Optional dependencies implicitly define a feature of the same name, and when they are enabled the feature is set.  More information can be found at https://doc.rust-lang.org/cargo/reference/features.html#optional-dependencies.  Can you say more why you think they shouldn't be set?

**Comment by sayrer** [comment]
I see, you're right. I didn't know that, and was confused by the project also setting features on those dependencies.
