### ISSUE TITLE
Do not emit error when conflicting exact versions are specified (for "private" dependencies)

### ISSUE THREAD

**Issue by stepancheg** [rust-lang/cargo#9815]
Consider two crates: `cr1` and `cr2`.

`cr1` specifies a dependency for example `rand = "=0.8.3"`
`cr2` specifies a dependency for example `rand = "=0.8.4"`

Now there's a third crate which need to depend on both `cr1` and `cr2`, and `cargo` fails to resolve it:

```
% cargo check
    Updating crates.io index
error: failed to select a version for `serde`.
    ... required by package `cr2 v0.1.0 (/Users/nga/tmp/exact-versions/cr2)`
versions that meet the requirements `=1.0.126` are: 1.0.126

all possible versions conflict with previously selected packages.

  previously selected package `serde v1.0.127`
    ... which is depended on by `cr1 v0.1.0 (/Users/nga/tmp/exact-versions/cr1)`

failed to select a version for `serde` which could resolve this conflict
```

# Why specify exact versions

Each of these crates might want to specify exact dependency version for private dependencies for example:
* to guarantee strict build reproducibility
* to avoid breakages unforeseen by crate author (e.g. even a minor fix in a crate may result in compilation issue with newer rust compiler; happened to me many times because some users ask supporting older rust compiler)
* to avoid possible regressions, e. g. if a crate is tested to work well with this specific version, no need to worry about full range of dependency versions and difference between them
* crate author may want to pin to specific dependency version because there's known regression in the next version
* these dependencies are private, so users of the crate might not want to carry a burden of dealing with these transitive dependencies

So _practically_ it means it is not possible to specify exact dependency versions in library crates.

This is especially important for depending **stable crates on unstable crates (0.x.y)**, because unstable crate authors often don't worry much about backwards compatibility even between "patch" versions.

For now a possible alternative is to import the dependency crate code into my crate, and this is much less convenient than specifying exact dependency.

This is the repo which reproduces the issue: https://github.com/stepancheg/exact-versions

**Comment by Eh2406** [comment]
This behavior may have been a better design. However it would be a massive braking change now. Libraries can and do realiy on the fact that there can be only one semver compatible version in the tree. Also we regularly get complaints that bringing in multiple versions of libraries at all causes to much bloat. If you want to push to make this happen, it will need an RFC that explains how the transition will work.

**Comment by ehuss** [comment]
Yea, as @Eh2406 mentioned, this is unlikely to change as it is intentional that cargo prevents you from doing this. Perhaps, in theory, I think maybe something like [public-private dependencies](https://rust-lang.github.io/rfcs/1977-public-private-dependencies.html) could provide a way to decouple, but it seems like that would be very difficult to do in general (as there still needs to be unification within each sub-tree).

In general, it is recommended to not use `=` requirements except for exceptional cases.  There are more recommendations [here](https://doc.rust-lang.org/cargo/reference/resolver.html#recommendations).

Since this is unlikely to change (at least without a major RFC), I'm going to close.  Thanks for the suggestion, though! I understand it can be frustrating when there are breaking changes of dependencies released.
