### ISSUE TITLE
cargo test --release ignores profile.release and profile.test settings

### ISSUE THREAD

**Issue by ferencdg** [rust-lang/cargo#9874]
**Problem**
my Cargo.toml settings

[profile.release]
overflow-checks = true

[profile.test]
overflow-checks = true

if I use cargo build --release then the -C overflow-checks is correctly passed to rustc, however cargo test --release doesn't pass the overflow-checks to rustc

**Steps**
see above

**Possible Solution(s)**

**Notes**

Output of `cargo version`:

cargo 1.54.0 (5ae8d74b3 2021-06-22)

**Comment by ehuss** [comment]
When using `--release`, tests switch to the `bench` profile.  There's more information about profile selection at https://doc.rust-lang.org/cargo/reference/profiles.html#profile-selection.  Named profiles (tracked in #6988) will likely change that behavior to pick `release` since it uses a more consistent profile choice.
