### ISSUE TITLE
cargo build for first time

### ISSUE THREAD

**Issue by frogtile** [rust-lang/cargo#9888]
I installed rust, cloned a git repo and ran cargo build. cargo says,

> Updating crates.io index

And it provide % count.

But it doesn't show total and received  bytes size.

There wasn't a prompt for confirming or a message on what command i need to run to update the index.

It would be nice if instead of automatically doing it, cargo would ask for confirmation or  tell about a command to run and it would tell the download size.

**Comment by weihanglo** [comment]
AFAIK, there is [no simple way][1] to [determine a repo size][2] before cloning it.

[1]: https://stackoverflow.com/questions/28678223
[2]: https://stackoverflow.com/questions/2882620

Many commands in cargo by default need to access the network and fetch up-to-date registry index in order to do dependency resolution. If it's a concerne to access the network. One can always pass flags like `--offline` or `--frozen` to prevent cargo from reaching the network. See [FAQ: How can Cargo work offline?](https://doc.rust-lang.org/cargo/faq.html#how-can-cargo-work-offline) for more.

Hope this help 😀

**Comment by ehuss** [comment]
Yea, I think it is unlikely that we'll change cargo will stop to prompt when caching the index, and there are just limitations to what information we can get from git.  

[RFC 2789](https://rust-lang.github.io/rfcs/2789-sparse-index.html) will provide a new method for retrieving index information which should be much lighter-weight.  I'm going to close in deference to that.
