### ISSUE TITLE
Can't use unstable feature in `~/.cargo/config` without enabling it in `Cargo.toml`

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/cargo#9926]
**Problem**
Trying to use an unstable feature in my global config requires enabling that feature in every `Cargo.toml` I interact with.

**Steps**
```toml
# ~/.cargo/config
cargo-features = ["named-profiles"]
[profile.release-lto]
lto = true
```

```console
> cargo build --profile release-lto -Z unstable-options
error: config profile `release-lto` is not valid (defined in `/home/nemo157/.cargo/config`)

Caused by:
  feature `named-profiles` is required

  consider adding `cargo-features = ["named-profiles"]` to the manifest
```

**Possible Solution(s)**
Allow the config to enable unstable features too (preferably only applying to features used within it, not features used in `Cargo.toml`).

**Notes**

Output of `cargo version`: `cargo 1.55.0-nightly (3ebb5f15a 2021-07-02)` (and tested on `cargo 1.57.0-nightly (9a28ac83c 2021-09-18)` which fails in the same way with a slightly different message).

**Comment by weihanglo** [comment]
IMHO this is convenient for developers to enable features globally. Since we are already baking [patch-in-config], hope that the config-merge rules and other implementations wouldn't be too hard.

BTW, labeling this as `C-feature-request` may be better 😆

[patch-in-config]: https://doc.rust-lang.org/cargo/reference/unstable.html#patch-in-config

**Comment by weihanglo** [comment]
Close in favor of #11552, as features mentioned there are still unstable, which makes the intent a bit more clear.
